apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
type: Opaque
stringData:
    HOMEPAGE_VAR_UNRAID_PRAGUE_KEY: ENC[AES256_GCM,data:UqTbYuXqkNbV+Aa1f9nMT6J+vYlG9TYw5qFEnxvF/30hLBlLMyytjY4Oj6q9KvipgQE77q5oQlzIWJ2R+w+WhQ==,iv:6gEF+zI6hoq/9/7g+zVkBL97iWjTOWXWG34brs6pQy0=,tag:R2zfV54s5l/KBk3EJ95bLA==,type:str]
    HOMEPAGE_VAR_UNRAID_GREECE_KEY: ENC[AES256_GCM,data:XqqIu+KlUJHHAgLhVImjfn4A8vQjh8sn+IuMF5CGiBS89qEyj+KQHFtTuvVBayZE5JBzEu+7lDb5t7lCqk6cAg==,iv:ZBtoJN0s0FHaxn1RREwdGEAiGgrz2blTdZG+Yy7AKmo=,tag:sMwGfMVVC8UuS5wdN/slzg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTHVjNUFVaURLcTdBWFJV
            ZlFjVWNuTW9pV1VWNzFIcXBVMk5pUU0vc3hVCmRoWFVrYzRHRWkzY0FmQ0xieXhD
            SldwL2I4QUJlK3huYVhBRjJ4elk4dUUKLS0tIE1FbW5WVEVmeWhlN1BpRFM4Mko5
            eFlEd05nSVdtS1pIWjhFWVRYWlZ1d28KDv8+I9QVKtF3gdgcpP1JksMN9mjhbSw6
            sL7qmqgvpDn/sSYPMBbLrDVdgLN3fRPAAEnFkA+7lVwOgbMXEP789g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dyttenFKNW5hQUZUcHdM
            ZW1aWmgwWHBOYnFGRk40T29WYmRwL0VOaG1BCmh1WGlMZGVVZ0t2anBzREZhM05k
            Nk4vU0pJdUo5MUtKcElRTVNZdHA4YUEKLS0tIEhEY2hZZXJZVXBlQ0pmM1NGVk1Z
            SlZzRmxBVlNMN0w0TTlqRUpzNnNBa0kKvA7j5TrHV1mJNmRrhwDn+qliV1v+4PO5
            x77jASoLr3vCyiZl9r9uE0/9YPoWTHoaUDWnfie1HFLJxNxlUMzAQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMjRoR2JPTkVLL0JpUDdh
            YjI0QXFsdHBqelpoTlhWdnBpdG9XZEcyaDFZClcrN1Bvbzd1VHA5NDBvUmJyRkdr
            MXVTcUtOaklsL3d2TTVDMDRkWngrTXMKLS0tIGVvQ0UzVTFjaHVaM0loQVRoRm9w
            VGlsV25VWDQrL29LUmpyQXl2bjJ2R28KudciTRZgtha2pSjHPI/Z5wJqdWJeIBIS
            UsYaC8gPPRZxu0f4sixf7541Rf9lPk2hrmv11B9tvQpzCI/oTjvLZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T00:44:42Z"
    mac: ENC[AES256_GCM,data:KPR22wE3l6EBONpmf+HsJsdEi4lj+tqckarL8obkV+c0pJY98IAwkFKkYQ4xPvWtGzKUOAJYVJ6ewYKPs0Sji03kB9xkuJICJOujH6KCwqA5Jq6m5L/38HvDEoIJoSOvZozlkApl18cvp4/SGRnn9+r8TGA+RdFFO7Gfe0xcrRs=,iv:lMTH6wxTVvxHdpqL7d3lJjGYwZxSww/Kl0aLdcd01lk=,tag:TuHSte2fFfWWFmFlTDqPCQ==,type:str]
    version: 3.13.1
