apiVersion: v1
kind: Secret
metadata:
    name: penpot-secret
    namespace: penpot
type: Opaque
stringData:
    apiSecretKey: ENC[AES256_GCM,data:lvSmXW+AbkgKv7yP5rVGn4eLHOdARhri4nG3oZfg5UkSkB/V6k9B8Wiixv6Wec/eaUR3gjnGde6fgvpCFvylWA==,iv:dP8Mxb7/mrRS/Itbgt4bHrdVK0JqRqFHBSbZhV6qaVM=,tag:w1gJoa87Q3pOiPGV3TVvyg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:/8/IZjIU,iv:yZPqYUvJjMteO0ZnA9Pgexky2ly5wGmEDu4KA5UmTIs=,tag:efYmSOhoKvuXCSTp78m3gQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:XN/ruMTaRB3VLBquI/HHQInGs/tKZC7Sd5rKZGB8xc3MX/tjeRGY9Q==,iv:M56BLoWSC53gBP6rFkfRs8f1pAaCmfdoGIWZHTnDtgE=,tag:toNuKHgV8RN272H2UpyUPQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:XxyBFbkt,iv:fnNAbNRKq4B51/hiObPf8IwEc9Fkxb7tfmgo6iI8abA=,tag:g1gsXOaDRotCJmdKyA/Ygg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSy9acHhFUkFZR3hCY2RX
            ekt4Szc1eVVsRUoxaHplbXNsNTBIVkpPSmlRClF2ckg4c2Fpa3d3ZExUNW5WRW5G
            NEVCeVNRbVpPNHdOVEtjeDVOeGpIQ2cKLS0tIFJhc3ZwS1pxL3ZzNXMwT09ualFm
            TzMzalR4L3NEYVlvVlVlSTdJdmdjamMKP86nruOG3DHoWmPMVr4jWblBXXn+7919
            gfEpQb6iXbFVJJya1SOxOziJDc8qJ2a45UGXBuvojuB4nRDdC6oD1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T07:53:33Z"
    mac: ENC[AES256_GCM,data:yAOkADh1MRyQlch2c1lrPDSqOWPLEKmKgfGAKe/r+59C6lyE2vLHb8byHnS0XcZcGS6s76NJ2radqKlJIfo1yJWyWEH9pKHhTbKKeysS+IKtj2vnZDgQwzGunVom/lz5ZOGI1iZT1SaX3NiLBwYy1D2QIZB/4bGMdo9CaIzA+tA=,iv:EA7lrg+epkYwyycGg3l66U0rfgHgawnBa/rbBgJSikE=,tag:gPG0IMIH6L2kau7iEypflw==,type:str]
    version: 3.13.1
