apiVersion: v1
kind: Secret
metadata:
    name: penpot-secret
    namespace: penpot
type: Opaque
stringData:
    apiSecretKey: ENC[AES256_GCM,data:lvSmXW+AbkgKv7yP5rVGn4eLHOdARhri4nG3oZfg5UkSkB/V6k9B8Wiixv6Wec/eaUR3gjnGde6fgvpCFvylWA==,iv:dP8Mxb7/mrRS/Itbgt4bHrdVK0JqRqFHBSbZhV6qaVM=,tag:w1gJoa87Q3pOiPGV3TVvyg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:/8/IZjIU,iv:yZPqYUvJjMteO0ZnA9Pgexky2ly5wGmEDu4KA5UmTIs=,tag:efYmSOhoKvuXCSTp78m3gQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:XN/ruMTaRB3VLBquI/HHQInGs/tKZC7Sd5rKZGB8xc3MX/tjeRGY9Q==,iv:M56BLoWSC53gBP6rFkfRs8f1pAaCmfdoGIWZHTnDtgE=,tag:toNuKHgV8RN272H2UpyUPQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:XxyBFbkt,iv:fnNAbNRKq4B51/hiObPf8IwEc9Fkxb7tfmgo6iI8abA=,tag:g1gsXOaDRotCJmdKyA/Ygg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNGc4TTVUNFh3YndBd01i
            cWk5QjhQdkpBUmRjajNWa3JjKzJBTVArdGpBCmRGT1VQVWxlbXZURmVNOFdQSitB
            K2g1bThEVnExdFZyYXJWZmRvTUplUXcKLS0tIFgwZTVPTjFBdU1jbHpkSDRNbTlV
            RW13ZG9LNVRQdEFnUjNDeEFjdnNlVGsKS+tkn33i9h1GBqpRuZaV6IEFPB6bIZzr
            M98Iu/hwOipgfEUB5unB38cICAtIBUaEzriRdHI1GC9ktm0ceR938Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQmZzejVXNjJ0eUF5MndJ
            Q0hGMXh4UzMxNlBJSlBXVVlZQkl3VGFNSUZRCkNJallLdzBXUTBKUWhUMkRLRXhV
            eHFUVEsxR1hLYWRzdDFrUE92TmtjUmcKLS0tIHZUTmxwb1hsemFyOHJMT1dqcS9j
            THZiZDhIaWNrTk53YldaSEV6M0t2YTQK20RXh6SEQqgwF3p1h4u6W3T058Z6PU6u
            wAuV0oNlJzP1Vq4VKHrAqAaszuYhxszhVLJ3caRRWkNWwszmAdJ6Sg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbWRhRFJGbEluRGFtaGxY
            Y1ZMbVgxdFc0UmFsMVNrbG42OTJCTXlwN1cwCmR0VWpTSU43dXFEOHNMNmVmb0ZW
            em9HOUIrYmVHd3NkLzRxUGRnSHFwOXcKLS0tIFNLQWdtTFIwQnduL1JzMkJ6Zzhs
            YXlKU2RqZUlYelI3elJNN2YvK2VUZ0EKHdKkS0KkXDGUeJP9qIU8NOtOZ/awrXjk
            JTu6+A2AcLjPA22YLi1VMiKqvTxBOqxRkBvg4GZvwYMMlgtXUIXznQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T07:53:33Z"
    mac: ENC[AES256_GCM,data:yAOkADh1MRyQlch2c1lrPDSqOWPLEKmKgfGAKe/r+59C6lyE2vLHb8byHnS0XcZcGS6s76NJ2radqKlJIfo1yJWyWEH9pKHhTbKKeysS+IKtj2vnZDgQwzGunVom/lz5ZOGI1iZT1SaX3NiLBwYy1D2QIZB/4bGMdo9CaIzA+tA=,iv:EA7lrg+epkYwyycGg3l66U0rfgHgawnBa/rbBgJSikE=,tag:gPG0IMIH6L2kau7iEypflw==,type:str]
    version: 3.13.1
