apiVersion: v1
kind: Secret
metadata:
    name: backup-s3-secret
    namespace: namosocks
    annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:1k8XSO6Qc41DT+Rvj427pA==,iv:VM1y87sVZliX6nJ/7z/z9JTj+E5C6z+KEGA75NmjAWM=,tag:nbJYJuvmnRgBL27Bv6HCig==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Yxj5R/PVFlcWQtzQ+65qx1Teu6laPq2lTUlOlNrIy09FhNG/mFDjFw==,iv:6F5dtzIXTWWEf+nkqRFKHNOJc3voZIIG0i76slJZ/h0=,tag:em6mOCL6duB0VOpKA5NK+Q==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:k0O5yd+2t3+Jm66l4UjVclEvv5t6ZElxVg==,iv:bcF04eAm8ZXbDZWraZCUjDyoXGzqZPsvNI6gf6WQfNQ=,tag:sGZsxzzfvHjPLGh+zoqEtQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcXNyL1RzYVJYeVNiWDJT
            NU50N3J2OTlJNEovK3JKR2VqcStNQkpWdDE4CmZ2T2RvRzdtWUwrTHlHZjQ5TXJX
            RWl3QTVJeXNmOGl2T0twVUNqcjM5ZGMKLS0tIGpnMWJGMTRRMjBkMHB3S3lCMGhO
            T1o1UllQM0pUT1dSRE10TGUwOEFVS3MKGfM1NR7bdu9kBouI3eVU9hcDDZPEunjY
            mAO1zDACymGox155xVmAlLQsRqA14Lm0jBRkziv7aS2/0de5U9sH6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUWZCVjJ3bVlONGFoVnhI
            Z2RuUmZ2aVRDOHQ1VkIzbEw2WVU1N0duK2xRCmNwZU5vTlZNeXh1MFNOM2gzK1hs
            bzlGTVZNcXVQMVkyT0NKRWN3WisveGsKLS0tIEpxdGQ0Z01KUzFkNjlzOG1RMWVS
            MkdjUm54UGFaaE1IN2FVUlROUmFhMlEKXhyOfvusGxAKBd0KYKuHoLzzZT9MyjWu
            CE8/hrRnWowHpFWa8a5YR3vsXDx5edTy3it9IFPWWUKG2fIQTZug4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bUhxc2NTdHp6T29uKzRF
            Q2NqTzBuZXFXbVVjVGFUNjI3Vmw0QVYySkFNCm1IMFhvYStwdjcvTEwwaWxobjBJ
            bllGdHVQcm1YL3RmVDBCOG8wSC9PcWMKLS0tIGlUS1VHSHpJbVJpWVIzVS8vMXNr
            Tyt4TjJIUFZYMU5xT2hPN0lvTk8wcVUKEs9vR9W8I3KqoAqjx80djAtCz1f2eupY
            B4SK4Y0DvfZbXPNf/smykgKr0LSpqmi0GSowGypbb0ZVaKE5jB0CwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T09:10:04Z"
    mac: ENC[AES256_GCM,data:ElNAKzMXvjud2a718lMhXwyiJzs/qZZSa3o/LIDSIXSCQPkf+MJ7O7j+x30s3oVszBd5FRmUPhEDPx5EcRXGUvsJCvpAmf+YC3Idi4J1RADxz4AvgCzijnr+MV0xZotypSa49mg0Tkioz14baf80UKJ9WtWsoVent9gDKzM+HSY=,iv:DmOn6S2Vt5sM1gj7+w0QG3bAa0Ffh1Vl2nl08EbkRl0=,tag:ZiPM6uL+w/XPF9HzJvULTQ==,type:str]
    version: 3.13.1
