apiVersion: v1
kind: Secret
metadata:
    name: backup-s3-secret
    namespace: namosocks
    annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:1k8XSO6Qc41DT+Rvj427pA==,iv:VM1y87sVZliX6nJ/7z/z9JTj+E5C6z+KEGA75NmjAWM=,tag:nbJYJuvmnRgBL27Bv6HCig==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Yxj5R/PVFlcWQtzQ+65qx1Teu6laPq2lTUlOlNrIy09FhNG/mFDjFw==,iv:6F5dtzIXTWWEf+nkqRFKHNOJc3voZIIG0i76slJZ/h0=,tag:em6mOCL6duB0VOpKA5NK+Q==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:k0O5yd+2t3+Jm66l4UjVclEvv5t6ZElxVg==,iv:bcF04eAm8ZXbDZWraZCUjDyoXGzqZPsvNI6gf6WQfNQ=,tag:sGZsxzzfvHjPLGh+zoqEtQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUmMybHIvRklXQ2J6YnVG
            Z0pDVFhJOVhyK1ZyRXd0OVZ4elNqbk44MTAwCmFjdHdBT1VGVCtGZml3K2piVmhx
            Q2J6YTFSR2JWek9DbTFjNHdEcGRXTjgKLS0tIFhTbWYxTDg2aGYvMlVlV2NqZGJM
            ekQySzBXOURjR0pCaDBYeWszMElWZlUKmHNmsB+46K0EVc7+InrQEXFVVWKAYbJc
            DFGn+B/WbyY++8KGEprfOVtVTnmI+G1/05jny56OGfmlFPw8Is95Tw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T09:10:04Z"
    mac: ENC[AES256_GCM,data:ElNAKzMXvjud2a718lMhXwyiJzs/qZZSa3o/LIDSIXSCQPkf+MJ7O7j+x30s3oVszBd5FRmUPhEDPx5EcRXGUvsJCvpAmf+YC3Idi4J1RADxz4AvgCzijnr+MV0xZotypSa49mg0Tkioz14baf80UKJ9WtWsoVent9gDKzM+HSY=,iv:DmOn6S2Vt5sM1gj7+w0QG3bAa0Ffh1Vl2nl08EbkRl0=,tag:ZiPM6uL+w/XPF9HzJvULTQ==,type:str]
    version: 3.13.1
