apiVersion: v1
kind: Secret
metadata:
    name: namosocks-secret
    namespace: namosocks
    annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
type: Opaque
stringData:
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:1uwji09nKWail9LpALqjv2uVc+Tv8i4vEEpmsTfIPWceV1P+lfnxRgbSEXIQ9cF0ZLejAst4QZSkr3g627mplw==,iv:R8+8K3Jy+1pzfxQ36Se84EYYFEH/MjItWnFAUK+FURw=,tag:55xLHHx1fxlbHelmD4PLFw==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:V4a/wkUXFRP5XjON+EGJKHJKD1dxC8TB2tSBk7hLCRDlsP8qZN27iiRAG6o3w4xFff0ZRlTnPzBGuaeUjOvkgw==,iv:xt3GmxSAg90jgcT9sPk5BuFpTPDFdt9k1Ez6RN0JAJI=,tag:9EA4cGCGQD2+FFvj7Im66Q==,type:str]
    WORDPRESS_AUTH_KEY: ENC[AES256_GCM,data:faLLxP/UdD7SVq3BPqli1JQRAU6FPDG+6V82WyJQzxDK0Ik5WV9yFCHACw2Q3xfokeujz2HitAUX6SR9JZMdyQ==,iv:V0OXUMJUfkMDUZPL6VU7kYobPagQglMWHPTYQktuspg=,tag:f9a8pbY1MMlMnyvgOq5PBA==,type:str]
    WORDPRESS_SECURE_AUTH_KEY: ENC[AES256_GCM,data:aq5wYIcptMeb5cXK1zC1TEPVRAXEtPBDxD+ExNZNXFR37DcGt7a/R9nc2cSrxwK8hrjmELU6R2zNF7BnIWOGKQ==,iv:a4+x6itiZckr5Tq2OU4NvaU3IsoMQISqWdDqlsFDnrc=,tag:lqxCo/tVcyrj7zwyTNsibg==,type:str]
    WORDPRESS_LOGGED_IN_KEY: ENC[AES256_GCM,data:zHVDD2dxMS2+ayQzxmORJihx/WqmP7NreqM9JoIwgfKXEBy+mnDc8Q3BBwpyZHwN387vn8elfhtgTwrdVPOIjA==,iv:jytovpj+aLIboCE5kUXKHBJNz6ifPm1AKFwkqUK/1lM=,tag:4q4c1or12uHjhtg2dP1FtQ==,type:str]
    WORDPRESS_NONCE_KEY: ENC[AES256_GCM,data:eqbrcv76AhiLk4Fyc15eHk4rbHrjP6PQo/8pVzYdIT5LA0WkRS69PVrvuEFrr8jO1+zcdXJOHw/d7LrCtwmAxQ==,iv:omRTRaVxIYVE4uMpwO3BBjYEYN1DT/5hIcmRKHmkCSI=,tag:d9y9xenGCT24rugLUQrXOQ==,type:str]
    WORDPRESS_AUTH_SALT: ENC[AES256_GCM,data:UKlr1qNh5Gkj9UBfmO4yJGg/pDa+tRJVK+OOXv1R09hCtShGxOMETmoWATXlFzCGBWcfhwN+471+YyA4wESihw==,iv:4SudGBJJqVDS/zK02VtJIfWEE0Fun7MaA1AbhhIuLkc=,tag:LusmH20R3ihnj0AKN45NoA==,type:str]
    WORDPRESS_SECURE_AUTH_SALT: ENC[AES256_GCM,data:ppl2U9S79g/E2EHqyPdAL9pMJa4Y2SUzTi3Rmlz5H4BXWNL106gcpJzw+9uap4G8LIwMCnZTITFSmOIppQcQAA==,iv:P0ZnIL7ieiMujC1byvaXr4xooePjuOx6TG5aCQ3QZ6Q=,tag:0zCN8hzXD4FCO8zW3CMm+w==,type:str]
    WORDPRESS_LOGGED_IN_SALT: ENC[AES256_GCM,data:dTM9h+c7bsCxVeJCjIamGE4iBOxn6rPOhOOk18aYva/NLFNWizk1NRJhUfsiTfyuKExodZptt9tlu8vSF5h5Pg==,iv:j8Zt8GoVoGXgUkE9gZOB43pk2KDszSGCrTjZ7lXCBFw=,tag:HoLZD3xEpSAnj/dFzUkTLg==,type:str]
    WORDPRESS_NONCE_SALT: ENC[AES256_GCM,data:i+Run0CcZ1GMVZ5Yg2XWDZcUOCMFBg9EJiCxRG1fhVwp9HVbPhAOJ+yR1Mdcv5BeR/rAmh1SQOKo4JMAafnsDw==,iv:4E/OYz4hfhsCfwZlRY+eHBVjG56qVOgE+Z6Z0EWTKSU=,tag:CqcxAb8qtxXsBiZHlaVsuw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNT3pra0xMZUg2d1pJclFj
            aGcvSW9aQmJkYXpYRmRWS005a1ZMbWZKdURjClVTSDM5bkZGclhaZmJMMkVOalhl
            ZVdPcFF1NXRBTXNEaGN1Q0J1U3llMDQKLS0tIGxqMzZkR3FoU0Y4ZStQamhTUkhE
            MDh1ZHdyVXozd1J3RjROWUJ3Vy9JOUUKQhzXDBRfKmQYXxxItM6LY5UewdpnN07+
            3JyjH6HyMdvL2Hjfzv0+iqJRmIriW9oJyomBC32uCR1cvy2H3sAgYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdEZPdDNhemtpdG9UeGNa
            QW9qeG9nS0ppUEl0aG9IZWFsL2FrdzVaQTA0CkdkUkNQMDlXL2hyZ3B4MklBQ0di
            dm9OQmNlVnI3WVZGWitRaU9vRjNsOXMKLS0tIEZEL2RBQXlOUUJtVjJ0WE1HVEEx
            TmtLVmFwWEFtVEdQTFluSmpqQ2QrblEKgEK1cvP67DNKOrP7LfngvddyoOAJhDFX
            UeL7mA2DlZ7qZNVD1p6nR1IZyraFGqGCaTo7Kb7u2/X6swHdBABx9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VFR0dUpibmhhaHlvWWtQ
            Mms1azM2QUR2cEljZ3NyQlgrSnBqWW95SXdNCkRwMEVZZndHL28zZ3RUbmtqWkpV
            QkRUMTFUK1NITXFGQ2wwNWVsbCtveFEKLS0tIFNpOS8yYlRxbGNiYWtKUjd3Qkdl
            NFhzc1JvSmI2ZVhKclhzaWhNTHpuL2sKevahNaCkpnUTKVj4rP8eqMAdW4dGoqhq
            6TUJ83ZzydkrMJYxw9T3SMS6i+EpAllGxfUlDX1CEzL4cxc66nWCuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T09:10:04Z"
    mac: ENC[AES256_GCM,data:MqHLgGN6b7y2TJqjJU4bgzrEzIJDxW+sWmbR0YyPb5gLbgs82Gct7Pc+jpMe4BS9yTOou48j5ZFEU6PAwrUFPrNQHj/HGZta/R2pdFBnh1PKVgAN70C6zargz1Z3hdwb3FqSYMwkKSQsBnmtmwVDQjTOicKNkzc5oC2oiMv7oIA=,iv:qvtJeLG0a7cDhRgbiT6bjcxVrRQ0wkSjUlmquk/K1W8=,tag:FDzYRv54pi/7fbWilAncfg==,type:str]
    version: 3.13.1
