apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-telegram
    namespace: monitoring
type: Opaque
stringData:
    bottoken: ENC[AES256_GCM,data:o4Y+IAJRjXiF9EJNcyWgWGhkU2cCOiQWOi8nRYAnil0vKPQUy6+LX/mljPdCzQ==,iv:oHLUTYlswsfITuDoaExiuocL/vgmOyg58BRViKjpccs=,tag:Ez01jdsXqBejTPWs1He2Hg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaS3hOeWFIWEthT3ZGTHBR
            ajNmdmZ4RGYydXA2ZnlIMWtPcTd5WTJHRG1nCjg1bGNDOGlFRDhWeU4zcyswSUlo
            Q2NaM1NmcE1lcm1nQTQxZ1plM0IvWFkKLS0tIGxGeFJyczdMY0U2UDIyZDBxRWZW
            SjB2N0F2WHBEQjhKdTY4RGhtbVRTdkkKfYJJ+V6bELEnxo1norfb0M0zSeaX8LYC
            LI4Cfej++r6bVJSCZdeTvozaeUkbAthYhWsFcPnYcKUVsdoVKSUQwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T15:31:20Z"
    mac: ENC[AES256_GCM,data:q4Sif5QHUEnjZk00INfRXokDW9Am0SfdEYENAa6FX/GOT/CyQRSTydD61mNb/opykas5vy2d6QfSibS+dDpJRsz4bVXL5J8WeE2OIUH5vV47dC7qP9wJxKhrMDMzgmweCecUrxmCfGk6ptjjNcTnvDTXXGe5ThrZDXb5s3slQsk=,iv:NI96IvQTEka4xB77zl5/gXudOKL1Hd1BiBlipzKsRPk=,tag:gq3oOsc5vBBeSqlkPUfp6A==,type:str]
    version: 3.13.1
