apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-telegram
    namespace: monitoring
type: Opaque
stringData:
    bottoken: ENC[AES256_GCM,data:o4Y+IAJRjXiF9EJNcyWgWGhkU2cCOiQWOi8nRYAnil0vKPQUy6+LX/mljPdCzQ==,iv:oHLUTYlswsfITuDoaExiuocL/vgmOyg58BRViKjpccs=,tag:Ez01jdsXqBejTPWs1He2Hg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpKzYvZTNWQlBsclI3WVdq
            eXZhd1I5MFBDV0FNdWEvKzBJYytSL2xWeTI0ClpucUxBMzNCTWRsM3dBaTE4NXEx
            ZVRPNWdjTm9ib085a3d3ZTB5dW9PVUkKLS0tIGw4L3ViZmxsdEhnQ1J6SVBaV2RJ
            WlZTdzN5U0dXVjIzWityVmtnaHdzckkKKs7m/pjUh/WkMfgYrRUnImu5Wd0GY+Fq
            uL/06VhKENmgi8QhPad3lu/YlG+PSXGPk/1YVi3z1KMh7mACRivRww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcjlUeGpVL1ZWZUtiLzdu
            bFZnM3ZkV3VmeFJ2QkNtODA0Yk1lNGtZeUdRCm5qY0hPcDFiUTNWMU9xeVArWTNo
            M1kzY0thMHJ6Z1ZsakhuMk91UllrSUEKLS0tIHduOUJpMEZ1WFJqTnBiMjdlN21l
            RzREL0d3bE5CVWNHUlFaTUVHeHJCY3MKV9W6uXX8Bnrsa+CnsYfHakfMzsojwkQ/
            lhbWJ4Tr6HDE+Tv9fBRxi9zg/rsPdrTCFo/AQGdh0HXXeJPeN2p7Rw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTVlRR21LSVIxNERYcVpL
            UzV1elJMcWh4OWUzQktEdW1XcWJDeTBnTzNvCnU1OTAwVW00S2gveXpoSzFDNS9N
            aGNyVzdyZy9GRmtUTXZuWEFzdCtVWmcKLS0tIEVMajA5cmQzczBPb09tcW1uOFNU
            WnpCellPV0JPbjEyMkNLUUxncGlRSzAKaOTdH69/XpP9OjyPVnkvy2YgmXeQZTWU
            jSZXzR7DqeOE94xM+8Zdk3WM7Ht0RaBNOGqIcmCupe2j23GF6wiJUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T15:31:20Z"
    mac: ENC[AES256_GCM,data:q4Sif5QHUEnjZk00INfRXokDW9Am0SfdEYENAa6FX/GOT/CyQRSTydD61mNb/opykas5vy2d6QfSibS+dDpJRsz4bVXL5J8WeE2OIUH5vV47dC7qP9wJxKhrMDMzgmweCecUrxmCfGk6ptjjNcTnvDTXXGe5ThrZDXb5s3slQsk=,iv:NI96IvQTEka4xB77zl5/gXudOKL1Hd1BiBlipzKsRPk=,tag:gq3oOsc5vBBeSqlkPUfp6A==,type:str]
    version: 3.13.1
