apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack-grafana
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:s5NHbJM=,iv:I8E80jFG91pP4uW2ta1Uc0Jxr7AC5W0VjOkjV0QKvFk=,tag:7KM7290kyuFLAmlzpuWpag==,type:str]
    admin-password: ENC[AES256_GCM,data:yoU5AIrKrAVfJjVM+AjX8wXKDnJI3VGKqkuOsR2V5ORqVShzbYlb1mv1qQ==,iv:OcI3iLg6MnT9a3dwyQj+MWodY8Imxuq6lj9Orjsme78=,tag:7bOYs+x6zaRq0J6UyoiSAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbmZta0x4U2o4cTlnRUEz
            dDhnU1JSU1pBdXZEV3g2N2JmVmU2elJlSFQwCnBMQjZMS3J1Tm9HSkFZYVJMNnh5
            VEVRd1Faa2hIMFNLN0p1aWd5WUNoQ0EKLS0tIGxEOTJwNFJQVTJ4QnBJQXZoc3hn
            ejBoTnFGYm9mV3NQcy96bFB5ZjBXa00KYHh2sSuQewX98zrZsWG1OZGtJpIi92rZ
            tVdK7dBbMHMzr83o2MOn8NHxjYgWE8jLup+clLbo/qV+SX6JSeIWoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcFBKVkFGZVMwWVhEOEE1
            Q3hJSzRxam1BQWFEak1SMGhvcHVtbGJvTjJ3ClBJejNtTkZGRWxLSFpvVElPbzV2
            MUJVcHFwbWI0ZVVqbXpKMWROaHl5bm8KLS0tIExzQVBNTTY3S1ZiZlh1N1lCbnBQ
            OXZjMlR4L3V5NmI1VGZSbmJMbGs0WUEKgh9SH/iIdVsf1Zo9SZ8PZxHx67q5wCPn
            q31vLx/CL6kAX6tuZrpL5uS1kgNf/2k657WvZUR8udYOhM6H27ACWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RGcxNTNWaWlJeFROakU1
            QWtBcGFlMFhaOXBwMGRiL3BwQUppWUZjeXlrCk56Ynk2YzViNUhHeW8ydEpaZGtu
            K1g4bWhnOGxlcUY3ZHNZcU94TGVPQlkKLS0tIEo1SzJCUTUxUnZOejhDaElJQ0tX
            dmxjVGM3TjloSkd5c1lkRTRrWDU3TzQKH+ndJJxun3qw7OC/yTYQzrrgDYRrF/eP
            5rWqnH+hLhhvAFQNr4MlWYdDiy4pX3IeG+X9x3ZgbiJeop3tnpkZ2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T16:41:38Z"
    mac: ENC[AES256_GCM,data:wG0UBQFS2HVvTz//d5Y81YohQdFqBei2zYhl8IBzyrp3OZZ5gX16N4587NPxeHNNqQ5lT1T9xPteIVBZ6nPHBtv4EBUS08PTGRyGQxvh6Wm1orV2kk4EW/b/GYTnqfOUKQt5M4Rj8up1TJvG+gimtBUkpdkjYjt0shdzaKQF19M=,iv:e7GHXh2RyuOUm8fwZMvWCh6EMRWaYi26FTWgC3l5PP4=,tag:tmB7OwE36Xxy2AL0ajyVxQ==,type:str]
    version: 3.13.1
