apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack-grafana
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:s5NHbJM=,iv:I8E80jFG91pP4uW2ta1Uc0Jxr7AC5W0VjOkjV0QKvFk=,tag:7KM7290kyuFLAmlzpuWpag==,type:str]
    admin-password: ENC[AES256_GCM,data:yoU5AIrKrAVfJjVM+AjX8wXKDnJI3VGKqkuOsR2V5ORqVShzbYlb1mv1qQ==,iv:OcI3iLg6MnT9a3dwyQj+MWodY8Imxuq6lj9Orjsme78=,tag:7bOYs+x6zaRq0J6UyoiSAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZy9oTDFobVp6TGRtUDhE
            NFB6cDdJZW10RXU5NXNXRHUvOFVqZC9Wd0ZrCkQyR1FBVUk0KzFHQjhFdUROOCt0
            SHM5d1k2enhNemlPMjRvTkszVzJUUmcKLS0tIEZxS1ZyT1hGS1FVVWhRR3J1cTFj
            TTQrZUp5bmRzODg1cTgyZ05HT3N6VWMK/sb2wk92PDywr1PzjiWq4UDHuRarjuAf
            Ji3Pvtb4L3QWnkHZ1caENQth57FWL1cVGjx4HifB5tY8xdIjnfaDDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T16:41:38Z"
    mac: ENC[AES256_GCM,data:wG0UBQFS2HVvTz//d5Y81YohQdFqBei2zYhl8IBzyrp3OZZ5gX16N4587NPxeHNNqQ5lT1T9xPteIVBZ6nPHBtv4EBUS08PTGRyGQxvh6Wm1orV2kk4EW/b/GYTnqfOUKQt5M4Rj8up1TJvG+gimtBUkpdkjYjt0shdzaKQF19M=,iv:e7GHXh2RyuOUm8fwZMvWCh6EMRWaYi26FTWgC3l5PP4=,tag:tmB7OwE36Xxy2AL0ajyVxQ==,type:str]
    version: 3.13.1
