apiVersion: v1
kind: Secret
metadata:
    name: pve-exporter
    namespace: monitoring
type: Opaque
stringData:
    PVE_USER: ENC[AES256_GCM,data:/W6+t6m3r3JhPihwsok=,iv:7Xru6br37ZlAcxfVn8TJ+QcbmEm+kEE8KVHCuhm9Pxo=,tag:YlXfELI+qGd+dTRv105/JA==,type:str]
    PVE_TOKEN_NAME: ENC[AES256_GCM,data:Csdc1kodPQ==,iv:S0vM3IsTjpDHRAphkKCh3dMI7Rw9b9wDxUw/X588dcE=,tag:aBnsUtx1hZHsqFQS1tlQ2Q==,type:str]
    PVE_TOKEN_VALUE: ENC[AES256_GCM,data:xkcXsMDASaS3eSX8yomk+9MJ+zTnwjypk2esAdPXDLY4aQD5,iv:B6yuIbHmy0CLORZm/3m1C0fuDH2JYClVYoGAqF9f08w=,tag:pfepCIrfMRH8z57gQAwzhQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobmVRQk1KNjhDZzFrM3FP
            SENDSTVqM2YxdXp5NDB0ckNqN29SVDVMRG1NCkpTLzF0VWN5SlNGSlhvc09xZUp6
            UHNXd3dBT01jSnNHRVdEV1ZpZVhMSjQKLS0tIC9ZajBxSGdXUzV6VTNmMFFmb0lh
            bWZjZ1BQMkJuWFRsTEltaUd3dGhpeUkKzwnhlCQRTTbtsPSDyr+IBkeHJnadn3u9
            U6d1PBmcBNX7xlclA/TLfx+k6a+wJCusVtv+ONZuB7hOdoaWTGevKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTmtXbzlXYTYzNGdIQ3l0
            Z2dUYzdVaTFGWkpTc3Z0Y0NwckVUN0ZMTkJnClJpYmhhTE41emc3d0RLaytiZmtu
            MzVObjgrellMeHZDUDhLNzNLYWtkTm8KLS0tIFZPY2E0ZHUvRzZEaVBlei9JRldM
            c3ZBL3RsYlJKYmxBT1dYa3RBNENWeEkK0vvitAiyc8EUvoIM/diazJAgAadzK88A
            fuTguz7zYcLeI2QiadWS3KHNq3XhXXs8TwuXnOSYq4gcUaWRg346eQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbXlaaEN5cnpmMkMrZ1hm
            K0FWbGhSWVArVS94QmpzL09pQmxqQzZWWm1BCnloY3d5dWtFQmdtVUowYWpJK3BP
            WlFGTTVidjdTSnE5WGNwN3lXY0NBMFEKLS0tIGFORWlTcXBUdXNGS3M3d2FJM2pp
            WjZWTU56VEtUWk5vMldycm44STB2VlEKrngA4HbZnRcMHN4KozJHii4spbIOkxGR
            X6dDvzM21JBDPCnqQer7mLZeNyWPjbQq/9tEqkI9XbNR+iwJ/tDXEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T10:16:17Z"
    mac: ENC[AES256_GCM,data:cLyd/0LW5kI8D9P0P3RM8fTg7TmXFJxGSBImmzSRZl4z7CTmVj4bkpqarvlQVDG67KwHIPYsqF9V+MgeND6blGIWQbXSUd6Sdt7eflq++uqqXQrwsg0LHZyHj5gUwQJ2r2P/sAInhmxjO60GYGNbDqxTkxBJoxKffMkclkeS0Fk=,iv:7r6k71rUtz+HIXZ+IzGYx0kz6M4yvzT/rCI++4ozYK0=,tag:meZU7MdkPqK5/8u9tmWjTQ==,type:str]
    version: 3.13.1
