apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-stefanos-thumbs-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.1.100
    path: /mnt/user/k3s-services/immich_database/stefanos/thumbs
  mountOptions:
    - hard
    - nfsvers=4.1
