apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stefanos-thumbs-ssd-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: immich-stefanos-thumbs-pv
  resources:
    requests:
      storage: 50Gi
