apiVersion: v1
kind: Secret
metadata:
    name: backup-s3-secret
    namespace: vaultwarden
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ZBG5Rq5kvbyIebj12duhxWMv,iv:YiG2KfbzH+nocpJPHnjDTlkzZ5iKkKRWukDzSpeKjL4=,tag:Hy/5rpUOGQORfTdA8Swe8Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:t3nUO0YUQEHSIUlMKDzQun5/5I00fU7M5y/GljNGY1Ap/LJJ4ncvOA==,iv:qaSh/4KmkCiPYBUTZ4AQd3+4MgNAfPBNTaAYf+W/ET0=,tag:sJX9HF2BqZMDsVsDvucNkQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:b737pJGuBsu4WiZtMebV+MsctBEpzwBK0g==,iv:WD84Ftmo/EOxnYId8owPEcH+qf7Q35y876gwcIJoWXg=,tag:nQWr26L6jGJzZL51jXH/dw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDS0hDNHBMS0V6MXh5amNK
            SE1KRzZxQ0JxNHkzeVhYMHFrcnQ1cC9mUTNBCkZveHFWQ3g0WnA0WHo3azBMdFB0
            WlJpbFZWWGljcXcwcWxhazNLWVZNOXMKLS0tIGp3OTBwOTdYNkVpMHdodjI2WXRo
            ZDNIcFg3dVBvVXNCSkdPS2ZjUHdmbDAKOChAW/2GCsMQM4dvWKFFd+g5bn822U5H
            TfkxaiFJdukM9+9SYDlH268Gg4mGVfRfhfxmwJg2k6JKUlt7+iCn0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T12:15:31Z"
    mac: ENC[AES256_GCM,data:6a3JNY1u9iqoar6JJlrQfCg/FYsVUw81WEB+Ge4sdVmHv2Q1XKzstZPwFnLUahUFefe95RoK0rR1gaRVPuo2GIkVybyi86fTB8COk983C4Gw7KJHM3Frx7lkX+9eGRlcgxDkAH3diUnv1yXS1Pwu0M7XBOXQf9bhmp4U8RR0T8U=,iv:0zNDIaHi96l94zCchs5K7CetMK2DBgV1bFfUgRSbIZY=,tag:gzrYCKy/nk5Wo/PSytj2HQ==,type:str]
    version: 3.13.1
