apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: vaultwarden
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:iv0Qbhi4FBQEEjgAUzaFBDp7YqechLUL1eaPBmFwslD9RbTfda/BL0E3wC4SCZDIfbXvIy+gTl373rtl,iv:5R67MvKntI9l1yCunnAvA4ZXUp0AOTmAwVpYr2R5zDU=,tag:N/078I+TgUTasu7MpnOOVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUzBMbUw5ZllMakg0UzQ0
            blNLMDl0dm1qeWZtQkRoTGQvUkxsOXBnSWlzCmg0WFpKU2hRWjczWkVWaTRGYVgz
            WkpEc004eWhYTzgxdUhLTEhCU3U0amMKLS0tIEJhN24zd0pRR3ZmYU5sRys0VTlz
            RXljOWRLSnA1a3VtSHJ1S2RmNFJBdTgKF3y018VFp4FJ2M5EqSS0JylhyckHiCh8
            auCWl8dyPlgI/wIzAh0Zs1RPwg5tIfXKxt5O1fWEDspTJPBd2FXsmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T12:40:43Z"
    mac: ENC[AES256_GCM,data:OYaACVabWcsTqe2x9NF8REw3bG9FUlmxM72+BZlcqiHY0P0IN3+LEA9YpG1LVu2S3BSk4+MTTKMhFHMmjnBgWGSGiWUbbezoI/0RtqRa0mXrqriymvIa0ZWvi2O1D7RLpRDrFUJ7UEm2dl8cLpwYhiXF9givOM+ig5o5hRz573g=,iv:fW0ubK6I67fpJcALfF5atbszqHfZM1BUOhfDllKtRD4=,tag:Ou9PGrOztSSIEzuMRxp8xg==,type:str]
    version: 3.13.1
