apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: vaultwarden
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:ntdd69pTtyswgUPygW6yjaeUHH7lU/z+1tDex3PUP488TOeETeoICuFFzP5p3wjqz/zFKgP8N6lya/mznrZ+GuimR3o8cRK7g3KIK1jJsXaDDdt5iuGBGavLRFaBo3JfJSV2i38SM9aBcNA=,iv:eoDDcGcIRAayUGHZcLEww46w4IZPTqWk1DHhmaMAc8I=,tag:uEv+EPBtO5mC/SSC6WEGoA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:3bGk6yWRp7a8RRXeZD9IkQ==,iv:XJJLPEychP4BZvIIF794RYJsnchuLG3L4++hYZvyYQc=,tag:YVZn8CLZyQHU6L1CwDnArA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabHY0ckwwMXpPUzMrSW5s
            RXlQaVMyWmxORUIwNDRsQzVvU2o2alphYms4CjFzcmF3L2NreE1URVFJWXlNbTMr
            K2FUemNOMmpGdDVURXhLa3J2VTVOQjgKLS0tIGJhQ3M3N1p2ZW1pNjV1dkFXZTBD
            OTZkVkRFQjhMVlBYWWhDUHI0YS9RQnMK2qZvlAiH6SIEGKuQhU4UFVVMA/9etU2k
            CU+EAjUFGKPEFG5jJlNbqdhkIyaw6m81aU+HHxdj3bX2ygH4T06aVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T21:16:18Z"
    mac: ENC[AES256_GCM,data:c8+gsUmCjaOpAqF9kKASNhZGQMbMO48I+KWk56kfEX09l0anq71nhC5hzh4utmC5S90MU/aDEnzV7MUYIjgtPDrUA0rcDm5Ww1j/9jtzqgSwZQ/y/J03vwT71MYZlnS9v/L4tPMsHeMc8eE2vxy2FSoc3KJHh0PFbdJupKRymNc=,iv:Pj/W3+tonKeyCFXSNJQfWEgY51KDX3aLf+nTf4PNj2A=,tag:ZnhnLggr6UHC7yFZ5707Wg==,type:str]
    version: 3.13.1
