apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: vaultwarden
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:QtwHFVC12sEGfs+O7jMw4O0OypK7xG65QJRMI6SsZIOYBqSWPK+pHzLonnpd179Ns42/0excGuSZPPX1QVEJ8g==,iv:/Obr81jG7zm7rp3FCCnf6qRAArksCc8Q3jB7R9LsZn8=,tag:0NxgOJsVOyG3kugIcVG4Cw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabHY0ckwwMXpPUzMrSW5s
            RXlQaVMyWmxORUIwNDRsQzVvU2o2alphYms4CjFzcmF3L2NreE1URVFJWXlNbTMr
            K2FUemNOMmpGdDVURXhLa3J2VTVOQjgKLS0tIGJhQ3M3N1p2ZW1pNjV1dkFXZTBD
            OTZkVkRFQjhMVlBYWWhDUHI0YS9RQnMK2qZvlAiH6SIEGKuQhU4UFVVMA/9etU2k
            CU+EAjUFGKPEFG5jJlNbqdhkIyaw6m81aU+HHxdj3bX2ygH4T06aVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T15:14:16Z"
    mac: ENC[AES256_GCM,data:kZRgbIDgjl6YqXXmo8KUukOMqzMS+cMSbQPdgjm/EXkHeGEGKt4W4ILtqcIcwdmZHssoxaI+KP3bD3K6lsvbsQILjyniiIQuJG1lGWysxWsDyruHbquGJotf8podvkX7ti61rDW8P1kbvJkIXrv6/ZthWXMXl/0Z9KjQPgyTEEM=,iv:RdgdJ5rCGqrBmhamnYy863i95bi2WVKlYDyrk2Y8rR8=,tag:YvCWFtRDnHDsG2bYFhwAxA==,type:str]
    version: 3.13.1
