apiVersion: v1
kind: Secret
metadata:
    name: clinic-api-secret
    namespace: saas-gompha-staging
type: Opaque
stringData:
    GOMPHA_MIGRATION_DATABASE_URL: ENC[AES256_GCM,data:Lgj7016HCecyJryCibAjeTRPj57q1XNXAJ++04xpaJE4UFTxsX3DiVHngkLdaQUfmVqHYiTFJYnJ4Tp226tOZrp3bYkRJv3mNRauWbyWQvxahCL2TaBBYE2lasEe,iv:INWwvHlMSEGaBlGFzfe1nuL+rEGulFVtDfUyDjFq8z4=,tag:rrH3CqCn424y5+wP3NORrg==,type:str]
    GOMPHA_DATABASE_URL: ENC[AES256_GCM,data:fcGRcQtVsz9dYKiENoNuvNB9kLtz7PMESlAhu/6EtvqnKIPT4sI4QD6PFp1GRZasP2HiacL9NUNrp7jFCX3vsZwJ3z8laRfXbpT88UZSJO1o/FgnNHv0UOjiJg==,iv:qMHb/VToaPb9yner4vraHMtpPu39E8DR/yyd74adR3A=,tag:rGu0kxgoGI9xfhfraxGzbA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcHRGZWozWnBFeFR5ckt1
            V0ZhNHMzeUE5UWkreWYxVEhHc0FpbWJpZUQwCjlWRGh6aDRJNFF6d2R5ckZNUk95
            Q2JZYXVUT1l4QVZUT3MzYVZnWEVzNGsKLS0tIERxT0p4aDZiZDRFQk1ncHBRbzAr
            Yk94enQ2aWMvd29pYzdIaGdpblVvTFEKD6nex0Hy4ZJmFk0Z2pPXfnbdIwfZiyKF
            oHQ5veg9JdCw96mjfYy/+Zd/BJ30gFlhtuzoSzownOxS5trWxRV4Gg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaFZZUVlpcG1zSXhUMnVa
            ZStXS3p4RjlGdXZRNjJzS2lkZGZvWUhKdW5jCm1EWkFRa21WUDVjclhYSzdLa0tW
            bUZuazJjZUlrN2ZjckFDTzduVWh1WW8KLS0tIGhGVkVmcnVpcEk3Y29oTHRITzJm
            OUhHNVFQdGx2MWVtVVBkejltcENpVFEKdXdd9Y0ucEHWOn/ia5UPckbWjkGINv7A
            TLVaSruESIsgDjCjjsyjJ5crjqVyV8nZlWeRa8FCRg+Tee2SSGRV/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMlB6RGR6azNPMkNSRlRo
            Mk9DR2RRMU45R250M09jRjFUaHMxTEppZ3djCjF6Mlc2NHJUcnhqblU5YzhOMG10
            dXZka0V1d2t4ZndSUS9wRGxJMmtUTzQKLS0tIE1abU01Nno5M2JDQVd1K0c2L2c3
            bGZBbGtUUCsxQWpkOUFHVXVCYzNEazAK4ZRIXaSMfKhauIdPB0eR1czQx4Xharca
            aySD8Cixg0YQ+8eIHkMS0Wz9XWNUbbkIIR2RJ0ci7xRrmtOvN1bu3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T18:43:47Z"
    mac: ENC[AES256_GCM,data:INdTXNenuIqX0GSqCgf7k7Xw3YkSdoBCHtz7ruqPfqO5/ll7avSEh9YwpUB10fygn8NtBHUiwJOt/aSxj5SFQOwuVM/w4YO/W7+VII20l29GIIuEA830hOCV3NGIifKb0xOlJI20ineeo0dEL38HLZ8fymXKA89BXXKxivmsoZo=,iv:l0O0GTjqAXqSp4Hn5z+Xvj6F2hF8TFMlofD+TaXq7jQ=,tag:kCOHLi3CqNvLj0INC8AC8Q==,type:str]
    version: 3.13.1
