apiVersion: v1
kind: Secret
metadata:
    name: clinic-api-secret
    namespace: saas-gompha-staging
type: Opaque
stringData:
    GOMPHA_MIGRATION_DATABASE_URL: ENC[AES256_GCM,data:Lgj7016HCecyJryCibAjeTRPj57q1XNXAJ++04xpaJE4UFTxsX3DiVHngkLdaQUfmVqHYiTFJYnJ4Tp226tOZrp3bYkRJv3mNRauWbyWQvxahCL2TaBBYE2lasEe,iv:INWwvHlMSEGaBlGFzfe1nuL+rEGulFVtDfUyDjFq8z4=,tag:rrH3CqCn424y5+wP3NORrg==,type:str]
    GOMPHA_DATABASE_URL: ENC[AES256_GCM,data:fcGRcQtVsz9dYKiENoNuvNB9kLtz7PMESlAhu/6EtvqnKIPT4sI4QD6PFp1GRZasP2HiacL9NUNrp7jFCX3vsZwJ3z8laRfXbpT88UZSJO1o/FgnNHv0UOjiJg==,iv:qMHb/VToaPb9yner4vraHMtpPu39E8DR/yyd74adR3A=,tag:rGu0kxgoGI9xfhfraxGzbA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRkhSTU9XbUovZTdPU3dR
            TklDNGpyVWlhYWxMZnVrVU5kQTJKWVlPOG0wCkVIcVBmczRRaDN0Mkx1bVBlejZY
            U0xkNVJBNDFmN3BBRlIxQVJjaW1uN2sKLS0tIFZ3bWpvWmxtTFJmeVJWb3JUYlkv
            SkM3d1pOcUJhU09HTXMyeHhwYVF4Um8K4wFMoNh98ctNEi1qSuEVtG0hTktGllP0
            uaZfKYA3zEUf4u5HKaa/2DRpjbTuxRgq+jHmP1jhNgMam82DWZhYvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T18:43:47Z"
    mac: ENC[AES256_GCM,data:INdTXNenuIqX0GSqCgf7k7Xw3YkSdoBCHtz7ruqPfqO5/ll7avSEh9YwpUB10fygn8NtBHUiwJOt/aSxj5SFQOwuVM/w4YO/W7+VII20l29GIIuEA830hOCV3NGIifKb0xOlJI20ineeo0dEL38HLZ8fymXKA89BXXKxivmsoZo=,iv:l0O0GTjqAXqSp4Hn5z+Xvj6F2hF8TFMlofD+TaXq7jQ=,tag:kCOHLi3CqNvLj0INC8AC8Q==,type:str]
    version: 3.13.1
