apiVersion: v1
kind: Secret
metadata:
    name: clinic-backup-s3-secret
    namespace: saas-gompha-staging
type: Opaque
stringData:
    S3_ENDPOINT: ENC[AES256_GCM,data:aQukdcSHzXC45nXleHifGzcTgqLPE62hsw==,iv:6DsNTd44YZsvi7lTwFJvMoYZAMBsIjzZhyeuOluMvfg=,tag:dWb/STAUXaFhlox3B6waLg==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:R895sXt0M3cSLFcQiyTMfioQvOw=,iv:r50/q/ipqvpBKXUBkfM7okmtFD4//TavE47Qv3PGEg0=,tag:zHzhCFSxCZ89DpTE5qCxwQ==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:sNRMrgBa07CSN2u5EuLSnpKrJjheYPIY8Rzswjqp0SR3WRCHYsBF9g==,iv:eyml+Wbnjp3g1ZiHaK/+Um4x8BQSeXfM5UjATWHdzts=,tag:5HQqACQTPXE96tJ/W1l1WQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUE9XWUl2RnZjWmluVUo1
            Rk5WT01mNndqRDBUODBURHNXdUZvaXMvaXk0Cjg0eUNmMmtaNjU5bVpXMDYweEVC
            RGt4T0FkUmdGZEZyRTRHT29SYmF6ZjgKLS0tIDJCSUpJNld2T3M1d1N4M1kzZlRm
            c1B1TWhqVnVzVkVkNDc4TlBxZktCeWsKbZ74SmtetAvSRDTmuqRCUXdMlLLYc45o
            xaWFl3Qse/QzwvVn33Euu1uhGrNzIfNljLVUxBa97yi9b8f5zl1kTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYm4wMERMaHBaalJzbzNF
            T3o4eHpLNFZaeG1SRWErTGQ3NW1CT0JGRVJzClRaU1M4bVNXVVZwRjg3OURuMzB5
            MzBlajVydHZTTXJyVGFJamtHSnFpcWcKLS0tIFhOOGs4ekliSWRXcFhiRGlGb0ha
            NjZySnhXM0IzQWsrdnFlMzVmSDVGU1kK4RQ8+e+jrC/cNukbrOWrYhqH77Pmdnn/
            C92DBPdrwpNd3eQR+hMoG5pSW7zdogNhtdd1Dy4IChSwwMMd+wH17g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDelAydktQR2s3Q3BHYk41
            VTZ2aXRmUGpXbTNvaHc2cWkxN2J4SkJwVzB3Cm56eWs2czJTYVVoSVZOckd0Szk2
            UC9LbEk0L3JTNURNVmlLVkNWT3ZzVVEKLS0tIHBiN0xETytDL2UyQTRrSHp2UHdM
            S29LblpPWTQvRkQ0a1ZxTkNSUWZDZjAKC2oS+SYNKxQgJ7lDPRPi1BJgYUuNQ8UV
            qDPBf2mpTLvJYuyCE5rueebXQAdsVBK3qjlQyT8zsIsHX8Gm77OfKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T21:12:09Z"
    mac: ENC[AES256_GCM,data:EE/pDPeVvMFsfClEjZgJzVPQo/4wpxopflBsCT0D69wv5QLOQZdiSS0BE27XTYAbHn7R55CxJEiaahj4MJDj8mXWEX0Y6ymIZu6RcLjBZxEdo8D2D2LlRdHWEFcGI/0T8+Ux3lCJ2yhmfXxqPcB7yjWPc9TOaTQ93euRc0edAQA=,iv:vi4p9x4N3YcM0HciiRo/8BqeIpwvcsf9KFdOD9Ssx6Q=,tag:jrGEk5tg6ve5EFV8OcxqDg==,type:str]
    version: 3.13.1
