apiVersion: v1
kind: Secret
metadata:
    name: clinic-backup-s3-secret
    namespace: saas-gompha-staging
type: Opaque
stringData:
    S3_ENDPOINT: ENC[AES256_GCM,data:aQukdcSHzXC45nXleHifGzcTgqLPE62hsw==,iv:6DsNTd44YZsvi7lTwFJvMoYZAMBsIjzZhyeuOluMvfg=,tag:dWb/STAUXaFhlox3B6waLg==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:R895sXt0M3cSLFcQiyTMfioQvOw=,iv:r50/q/ipqvpBKXUBkfM7okmtFD4//TavE47Qv3PGEg0=,tag:zHzhCFSxCZ89DpTE5qCxwQ==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:sNRMrgBa07CSN2u5EuLSnpKrJjheYPIY8Rzswjqp0SR3WRCHYsBF9g==,iv:eyml+Wbnjp3g1ZiHaK/+Um4x8BQSeXfM5UjATWHdzts=,tag:5HQqACQTPXE96tJ/W1l1WQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcUhjMnZwL2phNnpYR3Ur
            SmFMU0MwcXYvK2hKSHVZMG05VlFOQzZUT2h3CklxdENRTkhScVNjRVl4Zm56ZDNs
            VmJ3dTZ4TlJJTjB2OThKcko3Vkw4ZDAKLS0tIFQ3SVZnTU9GYWhWMHVPOVluZEhS
            VjM4SXRBc1hVY2dkcmIyMER2azgwdTAKIf3MncfBZpPl4NhT7whu9lxQnS2UlBoC
            KRIhCtwvfGAPLrZssbig36EYGY23gOegyi6ins9iyFUT04x9w7H9vg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T21:12:09Z"
    mac: ENC[AES256_GCM,data:EE/pDPeVvMFsfClEjZgJzVPQo/4wpxopflBsCT0D69wv5QLOQZdiSS0BE27XTYAbHn7R55CxJEiaahj4MJDj8mXWEX0Y6ymIZu6RcLjBZxEdo8D2D2LlRdHWEFcGI/0T8+Ux3lCJ2yhmfXxqPcB7yjWPc9TOaTQ93euRc0edAQA=,iv:vi4p9x4N3YcM0HciiRo/8BqeIpwvcsf9KFdOD9Ssx6Q=,tag:jrGEk5tg6ve5EFV8OcxqDg==,type:str]
    version: 3.13.1
