apiVersion: v1
kind: Secret
metadata:
    name: clinic-postgres-secret
    namespace: saas-gompha-staging
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:Wl9KpBQpmdY=,iv:EOOCfwDNYcaQlULv/dW5vedNWk7rIV5wANvpzspIBqg=,tag:0lnD2AkS2xpgzDZ9YpQmcA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:QBXQAYBIbBPT2eb0+EDo/wm4YGTPBt40r6X92Mm36cY=,iv:7FLB3d5f4Cfza6v4QgUTSBBthBRPxRe5wGmRnZjP/dg=,tag:n0W41np7dUhrmvbOQjdVFw==,type:str]
    GOMPHA_OWNER_PASSWORD: ENC[AES256_GCM,data:yJ3n7OFuBltOJBesJLAY2s8J5OQ3D2i1a8gJA2jMkzo=,iv:pL+4dJ9TyKQ4nFprpHIj6yykUYw6bYqh2DC0TZuuaHw=,tag:a5C0QDpgXkBgvDp919WuqQ==,type:str]
    GOMPHA_APP_PASSWORD: ENC[AES256_GCM,data:RTxVRGN3ORS9yeQc/SvAmWrPKsohTxkwtS8SLB23m+s=,iv:4FX/YKnn4JMe+yd/m8dONYZZz9ej6hcylmTCISoXLR8=,tag:lFEDlao4cNmQXYgUNrJF5A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZkNsem1CZlNHNGk1OEZ3
            YVhTK3luSzZTWlJmSWxJRW1NUVc0QS9xWDBzCksvY3dZUGNxc0VvMkhVSjFxZUwv
            QVk4dEFoWDFYekFjTmViOERZdlFpMGMKLS0tIHE1c3RDT1BIa0g4aitqL1JSUjlM
            eUpDNmZRQVBWT2V3em1rZTYrYXUzdDgKy6GoeyPl95zBuWwMEFO1df35tZpOzUcV
            9tcU0icsqWCM/EMudYVDTrsW13PffO/HxA5T9Dt6f72i/iAb+LBmHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bWh5Z3ZodklMNHExLys5
            MjNsQXRXSGR1UFlhZTA0aEd2T2o2MzR3Y1RJClliNjZUNUR2NGYrUThwWVZvTTZ1
            OFZ3b09ZcSttZGVqb1NIY2s1MlZTWTgKLS0tIGtLYm5JWUZ6M1VraGdhaVJIYTFD
            dUZGeTZlRlduai9hMFdlOVpiU1dUdkUKlMULhdrqmufe3pOiiNO5C7yr452/UohO
            1czZkZ28tpVebucB3FZLeB47aKhIgf3jZklMMfIq6Ce1DWNYlno4hg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbWsrV2pRYzRPTXVjdmx3
            SU52WEUzeFpzN25kdkozbTdpS0hFUGIvdm1FCjFSUTFsK3FEOXFycGhsRGs4a0JN
            UXl4WXpnU05JelhPN2pMZXRsTnBKbXcKLS0tIGkyWmZVMmtrVSs2UzVodlZGQngz
            RHU2d25JN09DMS8vNThwd0VWQVhmdm8Kv62ZEVH4Oql4Y78v8tkIu6LyfrTRNYTV
            s7Z18yUWjG2Yf8qgAzMZ/MMX6RtAfH7xh1uDaD5+Y+fF28uzBFbJFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T18:43:47Z"
    mac: ENC[AES256_GCM,data:N4Yz0Pf5ZY8URUEhrYDdQwS94Vu8MJ8vSXZJknPtSlWGJi1XXjYuG55Dg6OHVo/uGQL7CAcpL0IdfKwTM9LOY2AcwMZ56/udQDlJTGb7j5XhRFjXVUhgkYlvzh6ROYGbrMcq8n+6DF8D3eR7JjPJIxa4qpdOwl4xUaWQx/nD/3U=,iv:fogvGQrpeqYi02KLlfd8XZaEQw6/4bLVejvzmKy2tO8=,tag:Qsq+IJNScV7LvxK4WPPneQ==,type:str]
    version: 3.13.1
