apiVersion: v1
data:
    CLINIC_APP_DB_PASSWORD: ENC[AES256_GCM,data:W8DI4ipEVaUgWxO27dWLYIALh/XJv1BLbwMTAdzxEbFnZEnBjOjySb5vfPc/Yr2cdT2HzSMwGPSHuYgsovivHg==,iv:UpQpIW09UbqKK2ctJ6ZJz/rbr2rU8yf6hKrJuCOJ+oc=,tag:kTyn9Ji7qT4qbkwI/kyWfA==,type:str]
    DATABASE_URL_SUPERUSER: ENC[AES256_GCM,data:sv0z//yqeW9TZHkotvpw2jYwm/rB7tiVAhTREjv3NBjEVDtwlVQpxhsVxr2Kggl9ZqCi7NUMguUgU90KmUZ9/OxINY5c0b5Qwr3xFNmtPRANEdzWEc19UJeYuFQMTfosnz0YiSXpcXvn9cdB8dlfQeCEvOJCCD0mlsKM2HiQZS5rFkbEBnASYkKWamxN9Ril,iv:I+EGtAn/cvUVxaOyms36iG2dEbDTASdq6JMHk2rb4N0=,tag:XtCs7NiqtAuBV7KZBBgEOw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:iCvvBpaF7gZs/LI7UmHk5YxnXFhU0vT/yAdkYRDlo4DJ9twpvL1Aw6QUE/kHrWLGkT9c7ZqBhmdQkGegZ0vXJQ==,iv:KX3nV6fjn2aR5ClrRzWCUbTCoSyn33QuyM4MCOiJp3w=,tag:1p8Oo1o8+lfQUBZC82I59w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:PFYvl8EW3kJswvrJ,iv:FSiYRzfUdnOG9ltyMETn2fissDspl+vnsZfIWg23ezg=,tag:Vz6gZVnPHCoRqXLMJNC/+g==,type:str]
kind: Secret
metadata:
    annotations:
        apiVersion: v1
        data:
            CLINIC_APP_DB_PASSWORD: ENC[AES256_GCM,data:HE7sAAYGqmd9Stf7B0+oO/mn3xAswnDhZh5fGBKvnItVFCEBVK/sIV+DPRbgYxrvZLZOlSe94DoFgVIVaadoVA==,iv:jTGX7XNqN1J8TNhiTwHqHelBKhi4AGr/4BuDtdFGZN0=,tag:4qNEaupWquAtufXluavt0w==,type:str]
            DATABASE_URL_SUPERUSER: ENC[AES256_GCM,data:QEl+9vIh5Owt6G6tHNwf9QXJn+kYYy0IBjhr98VLe+2mwIEjChZVmTR3XbNz941f7sUzTAXidvdN03meENNxpCjnKfuq/BQ+17H8M9qDw67dXYZ1D63qq24MgipoINgAR1fjGhBO7Rmuxo9id3k5H1IP8Z/Ie91KXlJz2mbeP2p0ZgzCDq4dzZmFfQIyDElI,iv:wV/E03i7n1klat++q+/xcT1olQAgt9yHYyhOlmZpAWc=,tag:fdhNdHC3yMdQTRq+SvP/4A==,type:str]
            POSTGRES_PASSWORD: ENC[AES256_GCM,data:Yr9he7Xz16YMWYTfIk2IgzGcb95/iiDzzSKW/7tlLyYAeq5Ih8FQ3H+wFntKl09Exxpijq8XLccXxnn05VXvDA==,iv:BNXnCpkjpLCmE82arspvfLvdvgQt7Uiq227BhPfPdT0=,tag:r2JqclPWQZasrM7moA8+GA==,type:str]
            POSTGRES_USER: ENC[AES256_GCM,data:YHs3j/w/kCBmxyue,iv:H4bu9Otn0fHhudLUzvFqBX9aLEJ1En04Fw8PO3mWa2I=,tag:JXDxv9YjWjlAAs+cxt/OjQ==,type:str]
        kind: Secret
        metadata:
            annotations: {}
            name: clinic-postgres-staging-secret
            namespace: dental-clinic
    name: clinic-postgres-staging-secret
    namespace: dental-clinic
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZlhXTjY3SmloMkp3Uzc0
            akZ6elBDbHJ5cXMyZDYyY2E5REVLQkErYkRrCkhjaEZ4cXZwRDVTVXBlRElBQnQy
            Ym9ZNkNqekYyTzZYWDEyQVVnRDA1a2sKLS0tIGo3Skxnbi93OWFIUUc2YUlOakRY
            ZVMwUGZFbmsyZnZLT1c1ckU4czBZL28KS/cU7CAeSB8zjYMlxxJ+dO0nsvZcj3SI
            emDw8IDQO/Kh6K0570854PpeJSaO98my/LSJC4HZdZRKaxOI7XRybg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbEV3YmF0eks0aFJWRDdT
            NFdsWWljUFFCc0poVUdjTkwzYnRjek5hWlQwCklyUk9ESzRCdzVFUmxCUlhoaTY5
            ZE9OVWJ2VjBjaWZndFA3QnBQOFVueHMKLS0tIHBRdTFiZlNEOEdOR1daV1M0a1Z3
            dWZ3S3Joak9YdGZXM3cwTTNxMFp5bDAKbL4D+s4E5TpmfYxvlRcPulI84SKZNo7x
            iDrmRlr21ACKoqHw77pEM7UyJbXQDyAo4dSv5WU5AKsfv/85M8s/tQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubUEyTVk1ZUpZVk1nOEVi
            eE1pTmtIZWVYOHY3V1VYV1NKTUhBVlM2dnljClNkd2JrK1pVZ2dtL2FjRlplNEYr
            V0NxY01ZbFp2MDhpYXBFSkFLTFRVT3MKLS0tIDdZcVR3TWZYWjBzODlGK1JrVGVJ
            dWtHNjQ0RmJFM3p3Y3BPUk1MWThaYk0Kgha5U9apTrn/Ao7PVhhJALgE8hUpXfnA
            M4TwvLXgyjGajcy/QxDd+Ifaa5hfv+zwBQtnh1P8zg+86tdbtDX/Og==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T10:30:24Z"
    mac: ENC[AES256_GCM,data:42lIKs3L3H7SBdc7p9i0L3AaUSeXqUxQPNNnl08u23KP1fWDTymCO2alRTSLE8U4xpThfi+DtjU1XuEvFbPZFbCwUci1dlhruNe7ai2r0rgUpD13ljXJykM/+smK90ii5ZKtJLGqBBemgp0cS2PquTgfOaOzk/0pNAwAMeJncVk=,iv:VagSzT2mG7G4v/tYath4EhpHk9U0Eav+UAy8MBdNMyI=,tag:Z7qMg2IBCfPmAnXpE0MuHA==,type:str]
    version: 3.13.1
