apiVersion: v1
kind: Secret
metadata:
    name: clinic-backup-s3-secret
    namespace: dental-clinic
type: Opaque
stringData:
    S3_ENDPOINT: ENC[AES256_GCM,data:vmVbLwDvIBkoDkxAuTsCf+i4VqU9oqFkUQ==,iv:z4zspClCmA61k+YR5rjiyzdUaBbsO8HU+wsefstDDPo=,tag:dL8EYsgv9d4qgCb10Asakg==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:2NfW+eG7Cd7e3TJWAg==,iv:MUGHeB3M2PNm56Tg9PSeyDwCYAgh+p3h1sZxYH7yI+w=,tag:8+KCcYtuQbzLrGMuKBj14w==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:h8h+WKUEWobqzqwpQQ/AWXTu13DEuJqhT60f4cf3LLHL0nEnM8o5Nw==,iv:egjYLYMR1vZ/stzrfRc9Z2OAHZVfxrhRoE1v1dRd3bc=,tag:btks8uxel9zw81l2UroiiQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNmRpNk9VaXFzWGROcUdn
            WHBRSFpiT21YWE1QNDRyampzbStHY2laU1h3ClBqYnY3bm9qQm5aSkNJWjZUNVdi
            KzVMR0dpZW9EREs2RGNNbVhkdW4vdWMKLS0tIEJ1Zyt4a0o4OE1OTGt6SHgzbHAz
            N0ZPVS9UOU5BOXlUZmFVTW5GUGNYckEK0VIc5iZWeDdDp8M99nErs+2mNIUCHFoQ
            l3DzOBuANGUzfvritBH1YqAOhDZqiYdBhYZaIFS5ac4CDa/dDFtw0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T21:06:49Z"
    mac: ENC[AES256_GCM,data:4yxfI9027MrJPPFGyKdLl9f6FTt4BEa/tOt8S7znWqtvNx1wNbK+pqSFWhfSw1lCN0iRBTr1p1wWmnihs5+tROWbhcZsxrffTs7tTMFp91j9Q8P/0Eza/vi8AU7r8htsi3Fv30Z4n0flslhHSWBff03RiQK+fq3M+QpRJmvSJYk=,iv:oiCFAV/JfaNh7u8LaspyVeQ9EIXG9pCLyydlkRKdD4A=,tag:d5o8j7skf/InIZM5H1zNJg==,type:str]
    version: 3.13.1
