apiVersion: v1
kind: Secret
metadata:
    name: clinic-backup-s3-secret
    namespace: dental-clinic
type: Opaque
stringData:
    S3_ENDPOINT: ENC[AES256_GCM,data:vmVbLwDvIBkoDkxAuTsCf+i4VqU9oqFkUQ==,iv:z4zspClCmA61k+YR5rjiyzdUaBbsO8HU+wsefstDDPo=,tag:dL8EYsgv9d4qgCb10Asakg==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:2NfW+eG7Cd7e3TJWAg==,iv:MUGHeB3M2PNm56Tg9PSeyDwCYAgh+p3h1sZxYH7yI+w=,tag:8+KCcYtuQbzLrGMuKBj14w==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:h8h+WKUEWobqzqwpQQ/AWXTu13DEuJqhT60f4cf3LLHL0nEnM8o5Nw==,iv:egjYLYMR1vZ/stzrfRc9Z2OAHZVfxrhRoE1v1dRd3bc=,tag:btks8uxel9zw81l2UroiiQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQTN4dXdoMk43ZW0zV2c2
            M1NMckh0M3N4SEtRYkM2Z0NPTWp5VEllbXpVCnFVVW0zM2ZnOUI1Q0ttMUdUWnZq
            N0t5SVFaeUZpQnM0bXhFREVPZHZHLzgKLS0tIHorQ1VHdDFqL25SUHRxbXJZVTdv
            VC9ydDhWM05CcU9haFBFLzFxcVN2UW8KmjxJL4YZkod996y1H7YZqI8UjVe5PeJI
            IWeYfE5YeSbK1Xs8q1TK3fNT4G/TjUKbocnomnoWWMzGPfAUolDysw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaU5LNGR1TExJR0ZsTWdu
            MXhLbk5kMGwwc2gxaEgyVkIvUENqaXJadW5rCkt0LzkzRzYzbXBwYXlsT2k0cStl
            USt6N2xzRW1PY2VkK0s4d3I3b1RUemcKLS0tIEhKbE5icE9ueVp4bU9SbWRsSGd4
            Zzc2ZVBzbTVqM1pib25XMGdtQ1VWNkUK7r3zguT7x3oydD06qByDTES1zpS6zJz0
            nBJOHfnFdP/WW3KyHvamRlDohN9HDW5gVZzvPObKG0etgyss0lf4hQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MFoyWldxOFl4WWZBdE16
            Q09VMGhxejY3ek0zRU9ybWVGMGxaY1FSMWwwCkY5N010RjN4ZXFsN0pNQkxWSzJD
            bjZTTm8rMENvVzA0S3hienYwNVEvSmMKLS0tIGpUVUc3TDllb3RHOGRHaTVPKzhI
            TXZNRUIzRmw3UlgyOThYc2RPNDdFUTgKHxZk2kvD/FGnwimUoqEOv0s3q7YCmH0n
            AK3WdjfHKZ5Ij3G1PuuLB0WUHunRIymJTZQIQaWIdWqSka53ofnknQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T21:06:49Z"
    mac: ENC[AES256_GCM,data:4yxfI9027MrJPPFGyKdLl9f6FTt4BEa/tOt8S7znWqtvNx1wNbK+pqSFWhfSw1lCN0iRBTr1p1wWmnihs5+tROWbhcZsxrffTs7tTMFp91j9Q8P/0Eza/vi8AU7r8htsi3Fv30Z4n0flslhHSWBff03RiQK+fq3M+QpRJmvSJYk=,iv:oiCFAV/JfaNh7u8LaspyVeQ9EIXG9pCLyydlkRKdD4A=,tag:d5o8j7skf/InIZM5H1zNJg==,type:str]
    version: 3.13.1
