apiVersion: v1
kind: Secret
metadata:
    name: clinic-n8n-secret
    namespace: dental-clinic
type: Opaque
stringData:
    #ENC[AES256_GCM,data:OlDfzYg++YcN0DIsu9LGPWFqBLwXGw4unK0KwNTwb9pxbHbQp7YxRdFeedKArz0mdnOWrbElSMKHqDYD0KPLvCMHWVJj6Q==,iv:EBjpCOXwQ8CwSZre9ZcJoL7JifrTPG9CgsNFFNqOO+c=,tag:UfuKZb6uUtehYsKoUT1sqQ==,type:comment]
    CLINIC_INTERNAL_SECRET: ENC[AES256_GCM,data:DtX0H+qipclOjabiLqR1KeN5TAUeUwvOo9HooRORb2nmVMgX89iErXWXkK8tXZ2retO6Gcw7vmEYKiQb3T22zA==,iv:TW7+IKWsyyGHgotCsdIFEHRWRw+ueCeukBHxvw2wnyw=,tag:tzN7mLL60/0xpYgXUZz1mQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOHYrRW0vMGFpa0tWNWIy
            VjJxamZRc3poczdDVTJzZlFmNSsxZEw0N2w0CmUySThCWTNFMkhOWVdPMnFlMmZh
            Zm1wUVVBbS9Bdk02U0NiTlRrcmJwc3cKLS0tIDQ3TEM2Q1VLdE1WR0lLQU9rTXZO
            NWNPRzFHR24yb1c3R0dHVkovZzBJRWMKpmioaTlrHBQZ+mklwjz2cakPwh3kPOe4
            oMOhVC4/HUupY1zPS+DGNyawcx8HJpj5UVO4RpaIbNW5iUGJOu4C6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T11:03:38Z"
    mac: ENC[AES256_GCM,data:joiOnwSk3R4HqjQStxTvbNU/m0OgYpEQF1afkxuDqs5d7Jglkrjrf+8PboCm6Y4CBDI1/RtWK+TUwpV6U5mOEa49UC+LPyboZTSkqTvkRBvq7dpWJtyX5mZcGlxyrGmhO+yP1rfdRyq9Hxs3tULcazY6SRYiG4VAcI+/Ybqt5oM=,iv:Q1H74qPt8iBzPsxEuqsnOIMFWxdKiTkPVlcXRwvKI/A=,tag:min0tfn92uCIkAyd0GIgLw==,type:str]
    version: 3.13.1
