apiVersion: v1
kind: Secret
metadata:
    name: clinic-n8n-secret
    namespace: dental-clinic
type: Opaque
stringData:
    #ENC[AES256_GCM,data:OlDfzYg++YcN0DIsu9LGPWFqBLwXGw4unK0KwNTwb9pxbHbQp7YxRdFeedKArz0mdnOWrbElSMKHqDYD0KPLvCMHWVJj6Q==,iv:EBjpCOXwQ8CwSZre9ZcJoL7JifrTPG9CgsNFFNqOO+c=,tag:UfuKZb6uUtehYsKoUT1sqQ==,type:comment]
    CLINIC_INTERNAL_SECRET: ENC[AES256_GCM,data:DtX0H+qipclOjabiLqR1KeN5TAUeUwvOo9HooRORb2nmVMgX89iErXWXkK8tXZ2retO6Gcw7vmEYKiQb3T22zA==,iv:TW7+IKWsyyGHgotCsdIFEHRWRw+ueCeukBHxvw2wnyw=,tag:tzN7mLL60/0xpYgXUZz1mQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5N0tCc1l3RVQ2dFVsTzA4
            ZWk5RFI3NDU4MDlycm9sb1Mvd1NCaTJQWUhFCkFYY2V2SlM4QXZVOGE3Q292bHJh
            WWkzNkZuUzRXMzRhOE1HTHlIQXBjdDQKLS0tIGNNNUljSlB1VHJMY0lLWUxzeWNG
            Y2pwWExxbFhGQVR3TjlTWXpNWHBsU2sKbrw5/8EnFBDWgwg14gciQ+bsjUwbnTOM
            XPEA4IlhOqT4EEv6uLZXbwGFKalXbEvgAGp0AAz5dfmY2Y039carGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZ01lZzNnTWNST2tXTEV3
            Vk1PNkFpamdBWnJGTWk5cUxsV1ZKS0d4aFUwCjZDd3R3U3I4QXcvZDJFd2pGQ2dG
            cnJSYzkvWEdiRFhyK2JoV3RSUHdkNDgKLS0tIGcySTd6Z1Vwc28rV0RRaENlcWJI
            UEcvT21IVFZiMzJKazNOY3lyY05xaFUKFOXwc7mheC49nr3uTKkN46qATUOuy9vc
            yOSuDwcBUKuWCa3K8eNw3K+OjMSNcewCQJH0yh5fSjjxY+c4RH7zpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlaFNkdmlYM0Jzb1VoclQ1
            QmNxUDZJUUJveWNJVEN5SmpSUWJ2NEhVUlRZCmc5MFRNamR1L1VFQTRqQzNuaDU3
            V1JiS1QvRk9GT1IyNVd4SlU4YjFST0UKLS0tIG5VMXJpYmVBZ0RCeGM3ZDVyUWxZ
            d25pYzlNeWhQb083QVI5QU9Zb3hqdGMKHbv9v1NMqFKeo2bnF5IuKsbbD2p7XkWC
            bvlRtbuX3NZBpCXuviQBTHDvZPWcIyN8TtyQocJDHBdu3M6V4Q5mjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T11:03:38Z"
    mac: ENC[AES256_GCM,data:joiOnwSk3R4HqjQStxTvbNU/m0OgYpEQF1afkxuDqs5d7Jglkrjrf+8PboCm6Y4CBDI1/RtWK+TUwpV6U5mOEa49UC+LPyboZTSkqTvkRBvq7dpWJtyX5mZcGlxyrGmhO+yP1rfdRyq9Hxs3tULcazY6SRYiG4VAcI+/Ybqt5oM=,iv:Q1H74qPt8iBzPsxEuqsnOIMFWxdKiTkPVlcXRwvKI/A=,tag:min0tfn92uCIkAyd0GIgLw==,type:str]
    version: 3.13.1
