apiVersion: v1
data:
    DATABASE_URL: ENC[AES256_GCM,data:rDqYp0ZXIUQEwAMsKY2MR7ef/lQeTjf6vykHkg7lSwNxzd12R3DYUmImI6zR/L9OpcytdUKMWp3I0VfM8ZdTiGPtwh33eaRyKsJequ58Ydtho4MAduW/DwozwLGYOfSif+2HJNtYWEiMnI0MFoE/ghzKgEH6+wiNRy0DcnoTm7cTwlXxfkko0wOO9X8Yo8oq,iv:8Lmv23OKdfRiXoMf1ifpeIse8YCbjIB86+1a3kzTxQE=,tag:4ejtU2UyWpkordGOFiJDYA==,type:str]
kind: Secret
metadata:
    annotations:
        apiVersion: v1
        data:
            DATABASE_URL: ENC[AES256_GCM,data:SZX70rxKAmt84plnbXiWVkluSd5aY1BTeNjbNFFmDnujHjq0wtLRH9TdEFvl0JrJ7dXwe0/iDRfRRCeRyYOeLswT/PPTo+dKrqqkkwNS6dicIHZxlBQgKVP3e9ItMh5gYugCduPYIjts5Q0AQXsCP6wp/hU3cCQX4TtKs+xAhFfw48UFvV1OBx5BKFqFx2Jz,iv:7kJvgfaKrYn60W3DR0zer+1UvCUycC7EEyCgz1v9A20=,tag:FpuyRHdKIqyUFNcr5bRnGw==,type:str]
        kind: Secret
        metadata:
            annotations: {}
            name: clinic-api-staging-secret
            namespace: dental-clinic
    name: clinic-api-staging-secret
    namespace: dental-clinic
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxb0lLaS83WHdINmtMWWJZ
            YW9SQTNJNHdyNmY3bTZCakhjbFZ4YXNNdDJBCit0Z2xBR2ZydUZYZUIwMkdaT0Fv
            YUkwcHFMK2Zpbi9WeHd4K2NiUEtCYjQKLS0tIEpPN0NJY2NvaGMrVitPelllRDFp
            TThIU0tuRTVKSk11Z2dKdk91dWx0N3MKEFZfPIPggZ36H3eO884ip90tyxx3LSPW
            HfzEuboG0zjZutp+rmOvV8OhjxlQPS33oa+VyWc2T3TRl9VPPuoHWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T10:30:24Z"
    mac: ENC[AES256_GCM,data:QSGO+i1yOWfaHxmQPAUFbRJOfJO0sFSTO4x0cgpVbJ1uK4Ju4Pcl/mc6lXSswaIh2pPr7TCnH8f6cW0bw5AYUe1n1FG2vHE2ZTFDFtvHxp65V7C7U71bt+l2jqQb4lPwQWp9Q4QNQzIzpcpRvLZsvm++UCKxHkm7LwbtbYOPoYw=,iv:DFqGaQ5PVa3IJaGyQDfF9Hul3dQxPxmInUakCSLFvZ4=,tag:hxcIUF4fg1p8kmZr/VV9yQ==,type:str]
    version: 3.13.1
