apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:ac2MFs5wrKxUK0D4+BifYj13X6eolWAO8lZeWXxrthrMQcIafUCZrX+wyc5c1sh8SU8jnERS0HAQCfX29vjkWDxemEwnzMGqky0NxVgMFcjUI3lNxS0UGfj4V55olrdkW3Bju3PnPZ+tmNaoTi6EO8b3KviFAwjyBbqE7ViUpf1zf38Lu7Yon+cWiDv1gZRaknLWlTD9M39HgIk/11PiYGfZSah79swcRGnn1RAGRAMBv4LamVeqGXGyGEhOLFl5ZKAcr5IZ8Pm7Drm5jOUNrrYGwA9IHGCylv+w4f6M5SSn73ge6PnCmRDYwTQiT0SF,iv:JZxqYavTK35xiK5KOkLqfvQEtR4rAZun6/q9LHbMgXs=,tag:vda0Y/+ygIxuQYSDf4fFqA==,type:str]
kind: Secret
metadata:
    name: ghcr-pull
    namespace: dental-clinic
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkejBrM1NaU0VxamEreXFs
            Yml2Q1dWeHVTOEdxMEs4OHlRNEREN1lUSEE0CkZKTWFHR1pldDFwdGhmZWU3OGs4
            TEJmUVg0Q3l2cHRudHFKb3NwZDRBL1kKLS0tIHd0ZXpvalRoSUoyNW5FejZnTlg5
            ZzFqRmFwcWZXOUN0T1g3T3RMOEthMFEKTx+r55BnY2VaGpiojDFIeEvKHZ3xqRD0
            eiiJkNEeSXCCkHQ4vMCRJRgJ/fZv101l9cMWdPsZAZfuFou1r/QQiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T08:54:23Z"
    mac: ENC[AES256_GCM,data:73z3hEam6D0tke07ou1HQLpbex6GX75oMXUqtFaoRCvDnvwILafOS5/+6vCjKI/EKoGgYAhcrtVGSjhmrAaYFMxWPMZs3bQfxNAZZyZq7A8UXAno0rqqV1rwnLg4gEid3Fk7u0SfqBq4NqM+9Co92jdWHYSNodEjz3zQbN0tTOA=,iv:8PkB0Kb5isrT+GhJ1jA74ZHArWqUf1KJyhoPeZvQ/3M=,tag:TnYLK1ScgJOGrncAebYAPw==,type:str]
    version: 3.13.1
