apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:FuQCvGhFVGnEfCd50v+kUzF0dnFPEe4hBNEJ1W6/LzsLwAvTnF2pngOLxiVovWJLjUzz5qqMU2GEM33mk1cNiVIMIH8PrMxIF/0zQ3Y1eQ1EsZuOrKllUWo6DSvta4Dn5KL1yLaFBn7N9EM6G+v1YxGvErblIpn2BKmKOi+0aq7NVxD0MrB8QGgZ5ScHrFM4BTsaiQDPer/32uVVhYcqc+yR+Wiws9BqpTxRcNqusuro5Mp9oPXFcWSgftUg5Vy3dDSY2TQFfFYalrQ0Tl/6okL8jPo+P3iQBQOVTuhnmHvC6QiUg+JDXwlCgzAMSS/o,iv:jDoNOXRU/n6KBrT1tT+rj8OnpYTPw+VxUgWMvTmyzMY=,tag:8hDiUrivBu8fYmPFOR2cpg==,type:str]
kind: Secret
metadata:
    name: ghcr-pull
    namespace: dental-clinic
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WjlaTmZXOUhxRkxOamN2
            cEw0d1NKQVlZckFTVnJvL0VuaEpCMjdzZlgwCkdzZkx6SG5xQk5XZDJEZGk1dnNG
            OW5Vb1RjVCs5MndROHUvZVFIOUI2bjQKLS0tIGNCZmdDSStWSXMxK3daa2thdEtJ
            aWFoUFJZYWxCSm1BMFNJaG9sTmhZYkEKx1ermfxgNR0IzHri2i5CLSKV+fVNib6d
            NXA9bSi+6mP7gKaCR8BdUuqpsVnpN6nwyBapIh0iM3H0sB65LT5Sgg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T15:20:25Z"
    mac: ENC[AES256_GCM,data:XjsL3ZweNnrXyGyUeAbL52drhcA+NK/++ms/uHMXyDOjCT42jFyfsEmnKh34jeEyB5ZLsV7V4LZOgzU4vjtQlN88rA3nJZrHzjG0YILGOThAMNpJCuCc2p38bGleSzlr0lad4dQ7Yhz2yFhnlKJNnqzIdu1WHv5NYLVGxOPvh98=,iv:eLuQPnge/0BdgaPpsGLaVngY+eYyO3gdOOmuA7lGACo=,tag:Q3T+f6QGZkIRjoZkopxfYQ==,type:str]
    version: 3.13.1
