apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:FuQCvGhFVGnEfCd50v+kUzF0dnFPEe4hBNEJ1W6/LzsLwAvTnF2pngOLxiVovWJLjUzz5qqMU2GEM33mk1cNiVIMIH8PrMxIF/0zQ3Y1eQ1EsZuOrKllUWo6DSvta4Dn5KL1yLaFBn7N9EM6G+v1YxGvErblIpn2BKmKOi+0aq7NVxD0MrB8QGgZ5ScHrFM4BTsaiQDPer/32uVVhYcqc+yR+Wiws9BqpTxRcNqusuro5Mp9oPXFcWSgftUg5Vy3dDSY2TQFfFYalrQ0Tl/6okL8jPo+P3iQBQOVTuhnmHvC6QiUg+JDXwlCgzAMSS/o,iv:jDoNOXRU/n6KBrT1tT+rj8OnpYTPw+VxUgWMvTmyzMY=,tag:8hDiUrivBu8fYmPFOR2cpg==,type:str]
kind: Secret
metadata:
    name: ghcr-pull
    namespace: dental-clinic
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Y21qMnI0RDlXVlZ1RTl1
            T2R0T1YyeHZBVXc1UG9zL3EraFBreFRXcm5NCkhkdVF4TWR2TzU0UEovNTB3dks5
            eWlrQXJQbXZZM0lqZW50WEIzSkdSR1kKLS0tIEJnbTU2THpLVWx6cUNuUzZTZjlS
            MnNPVGpodVlBMGx1WUp4K2pwelFyeHcKU9LMgqcJF1DJ0psnov7WmigfIcbpWYsx
            VibGR54isQsrnEw33ZQlXFYQwZ9X52r/2l0gJmg+1U3JTPW0qlKyKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cHFKZVgyd05xWWFFR1R3
            QTU1dmVNN0JaQ3hqaG5KMTBWZFZWWCtKY3pVCldJdU1jZkJIYTJKNTl4bGc1L0U0
            eFlseSsrVnN2VkhlY1pDM3l6UU1FQkEKLS0tIENMd3ptVlo5d25CdHdQNk9JVzAr
            Z1hVNVJ4NWVxNnE2VjZpdlE3MUk1UG8K6DMORZ+3Yd/aNMSqIXVToIijMyUmr5R0
            sCUOSqpf2bJk5C1UJGc9B1X+30rcz997TpUbN0zg08ud02BZUvjATA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eDFIUmFrcWtXUmlYS3h6
            THg5MFdWYzIrTjVENm1rbTNNK0VRR2I1WXlNCldNZ2x6ak52T0xTUVZhYVpEUXJw
            dFdySUhIZXcyenhIQkhQanB5eU42dEkKLS0tIG5nQ3JxTmlCWndxeXB1Z0UzTG5H
            NFhTWG1TamQxZitFeml2dnJZS0lGN0UKVI3KKyoLDFUOAUrI+jTHp7dcNgu2jCBG
            IcZksmsT5X8fmZrobJzOe4+/GB7vRysSCxskgYxzSdmTMlIDBRjOxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T15:20:25Z"
    mac: ENC[AES256_GCM,data:XjsL3ZweNnrXyGyUeAbL52drhcA+NK/++ms/uHMXyDOjCT42jFyfsEmnKh34jeEyB5ZLsV7V4LZOgzU4vjtQlN88rA3nJZrHzjG0YILGOThAMNpJCuCc2p38bGleSzlr0lad4dQ7Yhz2yFhnlKJNnqzIdu1WHv5NYLVGxOPvh98=,iv:eLuQPnge/0BdgaPpsGLaVngY+eYyO3gdOOmuA7lGACo=,tag:Q3T+f6QGZkIRjoZkopxfYQ==,type:str]
    version: 3.13.1
