apiVersion: v1
kind: Secret
metadata:
    name: clinic-postgres-secret
    namespace: dental-clinic
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:YyGQRT7wPSw=,iv:B0FH3XlzKaa5bVUzjeMLrDhMvg68FhqUu8uilxtQuwE=,tag:8uG8pt4E7wbR6GK8w4+dag==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:4VSKWJCQy4tX0j33xweYkpEE1SJr4lhZW9wJWATEznF8h5l/IBlpYV2F/K0vrY0w,iv:S6dgSkDhbZdZenUYny4KHDAWPw0JGDk4J12wIR68Yvw=,tag:v5wTv9SdEejoiqVsuUpi3A==,type:str]
    DATABASE_URL_SUPERUSER: ENC[AES256_GCM,data:fZp6LMQg1DYDO03fAl/tht4uHRAm1uCxUMtWW0KLPY99Ckx2I0rz0NLme2jpSi0ZS/7iVacQx+CVHX+v+RrBTdUyYIUWKrL8DGznaIKrUO+JEsJ+jFfFBYRoAWZjV5L91Qo=,iv:IodfCC46+zeV/WCpKq4dHq7Yz25np4oT1pjAWzPcHQc=,tag:pCldawSy1zSzL373NPWxtw==,type:str]
    CLINIC_APP_DB_PASSWORD: ENC[AES256_GCM,data:oBfLZMe94+cJMNuf2rCwX5P0xfxBJWKwuy/xWCChuguxy/7apr+CsvcR9ScbJPF4,iv:g/1Nss6TgHRYvpLA5RmLwdGiEs9Jn6juWwDZKr9q1ts=,tag:DlD1tsHZYkAaYYNBIE779Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUFJ1YzdOV1ozeVBCa0Vi
            UTQxL01aWEtMUHRNckZZVFErTlhRQTNNY2tvCjIvUXRScmJKQ2VFT3NyRXhiMElR
            ZWUxam9lMU93NGZHUzJEY01vUVVrbVUKLS0tIFo0OEgrazBuMTZCc3JZekc0NXA3
            c0hLQXhUaXNnZTNRVXdCdDR3VVoxLzAK7QBB4O5G49GybzVxJXz6iEpYAwvzUpPs
            WngwVAcqOp7aQSbebV+ftUkgIj2hxnSSJQ80KlpWoYvSTAE1NLQzcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRkowbnZFeWdjQ1pLdmM3
            ZXB5QkFQMExuUG55U3BSNEx4VElmVUZ5WG5vCkcvYkRHdFAyLzE1SlY4dDFEU01W
            L1dvd2Mya0lqN0NiS21Xa0NxL1g3d2sKLS0tIEV3Ymo3d1Q2SlRYMkVGR3FGUnRu
            NjZ0NjJ4M1hDWGk3Vjk4TFU3SWxwY1UKMNIugDuY1lgr/w0NKstfbKJrrqN5ElcM
            g04uc86SDx+L+Lgva3Q8M0wAdxTLSbUBSKPIO2qb6E+xueBDvGkGLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwd1JLOGNjUnVjTWJhWmhT
            Y0NwN3pSRktIUCtpNkQ1dGRXckZoRXF1OHdFCmpRUS9GZEUzTjRBdERRam00NXZh
            ZmZMejg5aHpJL0dwb0FRNklpQXM5NkkKLS0tIEs0ZWlRMFVsSldHZ0x4Y2JaNjBa
            elVOVStvTFY0ZDRZOXF3MHJOemN1L2sKkZxacIqmWLzmqSWMpX0MdUbtywXxrUSs
            lDXN5Jks22IL0KcN9qSllJ3NjlsGFzwfc6+YyaK+KQiOQaRVbU4u3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T13:03:29Z"
    mac: ENC[AES256_GCM,data:0vjyxO6npXdtLDwbJS7jz0ESw9lVH1c3trqIuKQJ5XPeNxnWZ6950eHmAXvCKpyui01li1H9wzwmDWYkAFkHSj6KQyhadqpzXKaKY4HGeRFOckImnAYSVwHqb0y7zUitM63hATUXF/teX7Mb90S3FutiOfdRb5s9Bi8etzlPTT0=,iv:pSZJ7tzpmoBm5ukyJvmO3ajkUkZMI+Jhx0lyj9mNjxo=,tag:eSl5LN6s5VAj9R2HCPyh8w==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: clinic-api-secret
    namespace: dental-clinic
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:rilDOK0SHIx65mXltDpzj/Vh2zIGUJCPty/JvopgJjomowmUU2YFv2NxihcT1Gl0wHiD+ZRstI0MlgBRHXSgD3PhJsD9/ODvyWIgQc8kv2n8I6FMRpIMdWdKHEMGxeWdwZencw==,iv:LKGNQbmHScU4zzLjaqFO7LDnwOfrDSBRUWx1fgxzgFo=,tag:0YTZmbeGx9QAQQjvcmFgiA==,type:str]
    N8N_SHARED_SECRET: ENC[AES256_GCM,data:Clczktn8A0AJozRRPh3eyN6vgQzDsUdZrOHjrNLKFcxeVLeLLrGkf8b6QZ6asExDohsDqcNt3gpqCCJe4U3Mfg==,iv:F9lQTwJKEMUnmADb7S5i3JaeVea5UkctoMD0Vw2OvmQ=,tag:A1BCXAMMjIMCWyIchqkprQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:hVSJ7C141zsT7vMQQuaCGQ==,iv:zjbUGKJ+0HahRvnTE3gzvtdCLTtTyVHAlxFkF7X7N5E=,tag:BpzwxOjltjvfQFJsz5CiYg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUFJ1YzdOV1ozeVBCa0Vi
            UTQxL01aWEtMUHRNckZZVFErTlhRQTNNY2tvCjIvUXRScmJKQ2VFT3NyRXhiMElR
            ZWUxam9lMU93NGZHUzJEY01vUVVrbVUKLS0tIFo0OEgrazBuMTZCc3JZekc0NXA3
            c0hLQXhUaXNnZTNRVXdCdDR3VVoxLzAK7QBB4O5G49GybzVxJXz6iEpYAwvzUpPs
            WngwVAcqOp7aQSbebV+ftUkgIj2hxnSSJQ80KlpWoYvSTAE1NLQzcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRkowbnZFeWdjQ1pLdmM3
            ZXB5QkFQMExuUG55U3BSNEx4VElmVUZ5WG5vCkcvYkRHdFAyLzE1SlY4dDFEU01W
            L1dvd2Mya0lqN0NiS21Xa0NxL1g3d2sKLS0tIEV3Ymo3d1Q2SlRYMkVGR3FGUnRu
            NjZ0NjJ4M1hDWGk3Vjk4TFU3SWxwY1UKMNIugDuY1lgr/w0NKstfbKJrrqN5ElcM
            g04uc86SDx+L+Lgva3Q8M0wAdxTLSbUBSKPIO2qb6E+xueBDvGkGLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwd1JLOGNjUnVjTWJhWmhT
            Y0NwN3pSRktIUCtpNkQ1dGRXckZoRXF1OHdFCmpRUS9GZEUzTjRBdERRam00NXZh
            ZmZMejg5aHpJL0dwb0FRNklpQXM5NkkKLS0tIEs0ZWlRMFVsSldHZ0x4Y2JaNjBa
            elVOVStvTFY0ZDRZOXF3MHJOemN1L2sKkZxacIqmWLzmqSWMpX0MdUbtywXxrUSs
            lDXN5Jks22IL0KcN9qSllJ3NjlsGFzwfc6+YyaK+KQiOQaRVbU4u3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T13:03:29Z"
    mac: ENC[AES256_GCM,data:0vjyxO6npXdtLDwbJS7jz0ESw9lVH1c3trqIuKQJ5XPeNxnWZ6950eHmAXvCKpyui01li1H9wzwmDWYkAFkHSj6KQyhadqpzXKaKY4HGeRFOckImnAYSVwHqb0y7zUitM63hATUXF/teX7Mb90S3FutiOfdRb5s9Bi8etzlPTT0=,iv:pSZJ7tzpmoBm5ukyJvmO3ajkUkZMI+Jhx0lyj9mNjxo=,tag:eSl5LN6s5VAj9R2HCPyh8w==,type:str]
    version: 3.13.1
