apiVersion: v1
kind: Secret
metadata:
    name: clinic-postgres-secret
    namespace: dental-clinic
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:YyGQRT7wPSw=,iv:B0FH3XlzKaa5bVUzjeMLrDhMvg68FhqUu8uilxtQuwE=,tag:8uG8pt4E7wbR6GK8w4+dag==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:4VSKWJCQy4tX0j33xweYkpEE1SJr4lhZW9wJWATEznF8h5l/IBlpYV2F/K0vrY0w,iv:S6dgSkDhbZdZenUYny4KHDAWPw0JGDk4J12wIR68Yvw=,tag:v5wTv9SdEejoiqVsuUpi3A==,type:str]
    DATABASE_URL_SUPERUSER: ENC[AES256_GCM,data:fZp6LMQg1DYDO03fAl/tht4uHRAm1uCxUMtWW0KLPY99Ckx2I0rz0NLme2jpSi0ZS/7iVacQx+CVHX+v+RrBTdUyYIUWKrL8DGznaIKrUO+JEsJ+jFfFBYRoAWZjV5L91Qo=,iv:IodfCC46+zeV/WCpKq4dHq7Yz25np4oT1pjAWzPcHQc=,tag:pCldawSy1zSzL373NPWxtw==,type:str]
    CLINIC_APP_DB_PASSWORD: ENC[AES256_GCM,data:oBfLZMe94+cJMNuf2rCwX5P0xfxBJWKwuy/xWCChuguxy/7apr+CsvcR9ScbJPF4,iv:g/1Nss6TgHRYvpLA5RmLwdGiEs9Jn6juWwDZKr9q1ts=,tag:DlD1tsHZYkAaYYNBIE779Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdHNsQ0phWVNCMkFqS0VP
            cFMvQmlIbGhVSktyallJYjFzV0tuY3dFSUh3CmxMU0pxOVZkYVNYN0JyM3V2bzlL
            di9yRzVTemtmVWovcWtUbUFlZ0haVDgKLS0tIEtNdlpxKzJTeUlrbStaUklnRXJO
            ZEF6L1FtQitCUGQyU1R0S2pKbzZzNUUKJlFXtDerg+r5yLv6TQn1Lcsvdp5DuxjR
            sSjf75pzIEjEbHTq/rzMoucp+f94K0sdzc0OlNEe5SOtnhaeL9fUhw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T08:36:43Z"
    mac: ENC[AES256_GCM,data:nIWYJUVbCqMJ/QIVY6bi9sIdfP+vZ5EfMxEd7gP/SgrPaL95vgdrGzpLmQU8vO2avK+RTe5mI8DQ+wTVjXDbkMAZ7+HBL+EMBJhYGuhRJ+eg75RcIfSau/Tw5NsSk1HcAfHV2l/so2EjiPrxJmTyJVvnQ9sGveHEN4HYh9+PnmE=,iv:akK55JYNhR5UnRjuzQTzEH0KGuSnZW6jRbdXWWZ3f0E=,tag:E0aFO6g4XmHPjF+SGHmjew==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: clinic-api-secret
    namespace: dental-clinic
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:rilDOK0SHIx65mXltDpzj/Vh2zIGUJCPty/JvopgJjomowmUU2YFv2NxihcT1Gl0wHiD+ZRstI0MlgBRHXSgD3PhJsD9/ODvyWIgQc8kv2n8I6FMRpIMdWdKHEMGxeWdwZencw==,iv:LKGNQbmHScU4zzLjaqFO7LDnwOfrDSBRUWx1fgxzgFo=,tag:0YTZmbeGx9QAQQjvcmFgiA==,type:str]
    N8N_SHARED_SECRET: ENC[AES256_GCM,data:Clczktn8A0AJozRRPh3eyN6vgQzDsUdZrOHjrNLKFcxeVLeLLrGkf8b6QZ6asExDohsDqcNt3gpqCCJe4U3Mfg==,iv:F9lQTwJKEMUnmADb7S5i3JaeVea5UkctoMD0Vw2OvmQ=,tag:A1BCXAMMjIMCWyIchqkprQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdHNsQ0phWVNCMkFqS0VP
            cFMvQmlIbGhVSktyallJYjFzV0tuY3dFSUh3CmxMU0pxOVZkYVNYN0JyM3V2bzlL
            di9yRzVTemtmVWovcWtUbUFlZ0haVDgKLS0tIEtNdlpxKzJTeUlrbStaUklnRXJO
            ZEF6L1FtQitCUGQyU1R0S2pKbzZzNUUKJlFXtDerg+r5yLv6TQn1Lcsvdp5DuxjR
            sSjf75pzIEjEbHTq/rzMoucp+f94K0sdzc0OlNEe5SOtnhaeL9fUhw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T08:36:43Z"
    mac: ENC[AES256_GCM,data:nIWYJUVbCqMJ/QIVY6bi9sIdfP+vZ5EfMxEd7gP/SgrPaL95vgdrGzpLmQU8vO2avK+RTe5mI8DQ+wTVjXDbkMAZ7+HBL+EMBJhYGuhRJ+eg75RcIfSau/Tw5NsSk1HcAfHV2l/so2EjiPrxJmTyJVvnQ9sGveHEN4HYh9+PnmE=,iv:akK55JYNhR5UnRjuzQTzEH0KGuSnZW6jRbdXWWZ3f0E=,tag:E0aFO6g4XmHPjF+SGHmjew==,type:str]
    version: 3.13.1
