apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: immich-lightroom
  namespace: immich
spec:
  podSelector:
    matchLabels:
      app: immich-lightroom
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - port: 2283
