apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-lightroom-media-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.1.100
    path: /mnt/user/k3s-services/immich_database/lightroom
  mountOptions:
    - hard
    - nfsvers=4.1
