apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-lightroom-raw-pv
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.1.100
    path: /mnt/user/ArchiveDSLR_RAW
  mountOptions:
    - hard
    - nfsvers=4.1
    - ro
