apiVersion: v1
kind: Secret
metadata:
    name: litellm-secret
    namespace: ai
    annotations:
        argocd.argoproj.io/sync-options: Prune=false
        argocd.argoproj.io/compare-options: IgnoreExtraneous
type: Opaque
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:ANIsuccL2MeEPQB+31xPPgPOJdDVzKh0xY+71np820gI0ouRwSGV0SFI1A==,iv:Bj6XUFp/gbQ9fbGM+FI/ZLVPtWya4CK0cUR9A65Y//c=,tag:PJf5dPKzSmxXtCWjohE1Ig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YkMvNWo4QVFmRVRQQUMz
            cTRMRDlvbTB4cGx6WmFiNGhqazZsU1dWdnhRCm9lYVIwSW16WEhGK1ptRjUzVGVx
            WkhwOTRsU3BhRm1Vc0tER2p1YmJPZ0UKLS0tIGZrUXhhVW4rL2NmL2VrdXBNOTdN
            eTNrdy81bkVKWVp0dE9zSVJ0TGdKT1kKzhDQ2ktGzHj0VbWuYnI7sC0xN4JMB+tb
            Grm0HKDEHsjEywoJO4Tqsb8BmWibzq7S0ElU46dQDgk8DYGH0AsGfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-22T18:10:44Z"
    mac: ENC[AES256_GCM,data:SbGY9/OaSxG5vvnm5RgAPHyrasdElVOKoxSzZqSIqhJBLJVY3Z5ue8TB+sjjxkdDN5zZc71qqrlLcXdJ3B18vAoLP96zCw0+2vwiJ/X0t4R1jL3AX8wapDCnwxpNjhijSLbEkeZVgA5fwA2p9YG9vM1fPorkSuUnreWTAmn5l6M=,iv:ecPCqwuz+5dHztAvbZDjAqKkhbR1yOaEcD/XcMDdkCE=,tag:mJs3OeFnbve67OuZgcNF5Q==,type:str]
    version: 3.13.1
