apiVersion: v1
kind: Secret
metadata:
    name: litellm-secret
    namespace: ai
    annotations:
        argocd.argoproj.io/sync-options: Prune=false
        argocd.argoproj.io/compare-options: IgnoreExtraneous
type: Opaque
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:ANIsuccL2MeEPQB+31xPPgPOJdDVzKh0xY+71np820gI0ouRwSGV0SFI1A==,iv:Bj6XUFp/gbQ9fbGM+FI/ZLVPtWya4CK0cUR9A65Y//c=,tag:PJf5dPKzSmxXtCWjohE1Ig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOHJsbU1jRWJFdVVKVW9a
            ZSs1S2hkeUJFRTdTcEVxZ0dHb1J1K2Z0SEJ3Clo0V0RKaXJMQklENDZvc0xYejhO
            WFdTdGtMYVd3OW9DUmVXZVh3VklQQVUKLS0tIFNheHU1d1NNbVUwcWhEZTNrdk81
            NmtsNERBWFhwMWI3NDFCT2o1b1VGclEKdXtck2cRnbsISd+jqHzJKmtOPEWse/Ex
            UjLnvPFgbqgWuwt3jO1QGkNqFrsK2Wc1T1naJcDYxwudmFulyUwJYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNTZ2OTVadk0zNlE4S3lB
            bjhXMzdXNWtzNGlJK00yOXU5NU1LbkUrTEg4Clh2ZDFRNGdieitaUVZwMDV5bGhB
            TFhkcS9JeFBvRTR6bldEZ0FUK2Iva0kKLS0tIHZlVUFYVEtCVllERTdPNkhqMk9s
            dE1MTWVhMlFFR3A1TmZnNVYzSTZBekkKamHqdW7wZ+qOaTeTwr/C2E9hFGvrVah+
            rEaimR04NVF/28XHWC32GN/1klw9wFAcQ0mAregmqaoaigZ6WgGDwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cWVTdWdnY2xpano0RXg0
            WUJ5aDd2LzJPSFBnQWVqMEhmb0x0TTAzcXlrCmtzTjhpQTdDMndubUNsUDdxK0Ev
            NVg5ODNIVXFoalVpS1ZyTkFpclhsNkUKLS0tIGIwMHBCcVNlVVU5Sy9XTW9yQXhI
            VHhYSldrSzVldmVoZ3NVNlk5UCtsTm8KArCr1+SjbIM3SDyT41pbVVe/h7Kiw5i8
            KbL1/ls7bWas7787NYzJOgGjaVwp585N+q7ZxD0Ou/jMPTbHK691pQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-22T18:10:44Z"
    mac: ENC[AES256_GCM,data:SbGY9/OaSxG5vvnm5RgAPHyrasdElVOKoxSzZqSIqhJBLJVY3Z5ue8TB+sjjxkdDN5zZc71qqrlLcXdJ3B18vAoLP96zCw0+2vwiJ/X0t4R1jL3AX8wapDCnwxpNjhijSLbEkeZVgA5fwA2p9YG9vM1fPorkSuUnreWTAmn5l6M=,iv:ecPCqwuz+5dHztAvbZDjAqKkhbR1yOaEcD/XcMDdkCE=,tag:mJs3OeFnbve67OuZgcNF5Q==,type:str]
    version: 3.13.1
