apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
    namespace: travel
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:Kt/795tO5Ho2twap6yp9UxIg9swbYHWC1GRBx9Lsb8s4UJ1vQrGnlJ5/UN1y7cmLQ555o6qXgRODjCj1wM5slteTN0iQmB0ItWEiKL31G3fcV2MyW3gqmPIqw7ty5n4nD9WZkP4cLMVqcnXk2WKUOLeuvVxFdkkrXwUiz7kTwGtViPVu8hM9jatqZkM=,iv:8cXICSFEIr1xXVtc918THN6G14dIqPCBYfsnOU4uBU8=,tag:7/kxXWB0ayBECvhdQ17BoQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Mk5LUXpBWlRIUHgyRHcr
            Qk50M2oyZWRiaHkremcyTXpmcEtHc0x1YjFFClpWckFTa1lNM3JzdHhrVWozL2xO
            Z3BpSjJ0bkV1UThFNEhIbyszWFlvRTgKLS0tIEovTzlOMjZ0THBzZnEzQW8wSXIx
            QjN5b1podmFLOG5yQVJ1SGJ2dUFGa00KMXIrT3xMVm4M2n30YketLGVBqR0chF+c
            zJrYhxKbSNeXisHVGV921/OabTd4B9M1+vAO+Aoag0JDGRDkl15gQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T12:11:58Z"
    mac: ENC[AES256_GCM,data:cfROuKQIwFfdU7ePbTijp58ffVXkIoAuA2JAqFdEbv//+iyh4MrkbHl1y5mTj5Pjs9tgTDV+AFk8h0BsQC0hDtn4gHdZcvsMQVxq3lNzyIJkxKLC0bf9+q58/OM93i7GIAdvrq3orKObTnEoopiain2C9nC48slh24iGwfQ8K8M=,iv:c5XW9+6fECWpyKgkIqYBnsy7fD4hzS3F2/nySe8rNEk=,tag:VfPhVD/ZYxVu2PGXypcw5Q==,type:str]
    version: 3.13.1
