apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
    namespace: travel
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:Kt/795tO5Ho2twap6yp9UxIg9swbYHWC1GRBx9Lsb8s4UJ1vQrGnlJ5/UN1y7cmLQ555o6qXgRODjCj1wM5slteTN0iQmB0ItWEiKL31G3fcV2MyW3gqmPIqw7ty5n4nD9WZkP4cLMVqcnXk2WKUOLeuvVxFdkkrXwUiz7kTwGtViPVu8hM9jatqZkM=,iv:8cXICSFEIr1xXVtc918THN6G14dIqPCBYfsnOU4uBU8=,tag:7/kxXWB0ayBECvhdQ17BoQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCb3BmYjdSOVh4REdZOHFD
            L2IvS2RjN3piQ3dTaHVaRldlVG1IVWtrUlVVCmlwZnVwdzhROWxRSGFHZUlSY0VP
            ZjhyK051R2pybmFjeDg4YUd1S2l1UzgKLS0tIGdlTTYrSjVVNEFWREdQRnpzSE0z
            U0d0QTdJMmg3ZnR6S0NzKzFaRkxJbUEKVLTRiABvlKPataYHyFGyRVtQUsk8jU3g
            WQEX+dBAHDVtMLlyC+MZU20gtnsTxV+uQvGGaZtyWxJnNI9paUvCUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRWJVY3kvYUFIVUFaS244
            cmtENFVrNmlNNm1Fc2pWeDROTkN1bld6c1YwCllVMVpkdXlRaVNWKzhnRWZXaUlV
            ZzhWMjNtMThUV3ExcDRxcnJXZzNSeVkKLS0tIGo2L1ZMZUJzbGI5VzFtWTJCb3h6
            MDZzVHg1QW1rcjAwVVQzZzU4alJYVGcK67Vy0ebIYKlou5aA9EoT66K1z61kyC35
            YeGT4NRqJBDkLB6Qco/J0z31apQDFpSsT39HU8Q4bVGR3suiMqTn8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySUhET2tYSXVrQ3dEWEt6
            QTEvWmNyUXRFNEp2YncxT1RzZFNzc1pHaWtBCm9WenZQQ2wzdzV0ZGx4Q1NPSitK
            dUJOUmVLa1lUOHhMT0RZRTh4RE5VajgKLS0tIDhvWXkveGVWZklUa1dzUW1weUdk
            eURKMjIvVjhyVzdPQ0N6bDZRMnV1RnMKbHJF2UP3jG0W35/mhEkvIeXIc2aSB7jf
            aJPWkWPFzjNJdYwAqfyg3G+t733xyOhYDcKD1yA6tcqR9Or4+QA5+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T12:11:58Z"
    mac: ENC[AES256_GCM,data:cfROuKQIwFfdU7ePbTijp58ffVXkIoAuA2JAqFdEbv//+iyh4MrkbHl1y5mTj5Pjs9tgTDV+AFk8h0BsQC0hDtn4gHdZcvsMQVxq3lNzyIJkxKLC0bf9+q58/OM93i7GIAdvrq3orKObTnEoopiain2C9nC48slh24iGwfQ8K8M=,iv:c5XW9+6fECWpyKgkIqYBnsy7fD4hzS3F2/nySe8rNEk=,tag:VfPhVD/ZYxVu2PGXypcw5Q==,type:str]
    version: 3.13.1
