apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:9edwxGG0JTBsEu8gd/YHM+liT/S/+tx5r1hia9nMhmKVB5y2Gb+oqlGxydmJEdbrAMnUignC9cMx60LHtSKDz0ojzQSCFt76qNHjj3EJHNQdiQ0xziOGdp9zW3fCs8Eggxi47ThG2rFneZd5APs3x+TMx5iZvrP7V5xvxqdozfMcz85RHNgLDBql4LACuAqdvgZOm3cDA8bH9ANmjzDTVHDG7E5PEO7kkwl4nUOWwhhkWJLf76YUhV+HNYcdkzjNB1JpL4lZpkCbJ3gk+XKg/uo6TD0vPBBYVFb0RwpduGmQWhGY0ov/SrbvTQACnOEY,iv:eR9ixaa0AMXpo68Kr9dAhw+Rm4UcFW7FAH/hlOq1r+Y=,tag:KF5btTW3fvbpjJAwLkd1EQ==,type:str]
kind: Secret
metadata:
    name: ghcr-pull
    namespace: travel
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocmE5KzlxUkRscnhSY3Rr
            b3Fpd3BqYVFXdkE4Rk1WRFh5TS9pV2k3dXlnCmZNZERMZEVhSE1qTmdUZjBxR3FU
            SitaT1J4M2dmNkFXZmFwaFhocDVjMVUKLS0tIHcwSVdTMTFFM2FHS0ZGWmFsK2t2
            RXpCZ0E2U2tWbkY1bEhOU0NjYyt3a2sK8NjkcvAmjMrWl9I1o1MimDQN6mNzD6sS
            t8B/7CWZhb1n55/ecJNq1Xz0bfVCz/8nS1gGJIMXgRcoNJ/pNlJTIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T11:19:07Z"
    mac: ENC[AES256_GCM,data:xLJ4GEbVwn5TOsnmBdh7fxuKdqzVluXcS1yyrDskhMK3vyEDbxje2kR/hFcs6deNoMOfCUDW0yPzWRivBU9xkBcUKJsjc2WdSOLLn7qSCylZEIR/D8aqYXP0usdxPsDP/rk64OlTUYHskd5yEb1qfEAglmdcIJmxKmbZyx55itk=,iv:N7sVfU3bwtJnK6p2AGFVEcMBhH2VZcKRO4i0P+SdoPo=,tag:OB/psNlWtzO+AIfRQxV0Mg==,type:str]
    version: 3.13.1
