apiVersion: v1
kind: Secret
metadata:
    name: velero-credentials
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:U6m8wbWeTIh+z3wNZ5bHYaf8LQoU1IdvE0kSvvjUDPzattI3XRNiQa0mKiIopGQupWUVKXi/szytTPTlU5wRC8aI4VXHmkn5BJybG5scUs8i7dSD0zBuc4OYMEGXgNb03f2gn7LhzlPtVjSX5y9H7ouVcNw=,iv:S48p2DBRkCjBA0br40WDFEPuo6TPAZFId3fNqNBjvGo=,tag:hts8zVkG62IOyj18yIVvHw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRHlVNVJNNHRiM1JHeDZ5
            akYyVjZIRVZLdWdIZjY4amIzeUtCakRiVmxZCkNCaWN2M0RoWlZMeGsrdEd1aVhn
            ZzJERHFpYncwNTlrREQ1a0ZjZWkwVzQKLS0tIDBWcmV0SHpyMkk0dlR5TG5ieVNC
            cjdtR2EwLzBHNk9mMk5CTnhuYXZZVlEKnI1KXDpxma/hC0CPpuJCp9TD8lu7VDHQ
            OFFlZcVEbdHAntwyxO0mjVMACu8JwO9TG+sU8XIU5X58YjL7ld8xAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T09:43:49Z"
    mac: ENC[AES256_GCM,data:Igdh0t8l9ZwAJNRSRwGZa4pkXakFkPYZTbtjoaVMz1bG40I/5dvZ7IB/5Zizy8/e/3E7UxU6hlh9bNfzk1PgjmSd3BF8Fktnld9xNvy0U3+NwFZhjdSmLyJ7gcy25jY0Aj3KISSnahbiHkQRgxDoTFGdHljTC2VL+AEwIZdRGyo=,iv:CCBG/3Q514E79aFmhk/08DFgWROqQNUCVbqKBRi7/+o=,tag:ATA0psKcbvGIZq1wfB5pdQ==,type:str]
    version: 3.13.1
