apiVersion: v1
kind: Secret
metadata:
    name: velero-credentials
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:U6m8wbWeTIh+z3wNZ5bHYaf8LQoU1IdvE0kSvvjUDPzattI3XRNiQa0mKiIopGQupWUVKXi/szytTPTlU5wRC8aI4VXHmkn5BJybG5scUs8i7dSD0zBuc4OYMEGXgNb03f2gn7LhzlPtVjSX5y9H7ouVcNw=,iv:S48p2DBRkCjBA0br40WDFEPuo6TPAZFId3fNqNBjvGo=,tag:hts8zVkG62IOyj18yIVvHw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicEd4KzI2VnFPSm95UDkw
            dW40ZjZJWnVxT1dEL2cxZEE2eDJMb1BRakFrCnYrQU1CRFJMYmkvVUE0Uk9mc0FJ
            a2JtQ08yazZwYW02dC95ZmNPVjZmU0kKLS0tIEdla0VnK1A3NnZoRklocHJEMzZh
            aDQrcHhUVzBLc3l1OUhlZ25DNjQwQmMKbRkhJNKMqXMv3qVQoZmvnqmqWUpkBgG6
            JKIb8xWS8yMPD2fBKalaU7EdPKgnKVz7sL6tduRbJh/Y3HNdW6FhBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuLzhPZytqc1NRdUl4RVM2
            aFJ2aFFOOE41cmVXeGkzVW5zVXhTT1pHelNBCi9iM2lzajVzclpJZ3hPd3ZGY3E2
            TDM0TXk5VUJwakwyYk1CUHd0dGdsTFkKLS0tIHQxVno4ZmlwYTFwR2pGd240bnZr
            YW1aWEFOMlpjZ2RqSzNiUTZpWXloVmMKMV2DQw1GX24JsnlHpDyEfUWyrGh6lk5r
            af8vVe9Oa7k840h41bJGvu4CdF54BP7SJY2BbRKl4YEGTkMI3MSKsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WjJEQTJyaEFuQXhwTWli
            di8vdmlxSnhDTmFFeGlHTFdQUmxEMW1wbTNBCkQ5alpEZkJnUTgzVDJrZlA0NzRN
            NWw0MWdZQ0RvYk5ubFJXcm9JeUFpS2cKLS0tIElKMFQrQ2gzTW8vVDNDTHYyR2ww
            SkFsd1dISmdKVjhFVkFqd05hSzRZMWMK34DqnbEGEdhxCjLO1DKkmkDccR/e5G9l
            8OaT7NqDJiBoFjJGhPW7jz+9fjbrlEC0F3xkvmx40UP5jjd1mZuQXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T09:43:49Z"
    mac: ENC[AES256_GCM,data:Igdh0t8l9ZwAJNRSRwGZa4pkXakFkPYZTbtjoaVMz1bG40I/5dvZ7IB/5Zizy8/e/3E7UxU6hlh9bNfzk1PgjmSd3BF8Fktnld9xNvy0U3+NwFZhjdSmLyJ7gcy25jY0Aj3KISSnahbiHkQRgxDoTFGdHljTC2VL+AEwIZdRGyo=,iv:CCBG/3Q514E79aFmhk/08DFgWROqQNUCVbqKBRi7/+o=,tag:ATA0psKcbvGIZq1wfB5pdQ==,type:str]
    version: 3.13.1
