apiVersion: v1
kind: Secret
metadata:
  name: velero-credentials
  namespace: velero
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
