apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shlink-data-pvc
  namespace: namo-apps
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
