apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: immich
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:a4exyE4bnyE33PuvIsAcxVDjLoNN8AmawNE5aViS17s=,iv:xSmfEXhWJkFZuhy21PEzbb7ETHlzccdokNwmKJlEy9A=,tag:TfBVTqfECR5Ym1CxOaD58g==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:11/O4U+oxrEDP4I4DOFvNnMZJ3sz3gnQ8daeei7sUBU=,iv:MIU6dlM+garJm4W8dziwUIJADATMuVe8LwnbBznRywo=,tag:EwP1WOeemr048PzTfFDMpA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eFBWY1lSNXAyM3NIMHR0
            SG5WS3F5K3VuWC9Xb05PcUxYeUhFTU4rR0RvCmdlVER6MmNKS1lpQnEyekRwaTlC
            WG8zUGphQTBDb0RkSmtCcjkyYkc4UEUKLS0tIEZzUmJKYmx5NVI4dHdJZGo3NFFn
            NzdiWFVSL2NvdXAzdy82M1FaTUZZcE0KDYL9DBzvQOJZrADYpmTNX/ySxTxPjR1R
            1GydGq97ygyjni1Qqw35eF3HP6u37VShIQYPg+pJ0UBY9Iy1Ad1AmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eVRsMlFYSXdFNVpMUnVs
            UkdVN3RVRzNSOWVmeXczS0t6amlxUGUwTTJBClZtSzVoOUZ4a3ZvRm5tbDRJdXZl
            TTNoNGNhdFRSOVkxZ1JnU0NVMHNzbW8KLS0tIGlFSExPSXRGTGtNSDhTSkcvWjFW
            N3JrUzhtMnNOUXNyZ2JOdVpRTlVGQTAKU9BVKolK81zuecunCGFKWk2K8StzR6N4
            AHE9BkpKa4w3fmaDAcpcbUFeipe3Uzsazp4rlkStdytqyztjdFMX+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcEJzcHh0S3VVU3dIbUgw
            dTBHeVJqNTZWYjc4bE1PMXVuWm1HYXdKRXlVCk1PY1cxMkp1eU5pWlNmU3NIRGo4
            QmlyODhYUlVyWDNMcllSazhiTEZHU1EKLS0tIENmWVQ1NWplOW1iVjBBQVdxMk8z
            UGFXdnZnb0lrdzNzcVY0aTRidnl3dlkKe7SsDgmB5l1r9s7G8d5lxKVVNqHBZSFO
            75BLkf2Lw6JQSschh+Luc86LvHwoDqtdjSJK7Kg4463wp1KRBJKJdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T15:22:16Z"
    mac: ENC[AES256_GCM,data:svNaUqSZPAdqPNUhuM3zvRMxA66QtQLoMuQu2lQRO52yv3S00h60hmPL4bI0d+IkFBdgsUWA+Gctwgy3pkasAC8ekmzdQ6WC5BQtKVRnLQYVG5pVBpPvrUa+WFChDkCfxKnXLDdvU5HqSJqShNVJmK6ROCBwQvAdmqH/RP9/RR0=,iv:KhqXhfgAUXIowEbL8/QKg6Ofw1v7hYvZS1H5fWW3Y7A=,tag:/ltYLjfJlYr2N3rzkJi0sA==,type:str]
    version: 3.13.1
