apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: immich
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:a4exyE4bnyE33PuvIsAcxVDjLoNN8AmawNE5aViS17s=,iv:xSmfEXhWJkFZuhy21PEzbb7ETHlzccdokNwmKJlEy9A=,tag:TfBVTqfECR5Ym1CxOaD58g==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:11/O4U+oxrEDP4I4DOFvNnMZJ3sz3gnQ8daeei7sUBU=,iv:MIU6dlM+garJm4W8dziwUIJADATMuVe8LwnbBznRywo=,tag:EwP1WOeemr048PzTfFDMpA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMjd5TmdyUnA0OXhoTjgw
            VGNOU3pHS09PQ2RQTkxLYU9YZkowbEJCTkhrCitNekptS2MvY1V0USsyWFhuYnh2
            Z29WUktGc28xZzM5QWpmdUluVFRsUUkKLS0tIC95Rnd0QjNBZTZndGpIZGRRS3JL
            ejB3MS91VDJ3NE13d2M1ZEtqd1NFNDQKWr9VcsVY2YZeCxB4/DkEDftf8wMfH7Yp
            LIzcKFjz5lXYwMDd6kqPWiOKz8ypSqFu9GLhfgcBjzH9mvx1dMRuHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T15:22:16Z"
    mac: ENC[AES256_GCM,data:svNaUqSZPAdqPNUhuM3zvRMxA66QtQLoMuQu2lQRO52yv3S00h60hmPL4bI0d+IkFBdgsUWA+Gctwgy3pkasAC8ekmzdQ6WC5BQtKVRnLQYVG5pVBpPvrUa+WFChDkCfxKnXLDdvU5HqSJqShNVJmK6ROCBwQvAdmqH/RP9/RR0=,iv:KhqXhfgAUXIowEbL8/QKg6Ofw1v7hYvZS1H5fWW3Y7A=,tag:/ltYLjfJlYr2N3rzkJi0sA==,type:str]
    version: 3.13.1
