apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
    namespace: searxng
type: Opaque
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:PQlwfSB4gB3y1Ie1bNqIToPFkvxscVA0MI/OW6eC+Zt6zLVuAg7eDV/XF7Upft21lrh1U3FLr3/dcGJQTags6Q==,iv:+mowDfxrIW7IOC1rHW/P3pegjA658UwL+rJ8Tr1RuNQ=,tag:W+mSlUrmjuGoK9UIabk85Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Yzk2T0pSWU9BN0hBajAr
            TXlUTitMMFlJWG5ncit6WER1WmwzaU9LNmxRClkyMENNVEc5M1NSUjhkcFVYdFlO
            OWJZdWpmM0RDYjJiT0RzcDRJRlhIdEUKLS0tIGp4U3Fkd0diTnpETmhzWlJFWE9H
            UkZsQXlBZDAzNmFQY1JxbUwwTzJweFkKI9O0aLkgqgdx7dhHrrFyIajXm20tfnM4
            G6gbiLTFkfGNlvQ7hR2WvjjMWlTiUStzpHHwLyUBM3V5TgfOPjh+cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T23:54:39Z"
    mac: ENC[AES256_GCM,data:Om2eGI9Tkcc46Kl/zkQ48abfecsBIn9rudlY3HIBxNdnl8g4/0k8dSOyi6I9X6gHbQqgJBA+o8xKmZ3pJxnngt/TkFUKLkvaUltLuldCse72fMxi0pKQVnArTfSFyro/7jGAvVS71JShnzPGsMGlSjEoACC9LpL9JYuHmnsvo08=,iv:uvbhjwuWv4S5RDs/hEKFdiKZNPbSymriViBNSQVtHXE=,tag:q/grsuzCU17ZaV8XiAqPRg==,type:str]
    version: 3.13.1
