apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
    namespace: searxng
type: Opaque
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:PQlwfSB4gB3y1Ie1bNqIToPFkvxscVA0MI/OW6eC+Zt6zLVuAg7eDV/XF7Upft21lrh1U3FLr3/dcGJQTags6Q==,iv:+mowDfxrIW7IOC1rHW/P3pegjA658UwL+rJ8Tr1RuNQ=,tag:W+mSlUrmjuGoK9UIabk85Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RmV4ejc2UHI3WHBiMXNL
            VENuTVBqbkxJTXJGc2twUDhWem05dVpvWDBZCjJTZWIxRklPeG9TQVFoMDBUQ0tw
            bjAzOTBpTCtETVdxOUFtNUZOY1ZaVlUKLS0tICs0UFJEbGtudVY2bVVzemZMN3Vs
            cWkyM3BPUVJZVjJVUmZ3OHJMOFl0ZjQKA6MHbbRP6577Obhn8kpl8kV4iRswDKoa
            4TcyVKHDZudiZQPAR3MJ8XHW46fX3K4ijbIENa6UtwjXXO1n+4TRFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOVV0Q2xueDBheFU2U1pm
            QVVoVGZqRW5IUjJMSm94N0p3eG9KSS9NUlhzCmljMWxoN1lOcTQ0OTQxbHYybGV0
            ZTFUNTd5MC9KbEpMOXRoT0MrYjBEMkUKLS0tIHhDNDQvcjVQVXQ3cEUrWkxQZjQ1
            QWhnUG83UExtazlJNjMxaElTdE5IdGsKV8oDh0TNiao9tujm6HQvP4zL9msKlhG4
            2H0qRe6Xiz8keqLHnmssyDZ9+9jV2xyu4taqzFY51tsofMgvgB5lJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3a2svOHpQZk5hc2NpZjJu
            Y1diY0hMT0UzR1lRU2ZVMFJiQ2J5TXp1MTFNCm1CemVNb2llRjFTWXAyRTBPL2ht
            MmxUZTJoTkFQZWRoWmliQXJ5RlFlL3cKLS0tIGQ4MTY4NlRuS0I1VE9IK09wcEVL
            TVlDQ2pEeFhtTlVhSlJRMlNxbHN4eXMKjAN0V9tjYTtFwDH9u8l4TV2lAMRSKLIE
            w09Aocul58uRw+l5Noht+L6vViqXS5HuWMTryp1fy8s2vWRHogEflA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T23:54:39Z"
    mac: ENC[AES256_GCM,data:Om2eGI9Tkcc46Kl/zkQ48abfecsBIn9rudlY3HIBxNdnl8g4/0k8dSOyi6I9X6gHbQqgJBA+o8xKmZ3pJxnngt/TkFUKLkvaUltLuldCse72fMxi0pKQVnArTfSFyro/7jGAvVS71JShnzPGsMGlSjEoACC9LpL9JYuHmnsvo08=,iv:uvbhjwuWv4S5RDs/hEKFdiKZNPbSymriViBNSQVtHXE=,tag:q/grsuzCU17ZaV8XiAqPRg==,type:str]
    version: 3.13.1
