apiVersion: v1
kind: Secret
metadata:
    name: documenso-secret
    namespace: documenso
type: Opaque
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:bKdwqj2YLm/5ipwJzBKkSiSLQZSQwEmehZSVBxchFK48MdeFtkCxmer3Asg=,iv:CIrXp2LrksAb1Y73l0i89no7yU/8z6abMwMnl2kMCpc=,tag:yn0TOyGJmusGCsXUXwnhpg==,type:str]
    NEXT_PRIVATE_ENCRYPTION_KEY: ENC[AES256_GCM,data:PwXEuiyRvKsFQLtQVZuGVATYPSvOPARXn9Lj09UTipe9sSMhcE+rKUhWvkQ=,iv:qDipuKsP/tXJwRqqp/utsvhajl9RlrUvrGzvNFAd+to=,tag:Tt0bLqUy9E/eE+7xL24eEA==,type:str]
    NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY: ENC[AES256_GCM,data:6WF7T60V3ANbrbrwSvufVFCqo6r543nLT9UwCSE6jzqgbriIa2rhaIyhfu8=,iv:jFctB9H4jmk/oEFoQA3/T1bgtl4Ny/KnbULP4bcIqy8=,tag:RjmtnjG4RuQ/lnXAeifXXQ==,type:str]
    NEXT_PRIVATE_DATABASE_URL: ENC[AES256_GCM,data:fc3HUaKI3w1I68/wOdzZ8Anrjawe/QibQOV17+9a4H7RHnGiDRlQSbpv+5DzO9OnFiUGXgb2nru/2R4YAFtwg5arICuqZhrBV2JyfzP6Z5wiPFz1Cges/86/oWnLFxmjuf22aNeP0WJ7aRoEWdwuYOkI6w==,iv:PyGxDAMhPlneQf3DDUdhqK8rNb7nBHjm7A2qHE+naRI=,tag:EjxQMkf6xuU5m8NfXAMQkg==,type:str]
    NEXT_PRIVATE_DIRECT_DATABASE_URL: ENC[AES256_GCM,data:s5VTswUIZmSvMl0d2QaiKT54cxsReLlxPWl7FpGBu7WjeLkO2nqDnBYMxbn5YQnepfQZ9AXcmIc91ZfSukTd95a/UUrCTug7PSt2P+0Wj815PYaVu/wGCPng4jav9U4Sg1QFuWsHnAgm7wfnYM+JQJrztw==,iv:5AS9y9AvKEyq9UXrEw9+tWZWP3kG2p2MGeZLzmSyDWY=,tag:CwS5X5OBB/H+Riq2OhEOPg==,type:str]
    #ENC[AES256_GCM,data:W9vhjMMLg9INFHSW9W2zvXR4+E2bm6G61/C3z14euqU93rW3gPfJvcEFPTJHSdQZr/k9TH1Fb3YFerPG1VTmJR2GE0nN0ShIpVspqoP4HnmWNT63enaIiGo=,iv:N+nSRZyfb6JxStENXIJZSlr3QeYmcnOycyflgT6pZ6Y=,tag:WnW71B2nvfZ9E/VDEbJhbA==,type:comment]
    NEXT_PRIVATE_SMTP_PASSWORD: ENC[AES256_GCM,data:BobBYw4OLbyFn4IpHFBBlw==,iv:H0cxQonAK+hI63DazFBmGB++CZ6DHGuVlGIZXBAL9Cs=,tag:P81ZawFIRZnej4+Comg/7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHN0pNMFQvYU5tdFN5QTY3
            VkVUcXhVaXR0cFRnNnY4bzFtL1hwWGZuV1d3CjhZQnR4S1hzN1o3N1R1RG5IdnZw
            dVkrQ3Z4elFUMDhOdlIxT004OGVRcTQKLS0tIFljWEwwYmJzZzI2cEJpbDhBT0dv
            eTVPTlVXaVYxcUR6Tit5ZjE3QlRPZUUKk+dy0wqs4BWOcKLWECtO4uCi2ob8CZ7A
            BksE/gEe/WxQ3xYqChj2UoOCXjJk6ZMHs1MpnGe2ttArJXxuXfwWzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T09:39:38Z"
    mac: ENC[AES256_GCM,data:qUFvxjDdeUre3lyMqPhAIONr/nQf0zuNPnSPeh/YgoFPcRexsryIgj/2DZAtiZWHfhm8Los/Ifr74NCzww7fC5eilfG4U7hQd82sOPgH+jfxYOgzUAW0QP+hv6NWERlOVx5IstqrDXVmfhEqI9Sd6EeM7LCG3mSxQMEpaYE+cIk=,iv:6ivp8JqXPyNcWFX9kMiu7qQsqDwNgJW/L75f9TgJmGk=,tag:erOtGGptCxasA8vlVRVA/A==,type:str]
    version: 3.13.1
