apiVersion: v1
kind: Secret
metadata:
    name: documenso-secret
    namespace: documenso
type: Opaque
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:bKdwqj2YLm/5ipwJzBKkSiSLQZSQwEmehZSVBxchFK48MdeFtkCxmer3Asg=,iv:CIrXp2LrksAb1Y73l0i89no7yU/8z6abMwMnl2kMCpc=,tag:yn0TOyGJmusGCsXUXwnhpg==,type:str]
    NEXT_PRIVATE_ENCRYPTION_KEY: ENC[AES256_GCM,data:PwXEuiyRvKsFQLtQVZuGVATYPSvOPARXn9Lj09UTipe9sSMhcE+rKUhWvkQ=,iv:qDipuKsP/tXJwRqqp/utsvhajl9RlrUvrGzvNFAd+to=,tag:Tt0bLqUy9E/eE+7xL24eEA==,type:str]
    NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY: ENC[AES256_GCM,data:6WF7T60V3ANbrbrwSvufVFCqo6r543nLT9UwCSE6jzqgbriIa2rhaIyhfu8=,iv:jFctB9H4jmk/oEFoQA3/T1bgtl4Ny/KnbULP4bcIqy8=,tag:RjmtnjG4RuQ/lnXAeifXXQ==,type:str]
    NEXT_PRIVATE_DATABASE_URL: ENC[AES256_GCM,data:fc3HUaKI3w1I68/wOdzZ8Anrjawe/QibQOV17+9a4H7RHnGiDRlQSbpv+5DzO9OnFiUGXgb2nru/2R4YAFtwg5arICuqZhrBV2JyfzP6Z5wiPFz1Cges/86/oWnLFxmjuf22aNeP0WJ7aRoEWdwuYOkI6w==,iv:PyGxDAMhPlneQf3DDUdhqK8rNb7nBHjm7A2qHE+naRI=,tag:EjxQMkf6xuU5m8NfXAMQkg==,type:str]
    NEXT_PRIVATE_DIRECT_DATABASE_URL: ENC[AES256_GCM,data:s5VTswUIZmSvMl0d2QaiKT54cxsReLlxPWl7FpGBu7WjeLkO2nqDnBYMxbn5YQnepfQZ9AXcmIc91ZfSukTd95a/UUrCTug7PSt2P+0Wj815PYaVu/wGCPng4jav9U4Sg1QFuWsHnAgm7wfnYM+JQJrztw==,iv:5AS9y9AvKEyq9UXrEw9+tWZWP3kG2p2MGeZLzmSyDWY=,tag:CwS5X5OBB/H+Riq2OhEOPg==,type:str]
    #ENC[AES256_GCM,data:W9vhjMMLg9INFHSW9W2zvXR4+E2bm6G61/C3z14euqU93rW3gPfJvcEFPTJHSdQZr/k9TH1Fb3YFerPG1VTmJR2GE0nN0ShIpVspqoP4HnmWNT63enaIiGo=,iv:N+nSRZyfb6JxStENXIJZSlr3QeYmcnOycyflgT6pZ6Y=,tag:WnW71B2nvfZ9E/VDEbJhbA==,type:comment]
    NEXT_PRIVATE_SMTP_PASSWORD: ENC[AES256_GCM,data:BobBYw4OLbyFn4IpHFBBlw==,iv:H0cxQonAK+hI63DazFBmGB++CZ6DHGuVlGIZXBAL9Cs=,tag:P81ZawFIRZnej4+Comg/7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSTZpd1BqaFpkZE54RVZR
            bEQ2eEZUcUJCWlhIcGJ4WHo4SldLK2FnUVhJCkZ5RnVpY3Rzc2c1VmNtU0FJU0JT
            WkFteXViQUQyeVV0eUdPZHduSDA4UkEKLS0tIDlKcGZxdytkZWRSVkFUZlNZSkNC
            WHNaMXJJelV2RE53cmQ0WFhYN1hMS3MKqJHgHktdHprpE2kIYCO8/0+XO+XA31je
            ID/8apRvQ3Re6sur02agxs9S62GFdvGmQcp/mcQ0whby61uT427V2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveXA1a1VEakN4SzEyVXJl
            SXI3TEM3QldSVUt6REE1Sm1kek9ZQTVMaDFvCnNTcU00REJDeEZmSVEvMWh6S3FH
            ZmJuOHVHaDNqbVFxTlhLdmY1bjZPN2cKLS0tIEpRcCtlaEhSckhHN1lreFpkTkk5
            TlAzN0RWWmFPTVhwakd6VEQ2QndRdkkKC93BaICKVw9ikJD49yCbdmK4Q2v/px/c
            R/h7jL8s0D8mJmCO8T9XAjMv6pVvAQPbx+ZKPqNyeHHe0y6Fu+u3gA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMzR3Qm9pbmx4bVp0Wktl
            a1hlelJVUmI3UDNyTmpZcTBLbHJzWjJ6dkJJCnFLME9vVmd2R0RSVHpjWkpTcFB5
            Y01ydmVLMVMxcWhpKzV1bXplN2F6ajAKLS0tIGc0TEkyNWNGNmczTUVEOENaTFZB
            QWdYdWFYOXJ5RnYxcVZIRGZJRVM4NlEKX6ss2qeEM3kS05Z6/F6EtRZrMToKHg/F
            9oERYwK8n7hOufGMd9iq5tE5A1TBi4QMJ9q518tQoo91SLY1z7pthw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T09:39:38Z"
    mac: ENC[AES256_GCM,data:qUFvxjDdeUre3lyMqPhAIONr/nQf0zuNPnSPeh/YgoFPcRexsryIgj/2DZAtiZWHfhm8Los/Ifr74NCzww7fC5eilfG4U7hQd82sOPgH+jfxYOgzUAW0QP+hv6NWERlOVx5IstqrDXVmfhEqI9Sd6EeM7LCG3mSxQMEpaYE+cIk=,iv:6ivp8JqXPyNcWFX9kMiu7qQsqDwNgJW/L75f9TgJmGk=,tag:erOtGGptCxasA8vlVRVA/A==,type:str]
    version: 3.13.1
