apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: documenso
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:HuabCNuWp1dw,iv:iAWAbR6QpIPB+2zzOB21HHPHgqdCLj3fzj0mMYZIAxc=,tag:7CH4z1Fg1w5wECd/LEFdDg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:4rWlY87ie9htDTg5Lb82d4cJ30pUZoQmAJJYVn3UkjAtd7ekOOCTyA==,iv:g4gDcZV3h1uvrweGqrt92hpMLbuf+Fw7YAKpajcjReg=,tag:Kg+fYQXi1mQ6me1huQ4J1Q==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:80bUD4eo1cA3,iv:55L8FGystZ5rJaY2jPwcFDMCCSQr0L1ZtNtmZzVChPM=,tag:h3wg1W8QvsUqFZRRcmOWjw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SlpyWW1IcUtlNG5qWjAz
            SUgrb3RLTm1GSzFHaXNUZk9JMkdtWEVNUWlzCmVQN0pCM2d0TEhudUc0Sm4wWDlp
            NFM2ejArZVlGOTA5VTJzVDZDMnV4TDAKLS0tIHhIS3FJaVBSbXlqVjh4RVZuR2FW
            WGoycjJhZ0hzUnh0bXFNcWZJdjlrRUEKjsaXMB7NIm0o0mcQ7adgYythyWOAO0zZ
            iqYTntc82r34brChKxDffw3bqvfDnzjiCg8JzowJ0kHO+HoxrFrLbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T07:17:12Z"
    mac: ENC[AES256_GCM,data:v4gu4SzbOCZaXzfieGS/Y9UQXG8GxDb2LvpjIamhGHVVjygK2hfVK+YNczTQTm+5UG4GkZeDeTKzGJrbOseHO5pEfhuc97zrFDgS4jyZWE/b1oqqg36u7kki7nHFeXy8ceHxBbKtlyCCD0QRAD/Fb+rM8amyxk7Tmk5E85qJYf0=,iv:qoFp7MAROo1icDbEhsIDY0VS3Ryimxo2+FptK49lfDY=,tag:YXw9ujDYU+VVdZSL838sUQ==,type:str]
    version: 3.13.1
