apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: documenso
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:HuabCNuWp1dw,iv:iAWAbR6QpIPB+2zzOB21HHPHgqdCLj3fzj0mMYZIAxc=,tag:7CH4z1Fg1w5wECd/LEFdDg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:4rWlY87ie9htDTg5Lb82d4cJ30pUZoQmAJJYVn3UkjAtd7ekOOCTyA==,iv:g4gDcZV3h1uvrweGqrt92hpMLbuf+Fw7YAKpajcjReg=,tag:Kg+fYQXi1mQ6me1huQ4J1Q==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:80bUD4eo1cA3,iv:55L8FGystZ5rJaY2jPwcFDMCCSQr0L1ZtNtmZzVChPM=,tag:h3wg1W8QvsUqFZRRcmOWjw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdXoxandVTklmVEorY3lw
            bGJvWGlKUWplYmluREhSa3pIV08zYXdHNzBZCmI5Rm9zY0xrSkh1T1NzQ1FqZE5E
            bU0xSytLb2k3S3ZNOVFHSTBwakRFeHMKLS0tIGMxRUJiREZYSnJob0tVdkg5NDNu
            MDZsdUM3MVVUckgvTlhpdVcyZHpOSmcK6frOa/W6rIEQp3sObCGc7r1hBprHuZlH
            B3DnIpmUVRW2UwctlYBC7JmegOfvOxEKFuNgUqOlS/YdMV2GSG41gg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdUpwOGpRVXhkVFhIQ0Y1
            VHNEV2E4UEJpWnJ3SVRnZ1M1VzRNdGV1TGgwCjRnU09QTHlqVzR0NUJaZ0RwUWxk
            eXVhVjVUOWdNdU5CYjBQWUUwcmJPTEEKLS0tIFJ4NzhSWHYzYWYzM2VseVRUNG9x
            QkVSNU1xVk1SQmdrclc2WjRXYWJ3eWcKKBjN7Ek/XQrzHt5tZ+sb1mORpFxGwvCE
            i2ggwNpCsHepUvQ/tqZAfVgoSW4ANqKiMG4rk2DL4l1boXgKY2os5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNlo1MFE5dmdJY25VVGlK
            aStEa3gwT3FmMDJ5YjFQSWdOQ3F6WEczWUVVCjg5UVVGTVdTYWYwZEwwcGp4clQr
            VzNLRVRadDNSU1BUdk10VFlyd3B4ZTgKLS0tIERRWmZnc2tRanVBUStrRGJ3QzFY
            bW5xRFlqUjVWV1NrOUFReS95UG1GTGMKbK8OzG6qaoY+NYbSADas4SIRFBQOfoC7
            ZrV72xjweRsAABTVM2ITUwv0ZkFpqOYrFVYR2P/Wp/tg6IXUepVZfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T07:17:12Z"
    mac: ENC[AES256_GCM,data:v4gu4SzbOCZaXzfieGS/Y9UQXG8GxDb2LvpjIamhGHVVjygK2hfVK+YNczTQTm+5UG4GkZeDeTKzGJrbOseHO5pEfhuc97zrFDgS4jyZWE/b1oqqg36u7kki7nHFeXy8ceHxBbKtlyCCD0QRAD/Fb+rM8amyxk7Tmk5E85qJYf0=,iv:qoFp7MAROo1icDbEhsIDY0VS3Ryimxo2+FptK49lfDY=,tag:YXw9ujDYU+VVdZSL838sUQ==,type:str]
    version: 3.13.1
