apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:+l+2HofPBPwyNcbDwbQXh0KvFn5K3AbXD5u2jckuf9yFjY9eatco1rgTXkCxfsPiuDs8H60AUfBV7x79ZOrLQjWGVJxV9qJFaJKCJRwnrsh4UfhWBsWHWgkIYq0VLq+z+UTZvB2trmPvKtvnFyhZ6Ti2EV5TQ7xXe9SyYWNMRURfynaoAW4QivuhO+ExXAvITmP4j6/pzwLVl7wMSnXZtOtq3ok9w3C29O4Ud3wM8bFvsLHETxljzF507OyfgONwqdEidEnc2hZBXpbko0vBgXqvvn+3Sqfwgm9rVQKFn3SitCA2PzPMsBq8LA1AfRby,iv:HBlPWf+Sbn0lHryBfxMLnOoNgh9ZNl5rJwQ3xS46h/I=,tag:JdG22CWZQs1Qr2EUayCyJA==,type:str]
kind: Secret
metadata:
    name: ghcr-pull
    namespace: padle
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMnQ3ZEg2cHNmOTl5c09N
            amo0WE8zaG9xalRQZ2pzb1pCTE5PRTdmdEhvCnRaU3l4cllDdjV0aHJIZTJxUzNH
            Z1lnVlZmTElSVEJrUnozZ2FXcGJpOE0KLS0tIDZTRFN4ZmNqQnNUZ2g1cU1CREhB
            ZWFsRmE3WGhqdm9tcHNVZy94dW9RemcKvuX8OhwBjC5lUAu0xEJSorjo+h+OWKwu
            X9QW6+XKnpCiLI+SwQDnNXyT5Cu3m7hix7TEhf559OUGCrmKUGIfMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBON0k2aURXblRuSUFjMGZG
            TW1aN2xMQU1GQUErVG51YjVCQ1NlRXZwcFJBCjZpY3RKSnZGYVI0eVEwL2ZKNFFu
            a2lSRS9NRVNzdjhUWFkyL3BhSUpWdjQKLS0tIE1CWjdhSHNpcEdlUGY3ZTI5MnJW
            WERwTlQ3MDEyM0tLWXVPYWVoTUVOWkkKovxZf3j7rImxJIVv1jU8EyBGIAlcPv7L
            khH62MvEc73q3RDLs69kVdzK7oGuh5fSzVSUPO/RXTLbdpU/T8Uxbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRkFEVTRXaHFzckx6WENZ
            MzBXTm1nSWViL09PUXJDaGNsMHYyRktSaEJnCmhBK1RRdXZvWG5Ham02T0RHT1Mx
            T0ttMjhpVGcxZVRZT21CaU9jb280LzgKLS0tIG5LRytPUzk1cFRsNnRiamd2a2s4
            cWVLRXF1RGQ1Mm41YmFzNWduViswcVkK06UIifp/PIsNat5Rs6zRsXLY44c0LeET
            H/mO/+zY8KnYGUQHx962DUJrBQtalZiZErf3UwaoIppGDmM7jFyNFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T15:20:25Z"
    mac: ENC[AES256_GCM,data:Hxbr7SgJbB5MvBWffV7sWdtVUjo+Wfi70bsGwyU2R/lpZ9oDL0vURku4IlW7EaJ/+EK82UeG300a7fXd5GyYyXh+lCUKk3WQ1IMzFMlEdHukPitKJ4L7W5zLjEZCEkLscQisiP81EdHjQNixmS4xRjWhRmdl0FdttIRjjng3URE=,iv:POuu6kTAnwY7h+CAjlgCR0L2F6CBvO9mnmVMdVYE3BA=,tag:x9fdG5VsCSrdupaCLvXgmw==,type:str]
    version: 3.13.1
