apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:V/yh2DvWQgBvDDUkorqYPHoXaOHkx1m7BnawEwokg/YI1IYPdoaNSrq2C3kEaxV0LnusaKC3vA39fhrGECmwkeQXF0xLlXNX3G25A7r61e/+7gVkJ2+XgBKdJGu6UjGKtqVGxBc48c5a8F4DLx7r5lpTRu7DG+bHYlHDopNGeQisVh1r6BeAWxyj7001ilPGzHKiBqlg5mnZSmy2EujLdgz/4H2fkUIHHJ/+EPv1qWRUfzZKnwaYrmqnuk4fzCP2hiRC39XAVOrxiAWrRB27zl9e2jNiKWI6MywGCTbXhx9maOg9JT1MZ7FgZ9FopPJz,iv:OYrrUFkA+i9T35XdvJRL01ijOiXpoc5zbFjDoAPodVE=,tag:WyJ5lLGbioh50Gc5vcS29A==,type:str]
kind: Secret
metadata:
    name: ghcr-pull
    namespace: padle
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTmtrVEFJdTVQWk04c080
            NVV1T1dXMFZGTU9IeU82ZGFYU3JvM29aZ1VFCmtGaHdzbzYvUkZNbnhhMTFxRDg3
            OW1CTXRTODVVbW54VURtWHJUMTV1WWsKLS0tIDlMMHhXbllaSDNZS1IxV012YWZE
            MEdjcUVBZ2lFaUlvMTVUZHkva3R0cGMKj1wMKaiwFSVokjX3Q4Mh1bwMEqx12n4F
            zt8gXox0hvInxR1SUsKjR18DDbCV+2ixURW2PJIA3sRLznmtduLJfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T20:26:05Z"
    mac: ENC[AES256_GCM,data:QD2SosQupyo4W9/JOk/ZO5fkVygitXeSUiSlRmJ8uWk67KPG1MWLaJvUYpGHB0D26b3+wYjKEe0b9QLvGpjSLIchg6VKLBVctlTsu6UIGWOSbTFkq4CPhVZhRxmIYfA+Z8asLb9Zl08lRVGctu9NJVBUwfvdxnuZAdc0N11Tk4U=,iv:pVATSgWpJJ5c9vSlIACYXKS50N6A0bP2Rsx0jNfVNFg=,tag:7OtDQOweuyaN88pzSYPl6g==,type:str]
    version: 3.13.1
