apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:+l+2HofPBPwyNcbDwbQXh0KvFn5K3AbXD5u2jckuf9yFjY9eatco1rgTXkCxfsPiuDs8H60AUfBV7x79ZOrLQjWGVJxV9qJFaJKCJRwnrsh4UfhWBsWHWgkIYq0VLq+z+UTZvB2trmPvKtvnFyhZ6Ti2EV5TQ7xXe9SyYWNMRURfynaoAW4QivuhO+ExXAvITmP4j6/pzwLVl7wMSnXZtOtq3ok9w3C29O4Ud3wM8bFvsLHETxljzF507OyfgONwqdEidEnc2hZBXpbko0vBgXqvvn+3Sqfwgm9rVQKFn3SitCA2PzPMsBq8LA1AfRby,iv:HBlPWf+Sbn0lHryBfxMLnOoNgh9ZNl5rJwQ3xS46h/I=,tag:JdG22CWZQs1Qr2EUayCyJA==,type:str]
kind: Secret
metadata:
    name: ghcr-pull
    namespace: padle
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eXFTbmVSUGhtdzl3NDEx
            UU4yM3l5aWVoZUJFTWV5MlR3QmdRVUNnMFVVCk12WU5ITUpteEM4VDd4WVhnbVc1
            aVZSQ2lQQi9NNHZXeGJhUExVenB3bW8KLS0tIFZIL3BaK3FJNjFGQUpKKzF1VGRr
            Nzh5b0E1MS9CaG1MbWJOekNJZ3VzRTgKmTk4fm9wjF74ackBDAmdCVNWBlSOflQv
            2/g9z3BvwmSwfKSoy4wc4UpO8JAyshvMP5zC4Ktkdj7SpeBbpoI3oA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T15:20:25Z"
    mac: ENC[AES256_GCM,data:Hxbr7SgJbB5MvBWffV7sWdtVUjo+Wfi70bsGwyU2R/lpZ9oDL0vURku4IlW7EaJ/+EK82UeG300a7fXd5GyYyXh+lCUKk3WQ1IMzFMlEdHukPitKJ4L7W5zLjEZCEkLscQisiP81EdHjQNixmS4xRjWhRmdl0FdttIRjjng3URE=,iv:POuu6kTAnwY7h+CAjlgCR0L2F6CBvO9mnmVMdVYE3BA=,tag:x9fdG5VsCSrdupaCLvXgmw==,type:str]
    version: 3.13.1
