apiVersion: v1
kind: Secret
metadata:
    name: padle-secret
    namespace: padle
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:jJxZrEM=,iv:mka41W9EZohf9Dwda6L2LlXQz6o0jPCvi/BsRoaQ+00=,tag:9dDLOTvLkUpFAEdRoDUv1g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Uo61UumcFPby3kfs+2WsdGEr7aqiv0rcjEnM5Skizxo=,iv:Q7LpAIueYPImWRNfjL/SYpKtILFLoYrf/BMnwgFzxnQ=,tag:XV3LU+Jb8op0W/Z9c5MhVg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:J2VROO0=,iv:V09nV6nyPQSpv+MKDZDBEMgStIlzfr0qzEE+H4m3G/Q=,tag:jeMM6l8MPqHEFxc1NypG3Q==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:ElsReJ4rKozIAjetmqCZjJqytJgsQfFO3usXh+gk04XJPtUsiA/L48vJz650IufPB9r4ZRJjjfOStdmraNlNZwx5x0aXNm+FUyeo7pc=,iv:eZqocu0Sv9vOMQNyTulqebAMQVAriq5Ix/437uq0q1w=,tag:qffRnRJKdlGzLsovyag/lw==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:W1TH2Yi0pG4RLqxR/1N8TBhMJcdYTgZhPFsdUbOR/yKNLKZFVKAKkOxBXtXCpgVBLYGo99oXgZaN4mGWfNk+1Q==,iv:+pMehAIsF9PIMq8wi3bbQd20rGzqvRM1yOj2joeYF6Q=,tag:URIyVEjgsOXuLdT8I8LXag==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:wWxsPerrJ4EiK4Mfg/Jmig==,iv:F4Nku7FBHChUnjYuuWHfeoJ+wzlrFibBRGGLcrCgmww=,tag:hOV8DZTf34kmET1a1qGigg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISVdTazZvY0VxbVNIVE5N
            NlRrK3pHbDZiT3RKZWNqSDNFSStjR2xaUWxNCkkyeHdSSnRQUkR0OTRnQWJDZTdw
            U1FMVGFMYTEyTjhqLzVQTUtWcllsZWMKLS0tIHdheTdpK0huUXVYR1hUa0J5S2pR
            dkMxN1JpdWlkVVRDQzJuVjhjQytHVGMKOoYRTvZjDrRHkYop26Gfq07MnTpUfYRW
            E1dqAsZ7ogK4aF6p+isJCEsbSoBIOb24+l/LbZg7vk6Sblgcfn11IA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T20:25:43Z"
    mac: ENC[AES256_GCM,data:lC7iAxa+lV7q3DH8oE6+aGdvsLc1fAuAJVcmHDyS2H9cNcOqE1D+f1XP+0JR17r1sT9EmxdhGWMEFEc0QFG//9faQk7V7eUOMVyFFi5/Mzl339qVLicgmNIpdBy2TAylKKC4fYghj38YrGy0rZxJw1WlL+l27kIej43LUY7W2vw=,iv:JIRoja3Zhet3xFxG0RQyf4vnnj8FFuumeRKIInZN5S0=,tag:+dxsqUacFNlXyUslO7fiQg==,type:str]
    version: 3.13.1
