apiVersion: v1
kind: Secret
metadata:
    name: padle-secret
    namespace: padle
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:jJxZrEM=,iv:mka41W9EZohf9Dwda6L2LlXQz6o0jPCvi/BsRoaQ+00=,tag:9dDLOTvLkUpFAEdRoDUv1g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Uo61UumcFPby3kfs+2WsdGEr7aqiv0rcjEnM5Skizxo=,iv:Q7LpAIueYPImWRNfjL/SYpKtILFLoYrf/BMnwgFzxnQ=,tag:XV3LU+Jb8op0W/Z9c5MhVg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:J2VROO0=,iv:V09nV6nyPQSpv+MKDZDBEMgStIlzfr0qzEE+H4m3G/Q=,tag:jeMM6l8MPqHEFxc1NypG3Q==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:ElsReJ4rKozIAjetmqCZjJqytJgsQfFO3usXh+gk04XJPtUsiA/L48vJz650IufPB9r4ZRJjjfOStdmraNlNZwx5x0aXNm+FUyeo7pc=,iv:eZqocu0Sv9vOMQNyTulqebAMQVAriq5Ix/437uq0q1w=,tag:qffRnRJKdlGzLsovyag/lw==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:W1TH2Yi0pG4RLqxR/1N8TBhMJcdYTgZhPFsdUbOR/yKNLKZFVKAKkOxBXtXCpgVBLYGo99oXgZaN4mGWfNk+1Q==,iv:+pMehAIsF9PIMq8wi3bbQd20rGzqvRM1yOj2joeYF6Q=,tag:URIyVEjgsOXuLdT8I8LXag==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:wWxsPerrJ4EiK4Mfg/Jmig==,iv:F4Nku7FBHChUnjYuuWHfeoJ+wzlrFibBRGGLcrCgmww=,tag:hOV8DZTf34kmET1a1qGigg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnT3NlK3pSNHBCZlM0WE5i
            RGNyNmsxOGJRWnRPM05BR3A2NW5EQkJWbm1rCkUyK05Kd2x5cDlIUUxJdkl6eE9x
            NU1wdnVseXJvOEVaRlB6dDBIV1RtcGsKLS0tIDR2NUJnZEVDN2NOWlkzWDBkUzdk
            RGlBMk10TWtvbC9wUzkya0xtbTQ1TFUKpkAiw+uRZk4DwmiJVJiw1PrtHyg9g7Rp
            MpjcEbje+AoESFIDSQitLWixXGqWt5bqPmoWpFsZFoFAnIi/gJ/Ofg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuR0V5NzRXeXA0WmtPdUJO
            dFZaM20rVGZKaWtDRU0ydXIzSWNYYU03dGgwClN4SjZuQ1VmN1Q3aEFiNlMzSjdN
            RDY2c21GV2tzQ1RKMVQ0dDNCZkVIS28KLS0tIGQ4S05pcnBBMjZVZFg3YXdkTmgv
            UjRNWXZ6SGxsWU5yUE5iMm9LYmVHcUEKsv1aqG/uKx39IWxFt6czBxdjuynsfq3h
            7CouZGLaO/viChuUUleShcq7HnWqPF4m0JFtc3pS+Rb61ZZxnwqphg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXK1dkdW1DR3VEMjhVUm5G
            QXZnSzNTNUdNakFTbE9rZzhEVXVHT0taMWxZCkFKVDRZWW9adjgwLzhsTVFsa1pQ
            amVuR2JpbUVEcmxIZkxiMmFTVkd2SVEKLS0tIDdpY3lCL1lSTW1YUy9XcTdMNE12
            V0VNSHppV0xOajZpaXFrY0t1RFZuT3cKzuyYgNcer5gJqzt2rPBcPmy/os16ldUG
            R/ppyasDHB+IBJ0ecVqqK8kjavcQBYTLd4jpUxfVcB3i+6SfBBcJMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T20:25:43Z"
    mac: ENC[AES256_GCM,data:lC7iAxa+lV7q3DH8oE6+aGdvsLc1fAuAJVcmHDyS2H9cNcOqE1D+f1XP+0JR17r1sT9EmxdhGWMEFEc0QFG//9faQk7V7eUOMVyFFi5/Mzl339qVLicgmNIpdBy2TAylKKC4fYghj38YrGy0rZxJw1WlL+l27kIej43LUY7W2vw=,iv:JIRoja3Zhet3xFxG0RQyf4vnnj8FFuumeRKIInZN5S0=,tag:+dxsqUacFNlXyUslO7fiQg==,type:str]
    version: 3.13.1
