apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
    namespace: vikunja
type: Opaque
stringData:
    VIKUNJA_SERVICE_JWTSECRET: ENC[AES256_GCM,data:wmAo2sY/pCH0hbM14q1SmurvW2/oHE4jU39xab57Drj7+7GX8vZvSrmxS0IR+vrNx8paPc+w5/KoOzx8v5oBjg==,iv:Zl8lWwDf03mz/XuZE80mEOAT3++XEiHpFi+9Sqv2HQY=,tag:n7+pgp2H6PLf20gL6OefIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWE5SU0xFY0IzYlk1d0FC
            OHFDWVV1Smxwd2QwYzYyMnRlV0w3ZWwrVlFFCnR5dW1XaXJuRUFiQUovTjZDZHFm
            bHFhNnZQbUxKWXpCSXFUczB6RTRscVEKLS0tIFZKbDdBTWhDTWJsUnFmeE1nb2Uy
            UjM4Y3RPcXVyRGhqWFpuQWlLTXV0UzgKRQ8UZGN+uR5PzmYJHKqrOcH5jGFhmbkz
            Wz1h4L1inbBab6TCNpFFNceyIpysRsAIGP5TXcxeKVyoDcIMHqKi4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T08:47:01Z"
    mac: ENC[AES256_GCM,data:ai/sk0X5jXJTX4z0QpUAWTouxdgLVZzzKih89E0nRHw6g8QMd+lYpysjPRrghPG3njHs5owiQvs60RlGqfgHD15FiH7Ge5ijasEbhy1+sDT1OR2xqEaYueS3tgTUzzNOOwNv7kbkFz+qrx/yAtwCMhciuinny/PNSlzFO3iAJbg=,iv:Ohr0NinFOTm6n9x47B3FnhjqNP5GW+rP9KXDGZPp9wU=,tag:6AMyJ9dWghArVCpADE186w==,type:str]
    version: 3.13.1
