apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
    namespace: vikunja
type: Opaque
stringData:
    VIKUNJA_SERVICE_JWTSECRET: ENC[AES256_GCM,data:wmAo2sY/pCH0hbM14q1SmurvW2/oHE4jU39xab57Drj7+7GX8vZvSrmxS0IR+vrNx8paPc+w5/KoOzx8v5oBjg==,iv:Zl8lWwDf03mz/XuZE80mEOAT3++XEiHpFi+9Sqv2HQY=,tag:n7+pgp2H6PLf20gL6OefIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OURUWUlrNit0R0w4Rm8v
            TUkwNS9MMXZ4a0ZGSGRMQkR1eEpqaGVvTXhNCktGckVON3pKNUk0Z3Jrd2hPZURn
            NFo3QkxwSThLMEFOcktjVC9TcEZRR3MKLS0tIDRweUo0N2JqYXdKZnhtNG5vZFUz
            T0NGbmNvL1RmY3Y5NDY3S3I4T0NQYXcKHLF3ftNxe0LNbr6VpgnCJaCeCFNECPBL
            2IqpDqQFO3MjXUGjCxbnhicstxt6OC3HYa7dXe2uPOeCRGx68lNy+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycU4vTjdzNlovQkF5cUlv
            aU1ZbWhqWlVWTEo1Zm1LU2U1RDB4bEEyOVRFCmdLWUh0UGlYOHA4NTNVcUhVck5E
            azFRK2RHbkU4TWJVR3BGTjFxUURQYnMKLS0tIHF4R0ZlTnFmVzM0ZlBqRjZZMFFW
            c2dTQWc3NTNlNEVQYVZ3UmxhTlRFQ3MKhhWf4YoNbNDtQh/n1ZYKYBaXCGxAdAVP
            TRno7EIAKFP1oYrc3B2Xf41ZLP3TfRYkMxwaSaX3mkr8UHtBvoh6dQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkc0JMd1gzMkVzTlFEaU1u
            KzJMb2FiUno4eVoyd1ZQem9GYXgvcVBDYkEwCnYzTlVFUWxKemRsSWRrVGZOSlNh
            Mkp2Z2VnOEJ2Q0VUL2lsQ3lRUkZpS2MKLS0tIHYvcGxDa2pjM0txS2lqT3p2Sldy
            NTMxYVYxQ1FINlJYbnd5RnhoS3l0MG8KgZt/MKbJXejBZdh79i0X15USeXAaoAlU
            PLYyewNjnmTLdMEAy+Bef52TpDrxMcnijE92EPACDwkP3Cg5q9pnBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T08:47:01Z"
    mac: ENC[AES256_GCM,data:ai/sk0X5jXJTX4z0QpUAWTouxdgLVZzzKih89E0nRHw6g8QMd+lYpysjPRrghPG3njHs5owiQvs60RlGqfgHD15FiH7Ge5ijasEbhy1+sDT1OR2xqEaYueS3tgTUzzNOOwNv7kbkFz+qrx/yAtwCMhciuinny/PNSlzFO3iAJbg=,iv:Ohr0NinFOTm6n9x47B3FnhjqNP5GW+rP9KXDGZPp9wU=,tag:6AMyJ9dWghArVCpADE186w==,type:str]
    version: 3.13.1
