apiVersion: v1
kind: Secret
metadata:
    name: shlink-secret
    namespace: shlink-elwany
type: Opaque
stringData:
    GEOLITE_LICENSE_KEY: ENC[AES256_GCM,data:33eRC2neXzcjCkajNjZreN0/8cWJoy0HlALRcpHBTEhuQAx/F+yiRw==,iv:qbSICwek7eT05c7D9M7j5k+cmxa5tQQfl6zyWuXwJ6s=,tag:tux0qtdn7w42ON0gT+BO+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbUdBeExKR01Dek9uRVRQ
            b0QvK3pEMGZxVk1oYTlIMzY2cWJRd0JkWkRnCmpwNFFjdkJwSmxUV2ZuQ2NRYytU
            RUYybFJIeURhaWhKdlRUYVdkb3lxekUKLS0tIDZkaWduUHhjUTMrVm5FcGwvQWJH
            Nk5WcDBmdVQ2ak0vMUFMaEwwaS85WVUK3SpqMLMH71td2vCFbhCenCeKtSwpf7Wp
            NecDAjCmHP2AqceqXx1TWDhxvQQTofP1jfnfoE6lH9zYCz7hfWZH2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRHloQXZPOUlRS201M1hp
            MnVLUStWUkRYYTZ3bFlJb0JURklhZU5KN0NBCmJjVGRsb1RzRDNwQmZrMGQ1V1Rl
            dDY1WjFtSVplNXovZG00YmVvVGJjVVkKLS0tIDhKR0Z1VlJHTlVDQmxFclFtQVB3
            Q2FtWnlEQWZqNlBERGs5a0Fmb29PM2cKnCUp76jUUf+doWgZSg/AnvmAs8B9bV1j
            Yyvs7OyX9ET0ZA5EIixP6Y3rpzYWMwRLThC9aF3C7UEriN9HmZGW5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubEI5VjVJczhzY3R1cldK
            d2RiYVFCVURYYzBQMU1GdlVnbXJrVFFENG1BCkF4L2J2WTBwbVgvK1pUZm9FSVQr
            a0VTYVpXc1QzL1Vkb2JFWlpQbTZtb2sKLS0tIGJLbXVaS0dnLytJaUVHekVibGVW
            YWZIdVNrWW55MFR4NGs5bVlVV0l3SGsK654Nn3vxgX1UgY2kx6oq3MMincEITVF9
            uf/+bS2CCJJcOnKGGD88mnXq2Y1PMu4dhCmXSRZAXVNSLynbzZq9hA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T14:45:21Z"
    mac: ENC[AES256_GCM,data:vBfdQY+ix55AkPo9bD5+2960AGWDPZyxASgtme3OkKIJrStvMmuun6QuOzIrDk83k0HTyS2Fp+JxSpz39nXRA6g419CqaiiYbFh4P5ExWquVDqZhzpZt/UBtGTSgGBoQCf+UX7HvolIyVk3f4ydWQAyz9AoRu9Sn9cNuEkLwcy8=,iv:tVkF7dw7PzmMhN5yGK9MBOUTyWHwpVuUQJQNWeiZNAA=,tag:Y1A1vD6ztk4dEz1zkHajsQ==,type:str]
    version: 3.13.1
