apiVersion: v1
kind: Secret
metadata:
    name: shlink-secret
    namespace: shlink-elwany
type: Opaque
stringData:
    GEOLITE_LICENSE_KEY: ENC[AES256_GCM,data:33eRC2neXzcjCkajNjZreN0/8cWJoy0HlALRcpHBTEhuQAx/F+yiRw==,iv:qbSICwek7eT05c7D9M7j5k+cmxa5tQQfl6zyWuXwJ6s=,tag:tux0qtdn7w42ON0gT+BO+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpU2plQ2pod25NVXE3Q1d5
            YkVsUkdFVjM3b1ZsMHU1OTkyNjRxamRIcUNJCnpKcHY2V0VxQVpYb0RhU3Y2d0dZ
            dUNvSHJwWUFQSGFONTRtcjZYU1NBMEEKLS0tIG1OSEVhbXdaOGxYWThiYXNxYkI2
            bGdwMmRRZFZLWEc0MWtJOWFVeEJTWlUKQgepUvZtBjGEe/4de+8kvKuZAoi9T+GY
            /LHJp9T1FXly21Of3G1Tbw1e06vc5GgimD2fOu589uNtAt6LkHepog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T14:45:21Z"
    mac: ENC[AES256_GCM,data:vBfdQY+ix55AkPo9bD5+2960AGWDPZyxASgtme3OkKIJrStvMmuun6QuOzIrDk83k0HTyS2Fp+JxSpz39nXRA6g419CqaiiYbFh4P5ExWquVDqZhzpZt/UBtGTSgGBoQCf+UX7HvolIyVk3f4ydWQAyz9AoRu9Sn9cNuEkLwcy8=,iv:tVkF7dw7PzmMhN5yGK9MBOUTyWHwpVuUQJQNWeiZNAA=,tag:Y1A1vD6ztk4dEz1zkHajsQ==,type:str]
    version: 3.13.1
