apiVersion: v1
kind: Secret
metadata:
  name: shlink-secret
  namespace: shlink-elwany
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
