apiVersion: v1
kind: Secret
metadata:
    name: sorani-bot-secret
    namespace: ai
type: Opaque
stringData:
    TELEGRAM_TOKEN: ENC[AES256_GCM,data:QOj3pDAtJzoWLadP972nkhyAf46XfY2qmB6Sy/CoSUa69XRWeWVmCT8rqbvlBg==,iv:oUpqiQW/X3n34N/2zG9iTyixL/oOb7qonuT/rcHDQEo=,tag:XmUCL5PafvS72Xr0MOOeHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiREpsV3piVmpBS1dzQ3hN
            OGsrQmxYK3BlcUt0bUVLVnNGTy9VS1I4RWtFCjFnQXU5WVNqa204RDFrUnM4K0sz
            T0JhUmFsY2M4ZEVOVFRKNkpZR0lPa0UKLS0tIHJJNWdzNDRXYmlrMnVycnhuVU5D
            VGxGczFlUTM4ZTN2MkN6MUdWSG9Pd3cK1D2PuWcl2/+I2qeRZpLUnt/Ea7CZWKpY
            QEKeLmRg9Vy5z3h1XXV7iz+lSBVHlZDoBhT/xbqx3J0vqylmX7LgQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPb3ByQXROeHFXWTZETERj
            b0pMbitGNE5rMUlwUUY2bm5WTFFCK3QzV0dnCkVQK05VLzZDZEd2RjhIdEdTM0t1
            UHlGK0xEZCs0Z0djbDB2VVlKQWJwd00KLS0tIE5lWDcydmxXWVQwZGhEU0k5RUE0
            VDhjaXJtZWhIdzFrRUpMd1dVQjRhSUEKOiOEAbwtHU9SZo4LpLDcfmqNtjp3pYgr
            h3dMxg7SijGNghvVNtn3CFPIYTMWbJkbb75cZNTHGHZ3SAzgfWLJKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQazFvN0l0WUJKZmRQc1Rj
            UE92TWpndjZRMVIxbWRhT29XMW1SWmhBUkNzCkVPeUkzM2dHdUl4Ukg2TndIME1m
            WCtOT3ZLdGlFTXhwTjQzcXhVYzd2WEUKLS0tIHJRMXpNZFZHaERMY0tBL2UrV3hw
            ZllOOTZjYzVONHJsVkVIKzVUUWJnY00KCcuXkJP4248pWAlumshugV3weKXRiZ5n
            cgNOVgwtZARHp8OkaQdkpz9cm/qmFdv4gHn6xs+WOElOLnKVzZn3fw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T11:18:36Z"
    mac: ENC[AES256_GCM,data:iZHUODxAA7rgvKXfV3FXvK8feo0FF5IwJzZS+WBcSLqkDzs996PwsLVgqqjTQ4m0Q4vwNYid7xAU0O8Ma4q9wd4sKTCN/vQl/UTALfHeUKTsYzFk8fpWEUHaRX9iBKoLGqRK8EZGuD51sp47hJ1rBdsoCIpaN2MYcLC7vdokg7E=,iv:X6EdFbRCZot8SkV7zeyAhucl8gzdc3slKWlJvNttE44=,tag:39rzlIV4s9517ZeGvahJgA==,type:str]
    version: 3.13.1
