apiVersion: v1
kind: Secret
metadata:
    name: sorani-bot-secret
    namespace: ai
type: Opaque
stringData:
    TELEGRAM_TOKEN: ENC[AES256_GCM,data:QOj3pDAtJzoWLadP972nkhyAf46XfY2qmB6Sy/CoSUa69XRWeWVmCT8rqbvlBg==,iv:oUpqiQW/X3n34N/2zG9iTyixL/oOb7qonuT/rcHDQEo=,tag:XmUCL5PafvS72Xr0MOOeHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUU9HSFY5TlYzdEVpYlBH
            d0JzalNhbGJYaHpicWJaWGxoV1RFZlJscFRZCmoyN1UzQ1pxY1VUaGdsWFB0U1hI
            UFozdnV6OGdmMW9zOEM0cmNlK2VoV00KLS0tIGlFbWFqSVF2dUhPZHAwekpOUzF6
            NUhCY3U5SVl6NjZwV2srY1RFTTc1MEkKMKhkwOAngXQKmOW9R+DJt58rw/Zv9TRx
            x3ZHeazeahaFgwIUMEL5wGxZ/nhQlLg0lJVifBXR7C+dUwIxmfd/KA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T11:18:36Z"
    mac: ENC[AES256_GCM,data:iZHUODxAA7rgvKXfV3FXvK8feo0FF5IwJzZS+WBcSLqkDzs996PwsLVgqqjTQ4m0Q4vwNYid7xAU0O8Ma4q9wd4sKTCN/vQl/UTALfHeUKTsYzFk8fpWEUHaRX9iBKoLGqRK8EZGuD51sp47hJ1rBdsoCIpaN2MYcLC7vdokg7E=,iv:X6EdFbRCZot8SkV7zeyAhucl8gzdc3slKWlJvNttE44=,tag:39rzlIV4s9517ZeGvahJgA==,type:str]
    version: 3.13.1
