apiVersion: v1
kind: Secret
metadata:
    name: backup-s3-secret
    namespace: blanca-dental-care
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5DViZbYTTDSOsxHwdJf7QEY=,iv:SzyOTkSDOaNqMrEneX42P12oAj5vTCejcdlOVdzDSaY=,tag:a7BsxeHpsn005lPd1nnFXg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2Ygm1yw5GZKagBNXsx2sgsZ0S1d1RNu6JqdykhEYVnapyXQYa4S4Zg==,iv:NTQ8nNk2dkOTgLgcG4V+luGuTwtB2bzvz7CdVgBh+sw=,tag:xpncaf3p6GxxXZHmxW0TiA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:ovEK1lfbqYPGXfA9tJEAIowRHN2iGFFwag==,iv:eSi79qBmvwODW1T2m0umVnaA5YVAq2e6cVbpUEaOpU8=,tag:RKJHIUDXFV/cqJbuXE2meA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Znd2clp0RVBlWHRHNUNv
            VXJ6WUxydjBEWktkNVdzajhTOWpnVmltNVZrCjIzZ2tLa0h2MFh1VXlacDZUbkFT
            OEV0UXpwWjBXdElobldWeWF3c0ZvK2MKLS0tICtMZnBwRFZZZnZOakRsL3p5TFhy
            YllQbXN4ZEYrcUVmL2w2cDdPQVQwYzQKK7T2Xco+rYwvXSdF99KZ4vzUgXRIlDNb
            J+2VSHhVahc+XrXdS6NkwqjR0M07IADYMg6JIwAM0//mnXaw6l8wbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNDk1WEJLZEVJdzdsam5C
            TVJ4Z0xJb2FPenc0K1BXbWpZTFluQ1BHV24wClFQS2N0eitDc1FlMlJFUk02V0lY
            QWszVVJkQWhoTkhsMUNkQ2JFN0RQc1UKLS0tIFNhNnFCRzloSzZvRCtHdzBkVE9G
            aVl6Z2plQ3JnaW5qckZyT0dYbFBRVFkKKof3o019IMgURc8DLB/ZfZwTK+SfqvHt
            sL5hhGYnmESdTBnKwRkeFWbeeb1pG9wzUmuWA+ycR8hQivZ571AfGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJb2lqZGNxYWpXc0tsRzV1
            eVZyb2tDV2dxekVkMFZWdGl3Y1k0TVFjRjNFCnRUMXNiT0JJNnh0c29WRnk4cFl5
            di9vd3hZcUZ4V1ZKTDJSSmV6U1VpckkKLS0tIFNlM0tMRk9laHdSYmNMM0tVYlNW
            SnpNc0NqTWFUZWxkbXY3MFNqTEUzb00KHwovVABpQ8JT1Ne/Yo6Hm7zdDucr4e3U
            bNKce+PBuPKGI72l3Z+Wju65PQhwfwMSM0ZEbvjMTzBOdWVBMWeuAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T11:25:08Z"
    mac: ENC[AES256_GCM,data:QqTe5Nti3tQrbZ6ekjppQsNij5pfp9hfff3s95r2gtjdUBhUc1lwDK8o57BqZDGR4W4KBqO2XtgaL7pRTjSns/KfOQ9+yaXw+C8aBHyzNoldUXPbKytMwOVJdpaeh0iWOTrWVV+oatG908u13jql6gqbh/0zMEIGR1rGjCEt5+Y=,iv:0J1Y70VDQrLCTdnQo09FtYESAjZfE2OnboxQ1XBIn0s=,tag:CqZ5txsDi5hDPkpExmsUmw==,type:str]
    version: 3.13.1
