apiVersion: v1
kind: Secret
metadata:
    name: backup-s3-secret
    namespace: blanca-dental-care
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5DViZbYTTDSOsxHwdJf7QEY=,iv:SzyOTkSDOaNqMrEneX42P12oAj5vTCejcdlOVdzDSaY=,tag:a7BsxeHpsn005lPd1nnFXg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2Ygm1yw5GZKagBNXsx2sgsZ0S1d1RNu6JqdykhEYVnapyXQYa4S4Zg==,iv:NTQ8nNk2dkOTgLgcG4V+luGuTwtB2bzvz7CdVgBh+sw=,tag:xpncaf3p6GxxXZHmxW0TiA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:ovEK1lfbqYPGXfA9tJEAIowRHN2iGFFwag==,iv:eSi79qBmvwODW1T2m0umVnaA5YVAq2e6cVbpUEaOpU8=,tag:RKJHIUDXFV/cqJbuXE2meA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaODIzZFd6WmFZU3JIaHh6
            NmRRdjkrQzFPM1FJYTkycWZXalBwcjZMOUhrCkhYeGthTXlwaVZkSzA2RlFCOXdx
            bUdIUWpoSTU5Yy9PR28wV2pTYkEvdE0KLS0tIFhkVGpvTy9BL3lIeDRmWFdIRE5B
            VXJBcDBKY21HQkdXK1FvSk42N1h4NzgKacU4MjhGcz6vDLCrywv9JyrnT101UkxJ
            IYGmimULhvPjdF3Wm52rjTh8roO23uozqV4KO4JnX1p22JbiSlaiqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T11:25:08Z"
    mac: ENC[AES256_GCM,data:QqTe5Nti3tQrbZ6ekjppQsNij5pfp9hfff3s95r2gtjdUBhUc1lwDK8o57BqZDGR4W4KBqO2XtgaL7pRTjSns/KfOQ9+yaXw+C8aBHyzNoldUXPbKytMwOVJdpaeh0iWOTrWVV+oatG908u13jql6gqbh/0zMEIGR1rGjCEt5+Y=,iv:0J1Y70VDQrLCTdnQo09FtYESAjZfE2OnboxQ1XBIn0s=,tag:CqZ5txsDi5hDPkpExmsUmw==,type:str]
    version: 3.13.1
