apiVersion: v1
kind: Secret
metadata:
    name: blanca-web-secret
    namespace: blanca-dental-care
type: Opaque
stringData:
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:aB3k+NL5Dpn7BzHNLuSG0lixBMFCMtC6EOl496iGM3E6XrJhBPzRnw==,iv:G7HdrA7qCzO8jE3OKZfzeqNNVB01hfa4HN2Ucht68Es=,tag:0Ji9XyZ3zuTHM2f5i1Uu4A==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:TCKLS5dTtaMAUsRhZvJM95BXR9taTuebJQuiCd3uMxszLuHdV8ZuAA==,iv:jN5vYXRCHs6HlskMDZw9uOAKsn2OWasNBa8229c3U7U=,tag:6++BBY+UYwFW1VfyxdPnkQ==,type:str]
    WORDPRESS_AUTH_KEY: ENC[AES256_GCM,data:u3qYKSpC3Q/lr3bInTt9rpHOqY3em2gEW7z6lbi8rInhGLgffbddiZ1zTYmOi8EC,iv:tpMRI9nIp5sVrLts2UOB6H77CqASpi6RCtdsjRxyJLI=,tag:mIJOqjc3yggHe7/cjEgu0Q==,type:str]
    WORDPRESS_SECURE_AUTH_KEY: ENC[AES256_GCM,data:nG1TjsmWWia3V+Nrh9bVcLHrsT1lyB1ZEtUZSmJUhqQHf4uoWm8QNaeP4R9y2by3,iv:DDZFzSlCrgH8sq1uXs97jJI2lfbxwjfwOx2LpsQzZvo=,tag:HAPhldGqrRux7hAn4ixfOA==,type:str]
    WORDPRESS_LOGGED_IN_KEY: ENC[AES256_GCM,data:gvlJ0G4qYdOQ7MIIQi9V1B4h7WbI7ncxybe0Ah1yWFDxrZ4B5CWG4gRlxMUydF34,iv:aJSGIP6rAUAHGN7Jyii2PE40bH67uLbb1sPWOiwYCfA=,tag:MznUBcUj+5g9ATSGnwHgYA==,type:str]
    WORDPRESS_NONCE_KEY: ENC[AES256_GCM,data:G9DdlqCoW8h+d9uWX599GtO/g1ipQlD3EOwKBTdjjwDVe85X27A7pQ/z31wwIYXB,iv:fPcJVlQ3GK1OrgqbKznpkrEwuqdmpdXUjOQaCZQiq+s=,tag:9oPW9HzLN5JppMut5JVywg==,type:str]
    WORDPRESS_AUTH_SALT: ENC[AES256_GCM,data:DDULWkHeyiNYo/fhLCNZMWsNJdrmp8lirKoyr5yQSnf6YCR65UFTJErNi2sUYupi,iv:bk5FyhLuF7oWPVIGfqg7f1QMJtgqkbKVTAwClrzy/NQ=,tag:uQfHuigy9N/vlmUkTPUP0g==,type:str]
    WORDPRESS_SECURE_AUTH_SALT: ENC[AES256_GCM,data:LG7fZkCc8MnOHSJBhJWFEKVzTEeDrIt3kh5VOiFXOzS/71fIfm7/18rhO6MsbE07,iv:O5ZoQUXB14HDa9xXTw0i5bhRANGJENnyaoH2TQyIOgc=,tag:eYw7oRygiPcPqSm89m1pAw==,type:str]
    WORDPRESS_LOGGED_IN_SALT: ENC[AES256_GCM,data:TQ03gskB79i3260aPzOU1eUU3KqF1KwrjKdacxelU4ASDu3d8a3/vBsOcEFLN5ie,iv:L1wgjN5EK/i19w1sUCUEpjUTXqFCLXvkkptCQZ7dwVg=,tag:FV3mrW/pVyGAzl5Pcg/beQ==,type:str]
    WORDPRESS_NONCE_SALT: ENC[AES256_GCM,data:1rfw5ZJpSuURyufYOtIHMRHWU+Q/3U3MNnoz7FyLf3y1efcrNR9boLjcA6egSTTl,iv:IVjOW3rWjtQMYiOnvMwihaQy09kYt5OwRorbDxkYLvY=,tag:mGqZKwL9mi9CyROVmKWVqw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUHZNZ2RXR3NkSDVRNGRh
            VjNsekRweC81RURnNnFRVGJNVFpQS0lHZDNJCml3ZzJYY1ZhT05xZXQzMy8rWEhu
            WnBRVHUwaUJ3eDlpSjZ5blRZdnBFNncKLS0tIEJqOFh3R1FDcmZwVHJZZGozZ2FC
            aUlrZW55TjdiS3RTVnN5bXVDSFZqUnMK/Prf5KhH7EbqI5c2qwE07LrsvW6txryo
            3nh7hjZSiOF5rGxyBakqdmlwSZQ3xC/mOhJBLP+8+TQlIXnJl6xoDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T04:01:37Z"
    mac: ENC[AES256_GCM,data:mfxRS0KLDRThsYi/SV88GzCkNYsJFPJXfw9efiQEftMBvTXweH3jeoqSbOurMvHSA3+1c+U6cX6gAZTLi7Q822F7S8IOIa1HzuaJqWFY7hhdtfoMtT3vNA22mQBJtxxCs1ZLYgvPK0XVFysqxEWrL6k9nsapHryQetQ9EzL4pUQ=,iv:reWKf1W0L/XIrzrFzbPeLJA05n32BW0cFii5j2i5Xes=,tag:8zPblNXYSE3euacYiWsaEw==,type:str]
    version: 3.13.1
