apiVersion: v1
kind: Secret
metadata:
    name: backup-s3-secret
    namespace: cal
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:SvrdN4TW2xRhXg==,iv:EPv2JL4RZ8a50rpydhGtOQvFY5XFDeu5Yw9z+AyxTgc=,tag:2veyTVuYTWlmNhBaefR5gA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:qwm1xuvF2QCqwpbiu3jyryEyeHXnaTD6INIPSOkQYM4=,iv:s4VJ4hnSS68/PME1sQTZAyLc3To86k46BcLMHv2EkL4=,tag:Z8jK3ywIIZwWT2dwdNDm1Q==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:vZHVkC7wPxnovqOSTfJ9Jo89aDzpV1+DMA==,iv:zmIW25oLrA+sRpKJ19Kbn7nGOHLbG2adbeVMY3oUteM=,tag:llC/d5R8JKlG7NcC+dPQ2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWEk3U2c2cG9ybjRQZm5T
            ZXJzU1FDdWVxTXZHa3RhZDdLbm5BWUlsMEY4CmZxRGFiUVc4STBZb2V5L2szZXc3
            OEhjRndDR3kzenBHZnNuR0Ivc05jSmMKLS0tIC9OblBQM282ZXJBTE5PdVpVb0V4
            anZPUFJ1Rnp6bi9hcnUwOU5Wekw3WGMKaSNPVAjvs/BmBnpN/h6HLyiFMemTL48V
            3kAGrVqxiC4fXvinsr87jdT0wKJn75f7E53TmBTfFYAKCImRFJayNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEa08rWGpUcExIWWs1L3N6
            OW1BQ3RSOWMxT1JJTmdVL29XbVNQYUpMNlhrCmFXRmhoNjFDRWVpbVc4Sm5CR2pi
            aXdqTTFobHlIOFhPK2puY0VubXRPZkUKLS0tIC9ZeTFGSE5yejdVYW9TajY5Ymsx
            VklycWhFSHlNeWtLMUdCekJMOU5iL2cK8CjwJGUo03KNEBGbk+UyshHoH5y4kTd0
            N7HbYVb3QSxhscUM8kYVztrQV5071vS8h/ZQj/9ne7xoID6zQnyOLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3STRtUmFBM0I1OVR3clR2
            aHQ1TGNSVDFhWVVlZUhLTHlBUk9EbkR4WlNNCmJnYkdWMkF1YTJSRGtzL3Y0aDhi
            Snc0VFlkQ243UXgwMG5Dek1KMVhuRUEKLS0tIFBkaEdPczNwL2M3VlU5UWJRMGJD
            QlBxRFNFdzB1empHRjc5RlZHRVdXWEkKjrnSs8yWwClOm/yDpbWvIjyuN5uRBVSz
            D2gDRnMi67Zlniv6h39D2WD1ZJOMIxDYQ8Ox13nJvPYGlUwsDtGlMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T06:46:04Z"
    mac: ENC[AES256_GCM,data:ivlODYz2sh4qZ5ECe5D0782dQ/jxXzKCFGv6DPkD0TLADJfUCAMopggxy7ZmRHM2ScjPH7H0EUPJ4gT+dLt0Ae13PSqn2sFrMeOuoXHJhJxNmKaA7LZclytZvYL7/VScbL+GMitoWN0ZkShgS4eMWAlRnR9sH8GATonJyJSQUP8=,iv:AHqp37oGC0DKRF8XDM2WOQQ9QhO5Kkg4dV3Gh6Mmhro=,tag:oih5XTJDZbBA9ZBufrutpw==,type:str]
    version: 3.13.1
