apiVersion: v1
kind: Secret
metadata:
    name: cal-secret
    namespace: cal
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:3lePNv4YSZxktxjim6iRxpFqfeQR0kLWOX3yLk5AL5yM2TfL4SN7TwOZhvZ8Eu67DOEWVdZgxkw9Yss=,iv:8HQ9PLgaaqetRKsH5H+2RqzIAvrDe0L3ykRk24u5J4c=,tag:LwqwOCOYHotFFk7yldTVIg==,type:str]
    DATABASE_DIRECT_URL: ENC[AES256_GCM,data:Md/GcKripvaZxbaurk0qCuqvXUpWLWYLGhHUARjJ9tHNDJ3TCdNUTyey3s8Ou+WWTRCMOJf0afRNV1g=,iv:J8ku9MYUQWyXWhmXwqrBIQsFvklvwyYF6JgqacfTo4E=,tag:RULmgM0L+IFY5mlWKTHbLw==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:StsLvGuCprwLrOGbqNBbpTNbEvm/51WdNuTYlQ2ldouwyc5RFGmkbaHcDIk=,iv:dXiH3Mel410pCT353aJdhMptdTm8gVoO5r2t6Fql//4=,tag:PM8D/VaxIWsviU3wmIGVng==,type:str]
    CALENDSO_ENCRYPTION_KEY: ENC[AES256_GCM,data:tm9NG81O5FJ5ptOjx3LuzIPgDkEA4alITSyGV283s8E=,iv:dAl85q+6wxzdH6EYgP8FSLCumseckF5IxtcmsNK/tI0=,tag:ORMCcuemVlhGu7Aa9F1nYA==,type:str]
    EMAIL_SERVER_PASSWORD: ENC[AES256_GCM,data:lCQxNbPStDpZ+OHjkxKkog==,iv:vk+/XRcKtdvx9QmG7UC9/64p5wAaGoOR7A/TePaNaJQ=,tag:Zp5rowhuF41NRA9EbMMnvA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYK2QxK3JTUW93ZmN6OUFq
            d3VIRzBrdndBL2pRYUkxNWphNUVMREVwTW5RCmFVVGVvWUdNNTJnVHg5NnVXVThw
            dnNRWU9Ta3NjSmpDYmdsQ0NDUDJoM0EKLS0tIGxMbnQ4S0lURnFaclhhcStWUVRC
            TmdoUWNZSHVhRDAxOEgvaUZVQXI4ZE0K3jrSxaXGNuhePCaaKxOOAnNwbNzf1Cgt
            zcNwdBz8vzJB7znZuczYVN8fxzADGDjv05v6Z3hhFFMqnvIl+qVEIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeVB5MjVOREhCTWtVMHQr
            TG1ONStHeDB4c3ZBd0VrQnZ1ZzBCc0laL1hvCkVWTVJKZ1B5SjZhdm8rRmtSbWt2
            dE9KTHpsZ29WYVZibmZJcnNCK0h0MGMKLS0tIFNtT2pScjBYRVMvQkl2ME1vdGpn
            L01QYVdHYnRjaWw1WTJQbjdjT090dTQKBvcJopCAVT0Rzt1eheOQqms1uppFIbdx
            qz8TD1ocS3qhMk/jWuYA8E/cF3pyUEUenMm7i1xxxr2vZUjTSWTQJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTEV1TUEyZ2hxZlNNQWF6
            a1FJMkZGK3hVVE5MZnhjVk9SdHdTTngvRlRFCjB1QTNpVmNHMjVYR0xLY0lyeEpM
            QVA2RUpBYU5VY0hkaFpoT0pPR2J3a2MKLS0tIERVbW5SZDI1d2VsVU1WUGYyOG9H
            S3hLZE83UERaU0lRZ1R5QjhtbTNMOXcKxDFz0eAOq2aJRqKypEJf425IjBGdxT5I
            owWQS46MLgtUx5dmU2LXiFu+cZW/bBH1O+WTAr6wixMiYd2nOq7saw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T06:45:00Z"
    mac: ENC[AES256_GCM,data:O1haecUnLDIFiiZ9eefkR7fLtcJb/oLpuKPEFF3FSQYJQGMU3u4XkO2Yc6VqkLzhcVhx5uQhBbvjy020UQYVUdbWrqFbyylQ6JyfTY7AVnInBGjxN/NhB22FpDjAbBYyPgs8SpnG83ZmLfZLb1Yq5Rtbz55S6pA4jrEpFNlIxUQ=,iv:f4gILH0JFzDhdiNwodMwiV3COOvPpTkUzftaeg6VGfE=,tag:GbGAWtA/3UL/MAHi+EOMxA==,type:str]
    version: 3.13.1
