apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: cal
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:KGl/,iv:J/xyP/OTOEEsZam+B/I/8hdm5g+nbq+iTAJOZ6hB+eg=,tag:IkXXyFb8eVX7tw7CNqGkSg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:+dDTAxuNEdmi1l5wyXQKNKpUpRoq38qs,iv:Mo1brp/ZXXPUK9fma47i1RFC5jG99UGAIXPqY+RNGMw=,tag:pnOaaIn82ugxS6NcHseKJA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:w64J,iv:xaxiKnt0mAkYd6l+NGbg6PZk4FGasDYOQWUDv9nDXD0=,tag:zndOUpPRURW+/nFFSxxzIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUVBXZ3FQU2FpRGZmMHJs
            aThxK3dYNCszM3FLSlhWOEJHajVUcm9BZTBVCkZ3QkNZSnRILytqTXZoeGpWd0Ri
            eklwUktLMXRJcS8xNXRvMkVwMjlJOXcKLS0tIDR5VmZNNjkrZkF0bVkybUl2R096
            UERWRFZqM2ZVV1NDQ05tRXRLb1NDZVUKbNmqzH8JLaD3b3cdFsT7GKCcHyGfxL3x
            k+MH5IYB7EJU/Ml+VbLFwrsbQJ70fZx4LqxtRbemtZ/BM8NbZxjRYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZEdOT3JuY2JGTFp5cC9z
            T0V1ZnRsZm9ORFYyT1VNYmEzQ0hldUNnVlNjClVFamI5VExQVFcwbXR6SzhpbXZN
            QWxYTUtTVEdwYlU0N2U0eGtyYWYxTGcKLS0tIERXWjRRaEh6dDhvNHJrWEExQkZp
            bjc1WE03SVJMcG43VlBLUjBuM2FjRmsKElM/bQj6sQRXnGFJnCt4ReSTbTtXMvuW
            Tf+YzzEYbXsK0jrjj7ZFG6kq5/dgmohlEkLeDG1bCOM0Jvwzotpxuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWUNBTVdNTDFVcml5Wmty
            RTh0Y3oyb28zRzlhWDFDU0RuS1VpSkZ1dkRJCi9vM2Q3a3JGY0NYNEJxcVc5N1pN
            NUZtZXY0cUQ2cTVHNktLc0VYZ3luOFUKLS0tIFpKL21QcWI5Q3hJZ0NYZnEyUGdO
            RGNIQzBnRGk1ckFuVXhyWXhuaHphZWcKb+k+QJqkUWvfMHdeitFC9ROH+r63+d+M
            BVJ1jmPrBiH3W3ClsNU7FSsT0oSJXrU45cy84MuIx2CbsITpF+EKRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T06:45:00Z"
    mac: ENC[AES256_GCM,data:ENS3jUk7gBnJw8nQOC9Zvuz+X7ike2dgyvD329RJ3q1KKjNUY8QrlqfHq3xDme1aTc4EbWLBDAv7QSCCXKEevsWtlIjDjbGtid+FQoLsNkAsDe1sVIf2Apq+T5Z+tjxP4r3QHg4fHndkPuxEqhChjbXFB+0lvounVZ0izn+4NdY=,iv:ArV0sd3gHhW/0M/xD38BtC2kr6Vuiw9Oqwv5j0HdhSw=,tag:h2LkXRoqUsxbK9arMx6E4Q==,type:str]
    version: 3.13.1
