apiVersion: v1
kind: Secret
metadata:
    name: backup-s3-secret
    namespace: myinvoice
    annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:VRckJmPzb3Cqd8Cv1wJsUg==,iv:PH6vOK/8yIa0nOCK16qnnyAiM7eDOSaE4DfK2W1TDzw=,tag:QWxCCfHxAw5VV+hvgurWFQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:TkmwZ8KbrEWd/cs1MbjNPvo41rGWp6VAc6ioMsAkfas=,iv:enamIr4CNBxLSGnGt4wMweiTN3C57LjY74KILHxC2WE=,tag:iTo2sqqVaA+M2UNyVK0vAg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:cSYZAAncHPhJ/CDpcriiN6YU7e756wLxgA==,iv:y3PMCVX5Ih1Uzrs/KkdXhrx+cSC6w6DDzqVOo2n3R78=,tag:fbGs0uEJpuPym2StDo2B3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZVEyUGNaQVVTMWkxZllo
            ZnljcEhZWEowY2MvTVI4UzBBQzZmWDlyeFJnCkJUMjhEaTNFR1Ryc0VVbTlkMm1y
            MTZXTDgwU2IxdGVIZGNNNUZrcHdVU00KLS0tICtjR0lPNG9jOTdQMExkZCt6bjQw
            cmdsbkM2MnlLWENNVXZkcVpYN01ibTAKK5C0frkNNSnB3sIICz6jzlnpos+pUQH0
            m5bbh345XXyfp5eDQOaryCcVX8GS2MAcOpPaOl2wnPMl7c3c2pFU8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYWJHZ2M4WkV0ZkVPWDBl
            bDhwS1M5c295bzhuc2h0R2gyU3JtNW1SR1ZJCmlKZXN6UFZ5Z0UxYjh3L0NDcXJx
            RHVCRTdIMURIQ0R2U3lyKzQzYVZoSkEKLS0tIGVsRXEreTNCYy9BMitrSEFLRXZV
            dUh4UmxTbnpmMTE3Y21yWGFoK0ZtWTAK4AmD6aTZ2z3LiuC5ccqJlTIes2P2Pqfq
            03mGKhckBMOZTRJAi4Xqc/+Y/EmSlPaGFLDuF5kN3PvAvha0we/qHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYkk2MytiS3dXd0g5Y0Nl
            djdRaUF6WHhLa3FVUDdPd1VhTklyZHdjaWdzCjRCNk55ZVlnQWtPdDUwdnViZlpu
            dzlRRUJaSURQNldmOWEwSFB1S2gyL0kKLS0tIG4zbnRQajlTaFVkaW0vbDQ2eit0
            MlpvMzJQUkZYakcrckFDdzdOWWdZTlkKmWQ9S1F6VToAJrY2SYPN8KxqyQs1nzSz
            1g//UTwY7GIl/NzgBR2Xn0fSM1X0YDS7MCDehaspMCKxTJwHoI9HHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T10:40:15Z"
    mac: ENC[AES256_GCM,data:2+tbrtH8/sGSjrBbiIyqp/1AEHDFHzPEiNP+MgUphDG2iTaeLaWoHT0e6gO6wZTo2goXEp+Dpws19Ysn86Cm7sMWocJk9YwfbM1eITBnIKlGv0vhtXnAE9b7u/F/AYyhWbgwpHY21e9vS5aPnUwtZW9tJv4C0Y+qF0TtmvIBdJw=,iv:8VKnYAWpHVLokVYu8TX+Whj95g5fVAMgBfI7v/HJbK4=,tag:nwULfexo1tkcnx3hblW+Xw==,type:str]
    version: 3.13.1
