apiVersion: v1
kind: Secret
metadata:
    name: backup-s3-secret
    namespace: myinvoice
    annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:VRckJmPzb3Cqd8Cv1wJsUg==,iv:PH6vOK/8yIa0nOCK16qnnyAiM7eDOSaE4DfK2W1TDzw=,tag:QWxCCfHxAw5VV+hvgurWFQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:TkmwZ8KbrEWd/cs1MbjNPvo41rGWp6VAc6ioMsAkfas=,iv:enamIr4CNBxLSGnGt4wMweiTN3C57LjY74KILHxC2WE=,tag:iTo2sqqVaA+M2UNyVK0vAg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:cSYZAAncHPhJ/CDpcriiN6YU7e756wLxgA==,iv:y3PMCVX5Ih1Uzrs/KkdXhrx+cSC6w6DDzqVOo2n3R78=,tag:fbGs0uEJpuPym2StDo2B3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJc2dwRjg0VDJXb2hyUU9P
            MUE2L2tnem5IaFNyM29yaEd1bTJZTUY0Y0FNCkUzWWJBQ1BJdWlNSjdBaEg5OUtt
            amRMemhtZ09tZVc4TXNMZ1hXbzc4S2MKLS0tIHdMajY1cTkrZ0NOTm9memh1SDVh
            Yk5OZGhQYXN2b056WGJqWmhrR1hkQzAKiTmYZcIy3M7UbeNVZC/V145rgJg8uf8e
            6+6bQqhP6H9UOm1KgK3H4KYgV5AdP2fWvsd5wfOkTyIKVKiMgMelYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T10:40:15Z"
    mac: ENC[AES256_GCM,data:2+tbrtH8/sGSjrBbiIyqp/1AEHDFHzPEiNP+MgUphDG2iTaeLaWoHT0e6gO6wZTo2goXEp+Dpws19Ysn86Cm7sMWocJk9YwfbM1eITBnIKlGv0vhtXnAE9b7u/F/AYyhWbgwpHY21e9vS5aPnUwtZW9tJv4C0Y+qF0TtmvIBdJw=,iv:8VKnYAWpHVLokVYu8TX+Whj95g5fVAMgBfI7v/HJbK4=,tag:nwULfexo1tkcnx3hblW+Xw==,type:str]
    version: 3.13.1
