apiVersion: v1
kind: Secret
metadata:
    name: myinvoice-secret
    namespace: myinvoice
    annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
type: Opaque
stringData:
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:PphRcfkxW6P9OdGLk+OpGvgt5v6cnA3ofmNO5HhFC3TmmsRaR/+vIA==,iv:AOrWSo8Rg7bOrGpN2VlL8jUY9TM9/XmVm2zT6uiOvA4=,tag:8Dgk8vcVy+7eZfxKwbRaTg==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:GSav/bjYI37Rv+pH590groXa+1QzyF8tENXB0NxkZizD1sbmNez91Q==,iv:bQL0JPjPIRKOR+jcn0c9m27TJd/SHhik5NRs3Z7KWEI=,tag:gVaAOm4W62Y7y7ZGF5vNPw==,type:str]
    MYINVOICE_PEPPER: ENC[AES256_GCM,data:d9Ojzs1z9GfX9baaKnsaJW7ju0fDSd3Bi/+aEkqVoOn5fI3fFns4XlMWW4A=,iv:ejhvTstmI9UBkcZ2aejWcBTrfIrVGgd5SPJ9jfQgQsw=,tag:t3BnOST9YhyyfOJLFxqfSg==,type:str]
    MYINVOICE_SECRET_KEY: ENC[AES256_GCM,data:S0FIocBnbyMjIYDRfna1slazz6QVCGjmhbMhegrcirUSiSr8EZf4Jjcms/M=,iv:CpYLsu+jGftFdXRWeRxjOFeyferSh1gabGpxeg8bbbs=,tag:2Gp8kCg3ordPyY8C71iVZg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdU1XeTZNbXZGNVdLeElr
            NENsc2pYbThaQWlxaWdqbFA0ZXJCekJjYWtzCjRMR3ZIWUhUd3NqNWQ4cm0vTGZa
            cllXMi9OcmZrSFF4Zm9LZGZLV0RDeWMKLS0tIEdlU3FGZ0NCMnpGTzV5eFV1ZlRu
            RGRqRThZZU1lTjFiNjRnOHRCb0ZtbVEKgrrAPcSwsDMiG4RCqPF0rVn5pZF+hM8m
            Adb2lEiNEpFKaJJoGFE7ZOeJtk4t6UHC9YDPvpUA+BeEVoJ5aXQCdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T10:00:19Z"
    mac: ENC[AES256_GCM,data:HnI5qj6u1SRHDGwWlyI/tSxw0NxM7Dm/SaV2AUl70s/xWGolnUb4H8mBgZJAFYnYqKwP1HYFz+g2MmNj9f/RgMEgWefeSJ4C/4nMrt52yrfJg3Yd4s2f+5JlM1NlRXnvQ+Myj/BeDfUhKF1B5ldYxVKTX8KGCWDmPRNgHJ1QVlo=,iv:b4yjFrHAPefAkhYnbtnSFX258L2Kqd1IVYd0+oy3cag=,tag:6K4Snc6UiHzvsmXoK4mmyw==,type:str]
    version: 3.13.1
