apiVersion: v1
kind: Secret
metadata:
    name: myinvoice-secret
    namespace: myinvoice
    annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
type: Opaque
stringData:
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:PphRcfkxW6P9OdGLk+OpGvgt5v6cnA3ofmNO5HhFC3TmmsRaR/+vIA==,iv:AOrWSo8Rg7bOrGpN2VlL8jUY9TM9/XmVm2zT6uiOvA4=,tag:8Dgk8vcVy+7eZfxKwbRaTg==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:GSav/bjYI37Rv+pH590groXa+1QzyF8tENXB0NxkZizD1sbmNez91Q==,iv:bQL0JPjPIRKOR+jcn0c9m27TJd/SHhik5NRs3Z7KWEI=,tag:gVaAOm4W62Y7y7ZGF5vNPw==,type:str]
    MYINVOICE_PEPPER: ENC[AES256_GCM,data:d9Ojzs1z9GfX9baaKnsaJW7ju0fDSd3Bi/+aEkqVoOn5fI3fFns4XlMWW4A=,iv:ejhvTstmI9UBkcZ2aejWcBTrfIrVGgd5SPJ9jfQgQsw=,tag:t3BnOST9YhyyfOJLFxqfSg==,type:str]
    MYINVOICE_SECRET_KEY: ENC[AES256_GCM,data:S0FIocBnbyMjIYDRfna1slazz6QVCGjmhbMhegrcirUSiSr8EZf4Jjcms/M=,iv:CpYLsu+jGftFdXRWeRxjOFeyferSh1gabGpxeg8bbbs=,tag:2Gp8kCg3ordPyY8C71iVZg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbEZJSXAvbzU1YXpiUGFj
            UVZOU3FoTUlUZi9MZHY3dnFza2l6MkU0L0VzClhKRkZJMWkzMGd6bXo2Y3ZZWkFB
            NnV5ZHRPb0dHVENibG5OdENQUVh4d0EKLS0tIG1OSkpzRk5xY3IrZXBleXpyekdj
            T1h4UFNOaEU2bHlqNHlYcFR5dXNPR3cKtYmW841r700TY9y5ZuBdyW1rSFqwl3ta
            63IcLbgesLvT05OXz7mFW3DlMfUAKBkjIdm4xM/kfY9Lo2biAgylxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbUs3dlpSRTAvdW8yY0pr
            SitLUlBvUkNxWFBlWTJOV1JWdU8rTmtDNlRFCktNUkY5VXY5d0Jma21nc2ZlcGNj
            YWhFTVNWcG9mM1hyQlBIdmxQZm9ROHcKLS0tIG9MY0dwemQ3eWdXQkxWUUdlQ0FH
            anFGZkZKSndHazRsS3pFTzlyMm40bjgK9MivYnuMCenpcLSeKJc86l5JwC0CdKdK
            KjnnazKgmmRnuBCKEmlEOAXs/Rp91Sxr32uwu34L2rik/Pxs2oAGMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDczlDVXVuYWxRMlU2NjFE
            bUh0eDZjaHhhZG1xalhzWVZZSmhCOUthOGd3ClpYSzFPTkdxOXJFaXpjZ2YwSFB4
            TjhsczJRaUJGdFJNQ2RsQWZBY3Mrcm8KLS0tIERUUmVXN2NwYUQwWmdFUFBqSEIz
            YWx4WW9OazQ3QjVraXEvNmtWaDFCVjgKWj2Qvm6PxXj9Yg7SjPjEp0iZwbnM7wiC
            W8bYsnQ2o2inXRB+8qgjujO0gjiP3Ncv0+YOLl7vCiPi1K8urVwhig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T10:00:19Z"
    mac: ENC[AES256_GCM,data:HnI5qj6u1SRHDGwWlyI/tSxw0NxM7Dm/SaV2AUl70s/xWGolnUb4H8mBgZJAFYnYqKwP1HYFz+g2MmNj9f/RgMEgWefeSJ4C/4nMrt52yrfJg3Yd4s2f+5JlM1NlRXnvQ+Myj/BeDfUhKF1B5ldYxVKTX8KGCWDmPRNgHJ1QVlo=,iv:b4yjFrHAPefAkhYnbtnSFX258L2Kqd1IVYd0+oy3cag=,tag:6K4Snc6UiHzvsmXoK4mmyw==,type:str]
    version: 3.13.1
