apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:0iDagT6jkFurI1cEX8YYKjqKH2oZu4T0L48vksdW3Bmrucwlp9/mmexYIzoT+xvbI75dhsbmi7kZqZ+BY4W9E6hrpp0efgD+,iv:rhrwBC+en+t/kDklcRGz5glbrW31lTQPBolr5AyL6fU=,tag:EK4XjeO/3qekML1da1SlNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGV2o4QitEUkFHQVBGcE1P
            WE5oZEc2YUUzdDNkYktxODI4RlVLMEl6MXpZCjMxZitIeUZlZEQrbFl0TGtzTDdl
            NU1DNFc3RVo4dDZyWmJiTjh2eE55NVkKLS0tIFNqa01oQWxUWlREeWc5TXQzcytC
            b3Q0QVEvTUNua0Z2S3NuOGg5SEVMekUK9LpWClzO3EChLXVU2NwpBHLuelBYEfLM
            wXYWQo3ZOC2v0zRmDbPo8Zx3ndyHe3Dx2fburL5mX9H1mCymFOO1ug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybS9tL0Q3ajRocUxaeDNE
            NXQrTklxYUpEcTlBeDVLczVFS0FvdW9lMGtFCjVzVElxMTNsTXA0UHhZck84dGRE
            OE93d2ZaQjB4WFZJaE1vcm1vVjRCdXMKLS0tIHdCeDlVM3dwckVxenFhU0ZBZENH
            eG5OVFAyZTJOM0YvZW56cTl2YkFvTTQKFH55rgGsJfcPC/aobIQH3MrOVuHMREjE
            kFaYfFOriUl8nauLW3iMyVPN/IttU/KU6x949ZEsgjSWxiQZq0dOww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjb1BXUHBzQ1JNVk4yZUx6
            YUhzOXVJNGQzVjh5V1E2U0VjaldNNVphK3dzCkxiODE2dnZlRWN2SUVHQXByTnVS
            eStMV1MvUkJRM09UVDNDYVhGY3Uzc00KLS0tIGdIMXN0dHhtcllmUGxzYUpJdEJ5
            bFQ3WjhjTlpKeG9yUU1qWVhhREV0bjQKOUH0wuKuB3HyUWYBk4QuAdTNxPUd4Gzn
            wjZwlWezE54kh8Jpieek/YxxlH1iFy5/uio3+NcQpX/2wPcfLiB4Xw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-16T18:45:46Z"
    mac: ENC[AES256_GCM,data:0wDqgtBi5T/9uNaeUFCFMHmdmWHdlxYc24nWA7u3woAsdiGXuMchx7OD7ICxOWdvA/4G4DShosyS0MC5snOa88He2WdavBnl9VfL+nVgmvhPAmegtVEn24YkSFKCGYqwWg0k5AdcE1SIfPGZHrnjhlFJcMZ/1ZSt6J0GSNEAUlQ=,iv:nfTI5pKRoZ9n2jos8itEUuybnGgC89PHaNkvAjyJL30=,tag:RG4HKyrxS8Q8pKyqTfXTLw==,type:str]
    version: 3.13.1
