apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:0iDagT6jkFurI1cEX8YYKjqKH2oZu4T0L48vksdW3Bmrucwlp9/mmexYIzoT+xvbI75dhsbmi7kZqZ+BY4W9E6hrpp0efgD+,iv:rhrwBC+en+t/kDklcRGz5glbrW31lTQPBolr5AyL6fU=,tag:EK4XjeO/3qekML1da1SlNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdm1yU3NWc3FnUGtxeDJy
            clg4bGppOFk2aUYxU0dmZHVBRUc1a1crb3k0CjVkR2pocWxpYk4wTGgrbWwweDBo
            Y3A3RHd1RTFETXNBTWZOVm9CUktISlUKLS0tIEw4VHBrZ2hGOTMwem8weWRhRWN0
            cm9Db2p0N2pPRUZUbVB0dnNyREdIOGMKkUg7gAbsFeV95vXzFc399f7gwdm+ecMO
            O0KdwIY1VnBE3+2FZP+Q44AfjRTf7+dA8XzY4Z7MKJyY1JHS19pwNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-16T18:45:46Z"
    mac: ENC[AES256_GCM,data:0wDqgtBi5T/9uNaeUFCFMHmdmWHdlxYc24nWA7u3woAsdiGXuMchx7OD7ICxOWdvA/4G4DShosyS0MC5snOa88He2WdavBnl9VfL+nVgmvhPAmegtVEn24YkSFKCGYqwWg0k5AdcE1SIfPGZHrnjhlFJcMZ/1ZSt6J0GSNEAUlQ=,iv:nfTI5pKRoZ9n2jos8itEUuybnGgC89PHaNkvAjyJL30=,tag:RG4HKyrxS8Q8pKyqTfXTLw==,type:str]
    version: 3.13.1
