apiVersion: v1
kind: Secret
metadata:
    name: backup-s3-secret
    namespace: plane
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:64fv27qlvyG0l/Ba,iv:SSKUpFNU5WhKoiIGMl3gdAFMEVH3n2wGyy5HFEzekUo=,tag:9YDnjeScb/wtcMlpMaqKWg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:jpStMQbmFlPz9Lt2e6t3hUFvTeYPyhb+S08iDOvzEPzgvop9nPyRRQ==,iv:Rte7LHZ0M2N7xdn3T4b1ZhGvvcVdCTCZl9xRDeVZMSY=,tag:Cw2LmQLBcYn3FI9VPRwRww==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:iJFd2Qd9wUT+COW05sE0ksalOz/8vWeqlw==,iv:MjqkvT02cy0YwIPlDWL+UAX8J9ndDKhtBvb8r6704+8=,tag:Mr/OFo+e17ZEnUUC1Xj6Sw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUGJ1MSsxbFlsUEQ0T3BV
            TzBCdlpOUmNwUGhBOFAvMDhVTHRlbmVvU3dFCnJleDhZRWlKa1VKemRXYkJTZXVD
            ZXArcGFFZDduaC9XejRxc0UxUWU5aFkKLS0tIFdvWHJtMmxNcDYzWThZZGxRVlVt
            MUc2Q2dOdUFLQzZFaXZYeVJHekFZUzQKQj+0tcXuE4g74qJ01O5Jeu6gL3ypB3Te
            DhEqZH9uM2J/cAv+BIcANF3aIaQqP2qzk0mthDXsCPYtA5MwPk47YQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMUhRR2FnM3NsQWxOVnMr
            ZWZyMGM0WExXOFI5aW82bUdySjFwVDIzTlVFCmV4cjQvdXl2L3RzVEdSRUVQangv
            QWxaUnZZbjl4Tm5NaTc4VGFWLzErNVUKLS0tIGVWQnJIRlRxUjM2dEU3MHJURllC
            YVhiVGxpQS9wNTBTem82QWtjUjg4ZUEKfRqewlqup5PFh+bFrKiePB77SAFx5Vho
            OAzDEvPITLfMWxIpYQ70n2UInOdI41GtSEK43B6tDoHd7waIQk+kVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRTF4L1gzcHRycm51Uy81
            RVhKTkFVMUZOaGgveXNiYlp6cmp3MkhOcFVnClZ3RG1WWkdRMFVULzhTNTFnVEpl
            WVEzaFBoSzRqRE42MSt5VFg4R3Fxc2MKLS0tIGpmMitlUXpXMFpUeHdOa2JpYUtO
            d2hkWVZibHlic1hSQzk4amVmNkxRZ1EK09TrJp0bGM7slqqySwYQk+4oAbS591+z
            uB+oMXjYoCr1v31CLM/uuQuRq8acOUIIoAyHPG+dzoDrAL+anYLdCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T02:12:39Z"
    mac: ENC[AES256_GCM,data:HVDmJzWzTrbySBsOQ6QUh9Eq0D1DO7XSbo9qWyzbuEAEO+6xHcIpT/A4fICNyFZtd71ActJqqAUZfNj1ogG2TfMpEENYHk8+ivvT4Sdm+UzPU0h+opMVf18nWF6IphUI5SGsc/AAYpoSLJNj5Kat17Ao48rNl3OsFeNa7PC0vXQ=,iv:/+TajASN5PSFqdsVVdw+D/k41KEeLWGzFio396HiqjE=,tag:Mn45hIEY1xrezCX3vHR+XA==,type:str]
    version: 3.13.1
