apiVersion: v1
kind: Secret
metadata:
    name: backup-s3-secret
    namespace: plane
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:64fv27qlvyG0l/Ba,iv:SSKUpFNU5WhKoiIGMl3gdAFMEVH3n2wGyy5HFEzekUo=,tag:9YDnjeScb/wtcMlpMaqKWg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:jpStMQbmFlPz9Lt2e6t3hUFvTeYPyhb+S08iDOvzEPzgvop9nPyRRQ==,iv:Rte7LHZ0M2N7xdn3T4b1ZhGvvcVdCTCZl9xRDeVZMSY=,tag:Cw2LmQLBcYn3FI9VPRwRww==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:iJFd2Qd9wUT+COW05sE0ksalOz/8vWeqlw==,iv:MjqkvT02cy0YwIPlDWL+UAX8J9ndDKhtBvb8r6704+8=,tag:Mr/OFo+e17ZEnUUC1Xj6Sw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRE1OTSs4MWx6NnVNVjhh
            azEvOU1MWXhGbS9NV2ZweTRrU0xzeDJkMVQwCmhyOWM3NFZ0ekJNMUc4aUtWS0dF
            MVkyeVNqdzQwRnFsRkF0bVpIbjlWdEkKLS0tIHlaMERHcFI1TzBTbGd1VG9CbVNr
            dStIMzFOaGphVlJ3eVNwclBad0ZnNncKbTy7GJUdQfldNThnrIjkY6/Ql5XBbCc9
            kb3C9f45dVVu9UDUNll99avjFLVK9DBcDjQ7gqxggz2cYiagLru+qw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T02:12:39Z"
    mac: ENC[AES256_GCM,data:HVDmJzWzTrbySBsOQ6QUh9Eq0D1DO7XSbo9qWyzbuEAEO+6xHcIpT/A4fICNyFZtd71ActJqqAUZfNj1ogG2TfMpEENYHk8+ivvT4Sdm+UzPU0h+opMVf18nWF6IphUI5SGsc/AAYpoSLJNj5Kat17Ao48rNl3OsFeNa7PC0vXQ=,iv:/+TajASN5PSFqdsVVdw+D/k41KEeLWGzFio396HiqjE=,tag:Mn45hIEY1xrezCX3vHR+XA==,type:str]
    version: 3.13.1
