apiVersion: v1
kind: Secret
metadata:
    name: plane-pgdb-secret
    namespace: plane
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:00bPLuA=,iv:aCJQ25YUB3VZBirFjktsmGt8JmRieElycpvr5ZPKaDU=,tag:t7AtBGGhrH/L6Qu4m6HiBQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ZfIh2eIlSdMWfH0vrTU+YoulXkEPHw+dm3NxvKuXhDMsyhswObnR9Q==,iv:zlyaXFRGmDw77PzJZUYyYksEts+4yAcQX7g3N0+lGT8=,tag:vdppAd08+uAu+ygpAa/5Aw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:y1GSjL0=,iv:6jh7lbVOnDj2ZuZd5z0E+lCXYaxDGyAO1I/+kD3Kx98=,tag:xpEQSjiyU2xL6ZpIwSr98w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQ3cwaiszRTBBcmQxcWlJ
            M3FYWUNyM25yeUsxT3YwZHR1ckdhR2RtemlJCi8xTGl1aEJrYlQ5RmpFQmZPMkJu
            ME8vazVwbStzN08xL1Rib3BNeGEvbGcKLS0tIDVCbk15T1plVll2aWNpODFaVGp4
            YllqVGsvVzVhUFg1L0JVNmpWVEc4OFkKIYCok9TNj5aaj/CI8z9zsapNbt6xYCMb
            UpDQXwwzkJRP6UgBxtk293f3ZNqzYqg9xE/+3LO7QdHLevrOAnL36Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T01:43:50Z"
    mac: ENC[AES256_GCM,data:yr6Q7xDCttTB88UtVlkvh8MxUBBx7hpc8AysHPacMZrfo8gtfnq7GB2ByZwhSR2YOP3djV/taewpm65N8lLd56lgb4PRNrwtlPqA3oNZLnmcoP1pVUX53m8flrFK042v9WuUrTywBkn4AKOtdQEqk+7t+FtP+fQF9sKf3cmkS1A=,iv:MxVcS+MPfSwaG9yMPOAK4BRYysv8vEnmsSMV0lls11w=,tag:kaiFtCHkad8eCvRVMQbyBA==,type:str]
    version: 3.13.1
