apiVersion: v1
kind: Secret
metadata:
    name: plane-rabbitmq-secret
    namespace: plane
type: Opaque
stringData:
    RABBITMQ_DEFAULT_USER: ENC[AES256_GCM,data:dHGEwnY=,iv:F+bsSNB5956XVUQHOMFXUiqeUBrJ2YHC/h9XVLrq8pc=,tag:WZGXxKR1qNfK42fBGOjXaw==,type:str]
    RABBITMQ_DEFAULT_PASS: ENC[AES256_GCM,data:s3L8HKqb028UFFuseHgQWY9K4xtneLzVTst/f+dgJVNuowEcpFDCWw==,iv:mRIz/AGBS39KkpnfYFZj8Vic6LC+QduVSHLLqN3SqSE=,tag:wUWQ6vUaCBjj2gcnZKftNg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VVlGOHRUbERQam52amI0
            OWM1OWJ5d2NBdmxUa3ZqaUVpcGxsMTFxa0VRCmxOYk42OXVxTDFzaDZjTkVLemlK
            OHJGR1NBSmkydldmV0p5Rm5JREw0T0UKLS0tIGhhZys1TUd2RHhRTnRJUDZnTnFU
            KzhacEltbGdOaHNKc3NTODgxYThZc00KsAL8QAv8wmoJ0L8S2eVneosJAZjHxNSM
            NK+Uj6CoxWrSasJJUtvRyjdHct5cpM+OYhNWYcVY0ZkQ5xu6yTwSgg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T01:43:50Z"
    mac: ENC[AES256_GCM,data:tZXuD0DELA82omZuZj+/j2kzmivga7lCfjH2lGj5Sd5hhQV7dBvXDK/iowr5lT7AhXJSbqTCnC2ok1ku+h22qvU4nP+sajSQcmp6cZuXHSjqRZr9F2w7MqtWEUD4KKSN0EsuH9pLXegqAWwiZbIMq3B9ZXuzH8DF60MiC2Tm68I=,iv:5USvLX+JgdOwo24EF1KIu7GW3dhBjMvjn0TBITUZZ7U=,tag:YMPXf7ZjcIEsdVWMZa+tYw==,type:str]
    version: 3.13.1
