apiVersion: v1
kind: Secret
metadata:
    name: plane-rabbitmq-secret
    namespace: plane
type: Opaque
stringData:
    RABBITMQ_DEFAULT_USER: ENC[AES256_GCM,data:dHGEwnY=,iv:F+bsSNB5956XVUQHOMFXUiqeUBrJ2YHC/h9XVLrq8pc=,tag:WZGXxKR1qNfK42fBGOjXaw==,type:str]
    RABBITMQ_DEFAULT_PASS: ENC[AES256_GCM,data:s3L8HKqb028UFFuseHgQWY9K4xtneLzVTst/f+dgJVNuowEcpFDCWw==,iv:mRIz/AGBS39KkpnfYFZj8Vic6LC+QduVSHLLqN3SqSE=,tag:wUWQ6vUaCBjj2gcnZKftNg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBib1Nyelhmanc3NnBqem5C
            VjdaeTJINTVnTXQ4azBZRFRZMkhkbFoyUkhjCmp5NS9sMnNlc1IvZkt5bTUyYTFn
            dWdwc0dWWmlwaUZWcTRHbG5JZFdyY3cKLS0tIDVjNS9kZVV4M1kwL1RqeDFVcG03
            eFM0VldIL3hWVGFNbVRmeW5zdk5FR1UK3dGPpqwzzcyPm2fdpLmnxecBVHE6QVmZ
            rHT2bJnYL5Mudv7clHqT0xDEHJcz490wv9imH0VP/Wnedlz8MtLQWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZk9WNG5xRC96RXVKNE5Z
            ekQ0bGlKb0RHOHpDVU0rSTNWTDZjb1dVeDE0Cmx3dGhoT01rWG90b3NSUTJDT2xN
            VjNRN0RiUDZiRjJLUEU4NzFxbEtHeVEKLS0tIGRDYkJ1cm9pRkZ1NDU4UEFYT2tz
            TnFVbUkveks3STkxZHlhQTFjcU4vcVEKDfEZTyGCqOgANiOMcbHQyKM+clP/NRNJ
            CkucRlU50mC1JTHAg5NCan7RXZAziPt0ky43sAKK8LZO1s3wcFM4Cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTzBaSmFIdE0yWFZoL0lD
            R1BpWjJVL0xsa2ZOckoxQkI5Q0dINnR1M1M0Ck02L0xRaXc2Sk56M2w3RlFiaytK
            VTBKTW5tT29DUkFQTUk4ek5rbTIreVkKLS0tIExGTWJIcXRyR3N5bVBVWllUNlNy
            alBobWtFUm5jNVZ6bEsvOU90Nnk2TUkKEsM2ohRVfoIdeGw6UVfb0p3yuuIpr/VZ
            Ei6waceJFSG6imYrL6pB/cNmJgFnAx/ulHv3LYzNynYrJj4NO/HdvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T01:43:50Z"
    mac: ENC[AES256_GCM,data:tZXuD0DELA82omZuZj+/j2kzmivga7lCfjH2lGj5Sd5hhQV7dBvXDK/iowr5lT7AhXJSbqTCnC2ok1ku+h22qvU4nP+sajSQcmp6cZuXHSjqRZr9F2w7MqtWEUD4KKSN0EsuH9pLXegqAWwiZbIMq3B9ZXuzH8DF60MiC2Tm68I=,iv:5USvLX+JgdOwo24EF1KIu7GW3dhBjMvjn0TBITUZZ7U=,tag:YMPXf7ZjcIEsdVWMZa+tYw==,type:str]
    version: 3.13.1
