apiVersion: v1
kind: Secret
metadata:
    name: plane-live-secret
    namespace: plane
type: Opaque
stringData:
    LIVE_SERVER_SECRET_KEY: ENC[AES256_GCM,data:L/Gov1Tnb1yDNr3jMhY09bRA4TKo54/0C1s9BvIWcoxnU0X6sO6b6g==,iv:f0j1Nba1g8lHLYmszh1BH/9YO+E1O0WjUy8dgIbn170=,tag:dP8lOf5gyTuaARh/MvDMqw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:dXAEM2A9voT6nKPuYCeXqXn3aV7gGHa7t/f/DTxFxOtltaLSstsEZQH+p89EZrM+2Q==,iv:2FHrZI1HL4aoYPc2dCwtH6G6vPewVCPRu3KO6LsDr24=,tag:uHms6iugdPAt36WUYXNBYw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VzJXckt0N0huWmNuK016
            clIxUGRzRFFaMXA4dTQ3UUhHeXpjZnpTbGxZCmVFdnczNHNra3REYllObFY3MUJy
            c1VrSTFmNE1tSTJ3QzJPY3B1NHd4VG8KLS0tIExvN1JBUkVVa3pCRUJDUysvV2pi
            V1M4NnhZd05WZnZpaExLWXEra0MrQmMKnX+wEoTYoK0CpXClagSJzMtVk6zsffTw
            0pHr+HGUVb/t6gg24ePTRxGWWo8RgMSKB+fXkLCRRKJodyUKLWe4wg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T01:43:50Z"
    mac: ENC[AES256_GCM,data:V03EX4BaSl+ac9rjM/GQWOVpJ44GqRLo79cwzpItia0/mHA33Dp5ZEMQwdUf2qE3A31cfavhRvIa5g1LuE98TfAWmdgiVlClEUuTlk+CjrLq2KLdprYK4rQj8uDoCwi0EQPez0toKDZ4kbb0n8HbJLYhHf+5mitFyLb5xnFqc2w=,iv:hYJbLAqWZJknUCYH/Y90H0NTJkSqU6H59BfBmcMMi78=,tag:0PykcAr0HEeY7mT20k6W+w==,type:str]
    version: 3.13.1
