apiVersion: v1
kind: Secret
metadata:
    name: plane-docstore-secret
    namespace: plane
type: Opaque
stringData:
    FILE_SIZE_LIMIT: ENC[AES256_GCM,data:A2tF7knNw8k=,iv:w24aYjxK20WaSM3dT9dpw4OYFR+kDxzbqKiByA8kF98=,tag:XJv/aBeHcuHeYzhrs3X7Bg==,type:str]
    AWS_S3_BUCKET_NAME: ENC[AES256_GCM,data:2tW0B2MD2A==,iv:n8RLJ3+2RDRNeaUZc3i72EvfXxViwfvOF11TF2IDqak=,tag:QMFWZUZ73xM/rsNvfzVbkQ==,type:str]
    USE_MINIO: ENC[AES256_GCM,data:gA==,iv:Z1pQhH4VNNz0+gPz+VJPv0qkD7alZTuy8KSopWDCnmE=,tag:Ocw4Ri2oGXImGLU2AQ3iyA==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:Gya4DxwaSygMtw==,iv:L2V4/eXBrPgyzUGtiTP64Gd0QquY76nU/1dv2clxJyU=,tag:poPiXd3e//af9xkD0byUKw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:dxG0ZyWenctc4SNEx7wu9+wEfuqwlSHkcLF4SFPc5v03ukRKrLn8tw==,iv:5t0k+664ZCBtfOma69TDxExTN83oeYZUZ5oIIwJWMvE=,tag:jvSiMfefiP2YvUMu8avQJw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:6KqPsuJ4bLGJVA==,iv:BK+gySNs3yc47/KuRKNXfOkrLG1FYkoaY+kjUBhtm+w=,tag:dJea8WUKJgHxl7j1/OEeAQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ogAlN1bZc4Ngz0a7cd3ipZS9oS1Huivnn/uYVGZ1lJ245P19uUXi2A==,iv:RVTlubE6wvsDZxMq6J8z0TkCkrCLylAzVY2rExmPNA0=,tag:GPk60F5Lef4GpFJu5S6Arg==,type:str]
    AWS_S3_ENDPOINT_URL: ENC[AES256_GCM,data:UGgss+wAhyMoXOgn/it4XtpL07bjy10=,iv:dUDAPEOCVlzCms84hYk+hzKUPDFf3KGSZsKVFfGkueQ=,tag:UgcFniqMb7P1Nyr/Dpc3WA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUmpHL3dMS3N6Mzk2UFNt
            TUNnbnNNWXRrNnNueTlqRzZsN0xPdEV4VWhNCkNTVnprZlJETTBJUngxcFRxQjRV
            aGsrZU9wSGdSMVpUNkhvOUZFcmRjV1UKLS0tIE5EazA4WkdKT3dOTTBaQXF6emln
            bGljTUpWcGJCS29wdk92cGFYVmZUNXMK6p+/HFnjFaKskmlv4Htvp0EokdEuviI2
            R0eIoZ0C4zlrwb28ZpZTxj4cqi2owE+zRUOZNeEfAxh3HQcCTtk7aQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRGhZWnp0V3d0SUxrT0dw
            NERiUVp2RWhDQWVuQ2Z1UW9BQnU5dG43cEUwClFXK0ppRVZIL0lwcUJMd2pOK2Z5
            UEtrT2w3WEZLVld4N0lia2U4QmxkVWcKLS0tIFc1MUhMZWdxa1pIV013T0pjMTFJ
            bno2UzdYZjhEWFZnQXZVOTVvVXZkUWcKu6dE9DjZqGCELsMuuTDh0KtbxXOrMW1Z
            zGLgvHRY8k3ihziLRmlw1FiTql7hq9giHuiMox2mQ1YhnMAt4Rbevw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZXdIeFFhZWdwQ0ZWQjZF
            UVFpOHdWOERvUkkvM1MxMFhTcUtON0xpTHlrCjZvNmU0SUJkT1JITjdESHNDSmgx
            dUtFb0kwTFpia3kzNDdCTDYxNzRwZ28KLS0tIEh3K0hySHZkNDJOeTNyQUZIVE9h
            dGdxaEFWejlUSmtKTWJnV3BubnpYN0UKWgI+uDGr0jwckSN85afMRTtAxCSd3hVh
            lvBEytAeOgi8oBsx7Wg6XP1V6BjJorW45ssZAtKrddT7+XePTBRzfw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T08:49:55Z"
    mac: ENC[AES256_GCM,data:x8Ccmh91R1t8iCQa1j2fxXdgYvS1YF+2I9hRDxxRsbRf5htjq2Bd4gXCgQ1AjbmKJVBd9/LvIJdpGH/ioQ32ARLv6eWpNqM9bap5drvZi8BifTlF3xEjIDvJu7no5uWQfaQ07OYoC79BNaHi1EABEHaOi8UzVTtzf56j9aqOMLA=,iv:FQv7gwyy5vEeSe4WRPn3mXfhsVw1x06Ck77kkDjB/yw=,tag:Su5ZUXUljtTaK+OYQFXmaQ==,type:str]
    version: 3.13.1
