apiVersion: v1
kind: Secret
metadata:
    name: plane-docstore-secret
    namespace: plane
type: Opaque
stringData:
    FILE_SIZE_LIMIT: ENC[AES256_GCM,data:qSF3BD7jEds=,iv:creXJkqG9zjE/f0p+J9Ms9MD2OV9WhFNIqZyMq7ZHGg=,tag:rAucMvSz6Ewds8LXEQFuBw==,type:str]
    AWS_S3_BUCKET_NAME: ENC[AES256_GCM,data:y7PX+/xRJQ==,iv:LgZ7I31c/7qB6e+f9hbslnh+f0A+Qpf21q8Ep3+MOYo=,tag:MrVpeadqs53iYrvHgacSuw==,type:str]
    USE_MINIO: ENC[AES256_GCM,data:PA==,iv:NZZ5b/J1BzZM7ppYGwC5t+0fTla9GMwBQn4a24KFiRo=,tag:N1/WFjCmgcYVOPsGIUHxww==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:ak/gLg6QYFnn0w==,iv:zxgThMoyc60S5l9CXPA7XL+99WxuupmP5TF128eoOlg=,tag:wfDNyGYzXPtOxHJUUVJp5Q==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:0DLZolTj9pU3NqiHHzM1CgwJgNaNWaGqpekkKxK3yca9sNIh4bXEag==,iv:DO7JDVM/8+vhWiwTNmFhjvwK7cs8ovxhOcDTCVOJ2Gs=,tag:Dm61e/kypwxfiiF3SRnspw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:T38SrwQ8XsQLgA==,iv:GHDMrHxwvoI8TGFx9cQO6a6bHOZlStiEftkPhtkf478=,tag:rneLqysRc/DAvSAJzi9e1g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:JpXIWw0EttvPFmaQA6Tn7eH367TBtMcXmmuNwU7WPF1cCTd/+B1Y8w==,iv:DCBnJdKc3Jf6YMJyRxPSUM1vNblCnKz+jWnX6Ccm9E8=,tag:lylW5Daz6zmknGhPpACW/A==,type:str]
    AWS_S3_ENDPOINT_URL: ENC[AES256_GCM,data:Oc6ZgULqhTEuR09EgRJ4Ukjrc3dbwB0=,iv:n+K+RhXMdZiPbB/sg4g7g77TAPn2EgKZjng3HbbdKUU=,tag:kPF6CpAKr1Kz3P5wkvQKEg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bkRmQTFUQ213TjloMHZX
            ZnhjQ2l2Q3NHQkM4NmhuRCsza3ZHUnNZMjBRCmswZXBDRHgyWWp0RHlqZmMyK1ZQ
            WCt4djAyT3JtVVIrVnhIczBuY0ltSDgKLS0tIEdhakIxVU9hSS9UWUxzQ3dxaDk5
            VVJOdTdTSDE4cXJ2WE5oQXR5MFJyUXcKk6NkaxcjiJyZLO11y8qjvN0NywNwAKEO
            gm7SfAco8VUkbOMvtSznIWRXvydc4VPsIQsY474Dv/SOD5dXi4rm7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T01:43:50Z"
    mac: ENC[AES256_GCM,data:mATiv3Vx0RG/+lSj+C0lYMvk2ye2ooWiZqhYlf6iqXv67AjsUhnISkra1d35bW3QKICohemgO4BHZ7etPmI9EuNVLa7ishbMBEkNuaQzhirZVTk8hJ1nNj8fQKFnTvAQMzOn3FrSHWbjsTMT6JAyzm941FDw4bZKrVEUedJ6SAI=,iv:fjMEU92TiBod5yqxQHoASFAYGej7QVjTnq3SsV3afEE=,tag:tdGX0/vRgPgAir/5MVM3Ow==,type:str]
    version: 3.13.1
