apiVersion: v1
kind: Secret
metadata:
    name: plane-live-secret
    namespace: plane
type: Opaque
stringData:
    LIVE_SERVER_SECRET_KEY: ENC[AES256_GCM,data:L/Gov1Tnb1yDNr3jMhY09bRA4TKo54/0C1s9BvIWcoxnU0X6sO6b6g==,iv:f0j1Nba1g8lHLYmszh1BH/9YO+E1O0WjUy8dgIbn170=,tag:dP8lOf5gyTuaARh/MvDMqw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:dXAEM2A9voT6nKPuYCeXqXn3aV7gGHa7t/f/DTxFxOtltaLSstsEZQH+p89EZrM+2Q==,iv:2FHrZI1HL4aoYPc2dCwtH6G6vPewVCPRu3KO6LsDr24=,tag:uHms6iugdPAt36WUYXNBYw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUUwzdVcrVlhGOHp3NjJR
            QitKUVpQZWxadmp6TUtVWlA2RWlOKzVaWEI4CjlGbVF6WmFOU2hLaVpKa3VKcWhK
            NnpmaXF0MXVzTmFXeEV6TitTUWYwTEUKLS0tIDJCVFM2WVV5MWhrOUU0aG5VTWx2
            K2xiR1YxalFxWCs2MzRpQTU1eE1SWWcKb4MOZ5zHLDuICf0wUhGu302jo74gQ4Bq
            jCtPKETsfmKk7d+PhEOcZTrWgQ92BGNVppaJjOyUdh3HBo1ZDA83sQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVkNEb2dGSEI1V3lxZGxm
            TjdHSUlINjNKTXRuNCtFRGJha0dhc3lQbVZRCmZySU1CeHpIZWJMTDhjVGRqbzVD
            VEdaTjRpeEpCWERFR2FvZDN3NHBBdjgKLS0tIFRkVGFOaGNIVk1CUW1MYURRZ1ZO
            TTRQeHlaRnRXQ1kxNVBrNW1sOUx0UVUKJl/kKQBAp+0JsbxfhNiWkYWr2W15cSrg
            tfitQwzS1nY7DB7g7b7OQRQtf2FF1KMu7Oi1uhcr1FTgA62kWQyMqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDd2Z5NjF2ZzJreWtndnNm
            Y1NmOW5sVFhkY3V2djZSRUEveWZ2WXBsNzNZCktTOSt6cndWZEFYY1VZanZaOXVR
            OHhSUGVRVE9MSjhoUytaVlhhbmN0NWcKLS0tIDlnQkNtUmNiZGxTZGpGdERuL1l2
            Rk5HU2JlMXlUeFdxMUE1NnJhZGhERkUKFyy91uzDypLbgScKtOpHFp/X2oE8JuOD
            hgMnlVOL88IaJoPAE+DImH+LquMM+QsB/tnu448N8EBsOsHmFE9x/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T01:43:50Z"
    mac: ENC[AES256_GCM,data:V03EX4BaSl+ac9rjM/GQWOVpJ44GqRLo79cwzpItia0/mHA33Dp5ZEMQwdUf2qE3A31cfavhRvIa5g1LuE98TfAWmdgiVlClEUuTlk+CjrLq2KLdprYK4rQj8uDoCwi0EQPez0toKDZ4kbb0n8HbJLYhHf+5mitFyLb5xnFqc2w=,iv:hYJbLAqWZJknUCYH/Y90H0NTJkSqU6H59BfBmcMMi78=,tag:0PykcAr0HEeY7mT20k6W+w==,type:str]
    version: 3.13.1
