apiVersion: v1
kind: Secret
metadata:
    name: plane-app-secret
    namespace: plane
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:pEGKQkAb9G6GsbJvzB8Yb471fq+W+EOk53+QwQx1mSa+6JB895O+00m5OdqpYogiY24=,iv:bo+AIijbCFWsx8ii3X1jY9XPlujrADQ2Q0tu4mY3cCo=,tag:I8WqeF4ggqk/CpjcRBPL5Q==,type:str]
    LIVE_SERVER_SECRET_KEY: ENC[AES256_GCM,data:zAq/d6WKO8dmjl20ehrJ0aWySvdEw5j7a6aaR/urEFaaczjez3+8PA==,iv:wp0MKsmkh03/ykxyvRmzcv/n3UCgb0UZC9+zfaRBZc0=,tag:r/hteC718UFWRU1FL9eCww==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:D2B9fErOENSN+6FQTyHOQb1SyinTJxwJi0Yi4Tqp3KVTR5H3ri50dAO835qxDNM6EA==,iv:2pDF8LdCK91PwgZ3VThb+G6aApg9rZA2PA5BMl6V3Qc=,tag:ONgtJOyM/zOhseOy7tFYHw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:qM2YaqLeVtaIZ+v+ZSOShpHT8s/bGiYd0M722WqPX+4XKdpYuR4nmSGY86sp/wAhtFS7HLUmegwjrFTcvVedg59Waz0K7PympFDrcVkeTO+y5oOLBNIDET9eIgG+xfcqTQUs5g==,iv:OKHa+rlh6NgrG0gBWE3fkgWUmEhhYdsa6tFg0BrJH40=,tag:wORzhDMmNqQPscPN4i6bow==,type:str]
    AMQP_URL: ENC[AES256_GCM,data:HMcf6+VDV/g3t14+udg75mvISTL5dksEjkKOJ2QLo+vhkylmFcIw4YDAcw3FqmkK8CzvQWudJOSxtp3EJNZ+R2oxYHW+T0amKH4t8lD+TJyQMTuN40dTIiiLPUcl,iv:x/xRjKUEqbUq7QaNmaRNu0rhe2MG1PntJX09iaVmKS8=,tag:p0BaLMiU8ZvBKRN5xTZaMg==,type:str]
    #ENC[AES256_GCM,data:lslKByDx2mz7p+hipx36LAZXL6rp+UJt0FpXOV8sM7Na4nmUt1MnMPrIlAxgsWoNU/Ii73kVy6dE3QxJPthlATccXK7DI14ewA==,iv:bont3DTzXCBSZzupLSuBLD0jV8cy37uzE9lKlsOu89g=,tag:j93Fu8hXZgODuZ4vvAdyEA==,type:comment]
    #ENC[AES256_GCM,data:thVhKU19QBoGB4cs7V+uTgj+Fiz25iwksZmLvGF2NxHuskz3kMgatrIzcLaWPJyabo7C4OE/K6X9VhUc5XWngh1Ba86hKAjm0g==,iv:m5fD1yr6djpoNi10g8lidkeBi3zG+xPmZG4h+LkRqaQ=,tag:OSt39Rp+v6XIAfg7BGtiaw==,type:comment]
    #ENC[AES256_GCM,data:qPxYlcXeIaKKLqrDtWR/60BPBwlBgSrUOIWv3I5x9aVOxWJJ6TseM76C+zv48Q6/Vz+7LfTlwGobyvnzvldht4BDgF7NIBcUXnhAifo=,iv:zN1QMd/CL088Hz2YFM9GDo474sGsQ/VuxqY9gSZx8iM=,tag:mGmp4i9V+PiNjW3C+53gsw==,type:comment]
    #ENC[AES256_GCM,data:f14OSDe9y47GcwdOdTYBs6ET2O49N7hyklbd3n2sru+WjbE3J5tvjKs62+32nbiMOdirccKpulLkSqpS6vhgC+MRxpxzGcGN4BqjIQ==,iv:CaPsIXzT+w2QAOiCePiSjff5k1aCZyj4ZQ+1mLGH1OQ=,tag:Hf8UxH3wt3561eK3DjSdsA==,type:comment]
    #ENC[AES256_GCM,data:P4NGwVBFAebGcpIBm/l+D0a+ZpcHmGKcoBIckEZEQk4imMZa0lpC2Im0eAvkigJlI6XViyGupqkBlN90Sxp4N/0=,iv:a50Ne1Gu/2QfPXx+Wv0tqGLca6iSyRaGWtq9FG0IOn0=,tag:38aFj5Gn5v+NyiwZ4rTcDA==,type:comment]
    WEB_URL: ENC[AES256_GCM,data:GCQ/jOuQe/3J3UXcHTjkHxkMkihuMLrVQC/zDg==,iv:bxDOWgcOeY+yeYaojbZGyM1h4WIomVvNjQsagpfx3iI=,tag:+t1Ld539yBcYynBjW8wgXg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VnYvS0JtR0VrZ0lFMnBS
            amhPQlFUR0tPcWhpSXR6Y0xYTDFnK1RrUUJRCndRN1Jaa2QySlV2R2cxODhjSUpT
            Ym9YeENDSVlBdkZ4cGxRajlxc2R3ZWsKLS0tIFpVcitNQTBOYkp1NUxZbjBJVmw4
            c3FyZ2gxQk1CMjlvWUxrR0tUOVpvSncK6BSIdcc/cMkNoynQUli69cSOvVusaUtX
            ijYTSI5odG9hrgb1OiQB4h0CHK3gfKYFlKtcoQBcCzBmWPEA6mKe4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUUI2OUt2NzhWMmR2bVZn
            cjVVQU91cENzbkRhdTIyY0lleTl6a1lqbnd3Ckx6U3V2dzVDVncvN1lzZVZPTTFZ
            ODlmOVJtVVoxSTYrWU9PK0lrSE9ITU0KLS0tIHUyWm5ySmwzMGljQ2o0NmFZd05q
            V1RWR1ovRVNMellMQ01jc3lpT0xkVjgKX61y3R/8QW8G2Zrkpc3YNPbQ2FfEvjgX
            ED8wwkMEB/UBZFADkJep7WGJe4HTPZNcryw5/4A7QCgYoL/2+tdrxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMGI4SDNGdG1CODg2NHQr
            V0VmM1M1MDl5ZXRFVGhzd3ZHcVhuTDdVYmlnCmtxT0cyWVBYWTlweDRYYUxRd0hW
            Nm9RWlM4OWRuUm90emFwaWNHVHNuL1kKLS0tIExJV3VFNzBTa2s5UXZURStXTkZk
            Si9yOS8rTzhBUStBZURlT290cmxwdkkKVfP6JTQsIGVV6KMVfoWbUQs7WM+qfbrN
            iAJXUM7hrrxWrpF/bJ+ywd9jD4X3F8qOUYzwzQIoI+6E4lJkaRyX8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T01:43:50Z"
    mac: ENC[AES256_GCM,data:bPssPnibo99AxRGCV4+wKrIyaLXhI3QDqT2yipuNbH96EB6KoqyrfRYakSz35N+3qTIqmBkRlEqAJZqHRqYmuSATq3y9i77xI38ayu34j+bTcXUjDJDyBAnWFzIqhzWbW7YtulXSF63VU9QTO6epjL/K5Bmo8hL7SFTpPo14YaI=,iv:uzdcv+QX4jEtMHm1bKVbwE8mOMgFr/Z0NCpzmv2mqx4=,tag:zSHEUjx8asnKLCOjXt+IAg==,type:str]
    version: 3.13.1
