apiVersion: v1
kind: Secret
metadata:
    name: backup-s3-secret
    namespace: paperless
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:M2wG3DgNFcIOkXdwYuweMA==,iv:ewP/FhcqObIOnfnH4KiSr/3hdzja5xhguXhHf3TcR/s=,tag:+MBYSPTMAry/JiIsxrh4Bw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:9iPoNoOZiBT49kcIkWPBHixp0Jd0ZViOcDEdWKLN0dIPXofNGZv0ng==,iv:GYtFQJ2R/rFMVRKcl/5n0N0v4ZBoMmut4FOwyp3bDxE=,tag:WoEwiNzuxf76RdoSAn7kCQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:bS/lOz60bkypP5Q64zsQmI/gontxoQZqAQ==,iv:0kNoT5xbGp/j8l690PfivEq3/ii9elr7uotcgdTbEC4=,tag:XOt9A92zAdttSDL4QU6a0A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENmt2SytzMnc5TS9EQWZt
            U2tyQzBHbWI4YzJndjBXNHdLaVlBOUhJa0JFCmtoMHZlSTgxUW0zSUtoOEYwNU9k
            eGZoRWNiOUhwS0xQOGhlRC9LTnNkY2cKLS0tIGdhaXUrbUsvZUpJODVpdUFKSnY1
            WDhTRy9XanZZWFkwVU9hQU9FSFBLQUkKkLhRWGOiqqbQy6BZywNITVCuPq2drwYz
            SM0vUyxq89RbVObgypgRj9XgsCvcmmgTiUDZpCiZ5ZKtP8USFG6Ueg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNDdNK3RnOC9DOEk2SEVK
            MUd2Vnh1emJUVlBGeElGVnhUZ2pjOUQrclc4CktPREE5YjRJN2NGcjNKOE5mMmtG
            ajBxZXZ4WlRic2JRV0JEOHBkT3BuRmsKLS0tIGdSSWFpbFFFS2ZuM3FpMHJINVdL
            Szk5MzM0d0dtNXhZcXJqeUMzRE5kN2sKiDrux2/qJY2+35Cg1UBCg96NLyNA8OLy
            KUozzRzbQKVmpYCI5jtlge6DupIyZceUGzaInEvDv7a8Ke8qa4dFOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdXF6RWxjOGM3OEdtUlJj
            UUtMUklodHRMVDNDSzVCVGRsV1JRRDBVRUU0CmVtZVVHWkMyR2x1Z3VzbnJiTVd1
            d21CNVJwYkpzaHpXamJEMEJnVmFTMjQKLS0tIGRsNFdwaGd1eWtQV1pxTC9nUm9W
            UWtzOUlIQ0VUbWJPUko5NkNUbnBQNFEKXIj8DNY+O4OdRKfU3EHM4JvZUcWVaEBC
            mtj0sEa85gRCHyoHwxsOVlMsWtSljD8/B1p7ofLyFdG+bH/JICl+bw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T12:21:48Z"
    mac: ENC[AES256_GCM,data:953/t8EIb2KzPRPDv4C/UbGFWLCtbGUps/f2k2l8aMqK1g/IKYPI0ibSfc4vn6qMBY/yJr1XjAx0Q/LzboKnCsSkjHOT3J/hPWzfe/OffC1DAmMVJhsMOYtiEGrTZQLc7x5FFUTvjMtwn0FdxUDgmbesgE1PokYWv4xofN41Qjs=,iv:pUED9UY5efDMqLyRlLo8Jc5OK2hMIal2LL9x5EOFt7I=,tag:Bwe3p5JdGoio0X6hmSxOyg==,type:str]
    version: 3.13.1
