apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: paperless
type: Opaque
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:PDazJ0B1h2NkGBH2mez3EAi+f7J7csAtA7Pfh14RH8J/uaUlo7px3LjXyRK8QSuuzA8=,iv:Ud84jyGwDqJUlj7JmfqqDP7OM1KBEiQrOoCyro9k1+8=,tag:YbuuZRuoUtnfICjByNYqYg==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:tMQxpvDx6s576JpDt2S3o8T+webxI/ILbeSWi4lU8Ww=,iv:MCtFaypxqrJGxEjk2B8RZgUv7s3ymRqw/E33X+w16t4=,tag:ySv146fC0r9QzGiaSDDiXA==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:0ClGHcCcg6lmdUVrdwL1Q4JyK9VS0rcbcIUUeZSKwB4=,iv:vD6uRf8R9KiAbrr4vv5IMhZwYeuuirIr4iXfLed2ZMk=,tag:sYD1KJzN6QsoyPKx7sZmzg==,type:str]
    PAPERLESS_REDIS: ENC[AES256_GCM,data:lfEDP6VA5E0KMjGoX67QwwjoYvncZak86XdosEAHDms25OVB+DJejxImF0/HQiQgxu9ROg==,iv:wEzaWOvGzjyZWxuk4uBp6pJmafptor82JfkKfsVQtSs=,tag:2849OGiQI79yNM9EKgnVvQ==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:Tw7TqqsPzqw=,iv:LnxaBUqMDXblFt8P9YqH9Ru99IHq3d/t7rreo8c1qm4=,tag:2aSwyri62Div0gBRH3TaWw==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:UDPA+0VmAev5j5s4wCQpVU4LuGWvqLO/,iv:eaVb0d4T8uppZD4sSbBkl2hR+MaKdhcMQcBjn/AJO7g=,tag:X7R4VHFjbwdSc/Q/y0N4Sw==,type:str]
    PAPERLESS_ADMIN_MAIL: ENC[AES256_GCM,data:ZqbN5ro4lW8y7cSrCrbfiz4zZbcnhnwZy0eTbA==,iv:sHDqTluHqsq3+35lunuqc0wTSfVJTEI7o1A5OaUicQo=,tag:9JmkylQ/IyrG2LK5DJ8M5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ODdtR0k1eHFNa0NsaThM
            TER1djk1S0RPcEZpWUZVLzFabmtLTHZHS0RvCjM3WWV1clY0TmNCbzc4S255Yy9s
            TElIM2k4YkhDRTZtOEpqNUxYL0pEaVEKLS0tIDgxTEZHMWNvN2pQb0o3RjNBYjFv
            T0FCREFSNUp3S0VwOGhIcHlkRXRQb00K3rZjwpZOfjIUvPB6AkkMcCWZvPaZdSnm
            9OWBpkKi626ktLUyTy7Re2mKs7tkcoZrBtRNnYhjGMUmUNST8FlIUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cHNBY1d4VVMrZXhVVUtB
            WEJJL2tteFJsdUZUQ0JUYUxXKy8ybEdnWEZJCkZlSkx4aGp3bHpYTUhockFseEFl
            TEZHRkJDRTdodHFhVVFuVVJYMXFvOGMKLS0tIE5zWm4vWXYzb1lPZWhkMkdabnFq
            N3Ixc3JxNm15REFsWHY4QW83VGdYemcK+Ovk/aogM8Kpi1u7hP1AA5cV8m8QvSoL
            NvhUbuMDMDeE452T1oSW7okFlgpHZXJd7M1z3jAL5Dom4kxTyegoKA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YStTcFZGOXhMU1UzRWc0
            WWh0U3dIdlUxaHRsNzZkOU1ERXNBalpxS1VFCmltK216bW8vaktobVpIalhLa3V3
            dk1LWmRpSTNJd2xKM1RnT0VrNWZLdzgKLS0tIFBVVzFqeDRTeEVlSk1CSTlic0J6
            TStVcjZEMkhPUGszeUF1RStKQ1FoYmMK2FCxm1vbIKzQVo7XqmXHHobki8PCVzui
            Z6U0Ids9uNgy/kzKDUoz5lzTxo0EMFwjMC2NX9my40+/Z8hJWbAdIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T11:45:07Z"
    mac: ENC[AES256_GCM,data:+vazmmQRQPV3fhJE5Ah8OGHe9d/5bV5DokXpL3k/c5ftw1VQP9qBHgMlA3HY7c4+kLF9E2UzpZnU1NoD46aeHAZs/2EmmQMoDdo0QfcwOV05arEMpVK585u3ygSNXUprhCGeyz3gh04JN1ikO91NvvBBC0g8Mb36X3rhOeVNQjY=,iv:KAhvQ5A2MOuevMKGV5r34fDUgvlMxkWCyAO8QQ9qTKw=,tag:dB659fZ7J5WyRYuRGJQLEQ==,type:str]
    version: 3.13.1
