apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: paperless
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:L9N8xCke1tOH,iv:VrrvSZdEpl2zvGLnozThEGCTlt3mnBgMUEi3CNadcgQ=,tag:KPUxG9jZ5xhVpODoe0iz+A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:6/5DSLH16Aqke4yA6j4y5z0Q/XErrcgZAwbBDwH/ivQ=,iv:wR5OOD/AA9q9P4hOKVCPFbTDw4dxvDhxH16l1CbAykk=,tag:ifS2cwiyHRrIvWWg7mGbAQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:gTEMCGjZX0Or,iv:0flRktoWN5hbBLlZlw0DruAKQzdSC5GHNTfCC5x6B+U=,tag:gDZ4rOVlVk9xQKPnFjswaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dHVPUUxsaUc2M1BlYzBL
            SXhPRWFETHh1aU1oWFNWU21qd0ZtV1c4REIwCjRBNEY1REZhcEYxT0hQRGxDczBv
            eS9BNU9QWjNveHVNSWRJeDJHblI5NmcKLS0tIFdLYmpHTENyWk03TEJJTFNCS1NX
            UjNEVU9vZzZBTks5NEw2NGo2QXE2bUkK5+e5zGwVRufNpU0dCVPDeQaV8Yv32FmL
            JhUqIpLFS+k2J52QuLpXqagkL8N1SYnbsdIjKG56vx5Knw8eiywdCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYm5xUHViSDFVQkdETEFF
            bElFeW8yZlUvWEthYVpBZGtsNzA1NDJGWlM0CjBWc0t0Vjg2SEIxSFhCS0pwU2t1
            cnJZajUzQlZPVFkyRXhuWDgxNjB0Q2cKLS0tIE5DWEpaVkR0b1pyZ09LM0tFT1Bi
            dmZxZ3lRSllRdE5ZT1NmZURob21wNHMKMz+rIGL45mbUi3l4jfrVkmdrb78Vi8EJ
            iRoP+PfhRVZJ8QbDodSljN8zHVGbddw2I3+tmxsgI83HrTrJR+XMww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeXV2L1ZFbGJTWlo1VzE2
            b2hiWWpUL0daWWFKNmV1VDZlenpPUE9QTndNClppQXlQZVYzTmtFaEtBaFMrcUpn
            SW5sdDJESlRaSWdXejJiSlRJWVVTNWsKLS0tIElRNGxla0llb3Q1REFZRmlzS1ZN
            Rjl3Q0wyWTJZS05wNEdMY2JDYjVwSWMK3V9SrN/bjGVRd0sEjxzvpD6pf/eIEiE5
            CzRjJZymNFbFHQogRE/B+diQ4qCErwBjusxB80j5//JN2apnm8izRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T11:45:07Z"
    mac: ENC[AES256_GCM,data:9JmVONyEAz/vDSdONegwI5WhAU7VhxadbYc2fYutFNRsG2aBxYP+BTMPibGPB611Pf+2DgcmiLQDNL6jU9E1osBGRgvvDnZz8HWM/JW9iMxCLJa69o8mjPVONYnqM5paK1zM7mow32MBQoiKnXC7ij5ltiRIIkv98O4vQ8K187Q=,iv:8jBs4hLuzEsjogv6z5068FxXCVgs7KKXTlXK01kTwAg=,tag:DP94x15PVNUtaV279hOEjg==,type:str]
    version: 3.13.1
