apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: paperless
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:vskMEKD0IQnf,iv:fM0xhuYQsD2K/NgWpEXGU/uUdih1MC+GVTW1ZUm5u3Y=,tag:HAAFhf7lEOQDKtThlut4mg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:F2cRO2JqhShB,iv:u0puWlfszeuerOT273a+KI/VgtaglK+FvF9GMEFQnfk=,tag:g924AMk//qb9r0IY7cpMuw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Lx0aAb5CpILQI/YwnBIjB7RZuuA4utD+39EEOBA5HA==,iv:Ni1+Q3MfykkAsgHSh3inouhnuFMJIxNBIf9cHBvBstc=,tag:ZAScRCf68ggZt8bc9gnXHQ==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:gyopoq/1muZEfZNbXB8Tb/wX4kHpFyj7htkkoOOuYwlloFciR75F0zYs,iv:7zztzFs+9eSLfWvtWcHLcFGvmUTa4Rlc+an6MN9LyT4=,tag:cejur9L6MNUTwjZJAZUtiQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1clprSjRhN0ZyTnpLVVhN
            dUxYaXFKQ2Q0ZldKWktERlcyc0JaNmpnL25zClJJam9ETk5EU25LWUZaci9tNGJl
            d2g0ZDJvNXVYVHBCS1U2NGNGN2cvWG8KLS0tIHZIZnRNY1NQdFR5TlhhMEIydlNy
            eHE1QklpdnU0NXA2dmgvSHVqNUk2L3MKVlPVv5wWc/n3+6sEFTm9EYbYyah8lgUk
            tmHkyfP1vgiBh65xfe1LfS76g3a/AbJdbs9kX9bE1s+3spdoGTcayQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T07:06:55Z"
    mac: ENC[AES256_GCM,data:6/NPnggZJ0/cBkos9glto/THpE5rRTpSPXMzXe18LPu5TQ2Tcmy1yKjwb6u6KIvA2Em1hetGoqtTgJJGgebp59444xXOXNRvCD98Q3zcJ8ofvJwMC0GFwoupC/rmwwKyREiSuuwEsZySYYQ+88HSNlVnIHd6uYjbVQEjzRtRUDI=,iv:t36snfJJ85BCYvcjhUUHmI0Cwziek1pbWhe4a48K/Ps=,tag:MSX1gC6YdIi88CWoT1Qecg==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: paperless
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:MDfgQYsebUOYkRqQW6acDBQi5EkbyC6OpiBWZC1WmfjkoLTdHZze7TcULi5t1jjQBuKRaCnm3CkUd6Cb,iv:nkKpWiJ/s2T1Dtvrdi9/VFx7ref2BDYj90IFWCaC02U=,tag:9BgMMin4W9LEUvF7SYJW2w==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:LkuFFZvpU/DvlruoDZYbTVJrKizpp/q2fjO6phaINg==,iv:YziyWqQXYOSZoXtmn78mq3B+f3cFQ059F0IopFmaI+8=,tag:lDpFB0Un5hx8odPB3RU+dg==,type:str]
    PAPERLESS_REDIS: ENC[AES256_GCM,data:mHxtCII3LuQdAurqpZRuI23Gw2nULps2JysPq1XQwABFNll3dAtkV2T1nJOHySfPNoIyEw==,iv:dX5gFQTYzPsbtGXV0bwGnYxJNkybcK2gwRkthcoSShI=,tag:ejKiLtiWc1/QQzZEA2r//g==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:3bmONxWNOHzP2zOtnQgnvZcECwpy/Iy9woIfO6YH7oM=,iv:ivi5u5Bf6sQtvMy/m6s/rlZCqJzRtZlI//lGDtG4fQI=,tag:VdHw/iWGj4dS7B0uvGGnXw==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:+TINnjo=,iv:p0vOxHWdrGcEE2HRLb3CicsXC4reE3Dc3RD5OEPNV5Q=,tag:TdEteNWLoDfDfWXV5X62yg==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:RB7j7qGLH+lNIUbfg2eJ+GuG8Jv4zS5os4S1DEwKNFx42/CRTOoJrucfwQ==,iv:BjOWlWOeUQK5vzRzNB0jNSyCi/h60z+wNor8lPLcgLQ=,tag:b18Nb+Q1ehrIMHqzTw+u0Q==,type:str]
    PAPERLESS_ADMIN_MAIL: ENC[AES256_GCM,data:+RJGhZl5PQPWEinpXgYir1O0GbM=,iv:wJxSmNDYP011KRwY3CPzV5wjevBIk0VvxMV+/efBDos=,tag:3IEhRWudkV6JexUli9idSQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1clprSjRhN0ZyTnpLVVhN
            dUxYaXFKQ2Q0ZldKWktERlcyc0JaNmpnL25zClJJam9ETk5EU25LWUZaci9tNGJl
            d2g0ZDJvNXVYVHBCS1U2NGNGN2cvWG8KLS0tIHZIZnRNY1NQdFR5TlhhMEIydlNy
            eHE1QklpdnU0NXA2dmgvSHVqNUk2L3MKVlPVv5wWc/n3+6sEFTm9EYbYyah8lgUk
            tmHkyfP1vgiBh65xfe1LfS76g3a/AbJdbs9kX9bE1s+3spdoGTcayQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T07:06:55Z"
    mac: ENC[AES256_GCM,data:6/NPnggZJ0/cBkos9glto/THpE5rRTpSPXMzXe18LPu5TQ2Tcmy1yKjwb6u6KIvA2Em1hetGoqtTgJJGgebp59444xXOXNRvCD98Q3zcJ8ofvJwMC0GFwoupC/rmwwKyREiSuuwEsZySYYQ+88HSNlVnIHd6uYjbVQEjzRtRUDI=,iv:t36snfJJ85BCYvcjhUUHmI0Cwziek1pbWhe4a48K/Ps=,tag:MSX1gC6YdIi88CWoT1Qecg==,type:str]
    version: 3.13.1
