apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: paperless
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:8U8/Zfz4D7px,iv:qyrOkRFrS/49ym30biPOKiWj1XTBbHjV6+tqSoTdm5E=,tag:PFQbWmDyfEjNI/yw7noZ0w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:DfBrQ5YCLRDT,iv:PDOCeTkEErDf/5xzaNvcwMJnl8H0JBhuuuFQwdqE8R4=,tag:PLsxbFSMQiA5kFLbZMDuQg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:CRIO06h7f+aPhkt+yJWRk61BS1P1bLhASGei1OCqVw==,iv:XylxfNnh5lqMq6HBEZvLZc/rKBhZV/t/aY9Bp14K6sU=,tag:4697nxirlZvnEElvplKcaQ==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:q8+Yiquv7LPMdZmvtDmy99zz3ZGt5Zav4WQzYl4BbxX9tPxnFbEQOu1s,iv:qTGmssvCnk4dg6+6xcMU4yqhkmZY/uiwnd9ZX7zRuLs=,tag:L/DijSUXwhv30M+GqiURxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjY1d0U1ArK1FsRnVTM1FT
            b0Y0Q1haWFpZT3pVaHBCTThZWGE1dTZtb1ZZClN2MVFWRHNpTnBIbzJlQStQM3FN
            aFd4c1pDeUtjTFNrYVdzTjV4Y3czNUEKLS0tIDdZZ3F3Vkt1YjBHYmNxQTAvSU4w
            ZU5XZWR3bXhGZFRyckxtblRESFlqN28K9P5Mh7M07FiTpZlVuKlSo8oXEL4C19Dz
            GGme0QoqmsFAR+o8LuNE0hIjEatjzmQNIozFGze+x0o3hgGW16J2DA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T15:04:12Z"
    mac: ENC[AES256_GCM,data:kKC6nYRCfZw7VYQIJuzLAk9vnOgarTUUEyKB4RbWofyEm2Mpl3SFmd4+cyXfmkgq8JGixD275cmh0thE8p0Ha5F98oR6Q3k49p4FalGdkt9lHQEoTk6M1BVHIzsv+g+jiPorPoQa0vCAACwsUALxoksaNaoCpcwr0v/sSqyXil4=,iv:TOao3g4+BZe0Talcyr+CREtckN3p4V/+TUxifMgUyCk=,tag:As6oLK2KMGALnD0taRdJ+w==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: paperless
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:743mBJ7bZCaU680UgOgJeTNrwpCUvCStEwMqG6dq7KK54WNYgYZbSnCjttr9INtDFyYpgQ3oJKcvbS0n,iv:oCcBowcPFeK1Dfm65IJXR7PSIsXc4BDMDaJ9eFdwwiM=,tag:wel/3Wn/XLzoltYhXzuxzg==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:miRi/EV9VtPgmh6vmbNFGd4E0/10Mw3OGCbJBaOYSA==,iv:q+nfStsa8Pnj1K7yOD+d2m50x+jRVhRXzA+VsvtqLHk=,tag:wB+1gtZsWKZ31USvNOzF0A==,type:str]
    PAPERLESS_REDIS: ENC[AES256_GCM,data:qHj93vbdxecvFD4nCeA/MfsNW7sOIy7CTHbx+TSkP40fuUTU6W/jss4eIPqJBYvuIa7GVg==,iv:TeGC7c+k3LFmgD9QiFPp10QKCcmiVd+H6zlyq/tofTo=,tag:gmU4jquxVU/icncheC6SNw==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:HA9cDgkLvuNDDn9InAO3PZMHpJTqUzqnGkjyo2yKcLI=,iv:gngGkYV9dwRtvfqX2F7BJNO0ZZdb/mFoeSWgim7MBks=,tag:4xo0uRe3ijXk7ljSPxrrIg==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:qvx31P4=,iv:pgcqdGgxQrj1aYcuDR0FwLiw8Ep4Gb6fpcS96qmMDhM=,tag:FgjtlgNfoqfxEXcfumx1ew==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:IUF0ZcxcNVU=,iv:48WoSiXqWGGfXgvfE9lpn3R+N6RQszo9leCRsYxhnF8=,tag:DtAINtaKzDYoc3EcHtUy+w==,type:str]
    PAPERLESS_ADMIN_MAIL: ENC[AES256_GCM,data:o3tDq2T73X8WIqO4E6Fi4jme2+o=,iv:a/QI6FsPvOSKLpMEON/J+HGjUruEqVu4TfU8cjlf5Wc=,tag:a3qSyBdvDIsJhx7gOYpUHg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjY1d0U1ArK1FsRnVTM1FT
            b0Y0Q1haWFpZT3pVaHBCTThZWGE1dTZtb1ZZClN2MVFWRHNpTnBIbzJlQStQM3FN
            aFd4c1pDeUtjTFNrYVdzTjV4Y3czNUEKLS0tIDdZZ3F3Vkt1YjBHYmNxQTAvSU4w
            ZU5XZWR3bXhGZFRyckxtblRESFlqN28K9P5Mh7M07FiTpZlVuKlSo8oXEL4C19Dz
            GGme0QoqmsFAR+o8LuNE0hIjEatjzmQNIozFGze+x0o3hgGW16J2DA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T15:04:12Z"
    mac: ENC[AES256_GCM,data:kKC6nYRCfZw7VYQIJuzLAk9vnOgarTUUEyKB4RbWofyEm2Mpl3SFmd4+cyXfmkgq8JGixD275cmh0thE8p0Ha5F98oR6Q3k49p4FalGdkt9lHQEoTk6M1BVHIzsv+g+jiPorPoQa0vCAACwsUALxoksaNaoCpcwr0v/sSqyXil4=,iv:TOao3g4+BZe0Talcyr+CREtckN3p4V/+TUxifMgUyCk=,tag:As6oLK2KMGALnD0taRdJ+w==,type:str]
    version: 3.13.1
