apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-media-pvc
  namespace: paperless
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: paperless-media-nfs
  resources:
    requests:
      storage: 100Ti
