apiVersion: v1
kind: Secret
metadata:
    name: backup-s3-secret
    namespace: nextcloud
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:z3tE1QEzlFYoZ/Tmun+mLg==,iv:SZoYPEu/C7gopTZod8X8M+re1yNUC7uqxGlRScLv6tc=,tag:TloeL16gTpyl1C8SDdo2Lg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2bSyoF6ADkwG/jwCNse4Nlgb/dg/+c6xqIyYHxctZFk=,iv:PsVZx7mqzHcYGLl9Mkjh/DcgtLGQsiWreC2agdeqWIM=,tag:CTDPjxWfdsLjDyb5Ibo8UQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:njld2CX1iK3eEjn2UnMocQT3ronPMLrbXA==,iv:JLdibPrfZaIOBNXsBZCQupjd+ozsVRsVrjxfDVeKhhk=,tag:a6SD8P/SxO8h/AFmWQ35jg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eUdCak1FcE5iMTVFaXpE
            K0kxa1VDSytnbWxISGFSdlpDVmJDdVZLN0JFClhpTFJONHJseVVDekhvQTZuRDRE
            NUlCb09sSzcvNi9JQ2hKb1I1ZURhRnMKLS0tIG9wWDFaMDRnbTY1WVNudnNWZnc3
            eFR6R2xUM1VjZk5VbXZBQWkvL3VxcjQKbvJ9dL/2iwIMm4peHkHFmKHxK9jRVojZ
            r0AP/uiodiEH+nIde3FGL8qeeh7Qff+CXbgYNnn4e4ko90659jC+7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVFRYVE9YQ3BPL2hQS0RG
            cnd0NWx5ZXpkVzBReGZFSUpBWEZpaGQrSmpNCkxHU3k5alEyRStGVGVUaVQ0V053
            Ujd3VEM2U0FEZTIwZjF5VzhRMkhBeHMKLS0tIHhBQms4S1FCcGUyV1BFbW5RZnpm
            WVcxWVdSay90d3k1SWNvVk56SGR3YUEK7OymsvYurXNQBQwXIl5ngvv0Oidopn1W
            pYfkB5wr4f1tjDxcrwwWt24IahS7C+1v/yVtdRG+CDv+HL8SP+uleg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdGJPczZnSXFnd1d2VGZY
            VTRtdVd2aWVXaGF3QTlDdWNnTGo0WUZBRjBvCnZSTVFkSDQxOTBIU1YzTnpabFFl
            a2VFRW1vQk9ZaVI1NTcvcWFTMzgvdVkKLS0tIGVVdVpGOUo3WU9NOEdzVkxLVVJl
            SmRHYkwzTTlVN2Y3VW44YjY4ODBQWHMKrTSCswmNXr/ZLeRxSUyW78TbFC0q+aKU
            QBFkTSMzTnxdUfd0ZvbWq15wGYqFvrlwKUR+x0zVztIXNkbji7wTZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T17:42:10Z"
    mac: ENC[AES256_GCM,data:QlE/c5ikCsa6sPgJYyC7Cc7RMCPjUZ8bxIbTTuzwoNud73rVVXUo3vGOSrWE5Glyp1DIVK4v0vc4WDk7L9BRa9lbZE53BvaiVha7FPpbLmsH/EgKLLcJL+ErvMtfFyCBpSL7N69Du1JQEK4qMy47Ja8k0AR8ErNqQW5ojASA/A8=,iv:JGqQOezIF4nypKYZfZ0yIZgCqiIEyMUKikJfV6jXQAs=,tag:V5WTnKV+yX45JluEiDg98A==,type:str]
    version: 3.13.1
