apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: nextcloud
type: Opaque
data:
    NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:CcA6RtStNjj+MoKbgZ1kzDwPjF7Bkvfk4SDRy3aj7R0LD9QguwHqsZ6iNQpxkbpi,iv:jhJxOvAnEHVa25y0LmccsWtbY+Ct7o5OvzDVPYJK3/g=,tag:F7Knz/NjVC7gSTIssXCUcA==,type:str]
    NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:QQRnTvqbQ6Y=,iv:bDfbt/sGNux82VzetdJ0DNY6RUXiu/aiYu8RfAAuDCY=,tag:w/baSx/abP/bn/o8AeQ6sQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:dxukIwpzoiSVUXBvgbU33uLEFkP5xLEJdDZyhxHCASIoaMwuSaU6rQ==,iv:LlW0RH83xw/qDWrWJ1+mmP1wQ1zosR0FCCg9WDGlH3Y=,tag:hCYuKC8jSrPbajLOJdw2dw==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:G7SVsJc19mkGd3gIrsG/ad5M1zcREs9ZcysMZIBrScm6/mz1cUydtFZHb50=,iv:WwzTjwpNVOxR9PshXZpsUYrB/KHGpNymPOF9+kzcCTI=,tag:XqVc6uaRPg3JtD7qVEGkpA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcHZGSFVzK0VVTDIwU2xu
            ZGppUzdaUjhjR0tRN1RKTzMwcXJFemxsTEc4CjJpOTNIZTN5NVgrNW93b29Xc2xI
            Z3dQUGZWT1FBbmQ2UVJQQXVhaTM3K1kKLS0tIGtJNUhOQTQ0UTk5V0Rybjhjb3kr
            NTlXRm56Q0pNMG1aY0ZSa29lejVHM2cKj38Z02Dv3Q2kru6xxRWFhurAhjBBMbxI
            YF4Gdcg+TAJ+ms7xKF8ywEMWP12nuRajf3Y6DrsOgwlhP38S6+duAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T20:56:50Z"
    mac: ENC[AES256_GCM,data:jAeIFLIPlCEEaofYYEHb7IbckRHv+7Bw04lIYbr7oWNFNKY2Av+TscDpXJYtJFPGIUTNNOQ2BBmhRaR9n7MjNazWhEiDav9ErRbbR5zywcy9z9trga7JVG17WESu8oBL/+BiH5qmsefLS3CKT/gRB9hSN7xmlnvBglrcvdkzUko=,iv:HuZjtzr7yLjoyGnVAu+MECmoY9yTYDOnejvPO1o2MAk=,tag:QnCAxV+u7peIYP2GftWNJQ==,type:str]
    version: 3.13.1
