apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: nextcloud
type: Opaque
data:
    NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:CcA6RtStNjj+MoKbgZ1kzDwPjF7Bkvfk4SDRy3aj7R0LD9QguwHqsZ6iNQpxkbpi,iv:jhJxOvAnEHVa25y0LmccsWtbY+Ct7o5OvzDVPYJK3/g=,tag:F7Knz/NjVC7gSTIssXCUcA==,type:str]
    NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:QQRnTvqbQ6Y=,iv:bDfbt/sGNux82VzetdJ0DNY6RUXiu/aiYu8RfAAuDCY=,tag:w/baSx/abP/bn/o8AeQ6sQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:dxukIwpzoiSVUXBvgbU33uLEFkP5xLEJdDZyhxHCASIoaMwuSaU6rQ==,iv:LlW0RH83xw/qDWrWJ1+mmP1wQ1zosR0FCCg9WDGlH3Y=,tag:hCYuKC8jSrPbajLOJdw2dw==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:miqQ/jqkkJjQoXKTo/osE4XcvZkLyWev/rrPORAWOuv2f7i9Ia4xaX8gHF5N3r70usjd8WwOYtb5PrIfZ9CShNmFu2RnuL2FC5fk6P2BxoY7KVEZQKPCsw==,iv:fhqMK+Llu87NU+IOvDSENPAxvtWb2BnFsTeS3zT4PNY=,tag:YnVuBKTsdsCZ1dSbuFTvhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVS2Y1bEpsRDhXZVk0cDlH
            Q3NiQXNPczE2S1A3RVpvd3BhOEgweVhFaGk4CkIxcjdEcHl1dXV2ekNrZ05FWkRB
            OTdpZTVWU3l1YU9VN2duMTFoeC96bzQKLS0tIHBtMGN6KyttcFNIV2hpQnV1UUpS
            OHJmWlcrcmkxOS94OGNNc3IwQm8wRUUKOv2jb+oh60zFYou+9kptFVzTe3NxEU8C
            J4gnYbHKpfCvbZlgD6ROib3FrtTrHEMUFTiQgAd4i0OQqrXrfVqWLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNN01pUXkvMU1JZGZLblJO
            RFY5dThWYkRac0U1YXN6Y2ZTenZUTVFLOXhRCno1Y3Vob1BMVkx0VmQrU3pENVda
            YnFPamZmNGFkSE1CK2FOUm5OMGMvREEKLS0tIG9jVGxJVEYxQVhRMHhVb1BVSHFS
            aDFOWXJuMmQwS1hDMC9RY2Z4N1RTV00KUBrBxcXCAJ+r867upnEJFdk01wZzio6/
            PKYHdUD9i9GprFH1ulBPzWjiCu/sSAb7DF4MvNder+str8lDMfedIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITHVpT0J1VVdOTG9jZ0NI
            c0lPL0dCQUhqemFDNU53ZENPWndNWE5KRkY4CkY2b0oyYzNxNWNyRGY5alh6UUJ6
            M2Z0U2FwRjM1cGVNbjZzRlNubm9laHMKLS0tIHZGVVp1c1YvdWt2d0dHY0IzRnJw
            MUlwMEptdGZHRFNrVjJENW50U21oVDAKCUmpF5QbnTQS0fKSxOIZMZtrodBgRE1V
            QfnY/cwXpUXmQ3N1z3YWmLFNJLArLYE+hbaQJhaF4ppatCVHn07Vog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T21:08:49Z"
    mac: ENC[AES256_GCM,data:lbqwFoSVVRBwndYrZkxumAmkio2LIWRqNkQrl2PXRCMlHXRIwdlu5L+y+VgyEisoMZMGyqz1J0t/i90IIaq5n27aa4WDhpI5AF+seaUOMHLvUdzNJN0xUBfhIiowU4nOTeAF1Y7/ykUXhdnWYH2p5R78GuXk1nqXzuGe8YUs0Pw=,iv:e2PXVhCNyn+9/1P6jnJFprDYnEcSsU33ud5N5Rtjk60=,tag:65nD4DfAqWlQyHSMo1Rtxg==,type:str]
    version: 3.13.1
