apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: nextcloud
type: Opaque
data:
    POSTGRES_DB: ENC[AES256_GCM,data:KwCatcicuxVc6Lbn,iv:9Fwr7mseHMpmGGxt5l5RbkkSJJuoQ2uUjhwAcET7New=,tag:+oIpyGS20an+/cRHsni81w==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:+4V57xWiP5s94A8xYVowWvNsaI6E0umgR9q0DdOl9q/83706TuBaQg==,iv:fggnpfBqpZMMgW9OWhn0mxngy8+a2Y4uDqa03a0BcOw=,tag:vIydk0x6WC48wJi1/IjLvg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:fbXP7voWYgwxUgBJ,iv:NdUpjnnUDbb0tcBNC5l3ZtLkRPchhNLBikjG8uDPyV8=,tag:+yUCelum5/8bUgcexeHDJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSWk3RldYY0EwcGVPbm1J
            d0hGcUVwWG9JbTllVERJQ2xpYlBOVyt6dmdRCm5CRDBBT2t0azlLbU02RCt0dEoz
            ZzB0RUp1VklPRHNJRDRzMEx5ajJidTQKLS0tIHRCMUR1a0lPUFBkUGwxaTZsNkhq
            WWJCUlBvVDBLQis1Y1k2VWhvNnB3QW8KoBF4cHUH+FepaNmCh94mSTOzjCeiGm5G
            SUki6sK92GIFme7Sx7y1d3coY8tNAeBZdvZvcYmi5nqH3cSfD7MvCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-16T18:46:11Z"
    mac: ENC[AES256_GCM,data:1uEg/wwtuEKWIFTfzVTlvpAVbh5hUUs+YyZuePfdptZCsZOVP+nw+4SXakvcOS80UWIvI0cnP4ubO3cEgGHgxIoZ+UGGfYcZWW7NfkBbvlOfU7Gt3d3ketz9e6XsgU1Jmmuo1vytfRsnAMNBPbu6tJXjQyJzbyoxvG/3Tf7WJHQ=,iv:QgOend0auha5abqQrBecB/Ynm2j+FhmxLGkU6xG/Qn8=,tag:1KLYf61RAIJgqbizu7nZRQ==,type:str]
    version: 3.13.1
