apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: nextcloud
type: Opaque
data:
    POSTGRES_DB: ENC[AES256_GCM,data:KwCatcicuxVc6Lbn,iv:9Fwr7mseHMpmGGxt5l5RbkkSJJuoQ2uUjhwAcET7New=,tag:+oIpyGS20an+/cRHsni81w==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:+4V57xWiP5s94A8xYVowWvNsaI6E0umgR9q0DdOl9q/83706TuBaQg==,iv:fggnpfBqpZMMgW9OWhn0mxngy8+a2Y4uDqa03a0BcOw=,tag:vIydk0x6WC48wJi1/IjLvg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:fbXP7voWYgwxUgBJ,iv:NdUpjnnUDbb0tcBNC5l3ZtLkRPchhNLBikjG8uDPyV8=,tag:+yUCelum5/8bUgcexeHDJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcDJiUjZnbkVTSWZYQTNI
            MnZKdnlLTlNqUDFBS1QxL2RZUE85RUhWSXpvCmN4Z29EQUJwcnBYWG1yS3BmUXhy
            ZXM4SUtqTVZUbzlQbzFGbTRBbWVZMEkKLS0tIHJMMHptRzJOWnNIa2FpTE9wRi9C
            ZVExWU9sdzlVcUI3QVhDaWxEOXlpL2sKlqCszdlaR6qbkLA40huf6pH2OTPXj8LH
            QCHL9N3XHNxlSzGHsI1NmX1MtUTNoJuekXOY5AXKdAkjaZnKg3CvtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZCt4SHVNaGluUDYrRnBl
            OXg2b3ljb0lvODBIaFNDZ0RPZWd0S1ptQ2tRCmdDSmlHbmhKUkt4ckVETzNNc25N
            bzZmNDRqSTlnZ2pnMURhUzVjUWZKTFEKLS0tIDcxN1ZsR24yeW82SVJyMnRWdklO
            d2tpd0NoL082aWJ2eE55R3puTE1KMUUKXhmqiEvyjmHU8yatZjrWHy+mGUwWo3ru
            CyWQhxmleLG+w5J8Lf01O8zQdtCkXLt/fMJ990rpZr+DTDXKpZPXpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYUxCc0c2UGF3cVZrRnBV
            Qm9raXJpUVlXL2ZJSjZuc0JZdjdoK29CL2lvCk92UStGRzNSZEVuekF1aEwwSERk
            YnlXYmVTaDE1MWZCM2c2ZlhqdlBNY00KLS0tIGQyNnorZU13RUtUcnVWZTdENU10
            RnJjV2FqUW5ubTNQdVJXNEx3MjR5REEKiqV+FBCjyw7HkyfZgxd8ol/5EQWH2hI5
            VJRHWEVB9dMHhuT/lgHqVZ2A/a7MHZI1yXuVPwTiGSsIH+jhTBohXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-16T18:46:11Z"
    mac: ENC[AES256_GCM,data:1uEg/wwtuEKWIFTfzVTlvpAVbh5hUUs+YyZuePfdptZCsZOVP+nw+4SXakvcOS80UWIvI0cnP4ubO3cEgGHgxIoZ+UGGfYcZWW7NfkBbvlOfU7Gt3d3ketz9e6XsgU1Jmmuo1vytfRsnAMNBPbu6tJXjQyJzbyoxvG/3Tf7WJHQ=,iv:QgOend0auha5abqQrBecB/Ynm2j+FhmxLGkU6xG/Qn8=,tag:1KLYf61RAIJgqbizu7nZRQ==,type:str]
    version: 3.13.1
