apiVersion: v1
kind: Secret
metadata:
    name: brain-secret
    namespace: brain
type: Opaque
stringData:
    TELEGRAM_TOKEN: ENC[AES256_GCM,data:9Z1v3jPs+qAC/vyLW43T7bd2lW1Va7rwJ1R/DWeUTAPk23HusSwHInsWyjb1WA==,iv:kIJ18q6XXJHI2OkVL6toWSrVej1Y3l9SyWQVjRUdKew=,tag:82EGHeu5stoonedlPkA8VQ==,type:str]
    TELEGRAM_CHAT_IDS: ENC[AES256_GCM,data:WfgYZIribUcn,iv:qeEup1p+aaFravNUwpJsFAMq9DOHA86oIg2kRf3uQUA=,tag:GInJBZil+9fdtl30wwp24w==,type:str]
    LITELLM_KEY: ENC[AES256_GCM,data:oKX/mKmUYH2BqVOTSmkVK6EVKBhNWYn4u2piOHxUGmPH4AiEisaWAsh8XA==,iv:3AHDP0NZ6NKyzZbyU3Aq8yrwi4fnIZnD/q5nlWv/cnU=,tag:mknweqLvZZXSm0L1XNQymg==,type:str]
    KUMA_PUSH_URL: ENC[AES256_GCM,data:SwNMQGTF6yyJjkCV7VCuwgmQ+6o29tBycaTcidTiG6BSVFklgmsG2ZbLB2Ue1WiMpFKm45K6uwIvXJqKSaF3NkueXqA=,iv:9h/WKvxljoLWidwYSdIvBtLnoyk+0294OGbqtxzxFG8=,tag:LyLMQJozV8pRXWDN4MDNcg==,type:str]
    OBSIDIAN_USER: ENC[AES256_GCM,data:8OAq3Xd5p74=,iv:DnDFDj3nZsZj/mQzc84aOdYJkiSzRuLUgWnIk7JZ6cg=,tag:/NNdr56/UQd/Bj7gIPmiVg==,type:str]
    OBSIDIAN_PASSWORD: ENC[AES256_GCM,data:I/ZqEKVarrNmTnVeca5WbHCYDBM=,iv:KSRLWbBOErhPhUi8tNU76AA5l0jxFRhysCYNgeSH0Jg=,tag:ZEfkoGopDnJgSTaWlwqzQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmaUhPbjhOVnlDWTkyeCs3
            L1hYK2pseGhkTURsOFFNWGFuZUhBL0NuVmpBCkExemhYaXFOSVBuVndUZ2VoTnN0
            Qnl4anFndVFlaUg2Si9aWXJpd0tyRXMKLS0tIFFhVU1qWlR0SitiMzVaZ29QVG5v
            MjgwUUx0THlabk1sM0VycUFrRlRUSEkK5eQ9zCoz6/tABEVr8FeMXz2wCp/U4QbG
            Y8zTorHpg5BscWGriweZfeC2OkI7njilIVGef7jUWqsraaFXnmeinA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SG5hVTFSQnU4d1J5T3My
            N3NCMEE5d1llTVd0THpMMUZjZFZFWVR5WG5JCm8ybWwvYmx4VUNZWTZQSytHU1pv
            Zkc2ci9qWXJHcHdaK1VCMmYxa3FpOUUKLS0tIDdvWjZqTzhHWVZiaktzUTR3RVh5
            NW0wUDUzbG5SZUg5L2kvVWpxUVpoK00K2iih3YMIzuH24IGn3rzR8rcNWFm8TNKc
            M4hsM47lkQdq9S9Gg9/MHiuceT+MvO6l3oWTUgtjoxT9qvNJmyeL2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TExoWHBBRWJ2eWRIaExx
            RUZ3VW9wR1J0bm9kbHJDb0dVVDBDTm9weFNZCnFqZGFiTnZjYXJiWU9JV1ZDQUxk
            SjBYVDJadUVQdTVtM0hENjc3cDNmUlEKLS0tIDJuZTFkNGJPdmdKbituOHhVT2ZI
            cXAzQlIrNFd6dUdhMGRmVmZIKzd1STQKiwcID/EtwPA9tNdCnjB9Qrg8od2DUedi
            oE8z+M+qDA2gfrMiRXakEpt9NUfEPOk1YNo9uKoyV4Mh56BM67OUkg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T23:14:56Z"
    mac: ENC[AES256_GCM,data:VDrr6bHijtwDPXN+BvQDb+tVP3mxH0/BqEGF7r83VAS2MiZVh+wjVTrNFqRwuULIs3IJDEsa4xKibhvhg/kbmbx5J/bQ7P2esSjjAPRtmDnPPdzinCHbWNXB9hj1+YSLIupO9SlU6OSQMHvIPxITNZnhVbqkL5/LWSqZK3h51y4=,iv:d9aZqGPcyN1sWRSrq/jMH8XWz1toqqITPvYjD7TFcqg=,tag:10BaZyulNk6Kb0/LuXSrEg==,type:str]
    version: 3.13.1
