apiVersion: v1
kind: Secret
metadata:
    name: dataimporter-secret
    namespace: firefly
type: Opaque
stringData:
    FIREFLY_III_ACCESS_TOKEN: ENC[AES256_GCM,data:gXduJA/LigluP4ztY3tpFKb8Kr5fWmSTk2HI2AUBFMDzHxP5mgkwmB8/GlZ+C3SPOUg2xxzceJ2vUkpYgkXui3niyI5kXkuSQEDrF60b8tKeYRgj7ohEtubshylQEN0ULy7q7+aYhy1xabTQEou8RxuWWcTnln0fK+EQDN++CrBvFS27pSqYo7E6aA/VWoIAHUj8JaxRokM6zasWBTuHfyXKOa7Wd8dsnyhsxlKSREMYodn1QQMK/FBZBa16Vx/hDus6dMt5zzFKJWLjBTUpoH11iFx9FVVLzZYX8oDR7e/TZETBwDZN+MVOgZqRVNe/gS0DP85560UW1mylRI70EtK5UQCXu7SyNVpeAJWFAR2gwYE6oVi4cXdE8YyfJCVyfnagK3Shw2wNkboaI+0flo7E4D/TFE83l/FZFXnWoWgyq6mi6m0EvXV4T+P+Bt7Wmq1+gIsDbANc/OpUpubTbyZGa7cjrWQbtctKk5JSXgvGIUkiUbnZeNu4rb5Ig42iGiBljU26W8jes8Lpwboo25mx3xzOZbtGlwDeQHuWX1DyIvCZV9y0Bm41JaFMvnwD+IODquN//sFfOt+x1Z2yH7bgfYo7lAL6zSd6/q6Iv07fbKvCwghMtfzhuRt0kDjn/1y2Pf9jByt0bmqjY9ov/3qaYzZbE5aXNwiQRReClnU2+WBEL+JeiPpB07Pkw+tevZfN7S/os3ZcrOD+tRJup2Qcoeu5NocydgOoW6oYkSqPGZKiHZk/TU3dYQ56av6yuF+91t+yvTWmZCDtuQcG0qeFmeRWOCy7RFNsV8DMhkVKxPK6ziWLyhKZr8P+eSu9df7LaBijIlquBRmcfXcqdm+hNLOVfp4xajn/X1k5Y9Rm3r0/bnYoIq3evNJ/3qNYnYxP37Aef8RUcvYSQyKTfm56Klelc/tG2g/8B8ZeSXS8I5yqbKE7gi+0izu2g7nbGg4Ry/0jbvx0GBD51EGSR4w0h0QN6vONxjv6LQyerXKMgCyquzbrrik3R5qc7bsrq1PqORIN+0uq8ZD0x9ECw/vLTx+feJv8JyuAFLypf2weW4ILoTUg8Jqx8AnIY/+DpA8j1RqjqkYcVW9cqO0e8mjUVPwmRQ2XMp4GeOPqNm9gPRX55zzS5L+vW9yDuGJMd79KdLmqobBt0GvauW1o58AtQLWmBR5NCYswYdasK3J+8t4/gJweSZr/RL3++hZJa0pyUMqg1kp3sM/jZktSIDH9i6qk+tIChwBV15PY7yhvnaA1+fHveOciKLhxCk/SQFe0+3UulG8BrpGfxTfBEEnAPj7CNLem8p0L/idMoDSRpehDad+Ls8mRaM71gAeiBYvE4VlcpEZ4+IkzGprr34E=,iv:oYgkI/nGlrxLbTxl0st0HoeZEX37cQm76t7JvWyjONw=,tag:E8hoT5zusy5QiJkk4ZhWvA==,type:str]
    #ENC[AES256_GCM,data:jsEc+KLBYgDVkViQ6CojKe0AY6aWMKrtfPRFh3AHN5tJS3Rp5cxYgxthurPjYooR7SQYfXGfg325gawpGvWzR7CHY5up27/dYg==,iv:7rOziipxLdL5LQNBMpG3SXvwxtnkz/qvNNLUftioicM=,tag:CzwPfmoMWKKmqsLABsakew==,type:comment]
    NORDIGEN_ID: ""
    NORDIGEN_KEY: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbSs4UTIwSWVCZytUOThO
            b2JtSy91eDd6djJjNkJVS29EeGt1Z0tPRjFNCkUzK0pkWFh5RlJxallnSUs3dXh2
            cFhvVloxdEdkQXdVNDF5SXM2OXNRajAKLS0tIFNaZU0rSUV2dDR3aldxSDdUZGtP
            cmZOT1V0R2lBSmdINWZrU3pJZEhOSTAKj2nrSeHK+SDwKHi4E7g/C8AvBegrkUva
            X4kfvdC+JeHNspPC8SDDEE2bQ7R2utSgX3ym3iVh4M3vuW0murYQ9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T08:52:34Z"
    mac: ENC[AES256_GCM,data:RX8hLm0ujAT9+p7J3my3XDiISPo8qGS3m/zoQF/m6ZpaZn1Nrd+C7LyAS0zcmWZPzmcX7kpcR3oXI6bF5aTl4mTUzZuE2LYuxS6lrPdQ+U7i0VGvaRfvunyyciRrRuVovuyjq7Mm1aPdbFjU/n/TcFcIvMu2mU8i8AV7MCcyzk8=,iv:6R8D3xy67Kdlz68AgROru6PFhHQXiPs430Cdn5pI6pA=,tag:9g21lJHzGCZ7K+e5SrABAw==,type:str]
    version: 3.13.1
