apiVersion: v1
kind: Secret
metadata:
    name: firefly-secret
    namespace: firefly
type: Opaque
stringData:
    APP_KEY: ENC[AES256_GCM,data:uGj3ybEfJyq9QpKpMmhIYpSIqvuTyh0p2Ib64KoYcz4=,iv:5nFjGNTjpjemTVEO53mOkXFGBvuPXAB7uVnXZsPOlLE=,tag:BBJ2uPCksOqnUMVT1mODCA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:BMeT71w7Yoh8BelptmcLH2Swg6JPxMwObgksjhQkVT0tx5m5947e74hDvV2okeFW,iv:timfjq8gx6da4CAR8IicTKjPWnu2vDyALA8fH9auG/o=,tag:r0vmK2+VVsIsdL8bDJhb9Q==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:7GXOJEWvRIQK3IGcO//qGA==,iv:eGY0NYhhSZJeStqFss5iaoziQfTmlo4gnjyOlHZcgYw=,tag:+cKwURYn+4VOqDSyTAMlQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeVA5dzFGb2hZTUlMbUc5
            QkxHcTVtYUdqWGg2S0ZMVnJyeE9LTUVFOGg0CkZjWXQ2KzJvMUlaMjZwQ0V2Nm1R
            dFQ0ZkQ4TlpPMmpaVUo1Q1dIenVDR1kKLS0tIDdnclRUbm1kSzNYQWVJd0JPY1dE
            TUd4ZCs2eW0wN2pkcHQzM3JzellQODAKDp6WMSL2riXxsEvFeCVt68ACeIJC8ziE
            FhtAf+iix0b8f7iawEjaces3biN/vfsNj7vn3r3OFXgTAb71bM5OdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eWpNcUFoc2xZTFRlQndl
            RmdiQ3JXS1p6L29kZnplRHZKRmI4dXlvRkIwCng3TmdqZ1VWUjdxbUl0dzhhaDhs
            elNsVktKaVBhVUd4OXQzQWJTcm9aRW8KLS0tIGwwa1B1dnJNeGJjTjJvTXdNcW1z
            TlpXaGxTWXpkZDQwN3JFM054dERCMzgKe0zw/1WNdA7bFk+n6ff2ULIS3tb43g1H
            EuASg66Tjtt1HU+8avFKSQbLXl8m4a6MK8PklOsEpXWURxwcqkq0mA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTzJ2dG5LR1pIWkZkREpa
            YSs1b0JQWU85aDdub0hITGtGdTkyY2lqWGdBCnZZYkJ3anJtYktPa21LZ3krZGR2
            N3IrZXRFRE8xY0U0YlFQMUwzRVN3amMKLS0tIE4wajVXWDJSQkhiQmdodGc0c3p0
            KytxWHZFUkFWT2tzN1dnS0Q5UUVZZnMKtmPSlzD8MGPp0x39lg7GAv8IJ4z6WdwI
            MNhkvYRbjn5Yuehk//LRXod3hj6V1DJzrzQ5uoDyajIgRbcR199RNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T07:49:50Z"
    mac: ENC[AES256_GCM,data:sLzJotsJdk++2//VjB9oFvmca7BRfqQjAbTXyYyPYiCMNQOdFZPWIkBa+zssQ5hZcD6uA9tRIWXdWwatn6goYZTWKt0i9esTq/1zlw52U2jjN9JI5TUZfvMlUbYUcpza1hnT0Bdw1wh9jO7G4CKibW6kAtaIRsNf5nNfj7j8bF8=,iv:YdF8lJeZBbyqN4F3/0pE//D3Ld1t/esv9iCwTwOn+FQ=,tag:IO4EWGTyrd8J4MunbAndlg==,type:str]
    version: 3.13.1
