apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: firefly
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:0JSgU7nBJg==,iv:CDqNmvZWe1UbBKuBAlqQLU3b6Yl7d/vjdk0i0OCZc3I=,tag:rxD747d23uuh4o+RqSovaA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:4J/sZ7IXT8ODmq8QDZh8HpK9eeu+QZadgRNYm3muy1GzSLQqGS+E9ApbHFSbP7eN,iv:gZGaCTVSwwIxOlDBcY7rfRnDJjC6LeU2ZSruhbvY6Gk=,tag:RYSinISdHq16aDGUnfM1dg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:GONy/z0saw==,iv:11G7fwn2kVlVdupaWEVm3ClbEwbvTgi5dVU6KZI2t0Y=,tag:FbmB5LQ1YsJ/zN9jWgheSA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRFFaZTNPVzVjdFRlRUNq
            bDJ0b3BTQlN6REw1WDZTOUtxQUpMYXJnMldBCmNDczFuTkxvRG9BSHhzZHlBMUl3
            VnVXdjBxajFwUTB3cG5mZ0pjSnpoOE0KLS0tIEx1MnQ1RFhuV2EwUWRsYzJQbFky
            LzhEVTlkdUpSb3k5ZHRZSTc5SVRDcW8KHC6WgqbWxjtnqxgHrZTQJuTE291JCvPo
            +uXdsiW6Cs2tLEROM/pHxjVeOeRO91hFbD0fS3FPKZUVbE0N+bE8iA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMEw0RGlPUC93dUpYc1Q2
            cGV2dkUwaXF4dzhoNGltQjRSOFRBV0lGTWg4CnlRNGhWMHp5ZEg5MFV5ZVFOM21D
            bW5UdnRJeXZsQ1JRU0hEcU41UzNxMHcKLS0tIHZlb0doU3BxNjhNS3dWUytVRkND
            NlF5UktnMnNxcGprR1NicVZqRElCaE0K/H1CRYwtEI0u9JGJmioQlavRs/W1+O/7
            5vYzmKXX1vvAIkwHGXbH+82D1Q5mKqcyXWbSu0JaaL26ufTse4Thkg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bWpLVWlDaS95ZXVFcDBw
            dGxiQVQ3d0h3c05lVVMzTi9oN0V2TUpKdkVjCmpIVW5UOU05eGNPM0ZvOUpaWURi
            ZGQxSHV0bVBaSC93SEhYSFlIdkdENzgKLS0tIHhHTmdOZkprSGYyYWx4clJjOXAy
            S1lDbGN5SDFDQ05ialpxSkdabUc3eWcKwL9G8joc54Sv0ZWEfmmQPkbSzQTwDHhS
            KCtPXsBHhusTywhhhKRneEAUqT3ax9KxJDY/VgV4DncP/VQSW5ZmAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T07:49:50Z"
    mac: ENC[AES256_GCM,data:PJf4Uc8WdZfPaj5DHs1I41fQ7Kr9JvJEH0VwqPgoMqLsIEeN+Seb7nbkRrjDYbjVV1qltrKEBOu97D+bsKd022ZZ/IspEjAALiEIawJlIy7yUjmjgMfrrLXAmJCCvXulkX58XI2T6joALlHcq6RXDgMO4GwOrh8XEhOcxs0DSUA=,iv:BUHeAFdiNcJQomCltyBfjvhJAWYZlQ9uXMmLYmpCceA=,tag:9LnQK2HRv4kBeBvGTB2w9Q==,type:str]
    version: 3.13.1
