apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: firefly
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:0JSgU7nBJg==,iv:CDqNmvZWe1UbBKuBAlqQLU3b6Yl7d/vjdk0i0OCZc3I=,tag:rxD747d23uuh4o+RqSovaA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:4J/sZ7IXT8ODmq8QDZh8HpK9eeu+QZadgRNYm3muy1GzSLQqGS+E9ApbHFSbP7eN,iv:gZGaCTVSwwIxOlDBcY7rfRnDJjC6LeU2ZSruhbvY6Gk=,tag:RYSinISdHq16aDGUnfM1dg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:GONy/z0saw==,iv:11G7fwn2kVlVdupaWEVm3ClbEwbvTgi5dVU6KZI2t0Y=,tag:FbmB5LQ1YsJ/zN9jWgheSA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbnNqVWpNQVFPWFF4Z3Vo
            Vzl4UzRnMks0aExzVHNUQXZhbjlJcHpOeG1ZCnN3U28vT2JyVDkxZElEQjM5UEpx
            OTRkeXVRdlBTam5ZWGhWUlh1RDBvWVUKLS0tIGIzZlVPNU5TWTF3bmVWN1puS1pB
            M2ttVU8zUzRncEdCd2VCUTZ1SURmaEUKHEnH+RN+tPQ2bzWtyBySPUT3y9rqIQPn
            LgQGlY9ycdFxBQ5ikYmNSENMtyNHRjw/ARPKQ/lm1TDrz8ZrS3HwVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T07:49:50Z"
    mac: ENC[AES256_GCM,data:PJf4Uc8WdZfPaj5DHs1I41fQ7Kr9JvJEH0VwqPgoMqLsIEeN+Seb7nbkRrjDYbjVV1qltrKEBOu97D+bsKd022ZZ/IspEjAALiEIawJlIy7yUjmjgMfrrLXAmJCCvXulkX58XI2T6joALlHcq6RXDgMO4GwOrh8XEhOcxs0DSUA=,iv:BUHeAFdiNcJQomCltyBfjvhJAWYZlQ9uXMmLYmpCceA=,tag:9LnQK2HRv4kBeBvGTB2w9Q==,type:str]
    version: 3.13.1
