apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: firefly
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:wo+ofmIiLw==,iv:gzYU8IWfbSlkasxOtIZPdgB8ZW4ERAkl8qrzDz+0BRg=,tag:fz/+kT3PeWIq5Owr4+wb/g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:CfHCHEY0+WOahDN5JeEguFWYGBytwpPm6HRfl2o+CYl5HaF2lbrXtHVUx+87Cdsx,iv:38apjpGR057uqJHF9+uQARbyGOv/O2ijGEMiGjPpPHc=,tag:TA7KZ341Nkf84Mm08mzjsw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:BTWSgGlo0g==,iv:dHv32uI/SvEiyhzEO2dRiFjuM46WWzQG9XVBJZK6D2w=,tag:bE0BIIj8dvGzHA+ntONQTw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVFZNczBJMjRyZTVxNzZn
            QmQzcHhtTG9iU0I0RStmSHZicDBQcGh4ZTNzClE5YjVBMDVSLzIvN3UxVkVBV2JB
            cHFTTVJuR3MweVc2SjNYWW16OGo1TGcKLS0tIERMcTJFazJuWnltUGhKSkxneTBk
            bS91RTAyakpTOTdicTc0UHlXM3FzVnMKZOwIpJwBubq/9fAaz1DzABxyM4FdBRO0
            4Ig2iG8/DdN8rNbuq8hnWG0bkSFWeAUsP6u+Ps6sg7HxKUm+6zCwXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T09:57:12Z"
    mac: ENC[AES256_GCM,data:hxUmMxT0eQmeGQAqHFLQI/c/6UJbIvBlX2o1fi7poAy7QPvc7nJPUKTWR2Azg+iPchFl0rPkXMvUHdP2heuXrJNP6SEc99NWrs7d3CFNeO8wN42qN/4RN3uzZfbN8cAPw7XyeGwiPbIIKgqkSm7OtSBhoW3/NJ4KlIAOvgT1q18=,iv:FYRQHrcqj+mCy/XbJ4+D56Qcz2eP/UHQt9iyCQ5IC4U=,tag:u/Q5lLe0g01uIwgJh2A3gQ==,type:str]
    version: 3.13.1
