apiVersion: v1
kind: Secret
metadata:
    name: namo-n8n-secret
    namespace: namo-apps
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:DQBU3E4vIsNQrKBtPBsVLBBqsx6WgAVjM8U+LzKkfBGl9wPp9Q7AXnTkSPINIhMonVdFQGD2BMmO+gF0lj8xvA==,iv:cET8xFy/XOx1h86sTYWDb5A4yNUsovl59RdymTMlY3k=,tag:gGFdeDOy06cG46QtjiHqOA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Y1laMHpoTTNqaVEzYzh4
            V2JBT2xPNFFwdmh5dEtmZlIwSDljOHNPV21zClE1NWJoMHVvQlp4cmZhd1J1bExv
            VUpaSm9CUjI1UEMyQWVMdkZmci9qN3cKLS0tIHdZenNCdTAxTTh6bzB0VWxyNURt
            aVVGQVN6K1F3TzFTT2JkVUtIWVhOZ1UKtQTTvflKSjt5Efxo7WrYz2byZok/dgd6
            8vq5ilxvyQ3DENQ3bO8sWNVrMamvXzrO3WZ5nOlfTCBkjuf+KC9+Dw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T17:27:31Z"
    mac: ENC[AES256_GCM,data:boPluXIharB1fPkSGzVG+fcoOed507wlNF2rFk2yUxen8r9Zrqx5lsQsFlIF+dKeLH9OZk+lAh74ovQJJj0Hr65i4ez+sHQo8UQfN6lYifYtea1BFkCcZnGqMAeFh4Rh8zNfu4D39+uafS44zF+vONE8oPuXxY6tNFdkai8IsVQ=,iv:wgGhJUJ+cZmk341LqNbasbHujPS00TRzylyRlnh6AYY=,tag:HU4Z+eSTpcsF7oSSo8LGRw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: namo-shlink-secret
    namespace: namo-apps
type: Opaque
stringData:
    GEOLITE_LICENSE_KEY: ENC[AES256_GCM,data:Hgn+nnhTswz0uwrUMKVXb649IzdHx8Sw2vym1rCq09+ATD/rDViUAA==,iv:gVuCjNUsjCwcjpS2pqpSaBIrg2Qe84Ee0X1uv73vRzQ=,tag:5udeb/ZQ4pHRjtkDl13fAg==,type:str]
    INITIAL_API_KEY: ENC[AES256_GCM,data:zX58ns1ik+2Q61JkOWezX/GR6egBb4GWwL2uycGTQGg=,iv:TQiT4heK9ZwtGVCTqUv+yDotAcFK9WRuYRLZOBJ05sk=,tag:ieSaRGNoDfQx67GcDHM3kA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Y1laMHpoTTNqaVEzYzh4
            V2JBT2xPNFFwdmh5dEtmZlIwSDljOHNPV21zClE1NWJoMHVvQlp4cmZhd1J1bExv
            VUpaSm9CUjI1UEMyQWVMdkZmci9qN3cKLS0tIHdZenNCdTAxTTh6bzB0VWxyNURt
            aVVGQVN6K1F3TzFTT2JkVUtIWVhOZ1UKtQTTvflKSjt5Efxo7WrYz2byZok/dgd6
            8vq5ilxvyQ3DENQ3bO8sWNVrMamvXzrO3WZ5nOlfTCBkjuf+KC9+Dw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T17:27:31Z"
    mac: ENC[AES256_GCM,data:boPluXIharB1fPkSGzVG+fcoOed507wlNF2rFk2yUxen8r9Zrqx5lsQsFlIF+dKeLH9OZk+lAh74ovQJJj0Hr65i4ez+sHQo8UQfN6lYifYtea1BFkCcZnGqMAeFh4Rh8zNfu4D39+uafS44zF+vONE8oPuXxY6tNFdkai8IsVQ=,iv:wgGhJUJ+cZmk341LqNbasbHujPS00TRzylyRlnh6AYY=,tag:HU4Z+eSTpcsF7oSSo8LGRw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: warehouse-pg-secret
    namespace: namo-apps
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:3xOuuOtLXmErndwuhgLstvH/whnu1ikV1I1B5kO5TcuqjMMB15f9V/ovocZfOVw+,iv:qkpyD61v53oqHO9gJK4tcleoNbnvhSyMUj5p4Xjw7pM=,tag:YYhcSFG66KNAnoryYv2wgQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Y1laMHpoTTNqaVEzYzh4
            V2JBT2xPNFFwdmh5dEtmZlIwSDljOHNPV21zClE1NWJoMHVvQlp4cmZhd1J1bExv
            VUpaSm9CUjI1UEMyQWVMdkZmci9qN3cKLS0tIHdZenNCdTAxTTh6bzB0VWxyNURt
            aVVGQVN6K1F3TzFTT2JkVUtIWVhOZ1UKtQTTvflKSjt5Efxo7WrYz2byZok/dgd6
            8vq5ilxvyQ3DENQ3bO8sWNVrMamvXzrO3WZ5nOlfTCBkjuf+KC9+Dw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T17:27:31Z"
    mac: ENC[AES256_GCM,data:boPluXIharB1fPkSGzVG+fcoOed507wlNF2rFk2yUxen8r9Zrqx5lsQsFlIF+dKeLH9OZk+lAh74ovQJJj0Hr65i4ez+sHQo8UQfN6lYifYtea1BFkCcZnGqMAeFh4Rh8zNfu4D39+uafS44zF+vONE8oPuXxY6tNFdkai8IsVQ=,iv:wgGhJUJ+cZmk341LqNbasbHujPS00TRzylyRlnh6AYY=,tag:HU4Z+eSTpcsF7oSSo8LGRw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: warehouse-ui-secret
    namespace: namo-apps
type: Opaque
stringData:
    WH_KEY: ENC[AES256_GCM,data:u2nbva/n3C7BP3+c6oCHz6KNKcgyq4oUPfQQ3WCxqEKsHqQUVK1zIU/SJnPMVpmz,iv:Hq5crJ0eMtc+T4rCUjQl4kYepwaY0OrD+QpPnAybrAg=,tag:wzBP7jLzS/UNFo8sGEFOSg==,type:str]
    WOO_PATH_SECRET: ENC[AES256_GCM,data:ATBCJMrfV42SiYM/pc3L9Xwjo6lMpeQB,iv:SnjYpxxE0Mz/xlpEnj8lchbgsVwoiUa+RMqy3teOkbY=,tag:m5VrirqCH4EZOcQH7BArug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Y1laMHpoTTNqaVEzYzh4
            V2JBT2xPNFFwdmh5dEtmZlIwSDljOHNPV21zClE1NWJoMHVvQlp4cmZhd1J1bExv
            VUpaSm9CUjI1UEMyQWVMdkZmci9qN3cKLS0tIHdZenNCdTAxTTh6bzB0VWxyNURt
            aVVGQVN6K1F3TzFTT2JkVUtIWVhOZ1UKtQTTvflKSjt5Efxo7WrYz2byZok/dgd6
            8vq5ilxvyQ3DENQ3bO8sWNVrMamvXzrO3WZ5nOlfTCBkjuf+KC9+Dw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T17:27:31Z"
    mac: ENC[AES256_GCM,data:boPluXIharB1fPkSGzVG+fcoOed507wlNF2rFk2yUxen8r9Zrqx5lsQsFlIF+dKeLH9OZk+lAh74ovQJJj0Hr65i4ez+sHQo8UQfN6lYifYtea1BFkCcZnGqMAeFh4Rh8zNfu4D39+uafS44zF+vONE8oPuXxY6tNFdkai8IsVQ=,iv:wgGhJUJ+cZmk341LqNbasbHujPS00TRzylyRlnh6AYY=,tag:HU4Z+eSTpcsF7oSSo8LGRw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: warehouse-ui-basicauth
    namespace: namo-apps
type: Opaque
stringData:
    auth: ENC[AES256_GCM,data:ddKsO8ioJio+Dj+weRGaQlZSbchUWHbSVOTlUIT6KJhYd5HghwpCs/smEw==,iv:q3s60ZoTlI2k73z0R1at2Y38CNXwYe3DUMSBdnY/Pss=,tag:zyU+qK3PHFUIW6sTjstQSA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Y1laMHpoTTNqaVEzYzh4
            V2JBT2xPNFFwdmh5dEtmZlIwSDljOHNPV21zClE1NWJoMHVvQlp4cmZhd1J1bExv
            VUpaSm9CUjI1UEMyQWVMdkZmci9qN3cKLS0tIHdZenNCdTAxTTh6bzB0VWxyNURt
            aVVGQVN6K1F3TzFTT2JkVUtIWVhOZ1UKtQTTvflKSjt5Efxo7WrYz2byZok/dgd6
            8vq5ilxvyQ3DENQ3bO8sWNVrMamvXzrO3WZ5nOlfTCBkjuf+KC9+Dw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T17:27:31Z"
    mac: ENC[AES256_GCM,data:boPluXIharB1fPkSGzVG+fcoOed507wlNF2rFk2yUxen8r9Zrqx5lsQsFlIF+dKeLH9OZk+lAh74ovQJJj0Hr65i4ez+sHQo8UQfN6lYifYtea1BFkCcZnGqMAeFh4Rh8zNfu4D39+uafS44zF+vONE8oPuXxY6tNFdkai8IsVQ=,iv:wgGhJUJ+cZmk341LqNbasbHujPS00TRzylyRlnh6AYY=,tag:HU4Z+eSTpcsF7oSSo8LGRw==,type:str]
    version: 3.13.1
