apiVersion: v1
kind: Secret
metadata:
    name: namo-n8n-secret
    namespace: namo-apps
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:0FS+dli05G/dG+RUCyIMiyCwAmlf+Vg//WRuR1DCO9mX7tAGdS/oV33XqEy43eu9/MlLEh1+jmfSp+rCYEa7TQ==,iv:U7zOYmrBIZ2NIiQXCK8wTFRuGSS4IKNWBsLuqAvB2T8=,tag:1qQzKu6HC2B4hqd41pbj+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RHArZ1hQaWoyZ0QzRDg4
            RWhTci9paVFTZWJDUWg0aFVPa2o1N1JCVzNRCmVzL01iaUJGRzBHSGVqTzhyL1FW
            MCsvaFpKUXEzRFlGYkF0ZXM1NjVkNW8KLS0tIGo3cHU3ZHB1SkxRcWVJK0RKVjZQ
            aGlLc1NxSmpScDBrZzBlNGpPRlJadWsK4QxTSZhH0dWhJN65kCkGzDdq0+fP/77D
            eIzoKUU8PRzUZtq80q1sn6zTSeVEbWqo10ttnbTvHFkCYzLOIJeUCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T17:00:43Z"
    mac: ENC[AES256_GCM,data:Qox+uSG2a87q/5wdQhPMehlgvmsuhRUb27cHY3Qo4A1/jVCzzMCkXxbS3kwixH0bbeKlAz6dGBlgJOW83nuPMpbhAVAq3+vP+9IwXd9PtHKqWOtI7acza8/57aoklflEbPHogNdc16eTGaOJ11poXg5lxyfwjfSp8YxW4MRcYJU=,iv:L4cu4fp13m2Iqc6wwsvDxkoL/8Ro+KvAgf4CDeW39rw=,tag:F+l35027P/fOLqg7O+vqCA==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: namo-shlink-secret
    namespace: namo-apps
type: Opaque
stringData:
    GEOLITE_LICENSE_KEY: ENC[AES256_GCM,data:nQX0O/J/S6swZNxSIXkmAq3IcU14oQ9EeiobO2bTKH8GFFOhr9f6NA==,iv:HPC8qCzT9p1u2xiS5CVP32ztXdmczekpg1htf1+mD0c=,tag:8ka9DcWNqVs8/wFY8lMadw==,type:str]
    INITIAL_API_KEY: ENC[AES256_GCM,data:Kjmrju6CQubIOroI8PrqpDZei2sssfxAOiLRE7iMY24=,iv:FO94L8eGacw3SvIFlXHEdCUuWfD1tbK67Hltq1iTwRI=,tag:onM8oVNOXszaGE3J+tn1Lg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RHArZ1hQaWoyZ0QzRDg4
            RWhTci9paVFTZWJDUWg0aFVPa2o1N1JCVzNRCmVzL01iaUJGRzBHSGVqTzhyL1FW
            MCsvaFpKUXEzRFlGYkF0ZXM1NjVkNW8KLS0tIGo3cHU3ZHB1SkxRcWVJK0RKVjZQ
            aGlLc1NxSmpScDBrZzBlNGpPRlJadWsK4QxTSZhH0dWhJN65kCkGzDdq0+fP/77D
            eIzoKUU8PRzUZtq80q1sn6zTSeVEbWqo10ttnbTvHFkCYzLOIJeUCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T17:00:43Z"
    mac: ENC[AES256_GCM,data:Qox+uSG2a87q/5wdQhPMehlgvmsuhRUb27cHY3Qo4A1/jVCzzMCkXxbS3kwixH0bbeKlAz6dGBlgJOW83nuPMpbhAVAq3+vP+9IwXd9PtHKqWOtI7acza8/57aoklflEbPHogNdc16eTGaOJ11poXg5lxyfwjfSp8YxW4MRcYJU=,iv:L4cu4fp13m2Iqc6wwsvDxkoL/8Ro+KvAgf4CDeW39rw=,tag:F+l35027P/fOLqg7O+vqCA==,type:str]
    version: 3.13.1
