apiVersion: v1
kind: Secret
metadata:
    name: namo-n8n-secret
    namespace: namo-apps
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:VWzvlgQkQbTfIezVVfxEOiJmaKDw01DzbrMLIffYO+OFGyxkrykKCcr3739f2AMD/UR7qt/BGhWsOPCpkvtWmQ==,iv:/d2Zghz9C0SV3seIP/DJcjQkt0F6/gjdAWbk4Bb84r8=,tag:dRIA75skrM0OS9xD6Zq87w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNDg4YktqVVdtcUxSNUln
            YUJhVVdscnc4ZElGVUM2MXRtYjBlVmV0b21ZCmcxVXQyR3JJM3UzTUtRbjRlWERQ
            djdFdExLRnJpT3VqeVZDdUgwbmZKaFkKLS0tIGlNeVBnWXE1M1RXbU1KYnc2S0lk
            TjZmZnVYeUJIMlJmdFVWZ0FCbEp3b1EK/LibMVH+64Id8qiMdIJHINzCn8hsEBju
            5pYEwMGw+Y49z43BJR7oRsacyT5K+7z1iBeG6FktjC5lKQ/IHkwUUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T18:35:06Z"
    mac: ENC[AES256_GCM,data:7oGbQH9CGvJ+amAwusJdjUK6IEytThivXblgGnXnJbCH1V+c+ZZF6mE3IoSnxQqAK6wx1iuHjH5GsyqXXwTeQ0lI1p5631SZ5qxsMtra2EP8rZcOXnq2K8n85Zv4tyFAYyk+qqOWNE7n8f64j7moAuzApT55ICR9onOcjCQ4dN4=,iv:tbV9rUvI4b+cdfYR5AIPIQewnCLtQ9tmgplzo8mrU8s=,tag:EENb3YWFuRympwOg3Tq/2Q==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: namo-shlink-secret
    namespace: namo-apps
type: Opaque
stringData:
    GEOLITE_LICENSE_KEY: ENC[AES256_GCM,data:aSZCFoJ5XWqguG2uftc3CFvqfcLh9mMmfAEHaG3njkjb4BdeV1jRlg==,iv:anj/NHSooLMP/3MzE6HTwW1lhuxDHL8G5RCbksaowp8=,tag:gIgD1G+PSNlGho74R78wfg==,type:str]
    INITIAL_API_KEY: ENC[AES256_GCM,data:il1LFdaXANu4WHZeKA7CtMMFSAz4LPfdh8u6a/23afA=,iv:uxy5D3xHjSvR8voeVcICLGBKbZj7pORHXAb89Uc+pB4=,tag:re/Pzg41nJvzOgfdmBB1Vg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNDg4YktqVVdtcUxSNUln
            YUJhVVdscnc4ZElGVUM2MXRtYjBlVmV0b21ZCmcxVXQyR3JJM3UzTUtRbjRlWERQ
            djdFdExLRnJpT3VqeVZDdUgwbmZKaFkKLS0tIGlNeVBnWXE1M1RXbU1KYnc2S0lk
            TjZmZnVYeUJIMlJmdFVWZ0FCbEp3b1EK/LibMVH+64Id8qiMdIJHINzCn8hsEBju
            5pYEwMGw+Y49z43BJR7oRsacyT5K+7z1iBeG6FktjC5lKQ/IHkwUUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T18:35:06Z"
    mac: ENC[AES256_GCM,data:7oGbQH9CGvJ+amAwusJdjUK6IEytThivXblgGnXnJbCH1V+c+ZZF6mE3IoSnxQqAK6wx1iuHjH5GsyqXXwTeQ0lI1p5631SZ5qxsMtra2EP8rZcOXnq2K8n85Zv4tyFAYyk+qqOWNE7n8f64j7moAuzApT55ICR9onOcjCQ4dN4=,iv:tbV9rUvI4b+cdfYR5AIPIQewnCLtQ9tmgplzo8mrU8s=,tag:EENb3YWFuRympwOg3Tq/2Q==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: warehouse-pg-secret
    namespace: namo-apps
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:0a0kB2R2pMPryB5jMvcX21qdXXC7n5C12FzeUOHkgjDBDOe7tP1/uGMGrzjzs5/w,iv:6kCS1MyiQjYF9eH7230CMgMmyodvbSK0IZMVeM2IaKI=,tag:FhVxSEOhJhp6PpsyPgcK0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNDg4YktqVVdtcUxSNUln
            YUJhVVdscnc4ZElGVUM2MXRtYjBlVmV0b21ZCmcxVXQyR3JJM3UzTUtRbjRlWERQ
            djdFdExLRnJpT3VqeVZDdUgwbmZKaFkKLS0tIGlNeVBnWXE1M1RXbU1KYnc2S0lk
            TjZmZnVYeUJIMlJmdFVWZ0FCbEp3b1EK/LibMVH+64Id8qiMdIJHINzCn8hsEBju
            5pYEwMGw+Y49z43BJR7oRsacyT5K+7z1iBeG6FktjC5lKQ/IHkwUUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T18:35:06Z"
    mac: ENC[AES256_GCM,data:7oGbQH9CGvJ+amAwusJdjUK6IEytThivXblgGnXnJbCH1V+c+ZZF6mE3IoSnxQqAK6wx1iuHjH5GsyqXXwTeQ0lI1p5631SZ5qxsMtra2EP8rZcOXnq2K8n85Zv4tyFAYyk+qqOWNE7n8f64j7moAuzApT55ICR9onOcjCQ4dN4=,iv:tbV9rUvI4b+cdfYR5AIPIQewnCLtQ9tmgplzo8mrU8s=,tag:EENb3YWFuRympwOg3Tq/2Q==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: warehouse-ui-secret
    namespace: namo-apps
type: Opaque
stringData:
    WH_KEY: ENC[AES256_GCM,data:qCs3fAP8B9EI287IiXlJRAg6LAsvXnz8lTI0ELVH1/qxkNWmWElZoAvXZxsEOyNx,iv:ouZGQzlHgW5S6VtGqdTSyeITzuQTiKnvuzjRgMeLA6Q=,tag:80RGywxI8qbOHeOYvQKbyA==,type:str]
    WOO_PATH_SECRET: ENC[AES256_GCM,data:3WUgSC/LCucBx7RKI1p35wQqVoW5WcFG,iv:3Bh/ZJB9mxyqcxMKNtIdAEvFJ2jfw15oa9H35f/+ORU=,tag:qEKXwx+1VMNZqbSmPHoFPw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNDg4YktqVVdtcUxSNUln
            YUJhVVdscnc4ZElGVUM2MXRtYjBlVmV0b21ZCmcxVXQyR3JJM3UzTUtRbjRlWERQ
            djdFdExLRnJpT3VqeVZDdUgwbmZKaFkKLS0tIGlNeVBnWXE1M1RXbU1KYnc2S0lk
            TjZmZnVYeUJIMlJmdFVWZ0FCbEp3b1EK/LibMVH+64Id8qiMdIJHINzCn8hsEBju
            5pYEwMGw+Y49z43BJR7oRsacyT5K+7z1iBeG6FktjC5lKQ/IHkwUUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T18:35:06Z"
    mac: ENC[AES256_GCM,data:7oGbQH9CGvJ+amAwusJdjUK6IEytThivXblgGnXnJbCH1V+c+ZZF6mE3IoSnxQqAK6wx1iuHjH5GsyqXXwTeQ0lI1p5631SZ5qxsMtra2EP8rZcOXnq2K8n85Zv4tyFAYyk+qqOWNE7n8f64j7moAuzApT55ICR9onOcjCQ4dN4=,iv:tbV9rUvI4b+cdfYR5AIPIQewnCLtQ9tmgplzo8mrU8s=,tag:EENb3YWFuRympwOg3Tq/2Q==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: warehouse-ui-basicauth
    namespace: namo-apps
type: Opaque
stringData:
    auth: ENC[AES256_GCM,data:Ibs5xsDgWn0NuaEhZgIQ+LHVGyK2mfocv41Eqwe4fdeNJRf/BOMci9bV1biiUNPJJohseZefGdreZ6a31sBa/gx5vZIn9YSGPbaXgT0HAKNkyS7FKAkU,iv:rH7RlwM4MrOTK9bCbkiqqJU9Idh6iIhGUoBzCsqgwSE=,tag:lQloIhxgP1/acXJ5n2TiUg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNDg4YktqVVdtcUxSNUln
            YUJhVVdscnc4ZElGVUM2MXRtYjBlVmV0b21ZCmcxVXQyR3JJM3UzTUtRbjRlWERQ
            djdFdExLRnJpT3VqeVZDdUgwbmZKaFkKLS0tIGlNeVBnWXE1M1RXbU1KYnc2S0lk
            TjZmZnVYeUJIMlJmdFVWZ0FCbEp3b1EK/LibMVH+64Id8qiMdIJHINzCn8hsEBju
            5pYEwMGw+Y49z43BJR7oRsacyT5K+7z1iBeG6FktjC5lKQ/IHkwUUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T18:35:06Z"
    mac: ENC[AES256_GCM,data:7oGbQH9CGvJ+amAwusJdjUK6IEytThivXblgGnXnJbCH1V+c+ZZF6mE3IoSnxQqAK6wx1iuHjH5GsyqXXwTeQ0lI1p5631SZ5qxsMtra2EP8rZcOXnq2K8n85Zv4tyFAYyk+qqOWNE7n8f64j7moAuzApT55ICR9onOcjCQ4dN4=,iv:tbV9rUvI4b+cdfYR5AIPIQewnCLtQ9tmgplzo8mrU8s=,tag:EENb3YWFuRympwOg3Tq/2Q==,type:str]
    version: 3.13.1
