apiVersion: v1
kind: Secret
metadata:
    name: wallabag-secret
    namespace: wallabag
type: Opaque
stringData:
    APP_SECRET: ENC[AES256_GCM,data:7AzD2nzwTwm6bOC/pEbrUUhZtM/XHHvv0D4E7w==,iv:mxKH6PeAX4QJxSho/XdCOuDfQB42QaWQkxc3ksU5rXg=,tag:RIGX9tYxVgeiurSzIut4XQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMGRKc3I0a3ZYMUNkZStu
            ZndLTXpLU3lYS1JYUnlDVCtKQjFrUGV0K0M0Cm9iWWdnaUIyT1liVlRCa1F4UXZo
            WEp6WVU4NE1Jd1plQkhPTS9oRWNPY1UKLS0tIDJhcGU4Z1JWOU5uTDZQWHFOakR0
            aGIwV1ZPRkhIYmNCaXJkNzNMWGFKS2cKoqbzYX2olNAPOrzb7IGJug39/dU5FhdQ
            t6paiqC/LSpmAxX/uUz+AVPa3xxjFUN6QerlExLId3sijwxgcgX1Yg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T17:20:49Z"
    mac: ENC[AES256_GCM,data:FJd2CDZ0buC0sKpp//9LfkOgwsi7sUtW9xqQn+W8ncH89iCUkRn9FoPq1eKojveXcvHssb0RxcQ/Z/RjcTLAkxx4AaJpFNVBYokaRF+l8as9v3CzPKGRQ64Qav3uPLdGe+pCGLuv961bstqIXVhMil3HLKX6cs85tdIa5eGb2Mo=,iv:YGZBIKzhEvDu0nRY9BH+Or5DNCc02kEL6Z8aa6kS+Oc=,tag:DPiHrLeeFq2+KudLpsIOaA==,type:str]
    version: 3.13.1
