apiVersion: v1
kind: Secret
metadata:
    name: wallabag-secret
    namespace: wallabag
type: Opaque
stringData:
    APP_SECRET: ENC[AES256_GCM,data:7AzD2nzwTwm6bOC/pEbrUUhZtM/XHHvv0D4E7w==,iv:mxKH6PeAX4QJxSho/XdCOuDfQB42QaWQkxc3ksU5rXg=,tag:RIGX9tYxVgeiurSzIut4XQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArOG5oZ1hOU2ZFUDhaVnND
            dVd5YTR3SzJUdWtnZTFrQnp2SHpsNnU4OEVVClNPLzM0YVp6U3dQa2lzTHo0ODdY
            VlhhUlMrMHFLSzlxR2pTOStxSERHOUkKLS0tIGMxb0hMS3B6bEZrOGREWjhpa3Fv
            QStjdjZldmVQOFNWbGlUOTRKL25DK0UKCrbsv4DYOQBoTm7bHq+CND2RyXpSkVJn
            STr/3YaCAjrERI26hgNC8FWxqoeb5w5m3+SWAKQk/Y2r2sjxx9p2mA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhK1ZkZ0JIMStrNk1Tc0pH
            OEhQZG9QbnJxYU9teExuemtLbG9JY3BCaWdZClhpTWc2YmV3RWt1aWJXT20yNUZQ
            d1Q4ZGZyS2c4a1ZyVkdkZUliWUhCUFkKLS0tIEhOYnhuY2xGVk1lVVhieG9wNUZD
            d2x3UXNzaWR5SWkrZmd1NFp0bUFCS2MK/h95NiFNK+9ZOQicFq8VhMC25jw+YeBZ
            vx+itsO4kyBCya2eM0ZTbNHSGp6R5RCkAfW5SYeG3UA5j8YC+pHkyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPM1hTQlg4dUJyaVlZd0Jo
            cXlINGtwWGh0SnNTSnAxYjR2T2NiemNWdlFFCnJqaG9uMVFTR3BzdXZ2eWpUQXFy
            czIrR00rWDVMc09ZVE4xR0JxVW5LSEUKLS0tIEdNUTZYNFR4cC81Z0k1b0RuaHVY
            V25FVmJ0SnhKRVdzWE4xU1FON3cxRjQK2cQxohetz3SHlUUhQGXjUGsph/xoioCg
            Ay2jFO+J0/7Pc9hkIypynuxmgA8PgdK0q8MYnZRvX5ciPr1QZd4qdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T17:20:49Z"
    mac: ENC[AES256_GCM,data:FJd2CDZ0buC0sKpp//9LfkOgwsi7sUtW9xqQn+W8ncH89iCUkRn9FoPq1eKojveXcvHssb0RxcQ/Z/RjcTLAkxx4AaJpFNVBYokaRF+l8as9v3CzPKGRQ64Qav3uPLdGe+pCGLuv961bstqIXVhMil3HLKX6cs85tdIa5eGb2Mo=,iv:YGZBIKzhEvDu0nRY9BH+Or5DNCc02kEL6Z8aa6kS+Oc=,tag:DPiHrLeeFq2+KudLpsIOaA==,type:str]
    version: 3.13.1
