apiVersion: v1
kind: Secret
metadata:
    name: linkding-secret
    namespace: linkding
type: Opaque
stringData:
    SUPERUSER_PASSWORD: ENC[AES256_GCM,data:9OFMBLo0dqDoJaEIurCWZZpi,iv:m4mq8l7u84IyuW7ygmnILwaXM2SvA6okxO1T7++wKcs=,tag:yOIlJRab6uVKTEGc355AKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubDBwT0Rsak1IcDF2UVFF
            ODh0Q01rRWZGVVJodThCQS9LcytSbWVSZUJNClJWWmNMTWJvNVg0Ni84clJMNnZm
            S0VBZG1xR0JZUHlaNk5NVUhEeDRGd0EKLS0tIDc1anJUcVZlbXVtSThFTjJxUmVE
            ZXBBeEltdStxUVJGQlNod3hrcUh5Z3MKOvos6+CT2b9cVCxXRVr4LEtAn2F8ptk9
            6I0Kl1189pmKXTWmQZDTqJPMGdj90K3YL6A0V7hyipzCIN8zyJHFhw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T17:11:32Z"
    mac: ENC[AES256_GCM,data:HXtt3zUfopiq8IsQMR75vhyFYFoXsUnlvgltXxIHenWS/hnjB2sBZdCgmazAx1J4X34RV4Ysm6GutbGagm1uWD2X6YZApjSYkmMbIjjzKaODyK0Nyv37mh0q29inHyR8StzCf5ZnSPW+unuqAttgVIFPVQ2pbK8ARoI8bIV7zZ0=,iv:7SpYg0D0UnKdxddG/ZECC6Bkt7uZD5ICE2BRHaPyNwE=,tag:XOu5/aCM+7W7z7xLLopzPA==,type:str]
    version: 3.13.1
