apiVersion: v1
kind: Secret
metadata:
    name: linkding-secret
    namespace: linkding
type: Opaque
stringData:
    SUPERUSER_PASSWORD: ENC[AES256_GCM,data:9OFMBLo0dqDoJaEIurCWZZpi,iv:m4mq8l7u84IyuW7ygmnILwaXM2SvA6okxO1T7++wKcs=,tag:yOIlJRab6uVKTEGc355AKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UHhUZ3lIektiMkNJcTNn
            RTN6ZVYydlB6THhHWTRlV3FyUzFydVJHLzJFCktOYmcxWDhYaWVrckF0QlVJeGN4
            d2lpQnBFS1dlelhTOHhoVjFEZW9QZUEKLS0tIGo1YngySFlkWW1uU1BTTklxcEhq
            M2ovMm1BY1d1RjJkQlBlS3l3ek41ZjQK6AAO++tcrJdFE928iXtngZYfBb3g4jpq
            dJVzVwrws2Lool91GSKq/ZYWH/dyNwezE33A/vrvKClZd/99WqznOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOS2o1ZDhocDQ4MHlZU2tR
            b1hIa09STTlEdG9MYnF2QzhvTXNyNVRrS2dJCjJyV2E5Yk93dXJ0L2JHMk1IQ04w
            ejN3TzIrdnpEUG5rc05zRlpFUUVPTTgKLS0tIFZyMTFKcVQ2dEZ0OUxTTThQV1Rl
            Qm16Nzl5OHpIUWo5OENlTXphUnkvUmMKQbSZxHiJfgbKffLGueb8XNkewLRloys4
            cLK6VE+c4zdRzHgHm8DE7qSc2Lc9l/qc+qmsk12894KFPALxJ8GAKA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNkFLS2dXcFd2c0xxdTAy
            TlhieXAvbHRvclltT0h2aEFuN1hsb0dGZG5VCmxqckZ6YnhYeE0yV2NWZU4zWlhM
            dnk5TTlwZlJKZDlaQ2tHOHZnZW1ld1UKLS0tIGh3VCtaTlh5RW1mV3c3a0dPalJU
            MVhRQmwwOVdvSXRyQjV2dzBoMkN2WEEKueMYcTUFUmAhaN5s9lqY3E7wyNDqLO1y
            UCrPGEuQJQjCIWxomME3/bIzFVveOF9xCAyTui0z5PH7kjjSPTkbmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T17:11:32Z"
    mac: ENC[AES256_GCM,data:HXtt3zUfopiq8IsQMR75vhyFYFoXsUnlvgltXxIHenWS/hnjB2sBZdCgmazAx1J4X34RV4Ysm6GutbGagm1uWD2X6YZApjSYkmMbIjjzKaODyK0Nyv37mh0q29inHyR8StzCf5ZnSPW+unuqAttgVIFPVQ2pbK8ARoI8bIV7zZ0=,iv:7SpYg0D0UnKdxddG/ZECC6Bkt7uZD5ICE2BRHaPyNwE=,tag:XOu5/aCM+7W7z7xLLopzPA==,type:str]
    version: 3.13.1
