apiVersion: v1
kind: Secret
metadata:
    name: backup-s3-secret
    namespace: gompha
type: Opaque
stringData:
    AWS_ENDPOINTS: ENC[AES256_GCM,data:iPM/B7Ov2qga1Lciwzrk8gEymU+53t/32A==,iv:cjoaBf8SlvwA8mbr4yWSuG9Z4pDijQuxLFpfjrM4fhQ=,tag:u2OJYIFouCONTJGlv9Qvnw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/pkAkTLp1hMgRiQ7Jg==,iv:MhxUfjEZMrBt+C95OCdJ/mFBT6RKG0LF1QOhCWLZCI8=,tag:w5vBLuXdsiS9ORcVCREJDw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:fl7RtZkLy2nRgCIw2ZNkOZuwa8kvJ2KKXDhgVxXkf588NZrbUaGQ9w==,iv:f4ANFehOuVIpRfelDNo7I8z/+pjcTzuBSE1h8yOhOuM=,tag:r/ROYl43m6cUvf/Q7cQsPA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWnpCWmhWbEF0d3ZMbDBB
            aW0xRHpseVc3RnQwbXZIRUd3RUxuUkZmaUM4CmRhQ2pyMUFmZTBHTnBRalhDWlRh
            LzlSMXBhNEVIV3FTZnJxcGFvaFQ1R2cKLS0tIFE1cFZsa0dmZjUwYUNFQ29pS2Vv
            eHZPaURra1M4aW9hclFzNlhiN0tZdnMKn2dNWZ3/77NlUyPxIOH/vmr2LqJzv6m3
            OAzIwM+jv4mtP3C3Doryut5MQcI8bKNFLAMLHkkRifmMRFhOxT4Xzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T21:29:40Z"
    mac: ENC[AES256_GCM,data:GJL3NoRYKclrmDatmabym1mLGsH95YQma8j669/EOd1MesECoGb0nbfXGfq4ehoWfNrSCE1omUU549KBYsBuBYKpcOJNwAVhMrJLE7mZTsriK9mXCmQFSlv2gEjuAgR5l2Nmw5xm59aQxWsqkXHJl5BV4tVvmePITMS1zeHytcU=,iv:Oa031/Z5Vqpmx4uzpIIZ9XeCtx8oZPnVYR6gZ9otBIQ=,tag:bt3eroPBlL/vfjNQKFLs3A==,type:str]
    version: 3.13.1
