apiVersion: v1
kind: Secret
metadata:
    name: backup-s3-secret
    namespace: gompha
type: Opaque
stringData:
    AWS_ENDPOINTS: ENC[AES256_GCM,data:iPM/B7Ov2qga1Lciwzrk8gEymU+53t/32A==,iv:cjoaBf8SlvwA8mbr4yWSuG9Z4pDijQuxLFpfjrM4fhQ=,tag:u2OJYIFouCONTJGlv9Qvnw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/pkAkTLp1hMgRiQ7Jg==,iv:MhxUfjEZMrBt+C95OCdJ/mFBT6RKG0LF1QOhCWLZCI8=,tag:w5vBLuXdsiS9ORcVCREJDw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:fl7RtZkLy2nRgCIw2ZNkOZuwa8kvJ2KKXDhgVxXkf588NZrbUaGQ9w==,iv:f4ANFehOuVIpRfelDNo7I8z/+pjcTzuBSE1h8yOhOuM=,tag:r/ROYl43m6cUvf/Q7cQsPA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWkFMenRFanlLczFxZkQ1
            dWhyRzFURklCcldEdDdyMStsbmJxbldpeEF3CmMra21Veno5b2dHNEE3YStVOTE5
            aWROTUJKMFl0aFA1SStubzBJVXVOOWcKLS0tIGZIcUU1czc5ZGFaTmVnUzZGQkt3
            ay9IMis3T3B3NG81TFJ3aUJXK3hOdEUKRvzAaMc1ndeY9uYLC7843Rw8vwMZ5jqU
            87zH/uzus5iAePX6qA1Cwj41347PIGHRoltz5qQ8+5qRqdwm0n/mlQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpazBYMUpyMUtUNHN4VTQ3
            c1ArUkh0NithQ3lVaHE3cS9SUTVhS3U0SnlBCm9MSjJUWkNMRGVJMERRMURrTWdx
            dlpDa3ZHOTQ0M0dsekJlQzlpbTRRTm8KLS0tIHQrcGIyOEpZL1E0bEM4SkRjRmtl
            SnNUUWdueTFGNWwvcFBOS1M2ZUhSOEkKSowhv5wELyUpuQQcVG35xZ0c6+iSr02O
            FDrGMihEdjWG7fcJ03/4FqsI39glCFfrq1hcB/7EMLhWOVuZHgT3Gg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxK3JxRVlhc053MXpUZlp4
            NkpMcXlxNldxMU9MaXZYdE4rQ3RWK0Fpd1c4CkJtWEZWay94YTJ3WElkeUlTSnFP
            L0lmdzN6dUs0RG9rZlNEZlJxeEhFcFUKLS0tIFVueUFIeUlSTTNXY042MUo4STFD
            VUJCZmtyRnNjcUlta3dIbmJHZzNCancKrPO+m8rS/EMxJ8GAXldGqZvi+M/I0b6H
            Jxr7ZHO6erFz5Rh5aGB0C6VYqCxg5ZfhVFK6SstcYbuPdXmvqkrKZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T21:29:40Z"
    mac: ENC[AES256_GCM,data:GJL3NoRYKclrmDatmabym1mLGsH95YQma8j669/EOd1MesECoGb0nbfXGfq4ehoWfNrSCE1omUU549KBYsBuBYKpcOJNwAVhMrJLE7mZTsriK9mXCmQFSlv2gEjuAgR5l2Nmw5xm59aQxWsqkXHJl5BV4tVvmePITMS1zeHytcU=,iv:Oa031/Z5Vqpmx4uzpIIZ9XeCtx8oZPnVYR6gZ9otBIQ=,tag:bt3eroPBlL/vfjNQKFLs3A==,type:str]
    version: 3.13.1
