apiVersion: v1
kind: Secret
metadata:
    name: n8n-basicauth
    namespace: gompha
type: Opaque
stringData:
    auth: ENC[AES256_GCM,data:jphY5OnhkQIdD3nqYb/RoGXjwmoWMX5JnjfjXUDSWbeLWNPg6q1AU5x+o6cS,iv:RAq+eEiN5TsIrtCWQShJGd1QX59CuWfx057i2XHJDQ0=,tag:dSKDqe0J26Mt1wADxcD4AQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUS9Ub1J4L0x4MThsbkQy
            ZFNoVW01Ukk3U3IwN2NjTXNhRG9JUVlIcG5NCi9rNEM4Smh0eFFmdUdGMjlKVFFp
            Y2hIQzdGbUxRNUJpUmJuekluZDJpZ0kKLS0tIFc4UURyb3FLOVRoV05nb0N2QUxn
            MSt6M2lwMW94d1RUSGIrQ2RmVEdTeVUKi1qSLH+xz+QefHjbemb2lq1sAPWFh3kK
            7Olsq+KG9JvwIGv6oxyJw4tMkwE/5vNuKJOpmKimd+fxh+kRjAQ14A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHeWlaTWpvRWtTOXZRbDFw
            MlVuRDNCQXJPS1piS2s3elU0MWNvS29XMnpzCjlsVU5mM2IxRXgrSlFOVjIrSGlP
            Q1JtQmI1cXZicm9QaG9WZStiUTNqT3MKLS0tIDlrWmdKU3FuZGZQOG9PT1VBV3N0
            OHRrMXhjanRlaTlUSENJcmg3OTZHRVUKzi2Edv4AL342Z/zZ8p6LEVmz/2Ze+mgL
            JCLo1cIfmLOg1CqGENsYemL553VNygQXYc+I24VsyvasZBAQ1+EszA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQ0wrT3I0QmE5YUYycWND
            bkZkUTBsQTU3bC9qVGwvUS93UkRDb2xLUkE0ClZaUlQrSElBOWVCSmVxREg2OHB1
            ai9QR0xLaytKaXJtUlA2S092aXlyS2sKLS0tIC9YQisxaVJDYnRCUTd4dWZTcTdI
            dWdKQzRxM1VMQlFXVzBEaFkxMkdVZWsKLcue6yaRqWLohrUG4M6mDBZZYxrWMqq6
            jxhmxwGPl8a8PkZZHvCie7voptcs6XIA66bzFBYFxrddbsoR5AzMLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T07:32:25Z"
    mac: ENC[AES256_GCM,data:TAZxTk6/YUj6x/EEiPOdMFtKb4sy7Hdy4rXdCb1kK9Z2vbayJM4iujSWXTYEeXQe4orLKtjSh5J6xJuyAec2As6IRTqeSDI1hJd8FSJYoR3A7qQ9Txvv0Yt3PWIh3ws8DaaoiNoBmHeVfqxEJi/8+lH1kZ1wg9qo1If+lsbtCLQ=,iv:XZlP/6JLxxwHZcOfxVpjYEfzh029WkYyjr9zYPmM9Ss=,tag:Vw8TIfL1YqnVnZIMdaaByw==,type:str]
    version: 3.13.1
