apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
    namespace: gompha
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:y/8st2Y+WMLSgnAfLdiH5rNhHHu8+hQN5yebn4AKFco=,iv:PKS7AuJPGNa4Vt+7TYWzRSFBsSARnoKCnbQ6IICpZmY=,tag:ZKhATfT+WGlfnVe4THxBVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YjhRVTNXSzJkbWdhOUt0
            Q3hmelFNaXBiYUVmM3RYTEhGbzJ5TTY1b0NBCjFtTmpUS1UxSGliZlFLekp3UWFm
            aHlCdkZjdWJYMDkycWk2cFpQYU1MTTAKLS0tIFJnY2E3c1FMWG13RUo5aUZqMUs4
            ZVpuUFlOTERWTjhQL203RUp1bURmZlUKifUBbco/j88PfDjCMevEPEqcpcWJvDXY
            gle8r0xnpIvmKTxKh6TiMrLcZw+jWHl8CP+FmkaH/LhYH4+HQoIiUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T10:54:22Z"
    mac: ENC[AES256_GCM,data:VFB+zeKz95ZBrI1W3ZeDCy1JiFatYNxmRQMH6rMn4UHyBnHUOSrmeWFHHyBhoBJiE5wE3apKp2BroCvbpllW3/gKOIcGaA8pFrPu5Djuau3d90RQjmzK6LttIgk5wYtToy99t/L1gFJxJf4wCBQMaxsuPX1aCakGVqdhvY02fKY=,iv:I4Z6TaEq3i0Sf9CIBZ8gBTLnXcatjzClLn8Kz7BWkio=,tag:PuSpkgAEtk8TaRro+wl/aw==,type:str]
    version: 3.13.1
