apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
    namespace: gompha
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:y/8st2Y+WMLSgnAfLdiH5rNhHHu8+hQN5yebn4AKFco=,iv:PKS7AuJPGNa4Vt+7TYWzRSFBsSARnoKCnbQ6IICpZmY=,tag:ZKhATfT+WGlfnVe4THxBVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByckh1bzVwMlVEV2NJejA0
            a2tTQVN2VXQwdnhpTVZPZE5aVXZnMERaKzFVCjJBNmpxeDZsMGJPYUpwTjdURTdw
            VUkrcldVYjNtZVRrMTM2bmFmSGxENncKLS0tIE1lZlVsUkRsQXhXS1lLOEtQWUhi
            WnozNFVBUkk1am52NjBOZ2RRL0U2WlUK71VrD89iSzXIgo4OGOE8INlERtl8z8NU
            14mfJcJbewaM6my4nmLIJ+zbl99h5ivXmk7trPtWd6GwUx1mxhc8ow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyd0MycmVqaXJvUHBEUjIr
            d1g4NEd5V3BaTklScEpXUm5HYzhnMGVHNGpJCnhFQUU5RTN3VXNyaVpCYmo2ejli
            WlNjYktQRm51VHhJQllmM3oyTUI2b1kKLS0tIGViYS9QZE1VSWdDcmcvKy92cGtH
            UlBLREtkTlNENGVWUXJHZGRrY3IxVXcK70pCqFUO2G+SpajsVwbxi2+OoGOk3A09
            M1ME9hH4srkz92K0SFwmOR9dk35/kk30Y8nvf9Lc/Cx1W3NqlT4ONA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOK1lxNkE5aDRuQUZyenY1
            V0ovTWVicFNNcVhuWHhXU1RWZU0vVGdKdDIwCkFEaXVLTXpCam5SRmRhV2hETGZz
            Y013V0ZQRkJMV0FzMmZMQ2Z6alJ2MmsKLS0tIGVvY01nY0ovMk9XeDdVSS9WVGV6
            YU1PQ0tRSGZFQnVYRjhOMVBjZi8yMWcKunAhH1rAhXoBxm231VUKo2+6cbzEUeww
            LvPc63Au3IJmDxyZUWGVKscmpvRIk48ernEqaNGE7SDcV3n0VWoqRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T10:54:22Z"
    mac: ENC[AES256_GCM,data:VFB+zeKz95ZBrI1W3ZeDCy1JiFatYNxmRQMH6rMn4UHyBnHUOSrmeWFHHyBhoBJiE5wE3apKp2BroCvbpllW3/gKOIcGaA8pFrPu5Djuau3d90RQjmzK6LttIgk5wYtToy99t/L1gFJxJf4wCBQMaxsuPX1aCakGVqdhvY02fKY=,iv:I4Z6TaEq3i0Sf9CIBZ8gBTLnXcatjzClLn8Kz7BWkio=,tag:PuSpkgAEtk8TaRro+wl/aw==,type:str]
    version: 3.13.1
