apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: backup-s3-secret
    namespace: bjj
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Vl9RuTc50aVaNOnztFq99lhZsSop07NC9+Limg==,iv:DWgy5kABRutFfANgncxn9jlFguA/2VdxPzE4AOtWO+s=,tag:Bvhj0/lQbUTAhBLvVM6aGQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:lpbTINTrjIHQRREpnyztXTYZVvdz2fgqp1g5aiyAP9W47VL2wy5CatufmLMkMfd+/DvFCKUREG0=,iv:xD5/ajGgDn57V1yxwdKfuU1WCVNzR7R2MIy0gnGbR3U=,tag:lMcbk1xOqwmkqQ0AxAn3GQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:6p48OC/EIZM01HI2x5AKRMrG9eaMCoXVU1LIE2YBwyxg7Hn9,iv:VkC+bEPjzK3EuO5vTRjQTO2enXYZH5WZlUw0dGqS6YI=,tag:A+SKbsW0Fpv0Y0VTLBBHCg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTUVkVDhuVDcrSzJrbnl0
            TGk2cS94UEZsakc2ejRFMXA5K3lOSG1KT0hNCkFlS2pQWCtWU0ZHR0VhMHRZOExk
            RUNLS2pUYTlYRS9KNGFBV3U4eWNsY00KLS0tIGNHQ1M3dGhzUTVaTEJLemVNb2hM
            NE9XNjQ4UVcvTlQyN2VkMkhWcXQ3RFkKd/hdhgg6MlT7BWu37vWEeAPMgvyFdB2e
            B421iIy1o0NAs7GCk/kbSnTiJOkpp8JUxf1Sl4Iwn8lFHvoiYew76Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T00:22:08Z"
    mac: ENC[AES256_GCM,data:gYEeWlM377oA5QAdrsoty/nwL0X30if6axADXG3I6sYLAat9IygJ3XJ4L1VBzQ/a0VJ0Tgl8MaRlx0rMmWWgOmkYEvQzhyseN4HYeSJBsrl52ANdnlC9jzSs7OXhmGtflBLrPdfxlXJ62Xn7UwCdHr2MCQ+d1NP2NcloPWc3rLk=,iv:gUjm/2zxPn9YIb/qTMm0Ob9z3MfsQ2DqA1wEelCHKvk=,tag:OGcunrwWt8hs1BidD+H5Og==,type:str]
    version: 3.13.1
