apiVersion: v1
kind: Secret
metadata:
    name: backup-s3-secret
    namespace: bjj
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:6xvPTNAf9qyJZXd+niXCDL9MjiE=,iv:+RPatS2VrttYAmH6HhtFHiIpfku1uWxYv7VmqHpFOEs=,tag:P4JgVSO4FHyL93E/YrF/2Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:dCx4cyL6EQOczkoILio5Fh+AUoIJ3Ft+KIMFxLHX2pkO4Q4CEgqZcQ==,iv:tHwD59yNTzTO9/1GfvWdExPzJifKS87jOvgAzMWizgY=,tag:B1osQdRlcn7BAv9Rx4g0fg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:7SWJm4dKuA2/Frgv1egApza4RXtJi+KiZw==,iv:im78cN6UtsCE+svVGDGixc+ai1+Xa3LquI4c1vtst5U=,tag:coFewKxDrYHLEvThvGBkPA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIN0tLVytDejFMTCtTYkhW
            QVIyQWN2SFRIWXFlRkdjTWcvdVRENVdTbUI0Cnd6SjYzOTFXa2tWZGtVeG9TK1Vy
            dGMwOS9zeFlkQlpzSXRYdkxMdzdJNXMKLS0tIFFXMzZGRGJuNkdoQmVNeVUxblkx
            TjVwRWhNMXZyZHA3NVZucE5iUGxtYVkKzo/MOaY9LtnteXth5O8e+rfHGkT6+Rxm
            AX8gFpnkyCFMTFlnQ4RaoltmASSV6ukhLWRd3uiguoPw+NCPLEw7Kg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T23:16:13Z"
    mac: ENC[AES256_GCM,data:8/t4Ak5ozwjtMkfRVZbu55iBgIlherRwu4LQwdTsngefcyjTZbFU9Ep1mGkwFKKmRUscv7hz5yN/MH8DXY7qJ2iLxHFNmDYn0WkhYdH4K9zdDBYaj8pv90JuVaoX0ti1T2rRVC5+zJ/aGe0xOnnD18V+/g415RTZja/ScVGo958=,iv:Wr4ECAbRg6MB44ZuZJ0ncwH/I4yoEhVIldElZ36eVjU=,tag:zF4hw7a5eRj/G9sncTXDcg==,type:str]
    version: 3.13.1
