apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: backup-s3-secret
    namespace: bjj
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Vl9RuTc50aVaNOnztFq99lhZsSop07NC9+Limg==,iv:DWgy5kABRutFfANgncxn9jlFguA/2VdxPzE4AOtWO+s=,tag:Bvhj0/lQbUTAhBLvVM6aGQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:lpbTINTrjIHQRREpnyztXTYZVvdz2fgqp1g5aiyAP9W47VL2wy5CatufmLMkMfd+/DvFCKUREG0=,iv:xD5/ajGgDn57V1yxwdKfuU1WCVNzR7R2MIy0gnGbR3U=,tag:lMcbk1xOqwmkqQ0AxAn3GQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:6p48OC/EIZM01HI2x5AKRMrG9eaMCoXVU1LIE2YBwyxg7Hn9,iv:VkC+bEPjzK3EuO5vTRjQTO2enXYZH5WZlUw0dGqS6YI=,tag:A+SKbsW0Fpv0Y0VTLBBHCg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcFlUVlFaR09QMXhEY1F5
            NWJFbkR6cVpsZTZpZGhZZUY4RVh4ZGFSTVFVClU0Z2xCaEtyMmtZWlVidWVLdTZR
            QW43QlYvOUU5OHpKT3dQM1dXOWdWaGsKLS0tIERzUllJY1BtQ2wzQjdndXM1Z3B5
            d2NJOFhlNDJsTFB6QmYvMlY1SjdIS1EKSbdP39siptQMKgscSm6CB6T2ThdTwKQU
            L4rDYHFuUxm8KjrtRYAjwvR+Luy7wX9nrY9x394dbpzaFqSeDSex7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQjh1MUp2c0lJWWVzRzN4
            U3ByYzVlT29KTXFqT3lTdlE1VUQzcWNZQ1JvCkY0LzZWc3hQMUVDSVltU05TZUJJ
            cWEyelV2djJFendxZGI5eXNWRjVtWncKLS0tIHU4aGRZREdGK2ZvTEkrN0x0OThL
            ckxvYUg1VHVzaW9saVlUYnNSUFhtM3cKwH8HKym3w1uCeqRvVuCnpQvmqSQk65hz
            HHVyq9NKKtrAkwAets6hyUW4wDJpkuEDBslD36fX3SpLFfHFPTX3VQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WUcrSmIxdVc5WkhYSmNj
            RzB4cDQwS3YwUFRXMXB4alo0UFloS2JmU2lFCkhOT2h5VkhidE1jVUVheDc4dkVO
            R3pXNVc1Ty9acTlKRnBMUmY1Z0R0ZUkKLS0tIHVSblFJdTJKRURKTVQxMkF1SWdw
            dVhOVmFDSTl6RkdkWWhjZnhHbVd2UVkKR70U0VRMfEWQk1BDpswII2BSYYcGaLJn
            LPY5a/mrDHLW+y947NOvMHHY/kH5lAcX5zbp1HFPDGCJn0enqPwV6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T00:22:08Z"
    mac: ENC[AES256_GCM,data:gYEeWlM377oA5QAdrsoty/nwL0X30if6axADXG3I6sYLAat9IygJ3XJ4L1VBzQ/a0VJ0Tgl8MaRlx0rMmWWgOmkYEvQzhyseN4HYeSJBsrl52ANdnlC9jzSs7OXhmGtflBLrPdfxlXJ62Xn7UwCdHr2MCQ+d1NP2NcloPWc3rLk=,iv:gUjm/2zxPn9YIb/qTMm0Ob9z3MfsQ2DqA1wEelCHKvk=,tag:OGcunrwWt8hs1BidD+H5Og==,type:str]
    version: 3.13.1
