apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: bjj
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:rxwi,iv:3YT/yN/xsV8YLDRSYPyXZPiUhlcddNKvh8do2mYSPPg=,tag:TFjrnkKOUPzlsAUJHUWauQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:uGmi,iv:NqwvzqUZiKbDba3thFqgaaswC7HRYThYyl4lBCNydsM=,tag:c+HZBKcjsIgXAgUxsPIUNw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:5GRn8DM4ZsC4aqvb8i2gl8ygQJgWS6fDmmt7jb41HQ==,iv:JzWY7pz/BTZWv8fbp0EYZ54bJjIclsCMZP1DAF1ZjCc=,tag:B2DxxrhtPyMW5NlimYXOKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWWtYOVF3eFNhZy9nQi9z
            M3IzUXpZQzlPNGlPV2o1cWJHYitVa202YUhrCkVIVFZ1UWZHaHhRWURrT3dJL3lE
            S1plNkNmVjhBcHdkRVczMmRIb0ZUUzgKLS0tIEtYa1RPU21kK2pyVGdYeUJpOUIy
            VHMxVkhaODIwMFA3QlFpT0JPUWtHOU0Krofys/9B4zBIgWh+19LosCtqXluxqEVp
            x/P1AMSiFgY1xIjc37cThEiNbrkarzPs/LsA/YQ2xRAbTZ0nFHVtXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aTJWc0ZHaVlhOUpzTHds
            aXhXYUVOYXhRdDkzVTlSa2RSZktlcGpTWFdzCmxzZ1ZNUCtES3Z1blg5dXJNa2Yv
            bEQxb253VkJkV3NWd1FwMVIrYlBTYlEKLS0tIEpFVDV2Yk56bklQUDZDcWppS3M1
            bDVUOVd1ajlZTlk5dnJnVkhTU0tVWDgKajGFHnrGLYmVtlO+qZY8jG5XptQz3GaY
            pBmpbFHxPNy7SjfyzUrM8gKYOiKcr3dWh9sESDbvTjdcmTLs0ucS6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RWx6a0VlbG9TVGJTbGNt
            MG5EZG1nbjBpTjZPRFBpVkp4Mml5NHhaZVZNCnp3UFgxZ2YyT3ppYURmeXRsUzVn
            QkR5K0R4K1BIRGtrdTJxY2dxVU1YazgKLS0tIEszUnlPWDY1bkxjbUZMYXlXb3Ny
            aCtGQlNaQkZSQkJobE9jTytKWmxnZUUKX+do1hXxTkXNJAv1ewK22XbafvpHsWON
            cmv9DilodzenQ489DGsXplTVqNe/SWH/fvJt1x3MinoDm8m0cGJzhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T14:00:34Z"
    mac: ENC[AES256_GCM,data:Gazk2UhW7w3oB2tkKKxrUgU1nLwfkuZwgHjOAOtwupEAEPdbbPnxiZzKc4+KDs1PVFe06EqpLpafF3+hSgs2tXivvdJNGGc62j2SjlQhlwTdgMfM2mJhgJpkSbkXnzk69yXL1gtUQL1TS24wwUSVYYqYsJT9MPoNsuz3a4kOm78=,iv:WlA2v7NaKPNOOBDm8+iBcEs7WqTDyYZ7rsAPMIhemt8=,tag:VQDNix06RFLs98hCgwJnhg==,type:str]
    version: 3.13.1
