apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: bjj
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:rxwi,iv:3YT/yN/xsV8YLDRSYPyXZPiUhlcddNKvh8do2mYSPPg=,tag:TFjrnkKOUPzlsAUJHUWauQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:uGmi,iv:NqwvzqUZiKbDba3thFqgaaswC7HRYThYyl4lBCNydsM=,tag:c+HZBKcjsIgXAgUxsPIUNw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:5GRn8DM4ZsC4aqvb8i2gl8ygQJgWS6fDmmt7jb41HQ==,iv:JzWY7pz/BTZWv8fbp0EYZ54bJjIclsCMZP1DAF1ZjCc=,tag:B2DxxrhtPyMW5NlimYXOKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbEVuVlU4MTVDNTRBTzBw
            UHNmVnk5VUJZMURmSUF5dHZObTRZbGpzSFFjCldTaFNqMGFPRzVpVDRObHVSMlk2
            T0I2S01YTVhLU2IvT3BYM0h0L3pjMjQKLS0tIHV0ckIxbDcwT0dLU1ZWRmVzdE14
            RVVrMTRweEhwMVVnVkpJRDc4Ym03NmMKUBKtzKZJnH4WY9vRIKUbnMcree07sLs4
            UddGDwpC8bcBgY2xLzSB9QZpDloCYbu8LJjfxavfRKW9/peMupyi0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T14:00:34Z"
    mac: ENC[AES256_GCM,data:Gazk2UhW7w3oB2tkKKxrUgU1nLwfkuZwgHjOAOtwupEAEPdbbPnxiZzKc4+KDs1PVFe06EqpLpafF3+hSgs2tXivvdJNGGc62j2SjlQhlwTdgMfM2mJhgJpkSbkXnzk69yXL1gtUQL1TS24wwUSVYYqYsJT9MPoNsuz3a4kOm78=,iv:WlA2v7NaKPNOOBDm8+iBcEs7WqTDyYZ7rsAPMIhemt8=,tag:VQDNix06RFLs98hCgwJnhg==,type:str]
    version: 3.13.1
