apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: bjj
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
