apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bjj-app
  namespace: bjj
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.teamelwany.com
      secretName: app-teamelwany-com-tls
  rules:
    - host: app.teamelwany.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bjj-app
                port:
                  number: 80
