apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
    namespace: saas-gompha-licensing-staging
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:gnb2dWVx/ToFnZNHS5N9El5XrQpvYB8ToMQrt3E6xCHUnJFv2U7CkokPLdwp/TFx+mH7yWavh3JZsyr/Z9wkxrCTFLTyc/jfysi76a1Hs5LD6R8exUYn54UmNtBzfIuuToOW8ORmp3ovAcV72l5x9kIVeT1ONSs6smHR8Z6RO6u8X2mhB/R1nOyov/grcFz5i1/cXLeDKnMTOS/Xv35gu5S4IDfFhQO49IC8YLGH0nCrbGQmkmFHNvy3hu0awoMocB75fedhOuyGfdoy19PJnN6y+2prfkij3HVq7OwApmv6SuVHI85mhytpVGIWqkAg,iv:F1VmKe2Th13n+N48yS1LDcWjT9TUF574KiDPVvNlWh4=,tag:pNtwyoklq99RI9EMJv7UVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWaWg5TE8xV3E1ZGdqKzdq
            WGtsNWVXOFlXZnJQMmpmc3FzN0t5SE5SNld3CmZKdTFvVTlucjhyQXF2ZGxyTG14
            YVZwZjd1ZU9VaExqeU5zb2pZQXpSa0UKLS0tIFhMN0w1M2JnQ3I2bEZaLzBxdzJX
            cGNzMDV6dXRJL1gwOHZwSXFGQkF5Z1EKK9tT9JQmSBOJAFjZLBm4DNWLMQk/UIzO
            sfIgpTKyT1a2vIeVHxkVpIlafPlLqL6hT2Bx6ouAFPwD9ghm2em4hw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYTg4QUJHTkNIbE1aWkZM
            dnBZU3Q1T0FsWFo5dkpUbjlxY2wvdUhKcVNBCnYzdFBjVURDL25HemlpRkhUT1ds
            RjUxUzFDUG5hUVR6YUh0QzY4NVFsbWMKLS0tIERCa0Vib0dzNUFtVVBmcmFuMTZq
            ai9FYjBqdWRKV2JwQUtFNUJwdW9tWXMKLq+PSqA6VJ+68I7cu8XJpXKBpnysqpr4
            /bqqwTzV9hKbJGYfqWNlSq8ZQrMxJOMbjezAb2qp4c7tg0BTFyenpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocEczL3BjT1hvR2owUWRp
            ZUtPL3JheXdjYjhCWmpEcHFkd1FockhIc0RjCnlGWGVibEQyKzdFVVB1UEt0cFNw
            NjA2V1BmNUtQaitIV2NmczdLa0oyd2sKLS0tIEh5NlljSVh6ZnpzUlQrZkRuVTV0
            akNFd3JSWERhVU9kWGd6OFl1WmwrMWcKylNYBUKN5H7yHCECJ+mgBZiCpHzq38pI
            qGuZK+dx7YKqTm22mf3wuWJsqlQ7NjhUs9ki+XJRLdRpTxxlP1EXVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T21:06:12Z"
    mac: ENC[AES256_GCM,data:g7CGWQ/iDsGSL8VHMMulYBbzrEjNFMvt29sNx9vhs4TYPDQxjoCoFmmNqz3MGxzXsxzlQiHDI7cKKzO1p8T+/8XJ7s9+/sERMW7+0k7F6tp2dS6XXPWx269IZtAg95zsSvCYgTStelOiZhsyXcxtJicezMaU++UjyCbX0ba43yM=,iv:KRzSpyKjQyL4Q4hPgxUalBRjEQeEAuB/cWPAkk0OWzQ=,tag:UIYFWZ4sYuB/QtNsie70Pg==,type:str]
    version: 3.13.1
