# Sealed 2026-09-17. Credential scoped to clinic-backups/gompha-licensing-postgres/* only.
# ArgoCD excludes *.sops.yaml: apply by hand with  sops -d <file> | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
    name: licensing-backup-s3-secret
    namespace: saas-gompha-licensing-staging
type: Opaque
stringData:
    S3_ENDPOINT: ENC[AES256_GCM,data:fbXK/ea0SlaNJmg1FbaYL42ef1Rd/eJbiQ==,iv:Xwlx5l3yRxGNuLd8zxaSUrdcRzVYTpl58mZwhBk73yE=,tag:f7/9RY8apI4HLtvRp3DRVw==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:T9e9t48BKRovUWIYQQ2UwDwZssha6hI=,iv:oXa8j5tzXlvHF0kvYbPIPhFS+pKjJKlSJKzDEVeF0YU=,tag:NSNZ+jJsDGqJso9olXWf2w==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:K9TuFuMc6o1JfdLTBgYfWjHsbIJeFeDzHkqAsP3fT28=,iv:gGqUXJdMHfuf48Dc2djkhEyts8IINYUgKZO2R/4fSUY=,tag:AGrk4NOGzICN5rSyhQoDVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdit0TGU5dG1PaEFvcUVL
            bW5rdGkxTGRnTVdqZ1FteHcwS0F0SnZhM3lNCnFmV1YvQ0IwWkRlblAzNWZNaGll
            NjlZYnFqdnZielVFdjhoczJOL3ZRVU0KLS0tIGtERTc1eDVodXE0UzczOUY2eG5k
            ZFExT3Ewdmt2SUFVOS9Xc1BQM21SUlUKFidm82cj4w1/D8CTNIEMSPDoMwILEHtx
            H28lo0merZ+H4TT7TEZ+KnJjpS4X5k7pJ8AC0EislbEDwoT9mXWCAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOTNzdDRqK25rMUV6OUFt
            UU5GK0lNU2FubjhaQlllZ2pVeFpoQXlNSkdBCm5xZkswY3VzQmFkNGhtWWZSa08z
            OUx6OTRVQVJFbDdoc3VzMUdSTVhsM0kKLS0tIFVMQmQ5b2tKZitEMGZ2cXhDc0Rm
            WE5idjRmS3NjZUdyVm5wQk1ZeC9NNE0KCcL8p77tCqW17gx/gkyR5I8LOB1iK6KY
            3or0qBcEat5AhuHbPWhstIgwR6YLRSDlxeuxBEf386Um737muAZ0Ug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScm9JcjQxdzJjNXhnMTZx
            d3Y2dWR1YnhBdkMxNTBscDB2V0ZjS1lGL2wwCmZ5c3lJbExINUFKVEc0ejlYclJa
            TGdDbnJMRXhIVTZXT3BZcGFYOFBmdVEKLS0tIFJiU245akxXeDAzSmdKVWdxSmcx
            dnlqY0s1cUd1Z2NFdStGZ2FMSmphUEkK/k9QP3XVX15S5n6/kSyYegnmNeCvv6be
            kswgs+7CbFZN7XcKCygBm2wWqj2s6riEq9p+uNyEAoahHn7kP9P1Rw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T01:18:35Z"
    mac: ENC[AES256_GCM,data:8B2qEPoGaYIWczBYYacrGILdbBYuP0gTEGHkFknFaGtwlydaYMqQsChzXcgHythxzv462JW/kBUQ44s7JmW+K810KdmvXjw2IM0jEovFs+ewBYcbzsAWYmikjLJ0m0ZRruI+A5LXNBkWadF57wW0DDVxpXePlkw7dlZ+UxEvNdU=,iv:5yTkvuCy50RHj5WH0GvNuSLHXQT4l3Q1xfPPsX0hjig=,tag:VOU7emgg6oWRhnhdxsNI7w==,type:str]
    version: 3.13.1
