apiVersion: v1
kind: Secret
metadata:
    name: licensing-api-secret
    namespace: saas-gompha-licensing-staging
type: Opaque
stringData:
    LICENSING_DATABASE_URL: ENC[AES256_GCM,data:hz1KaSGJjeJzMkeHScvZxdLcf8lQmdgtlZ/FqFDY+ABXoFYVxrZ0dWYdc9m04m82CivxKjyZh7zOksr23w802eXzz4E6WnA9J0A63EDBd1xqAn4EB+epKQ==,iv:fxfycJlxVImzhCuGSDhYSHI/brjqg72uK33z6uYxRQc=,tag:Xjg70xdyVqhFt6Z4kFFcvQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaUlSYjhLbkcwNkM3YUo1
            L2ZyL3pWRTdIZnJrNmRLeG9QMHJpTGMrR25JCnJ4UTVlQWZyemRLN3JBWXFPa1Rp
            K3I3cXZ4RzA4clNzbXZBdnlQV3piZFkKLS0tIDlieHE2TUlONHdsVS84d0EvK3dB
            UDFJNFhiV0ppVVZFdzJtMTY5UndDWkkK3IzZa5GCcCI+QmwJTxnFE7IrPrZu1SrR
            50pHQYgETBQMRg3Wdn229d63XZgGtTIB/wepYXBS6JXhGkI+b4iX4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOENwSWphL1JhekdhSTZK
            dDA5MWlQaXp6a2t0SXRmUlV6R3p1YnlobTFjClRBQks3YkN6d1UrQUFnTWw5bEhh
            VGpHb09oUm9XYk1sYm1WVVNzNVRJQlUKLS0tICtNa25BZzhNeXp5Qzd6TFNRNmdV
            MjlpN3A2SzUvNE45ZkFqbGowbGFCcFUKMsLrlm5Sg9rkaoZqyt9a9fuESmd8dofP
            V7NTM9o5q+qMIzOCqpIBqan7JntlbKbH0h87IUijvrXO5oWfvbudTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaXhFQWpIdlBwYk1BZzhI
            cnM5VGJuSTJ6TlBSU2grcmNkNi9kaFpVYURrCldNSGF5YzJjU1ZyZ0x0am16TEls
            Qmx4QUh2TENOZVBsRTRlNmwwSEZzRmcKLS0tIER4WG1hTHk0RkZ5aE5BaFpJOWpx
            dkVCZDJXZzRFUkdmdklTcnFoYU83cVUKKCS4gjTZKtWUbX7m7E/uUHonQpmqWuqq
            AS7pkNWtRW+BCwC4WJTg9tvVuYrKOpU2KwAScr1i/bJoesZnK1vkLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T21:06:00Z"
    mac: ENC[AES256_GCM,data:xy50pLHFvlkGQDza6wy5eqFNXZqF3jAdHz0FUBUt3rt6BkYAj8UznydLh3YdvuO5XwUo2MoJm+n5ajnq8ahr5QJEzYc0EsiZXeYcreAFIvOvROzXYa/fckzAlDdeUnVBJ6e7nRFQjh73p7emSPLj3dLUgF8F44JWmdgyvxf2kXk=,iv:fte4pBj+B8a95V6IIHOqWaEp9TcS1jhREXj/qnqc7XY=,tag:Ha0yFdyOIcUvebEE9f3tqA==,type:str]
    version: 3.13.1
