apiVersion: v1
kind: Secret
metadata:
    name: licensing-postgres-secret
    namespace: saas-gompha-licensing-staging
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data://nHYluCgrqv,iv:2P96699SQJmEVbpBbw4oPgeaB/DgveWvve+eAyE2aj8=,tag:X096xFaLdPshH8F4jdxONw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:bqtd6l6FIkrtJkENoqy/VQlbN1UIlne9eLQKeRT+7w==,iv:M0iJ4DP0a1+aSO8jRYNIkK+7piD5vLW4AnPy7Cgx4Uk=,tag:cLQlBDJzHSvOEFYl+hr01Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VGxPK0hYcVlvQ2lSVzNx
            aXg1b0wrb09yY0RYc3VPcGl2WWY4M1N6ZEJVCmhQaEJzWk53Z0hUV3N1eXRIbzlO
            WGNOeDFVNDNwd3FlNlN2NWcwdER6SXMKLS0tIHFMcHNEY1ZXbk55QnFiMlV6cExx
            QXdlekpHM1N4MURZdW0vZCt4V0NNRkkKn+i7tlHvOGEwapNLeMfzxbtZd6n7vyca
            bxpTKb3x+j9wIlemXJIgp/0UYo6wRelDKWPwOTs/PSc2k315L3y4Cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MVdtKzM3M013UnJFRk1K
            TnlwZDlmSHJtbmJNbUd2Z2pvMzd3LzR4YUhzClhHZ1NaSnFMUGhlTURycnlvSzlh
            NUxuZDJzWnRRNng3T25FdFJ3UERCaTQKLS0tIGZSaVVJWktxWktET3ZCYU1rMWhk
            SHRjNU5HajI5V2JYcVRyODhOdEtpMGsKaKPfBmpHz/WBBeP6H9HbavxBpHbo007T
            KWBjxPkH3ao/AY+5keY7/qNhIk1+pP6OPRbgsUhvJcV9XnSfuRL3yQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMlRzTzgxa2puWmRvMzU4
            cGE0dzVDdVlxK0dvSWFETU1ycytBbE93VkcwCjNJUnhvdEpUZlVEMlpRdnBPSmRm
            YjdmQ3FrcVZ3ZDBEKzIvUlBOdEZBSDAKLS0tIE5qSDM4QTB4bnVFRE51ZUk2aStW
            Ti8yanhDM0xJSGFVQ1BnVVFGZ091bnMK1M8662CfyN1OtsXq4HKbaLnH7FV2NITW
            ONJTpaursy5wTeOtf4I79S2eMoHKj7zwBpLhy7aGCDvhKD1oU9iowg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T21:06:00Z"
    mac: ENC[AES256_GCM,data:Ggdmhc47woAkeVNG3gaYjbwfpwxJcXwkZNX9thxdOa6gTZ15GwNTvqet7N7Q8Ty13QqtLxJP46ZE+u0SodY5n7zehhbwIMOWRtc63iCbgy1JWviJ/2u1V4HbmMmMu6DYYtPvNkdJWDhkOQ8DwcnhErOas5YYZWTpDQU34OKRnUg=,iv:qgPVuGF0/WT0mqqStGUEXIeyEE/rARXEE/ZNOfKErU0=,tag:5mc7LtWl1Biif6TZlReZWA==,type:str]
    version: 3.13.1
