apiVersion: v1
kind: Secret
metadata:
    name: licensing-postgres-secret
    namespace: saas-gompha-licensing-staging
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data://nHYluCgrqv,iv:2P96699SQJmEVbpBbw4oPgeaB/DgveWvve+eAyE2aj8=,tag:X096xFaLdPshH8F4jdxONw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:bqtd6l6FIkrtJkENoqy/VQlbN1UIlne9eLQKeRT+7w==,iv:M0iJ4DP0a1+aSO8jRYNIkK+7piD5vLW4AnPy7Cgx4Uk=,tag:cLQlBDJzHSvOEFYl+hr01Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdEhZdkFla29YREZWMk5p
            Q3hzRVRONW1LelNBbE5OTjZkMzhuRER3MjFVCmZtK0dEcmNBL0NGS3RxYXo2c3dB
            RkJ3L255K0tnMjEyWjZtQ2ZEY2J4bTAKLS0tIGpGY21UVmorZDdDc25mdytuc08y
            WS82K2U5eEVQYU16YndHa1l1RHQ3MmMKix1QnYQ+PKYD10N3d4fSTa+ICzDBtEtq
            D33lLHZO+yfYG61og7u1cMZKSmeIBlTA4AxahG/sQl/EkKVV9Akf4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T21:06:00Z"
    mac: ENC[AES256_GCM,data:Ggdmhc47woAkeVNG3gaYjbwfpwxJcXwkZNX9thxdOa6gTZ15GwNTvqet7N7Q8Ty13QqtLxJP46ZE+u0SodY5n7zehhbwIMOWRtc63iCbgy1JWviJ/2u1V4HbmMmMu6DYYtPvNkdJWDhkOQ8DwcnhErOas5YYZWTpDQU34OKRnUg=,iv:qgPVuGF0/WT0mqqStGUEXIeyEE/rARXEE/ZNOfKErU0=,tag:5mc7LtWl1Biif6TZlReZWA==,type:str]
    version: 3.13.1
