apiVersion: v1
kind: Secret
metadata:
    name: licensing-api-secret
    namespace: saas-gompha-licensing-staging
type: Opaque
stringData:
    LICENSING_DATABASE_URL: ENC[AES256_GCM,data:hz1KaSGJjeJzMkeHScvZxdLcf8lQmdgtlZ/FqFDY+ABXoFYVxrZ0dWYdc9m04m82CivxKjyZh7zOksr23w802eXzz4E6WnA9J0A63EDBd1xqAn4EB+epKQ==,iv:fxfycJlxVImzhCuGSDhYSHI/brjqg72uK33z6uYxRQc=,tag:Xjg70xdyVqhFt6Z4kFFcvQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Nk42MDB5aW04TndFRnM5
            T3liSHI3SElPK1NmQUx0K1ZaT0VKNzdhR0VvCjNHWVpyRlFGYURRbG9aY1pnRWNU
            dHQvUjBXQ21mQmVlUkNYSnAwQVdHUFkKLS0tIGczZ3ozSy81NVl3TmI4VGlvc3Nu
            eUZBL0NIVGZmNDBHL2ZqNnBKYmtTVzQKECRoEnSPMtKqGvOHK/AE+EW/Yf+H2Oap
            Ey6R6KlHAR0qMEjzsQhf1JqNOYuB6TExZUXsmIOrh2azxHM9HhFmwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T21:06:00Z"
    mac: ENC[AES256_GCM,data:xy50pLHFvlkGQDza6wy5eqFNXZqF3jAdHz0FUBUt3rt6BkYAj8UznydLh3YdvuO5XwUo2MoJm+n5ajnq8ahr5QJEzYc0EsiZXeYcreAFIvOvROzXYa/fckzAlDdeUnVBJ6e7nRFQjh73p7emSPLj3dLUgF8F44JWmdgyvxf2kXk=,iv:fte4pBj+B8a95V6IIHOqWaEp9TcS1jhREXj/qnqc7XY=,tag:Ha0yFdyOIcUvebEE9f3tqA==,type:str]
    version: 3.13.1
