apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-token
    namespace: cloudflare-tunnel
type: Opaque
data:
    token: ENC[AES256_GCM,data:C9YZ7P8Bj0g6SsEawlJpKuaR64mqxSLeVuq4PjUdFZfxOcvnIzYg/khMj/oYZAQfvFxo+9TSZ3cu+IHeBwmVvXubFIwEO6+X5FsmXOy4ZTGeHttg4iuO70zPpyhL7WHapHPC2o03rQ9/GmhzdoTVWG/m5dNSAZJ89L5Oq4xMPKHZAwPFfwfBcoe3dJeY2j8Xu/slQ12Ejd7TlYy67LzMho2s3I7zPohnc4sf8HDwl2u7IllWwWYMNLGHIjxJdpqulJ1GjBLPfBkGAp9MbXYE8E70SHrVdU/Z0d3owulB9aDklaXmwsf+aP8nfrtCxDc48Umh4vZ+Hzk=,iv:SrpoctE4aUODydSeRpSjzZ+sqkDWbZjOHjFFnihgH40=,tag:8XJSeUpLKo1IyQQb3ZP88w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0emhmMWtQVEUyZVArZHJS
            cXQwWDRZQ1NteCs0aytCMGN3SkFqcDU1c2gwCm9tWW5MQ2tpdHRSd0N1SFpEVVZ1
            QVhjZGNaaHFtUmQ5bUpWaUpNK2lDM3cKLS0tIGZMRVFzczlyWXlzS1J4RkE4REZS
            VUR6UkNmeTFxUHJ6UlM1bjdtTGxkZ1UKqufRGvP3S5+97mz5cMMDSdObbEM1p+Wz
            NNtPIv8SqbmVfB6OpoiXWz27HiQBbPRHm7SIZi+En7Xr2vGxv1oc6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WTdPQnlPZmJLOFNpQk1O
            YzN6b24vc0VjUXJTemN2N29ZTFRLb0NsYXh3CndUb1pOYk8waTEwdWlRdGVEYWNH
            MUJGN0U3N0FWcGQrQzZWQkdRL2tieXMKLS0tIDlwZ2dmQUxwTHVLMXNlT2wxOXNp
            Y0s4WDJiT1ZFSzFUeUk3NmFwWmNJMTAKQNBaffXWLofg9quTldG5zJf4vMDJRh3Q
            8m3r549coUreVGO404XM0o4RlJtq4q5OypulwIEMG/DNH+41CYe2Zg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaeStJekdlYWEzZHYwNkdC
            TGd1RmVXc0FWRUsrRVpOUTlINjZnbjF3cFZRClMwS3lhR2szWUtIdnA5UzErdS9F
            R2xKZGJkQ1hxM1liQjZOMmprS3V4VE0KLS0tIFRheXdLNjZMQ3dyMDJTQkhNK1N1
            eXRSZHNXSThzdGZXQUpMZ0pRMklqRnMKnLr7AzKjIbTc6InFfXo0pUYXrtrWj3dL
            yr9J7qrgczCNK5BQW+GTRTBegSJCnGes4tSY4OM2b3MtNFXTEq1jnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-16T18:46:10Z"
    mac: ENC[AES256_GCM,data:ucR1u0v/4HVjD9AxH1DGc4uDtOqUVCYO5Ry6FQZdH0k3dxti8s9ugnDHXN35/ZAAQDuAhSBHlT2MuTQotNBqCiSFOM9YeABN0zJfjVGaZ3M99br+KillUNQqdq3VTmYDyHMYtGucC2/rIy2ZinuOrJnLCht6g9BEjGKX6/shkU4=,iv:Sv1I9TW6vU5BecxVsdQNblELzBk+zoTsEzcyOYZkpJ0=,tag:Mswf0VO5SfuMoRF+ccEMDQ==,type:str]
    version: 3.13.1
