apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-token-namosocks
    namespace: cloudflare-tunnel
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:85gfN7nNyqrRx9JyudzNBjRf/eGMvD3ccFF8+p7MhP1EhNveURrflWKKhH11iNNh9HQhG7rp4EV/ubvXNIGLDkzTsdnLw21vxuyRjTbzS/zwPBc7JHkJ+W3W2jMz7NhmJCjPnP23i/K6js64yuxk0DRW9xXB2R+fnlnBLiD44CFKlbWpIX6RasHX7lWlQGiXnUgN7Iu989WGyTcMPIhN4YozvajgAT4CjMSYhFt5d/cHgubCAe/dow==,iv:MXxuiA/WUw8rD6gqX41xbGbe+lMExhxFg3LMD22vy/0=,tag:vvrCXgpvjTjvOD/y8tBfnA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArLzdvUnQrNGxwQ1RUZkxH
            dms4TVVqN0VpTTBUNDBqT1RBTWNsZzV0N0dBCjh3Ym1RV0h0ZWJKcnI5L2IvbWV6
            cVBsR21Lb0hqa2dBaGR3bVdXd3FQSUEKLS0tICt0bUVVZVdJRGJUd0FGVGI4Tk9o
            S21tdllYZXY1OHcwV01uRXdQY3Bvbm8KE5nAbb9KD6xq7IhsoKDmx7EvVvF+xJ3g
            o0Dc071NnXazp6UYELeWEaVlbYlaRUMLkDSYbJwItqNdh9NvQseA7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T12:37:30Z"
    mac: ENC[AES256_GCM,data:9fvcDuq3gKeK8pEKRZRFmwgXiLRP6Z0790+cxYO612v5WXjwuNs8Y1pWvlE4R+TZCvlSp7rdh26OJTGc7zS1nfRSWQSE5xzOjad8InvtzIblrNtwzFtBUgxjxmHL/blAXEwigP0UNYkUX7PpP3ULNqv/4nnQOZt/BNe1OJWZyPo=,iv:Co9uXrKOZGF34/LsbXkADQVaAqCzTQLCgeqn4OoOSoM=,tag:5ZKK9Vuh2BSTKHYmGIB6HA==,type:str]
    version: 3.13.1
