apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-token-gompha
    namespace: cloudflare-tunnel
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:oWsRMLz7e/zQ/DlE7z1Cd9k8C83kfv3rG/RSQ9/CbY0Br+gZSI3bsBL48TuBuhy/PpKYctcEOGx49xv/ohyhB98mm4PbEQzjuA8fs6NOw2OFcoLn9oGovnyCaolJOUz1l3/Kgof/aY+x+Z9qf+mtd7sKN9QdZiVdFX3to23EIb1Ipqs+7IzltEpswFSAiy0GGPdFbShboTD0RUhORX2MMwlv/dyawJNJktVsYL2usgCnh9Z/ZyURiQ==,iv:1TLYQi2307VIWV+CZScZkHRbnvdoTNg6CUmYi++bDh8=,tag:zb6SQW2vWuoErDVdYGsErA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNXhCYjdEak9Xei9GZkM3
            VGxiWTdESjBLMlFXQ0RWSnlnOTNVcDB1T2hJClZJeVY3bjEwMjBjeU9qUE9uT0k4
            c25TdThENGVjbi9FOEpIK0JTZ0VPZWsKLS0tIEkwaU1Nc3lVU2hRME14WXluUmpN
            MkJVVXpsTG16T3RickVwM2tXTUVzcWcKz371ND4a2KldnjRL5LHhQhFpzXMGEs39
            UFlI6FyV/ws8Q0/4GNveLAPX1TQQniimfHB4ZHvzLqzK+soQ8pK4Og==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdjFFUndPY1pIRExuMEVB
            bVNSZm9Fa3FoeElBUHNLQzJhdmc0Q21vZlFjCkRoRU85M1kyWklCcGR1d1UxWHd5
            NkNPS21QQXYwVml0NkJqVUtGcG50L0kKLS0tIHhyUjk4MWJtQWYvVEhtT08zSkZV
            eGxqbjhSNEpLbnpGNEFmT3NaUU0rNWMKsITTaEhPjBkVm469L+s3AgbaFdvPjZS5
            LB9Tj8cbhDxxs0JizR5XsC43KsGa8XiRgdpODEmTwDGkc+o+arneRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSE4wWmJUQ0hwRUwxekRG
            d3ZjMW5DYmFLY1ZWaXJQbDl4RzltNjlsbXdBCjFQeTR3K1BnbnZvdUxiS1FLTVlK
            RUVqOGZTTHQrajFCUDJabU1YZ1pQMGsKLS0tIEFtdHdDMTN6MURzelFLMk1mVnBv
            VTdSTnViRmxNU2w3NS9Hb3hJeUlTTFUKyiYrFPSrBPssqQUwnDgQZpF1/3CCJMuC
            kEhO/ulHj0Gpoahy4g7Nj05R8DVhevTiJlXM+2EqSA9zhTzYSTgJWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T10:31:25Z"
    mac: ENC[AES256_GCM,data:Usj8FO0C59y2hpTFl/zGj6o2Nc8JkGkIlgVkHdYpD7GyJNJKt6Ka3e/OaiNqS2i9AXe+w00McDRGhHJazp89vyZ/09TgAEt4Wggd32Yvpgui4VFFtxJY/u8ouU2LiV2834KWVzBiPiEKryKJwoHwYTtiCU4IWBcNrcxbdBHNUco=,iv:nLS6CKFDealcD3RBBwkIq0lQk63P7pgC+QgNEVXwhzg=,tag:mTxvtmp+us7jY6Xe/e0WQQ==,type:str]
    version: 3.13.1
