apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-token-gompha
    namespace: cloudflare-tunnel
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:oWsRMLz7e/zQ/DlE7z1Cd9k8C83kfv3rG/RSQ9/CbY0Br+gZSI3bsBL48TuBuhy/PpKYctcEOGx49xv/ohyhB98mm4PbEQzjuA8fs6NOw2OFcoLn9oGovnyCaolJOUz1l3/Kgof/aY+x+Z9qf+mtd7sKN9QdZiVdFX3to23EIb1Ipqs+7IzltEpswFSAiy0GGPdFbShboTD0RUhORX2MMwlv/dyawJNJktVsYL2usgCnh9Z/ZyURiQ==,iv:1TLYQi2307VIWV+CZScZkHRbnvdoTNg6CUmYi++bDh8=,tag:zb6SQW2vWuoErDVdYGsErA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bmZ1bTByRmpBdzJGQkRs
            Q215OEsweXBzc2pLTmZOM1lTeW85TUJ1UTE4CjRxQTZ0Z3NDbDFZWHVwaDRzdzRk
            dWlDckNES2s4L2x0R0xWN2JEQUZHZFUKLS0tIHZ6TU9Hdk9oeWIvVFZDZDBMWlk3
            UGFpby80bk9kTWFiQ01qbFltSk1qejAKh/OvxES5BJVA6R6gOUXWTUqb0nlu5R7A
            kGnEph4jkt5QalGAHwjiQ7xUbM9yu9Ctedm+lVI3zCxbXfABvibDgQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T10:31:25Z"
    mac: ENC[AES256_GCM,data:Usj8FO0C59y2hpTFl/zGj6o2Nc8JkGkIlgVkHdYpD7GyJNJKt6Ka3e/OaiNqS2i9AXe+w00McDRGhHJazp89vyZ/09TgAEt4Wggd32Yvpgui4VFFtxJY/u8ouU2LiV2834KWVzBiPiEKryKJwoHwYTtiCU4IWBcNrcxbdBHNUco=,iv:nLS6CKFDealcD3RBBwkIq0lQk63P7pgC+QgNEVXwhzg=,tag:mTxvtmp+us7jY6Xe/e0WQQ==,type:str]
    version: 3.13.1
