apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-token-namosocks
    namespace: cloudflare-tunnel
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:85gfN7nNyqrRx9JyudzNBjRf/eGMvD3ccFF8+p7MhP1EhNveURrflWKKhH11iNNh9HQhG7rp4EV/ubvXNIGLDkzTsdnLw21vxuyRjTbzS/zwPBc7JHkJ+W3W2jMz7NhmJCjPnP23i/K6js64yuxk0DRW9xXB2R+fnlnBLiD44CFKlbWpIX6RasHX7lWlQGiXnUgN7Iu989WGyTcMPIhN4YozvajgAT4CjMSYhFt5d/cHgubCAe/dow==,iv:MXxuiA/WUw8rD6gqX41xbGbe+lMExhxFg3LMD22vy/0=,tag:vvrCXgpvjTjvOD/y8tBfnA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHclM0TGJWNE52dmtFU3Zj
            QjJPWE5zNDRsTVlKRk0wWGVlQUMrOFNGMEdnCkl4SmU0Q1M4VEMrU1N5aDhpaXV2
            RHNGTFN4NldTTHpSaGRLMkg5azJkWk0KLS0tIEp2L2xWMnlvZVE4YmhZQ1JUQ0Rp
            RkZEUjQ5TUZUcGFTMFB5eWZvdDV2aTQKkkzIiS5DqUc5bHSQzNm6/X5KtsnKKHUo
            MFlqMx8U/rZnFkp29s4UyGrmjxj4M1iItsb58FDVdV3j86A75oxTPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1K3hhaGNkRmFTa3dtVEpq
            TmZLMk1aZy9rWVhoQ1dWRFJibkZhWmJGTmd3CnkrQW8ySHlnUnk3RTNxUzhDcm9Q
            dFVsbmNEMCtTKytOaTIzTXBUZTJBT28KLS0tIFlicEcwTlZpek42YWl5MHl5WWFQ
            MDFETkF1Q3k1UWhFblhtZW1vbTZOUmcKFD23Bab+pwpFBcglk+ff/15gfXA2M5Dd
            fZuQQOd7uiEIkl/KCaHth7TjbkSult1//bjyKuZ8A5NxlEuw/svvSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMzJxTDk4QU1rYzB4bjVu
            TjZnb3ZKWkp6YmFoQjNxYjVXeUhmeUF6WWx3CmtEYk9URUFDVXphWU1VbFlMRk9x
            aXRCcERnQldOSWpTZlIzZ3h4L3VuL2sKLS0tIE9nZVF0Z214ZDVibGhFZXJvY0lS
            TjFrTlRTRVdaZWo0aWhNRTBUSlNta1UKSy5JwPoswo/V4jkaVaMYvKeg4N8VeHAW
            C+foltPqgZ684O+mm50nRLphwPWdwP113GK3EpVNj0hGBw1RM7YMJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T12:37:30Z"
    mac: ENC[AES256_GCM,data:9fvcDuq3gKeK8pEKRZRFmwgXiLRP6Z0790+cxYO612v5WXjwuNs8Y1pWvlE4R+TZCvlSp7rdh26OJTGc7zS1nfRSWQSE5xzOjad8InvtzIblrNtwzFtBUgxjxmHL/blAXEwigP0UNYkUX7PpP3ULNqv/4nnQOZt/BNe1OJWZyPo=,iv:Co9uXrKOZGF34/LsbXkADQVaAqCzTQLCgeqn4OoOSoM=,tag:5ZKK9Vuh2BSTKHYmGIB6HA==,type:str]
    version: 3.13.1
