apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-elwany-media-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.1.100
    path: /mnt/user/Team_Elwany
  mountOptions:
    - hard
    - nfsvers=4.1
