apiVersion: v1
kind: Secret
metadata:
    name: nocodb-secret
    namespace: nocodb
    annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:YFIvZ09b4KEKCvohXedNg+vXca2RNC79jiPerA==,iv:EjZyz2W8sDWE6hnMcWQV1Jjfo+9xDV+BPn25xur3QTA=,tag:FOG9/J3xolgatfJbG19y7g==,type:str]
    NC_DB: ENC[AES256_GCM,data:1YkfMGJnkbYMqDfnOZRR3FEqcCXxu/elDzPf/viIHrm2erHC2WECTOAXwWNq7MZE4IgR6fBmER9nIVeptusPU/zeNw==,iv:n22Y2J64nrCWJCbbhEzrFLZD/X5QtWQUbI8oDGcRpk8=,tag:uCZ6UDna98RHJQvW2BH1MA==,type:str]
    NC_AUTH_JWT_SECRET: ENC[AES256_GCM,data:7Qb/52+HJi+2Iimp1lHq4+wvH3hQNlAQ5qSXwbbWLT/hvz3JHJKOWANG6js=,iv:v2k4BUgApIKO8fjA7c/+xYURjVEAZ4UHCBCwT7tvHEQ=,tag:pCKWpYJkoDlotwjDY4QkZg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMnFhNS90cnVrRHZqUWsv
            QkdoZHhBT0ltN2FHYklDb2lYVHZkRUU0VldvCmNKbWhnRmxJRjJIYTRydlFpbWlq
            blB6ZlAyTFRDM1M4QTRqdjhobGEvcGMKLS0tIGs4Vk15T0tOWTFuRFkxV3dQWmhF
            YVR2Vk9iNmpmWkR6SjRCZmkzSCtvQU0KXgF6Cs/sIQN2FVqrRaEyDRWoZrI/1Qc+
            Z+AaONR/uxgvV9Uo1s45MPSYt/NtPvyYKq4eaeul0sU+k/OIjGShUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T10:52:56Z"
    mac: ENC[AES256_GCM,data:jm/WbgUbLIP1zETOJAHpoTLEjwE7d03IZpGC9j8/YEUnwTe+52gKptwiGvTCsLBxGw3AvCAX3yFxaexBzX4LDUyVxWv0iFE5+VlwhKX6v72Yp39yi8DkZ2bulZLZtnQCBeH9jhowSrKqx9fLznt19HR2lqQu3i4DUPr/7T/yzbI=,iv:YFiv/yeaEbI1OVvMOX7JrouVX2OMy8ez+3V9WzkSVj8=,tag:VhlVix2n9/eMY5EpDtvTfg==,type:str]
    version: 3.13.1
