apiVersion: v1
kind: Secret
metadata:
    name: nocodb-secret
    namespace: nocodb
    annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:YFIvZ09b4KEKCvohXedNg+vXca2RNC79jiPerA==,iv:EjZyz2W8sDWE6hnMcWQV1Jjfo+9xDV+BPn25xur3QTA=,tag:FOG9/J3xolgatfJbG19y7g==,type:str]
    NC_DB: ENC[AES256_GCM,data:1YkfMGJnkbYMqDfnOZRR3FEqcCXxu/elDzPf/viIHrm2erHC2WECTOAXwWNq7MZE4IgR6fBmER9nIVeptusPU/zeNw==,iv:n22Y2J64nrCWJCbbhEzrFLZD/X5QtWQUbI8oDGcRpk8=,tag:uCZ6UDna98RHJQvW2BH1MA==,type:str]
    NC_AUTH_JWT_SECRET: ENC[AES256_GCM,data:7Qb/52+HJi+2Iimp1lHq4+wvH3hQNlAQ5qSXwbbWLT/hvz3JHJKOWANG6js=,iv:v2k4BUgApIKO8fjA7c/+xYURjVEAZ4UHCBCwT7tvHEQ=,tag:pCKWpYJkoDlotwjDY4QkZg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTlo2RWZORVhmWDVaS2xz
            ZmtiZjgyeWt1bVcySEZzMmZpNDRvYjBEeWh3CmVFdks2ZnlTSTlvNGF2MXlITkx5
            c2J1YlNYYUlMRFE5ZVB6c1hxVHNDSHMKLS0tIEhzY2VWdzdCeG9xdEJLNXFUTTZ3
            b0xWVVFSQW5waVVORFB0K1RwZmpPWjgKkrb044ES1MPUvpZJESo/ucIQnFbakgTJ
            vXrroF+0dd9vLBgra+GJKpYgc0H/p+OSIeaCxEw95Ml0u8T8X7+lHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraVFhUDhiOFVjaENLbkFi
            QlpjbXhuWmFHSElzbTZsU0x0WCtIMkFvSG5ZCktBck9lMmVoaTFleEY1QW01enJr
            NGJvZDIzem56c0JNdUVlK2VjMThFK3cKLS0tIHI2SDE1blh2bWkyYzJzL2xYcWxN
            OE9wU0RoOHd4VlRncE80VFlxNEY0NFkKEEFPOk32d/wZbSlUdK+sPATTpy4wuQn+
            Nc/YI7+vLHzm6DmVFoMbtCOWqhq0WsxpFtTOZmjbRhFcha7zI3VDCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6N2xvTzVnRXVYRmNvaHpM
            SHNraFF3Yy9tV2dHeUphVi9yV3NSQ3M1Y1dnClRhUDg4dDE5WXJGb1RUd2dBUnFV
            ZlNzTGl1c21lZWdGQ3RlM3NrMDV6ZEkKLS0tIExaSWFFTWFLakNkVWZHVE1RYWhV
            SzRua2ZRUXgzOGpHdDAxM3Zyd1MxN3cKj1xCHQvarYTtF0uHoJxdm7Rxk2wlLakc
            yWO4clHcWQigVKdMOg36t55vnFFGCRd+3gRSNUuVfJpVVwjunKo1jg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T10:52:56Z"
    mac: ENC[AES256_GCM,data:jm/WbgUbLIP1zETOJAHpoTLEjwE7d03IZpGC9j8/YEUnwTe+52gKptwiGvTCsLBxGw3AvCAX3yFxaexBzX4LDUyVxWv0iFE5+VlwhKX6v72Yp39yi8DkZ2bulZLZtnQCBeH9jhowSrKqx9fLznt19HR2lqQu3i4DUPr/7T/yzbI=,iv:YFiv/yeaEbI1OVvMOX7JrouVX2OMy8ez+3V9WzkSVj8=,tag:VhlVix2n9/eMY5EpDtvTfg==,type:str]
    version: 3.13.1
