apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shlink-data-pvc
  namespace: blanca-dental-care
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
