apiVersion: v1
kind: Secret
metadata:
    name: immich-lightroom-secret
    namespace: immich-lightroom
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:xPOBQ7RrUYsyN07JuTdIF/ywD7tyb8fykTYQoH35c/LoZxdREkOsUPkwjL0=,iv:eDz4ITxPAGgTObilNo+a4pC27IlYbhvuavg8XdTLQe8=,tag:Nb7gprIH7OvubeMMFKbHJg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:40uvxjUgWuSz0LYX4OKnzMenVZ66rutcnKoTNN7rV/UUb6vXVhboHRmIyx4=,iv:sMkioeoYFHyrzSJiyKIWTCvAaeSDVenz5JQOfSdx0CA=,tag:ZIOlQ3BRJTHlWhB8Lxysgw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQWZqeWt6M3FRVjdUamtt
            c1EyNDBDbDNiK0RTenYraU5OR05jZElCSlRnCkV6Mk4xWWI2d1VySXNVSVpqcEpB
            QmlmemFEcDl3SWEyUjhUVDFHK0hwc0EKLS0tIFRuOFNMc1dxMlBFdFNjYVUzcmpY
            ZE9uT1AvOE5FZFlCVXBuTVh1WDltQ1kKsVMX7McpGc6AVcEXINjK2D/08LG9mSiD
            +XJ3X8N9/JoE2lPFr7XRzQI/ph9Di4XXAKxHq3kZ9C64iI1fMWe2YQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-20T17:11:06Z"
    mac: ENC[AES256_GCM,data:FtoE4Chk6syRACWBDDrmzPmk4Y6TRAGY/oMJn+kCRy834fsodENFk4vIsJkkX/UlSwJN/8+HnsVzLzMdoOmsGltsxzSgC/oBuy9cwi6xbWxI3D+vo/f4AvuRxVPHgPq+uvDeZn0dIkmc9HcpFuhP+PB0sEnFFUHPjRJ44iMXSSM=,iv:XN8u6Hkl/SwPLFtt8pbUTbC1MAgRh8vCfcymEdGEgOI=,tag:8p86IDDDxUT1WUgoI3s9qw==,type:str]
    version: 3.13.1
