apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress
  namespace: namosocks
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "64m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - namosocks.kostikidis.net
      secretName: namosocks-kostikidis-net-tls
  rules:
    - host: namosocks.kostikidis.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress
                port:
                  number: 80
