apiVersion: v1
kind: Secret
metadata:
    name: kuma-push
    namespace: backup
type: Opaque
stringData:
    DENTAL: ENC[AES256_GCM,data:QCnRTjxPFq0cG4EnNqaojFW/6q1ZL0gHOK3Pqdoi/5gbmQh4zgNyZ6JhfFcz,iv:I9DYHfq5Zkj78Lb15qcXhso+uA1P/58MyKTnZszWwzI=,tag:KTAfWaLBx+WWKQL7tQJTZw==,type:str]
    GOMPHA_CLINIC: ENC[AES256_GCM,data:It9YYpVUXXMfkPyAbMFPCokiL6/zsoS7W5jNU7XXqMTuIWfyIhyN0aDFDY3WWM/Ch8td24Wjruw=,iv:ibfNcbB9XF7PS8Nnh19kOPJgHT4VvNB3s/VqlW9ha6w=,tag:1+hv+lXdmIYxlRlZejnCsA==,type:str]
    GOMPHA_N8N: ENC[AES256_GCM,data:tM7noxREKyOR+IHAa1/dNUePgtT9FoP8rhNX66SEB4SSva5/NACRvlDSyliu,iv:N7B2d6csRhbyUUm/vqn0g5yzcRjQz29oAkOE1vaRUfQ=,tag:6xiYjEGi3x1uj/KzWGTISw==,type:str]
    NEXTCLOUD: ENC[AES256_GCM,data:599j1d2juC+vvsds5h2nHu3uHiwn6IeswbliHeBOveA0zbs0ZiHDrdO0CqdH,iv:kwirm3ruK+YHh2xH2JkWjnxdHfa949XItnOMryLbrR8=,tag:iHZ130PVvlqGYxzcoBxRNw==,type:str]
    REPLICATION: ENC[AES256_GCM,data:2nMAaYxrgAzT8XOYX7k8U07jIvXSF41hI5hXhYENjZP1cHz0L4JiqP/OF5Lt,iv:wNXEZRU0dPIul9rpyhE0Np+MVI0jwGUDr0W2NH9Fx4w=,tag:ogHpaBfaevaO3UBXekz4dg==,type:str]
    URL: ENC[AES256_GCM,data:fBUKuDNFgPFZ+ZSATDJ5SG2FBmcfG5UWJ1cUFtPKwaz8Z4vssns5J4vS8Bip,iv:0aP4NitpQcxChu07wo0nuqSa84xbtXKEbdWRahSW3Q4=,tag:U9J7bALHsb7gw4KG+gakzg==,type:str]
    VAULTWARDEN: ENC[AES256_GCM,data:dCUiAPoqjKJX294FakB6O04/ylEgYnOJRUtBnQKxDvgYO9DmL+B/GB3oAwqC,iv:cPn5yINhJGPbvn4t3donIPNwBDMRArX0co6bI8o4rPU=,tag:w49RfQOs13UWRB5I9wdhWA==,type:str]
    PLANE: ENC[AES256_GCM,data:DlqUMr93IuZPCO9cKmT2NmMlLwgT5FmAExHwPmce1tzlpEILtytivvNsA/v1,iv:yx+4zelZKIdomEXumROc0cCj7u3+XiAsz2RmEJ+DSg8=,tag:C6utqXKNMj2gQjQks9mxLw==,type:str]
    BJJ: ENC[AES256_GCM,data:bwfSvJHSivpZkGOxHhjC2u6fOO2vMyfwuYeUTMkb/KiHAZb4f1ND6gxbaXXC,iv:6OnsqCSQmiBIuUS27XusYdaOPZ5nI9ZzPNRuz7GyiAY=,tag:MmDMAuLN1ktk3Mie7M4g/g==,type:str]
    N8N: ENC[AES256_GCM,data:jqdUz29BD4l7GSFEHQltZ6nhaf6L6Rgw8TTQ8LJTH45SFeoGe4XTT0Ipum8S,iv:SV1i/1jSyCdsmHFfKI2aJANiROk6E0n5s+PUISuKGhU=,tag:bqSG9x4I+RZK7UL1Y0vr6w==,type:str]
    CAL: ENC[AES256_GCM,data:+8Vi8hNqY1Sww/rAkjwpfztNmY5Es3akz7hrhdMC+tIUCXynms1iULLSv5v9,iv:96DMQyMcVH1PjJ2wSyp0T1Stq8Jcokblh8Usb9Uv2kI=,tag:Zr5upC2WKhb4tKknr+c2dA==,type:str]
    MYINVOICE: ENC[AES256_GCM,data:p5IZu13xqtj8j7g+pTY3ZoF41QLl91WH6HCWGGWLtcl/1P83Ltd+w2nU8En5,iv:kkN2MNW5BV2yOq1cL6mqNeP7oOlYMMr581E0fI2JrOM=,tag:KidCAdhveMZCQL79Pg1J0A==,type:str]
    NAMOSOCKS_DB: ENC[AES256_GCM,data:on8D9Tv+oRD4TPZdYWt7Mv0t4ZQtFYVAF6aWFtH1HzMlOEqqOIlVuX3CfNXJ,iv:/pkZbqJ7xqrTn/yKRZIdugtsnbcvqqYuoUol5ZEg3mQ=,tag:oyO870JR35ov510kMRXJjQ==,type:str]
    NAMOSOCKS_WP: ENC[AES256_GCM,data:m59eUkksc9SuOObL5gPOYiDQdUhbkn256d5GJybfO+2o7fIHY6KDKGEigFO9,iv:r7+pTb36YQp0fUu7txTVX6ejn0s86ngpP3cmGRsNnSM=,tag:3OopBYzfkkTOEeJ5LVCX+A==,type:str]
    NAMO_N8N: ENC[AES256_GCM,data:z+JfdEIE2ZMebfKr4KSNWBrePkqw13o/Iur8/nYgKjENuqu1zReajWzTLmk6,iv:YqNsFlq0lIvmhClE21fCyr57fAU1sbOxzMGbK2y8i2M=,tag:Nb9dZOMdjVmv7scg0n5Rxg==,type:str]
    NAMO_WAREHOUSE: ENC[AES256_GCM,data:7Li+xU6+u/NpM10hnZual0Gm6nb1e3Yv74XpdSwCiOlUqb7QPGrXKmFibLFK,iv:f3bR0yg//8JpdAJTURT1/dT3wuU73axPt4kBL3acHDs=,tag:Wx8l+on8+zgdIp+mGcBJ/w==,type:str]
    BLANCA_DB: ENC[AES256_GCM,data:zRgP0pe7ig9FxHZz7b9L2+ADMdULEUvv3jluPKBB94CQPHE3rPdcLiIDQUHG,iv:Fxl6YYkIs8LSSR2RypTw8UeYSYc2NMIbSsJfjZ+RdF8=,tag:D8z28L9tcUplWzlVA8zp2A==,type:str]
    BLANCA_WP: ENC[AES256_GCM,data:ynX8mlufeUQiR8eE2bCWXVhHmP9jkjS6dlaNHNEFGmMCaxee0YDoxszDoua6,iv:VhEFMi8Ef2MkC0IqV8MAtgnIaQ45hDloo8J02Rzj02I=,tag:N4bOt9A2UjUf+p+IUrh3Kg==,type:str]
    HC_WATCHDOG: ENC[AES256_GCM,data:0FJ+nCf7+fluB3RXrD6UoAO7FzUjuBlgm/ZKxRsy7l+zW6BD86/mcYzQZCprAjcjyJKb4aJjGBI=,iv:Tr3P0pE69sAXW1YAT8/sB5zP4bGPvGDtyh2980jjIL4=,tag:8jybTYpxQBEaF/6BtNlrvA==,type:str]
    LONGHORN: ENC[AES256_GCM,data:3i16SQETgJQuxHErA9t6nwJxduzSC2+3qZ20xnoLx+YufQG3NxAqMaBCkYUv,iv:bvaaVg6upQylX/hW25ln4HcO88sGpRd8rGVdt+vVC/g=,tag:NFrtnL5l1gkkzc1o0RuAfA==,type:str]
    VELERO: ENC[AES256_GCM,data:fBUvL+Lb2aMb2ZwWk+PIrTTwA3TUECPijjWmVRONUQpQOnho50/uVSUr+yk9,iv:Q2w9hZg+l4VLh9Qs9Ucgsi+gnY1g1wMYDCi0jLz50M8=,tag:Ya7LyknXoTMcG0v2ptBaYQ==,type:str]
    PAPERLESS: ENC[AES256_GCM,data:q+vZVO5hM0x8h0sACVoWlr+Mls3t/0pn/RkT4daimkhOgWs+pS/V8cDx/17V,iv:B/s7ryyitaElqCmUj4tsLIO/dRSdDPSN6fovFpZH0J0=,tag:WQNDBFo2+x15rq2/jbXaFw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRzduTmlaZzRLZFBUMEt6
            RnZmUWZUMldBNEZQUWpoeXhNNkF1NHdwSlVVClpZOTVkOCtibVpBUmp2cDkxb0hh
            VkpscGc1aDlQc0ttTCtQdHBqRzBLYWcKLS0tIGtWQWJ5cU1CVDZQR0JXV3MwMmg0
            d2M4QzB0VUJ4MmYyR29QQW1kaStOcGMKTc5zMClqIp+6e9FVZ6ElyCXjfCLjjzsN
            M1uetjXnXyyWyKES0OP0h+aOhxusjF9S1UCF9jrujQoZD7OVg1wHCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQmhTME1CandVeDVScWFR
            cUorUXFRcmk4R3BTK3RDaUxPWEwzZFE0S1FnCmM4V3lXeDdPUlIyTDhvZmRGaXNq
            bldwRGs4cDAwRVRPbjJzRyt3dDVyNmcKLS0tIFlTVGJTZWMycGdYYTJzaFEvU0Vn
            enJHbVdURTYzcGNjc1FlWFhiMWVWTmMKHcNz9wCD90lDGEsu6h3VXrmlogsPGMwq
            u9QZ38vbmQkvkNjr/9J6Bpz2/4dttpEOCL5sXkyhVBxkSgNFz/Nj9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QzZ2aWZoSmFxZUVyeVpy
            QmNqUU5KOTZ5aFN4dW43N2lCR2h0SmNyR0dNCk9VbTZYcllieEZ5UHZMSWxEWFd4
            eGthOFBhdVpCNmxFQzV6L1B2a1VmSTQKLS0tIDMwQ2xMUDJVY2E1bDRvelN0MDZG
            NTZwZUF3VEZuWEJTQ1hIVmQ2azdzWGMKuKKTbxuUiGKohyeENuXsnVNDZKzK8JUK
            W+zak1dLYGO5URJXxxbsO4bfOs9NuHnAaXmMpmViwv1kWdjA2qUz9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T12:31:38Z"
    mac: ENC[AES256_GCM,data:NHcCHKK/GByCesNBNSK155q+Dfhul+zHJjhIpD1+20Ef1PBXHpRC7CE0aG50Ujut6qco4AB3Is/2Wffa9VFMCJTom3NGih4jL/mW1Wkq0rQJqobfNO6t0FAwJfNwFaLj7M521f4fzeMhedh+PDJ53nTmO74IxpsbS7TKtYPwIL0=,iv:ionWx+uhm7M5/2Mfb9ookp7zzHIA7Uq+peFf6E5GOlw=,tag:8q4lu0CGZaTkIx4YOdWuqg==,type:str]
    version: 3.13.1
