apiVersion: v1
kind: Secret
metadata:
    name: kuma-push
    namespace: backup
type: Opaque
stringData:
    DENTAL: ENC[AES256_GCM,data:V7PXrFKyDop4qnJm/LvLsCob/Dsmca+p9iE2eVq02XeeducqgIAZJYP7Li3t,iv:eAqDKcpSyvIoXncaplYKzuilXyH2Cp1jj6iLzlPRlEE=,tag:rPXbZp0hu0tLwBiJowqA+g==,type:str]
    GOMPHA_N8N: ENC[AES256_GCM,data:Mda4XJIrF4xeT+4Xtwhi9x7Lu1Ic3At+e9b72BXZmkvh+DYALdt2ejveGbmn,iv:3Jq9W9jCOZgSs1oRs+492nNWFK4hIEDXEbLwOY1TNyQ=,tag:z94FE8Hx2t9niqRUVPi0Cw==,type:str]
    REPLICATION: ENC[AES256_GCM,data:Zs2A9lYNWrYuFiUUqZT9lbwxIm5Wv57hkIJ2DWDdH3D32yGg3eaO06RoqHjn,iv:0njLcYExhJIiF0DY2trqeGRTDYLzGs77wK9ahok5OJo=,tag:KNDiMjndaypKCAB5XF370w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYK1Q4S2lvQlBSQ3JTc3hm
            UTJPYys0OWNER2Y3d2ZsbzI1dWNwNUcwalRVCmVtcTFFQ2JFN2JYMjNqbzloQmV1
            eVFhSGErcDlyQjNVTWNUMXBBY2pYZFkKLS0tIGdmQ2dyd0I5N0NUK2s1UENxRyta
            WVNNYnkrSDhkbGRyejkwVXFuYjhOUkUKhH7tS1DKYqB8glxg5f+Vy01wt8TCkZQK
            cyukdWrcMN8u/SXW6LodyGK9TB6XgFGUhO59dblGUTktptwzBFHT8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T05:46:05Z"
    mac: ENC[AES256_GCM,data:PNqIPTjY3dumixgm1/Jd4gJrEs3w2qBdZ5J1Osan9HnqAo7krse0lwnjGbrxR519Ho+MucEXY+BAzc2gDJt9DdCC+EwIRY37+MBBWwIqsnKDo9c0shDejqd/Cs7Hp5WxvqQrFoHGm2YO1TKzGBGPIC7aaE3tTna/mWUrkV7MHcw=,iv:wEG38sLICRSAqrkKb58vuT7KSUfqr/e0xq7Z9qb7ylg=,tag:sgJFdwBzERWBSGQfp+uiQw==,type:str]
    version: 3.13.1
