apiVersion: v1
kind: Secret
metadata:
    name: kuma-push
    namespace: backup
type: Opaque
stringData:
    DENTAL: ENC[AES256_GCM,data:V7PXrFKyDop4qnJm/LvLsCob/Dsmca+p9iE2eVq02XeeducqgIAZJYP7Li3t,iv:eAqDKcpSyvIoXncaplYKzuilXyH2Cp1jj6iLzlPRlEE=,tag:rPXbZp0hu0tLwBiJowqA+g==,type:str]
    GOMPHA_N8N: ENC[AES256_GCM,data:Mda4XJIrF4xeT+4Xtwhi9x7Lu1Ic3At+e9b72BXZmkvh+DYALdt2ejveGbmn,iv:3Jq9W9jCOZgSs1oRs+492nNWFK4hIEDXEbLwOY1TNyQ=,tag:z94FE8Hx2t9niqRUVPi0Cw==,type:str]
    REPLICATION: ENC[AES256_GCM,data:Zs2A9lYNWrYuFiUUqZT9lbwxIm5Wv57hkIJ2DWDdH3D32yGg3eaO06RoqHjn,iv:0njLcYExhJIiF0DY2trqeGRTDYLzGs77wK9ahok5OJo=,tag:KNDiMjndaypKCAB5XF370w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZlovVmZoMzRBWkdqUzJl
            eHkyS01RbllmYi8wK25SSlRINTJ2NGJIS1ZJClBML1ArcXhhZ0FlWnNxdkdFTGpl
            TU1sWURGdE1UM0tJUDZyKzFsc0EvY1EKLS0tIGRSTUtsbHg3OTQ2VXhDdmJOaUlv
            RUtqLzFJZzZkM2tEY0JTZklBNlRUY0UKTJLpqxzqY+YdathvLjF5sIYsqgPlLRA9
            rCvfxaUUQE/nVkj9xdAAFzts4B99qenDFQ4bMgjQpa33OjwQvE4jxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUnA2UmZaSVJ6K2l2bW9n
            SmUwMTcvMjdLZG12ZHFMYVN1OG1PMEk1bkZvCkppS0ZaOVg5U1dGUGR6YWNPU3g4
            OGlmV2pFQ20zVlMzWlJ0cHZ5ZXdGWFUKLS0tIGxoSS90OEZkNWswRmZ2bjEydmtk
            K0c1QlpPV1lDRU42ejc1ZFF1VFF0WFEKzJvmSZkLNKtYtJvWUAheSetkIotpmUWc
            MZWNvpJcrAA5SLRkJB6LxPxg7tx3bdw/1WJvTZYM2U1lh6pW9xSWjg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaUxpY0dSblFSSVBxbk9G
            UTFpS09YYktRVnBLeUV5L1djU0p5Yi9rWUJJCmVxZXZBWnlyNlhiMG11TU14aXA4
            ZVVOZk9XTjBoSTJaR1RQWm5ESkszcTQKLS0tIEhVMGhVL291Qy9tM09IM2c2OWN3
            U2cxZDdvdEZVTEVCdzBvRGdFSm54bmcK16+LBdp1BztOXkZr6T/5iWxqueQWuAIA
            0dysU3a1SnFrJpsENFVrQG/FPjpiR5nw3YJa4PkwVKzLsyBshm1x+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T05:46:05Z"
    mac: ENC[AES256_GCM,data:PNqIPTjY3dumixgm1/Jd4gJrEs3w2qBdZ5J1Osan9HnqAo7krse0lwnjGbrxR519Ho+MucEXY+BAzc2gDJt9DdCC+EwIRY37+MBBWwIqsnKDo9c0shDejqd/Cs7Hp5WxvqQrFoHGm2YO1TKzGBGPIC7aaE3tTna/mWUrkV7MHcw=,iv:wEG38sLICRSAqrkKb58vuT7KSUfqr/e0xq7Z9qb7ylg=,tag:sgJFdwBzERWBSGQfp+uiQw==,type:str]
    version: 3.13.1
