apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: minio-replication-secret
    namespace: backup
data:
    SRC_ACCESS_KEY: ENC[AES256_GCM,data:zDqwXhcdo1UJrBfvCld+gEAyr/YhC934I0rWAQ==,iv:oINtjzX/VdqfQjuhxieL77reWpkwMaUk5oQbp7YXbc0=,tag:B7UYtaXB2mqHZY7oEHORlw==,type:str]
    SRC_SECRET_KEY: ENC[AES256_GCM,data:hSuGKalvwFSBkNjRd1lcY5K2v42ymPIrrMXX1i96TPvKwUEZ8js1134weLFzywoMKFUSYdd2m2I=,iv:cghZnSKXBglOThh/yJFb/k9jXG29B+dwrfrgQYx2YCc=,tag:75SZShIJvu/95Uh54XbsJQ==,type:str]
    DST_ACCESS_KEY: ENC[AES256_GCM,data:WREaSrX9JVriP8iWMD5YLw==,iv:Zx496C9HQUgLs1BjsN+X6XfAa8+x58OVUqJ/lvkZYhE=,tag:rEywMbtcMEZnW5FM4oDfvA==,type:str]
    DST_SECRET_KEY: ENC[AES256_GCM,data:wi5d36s1B8v2QWVhIN7pDPAZB0kmqqdNhYz1I30SoPM856hH6JW7iQ==,iv:hIVBrA1+eVqg1XOun/ej1B5h6TcAey5o3awbhHx5GSI=,tag:l/+B3aiI0HNhP6+pTpex1A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyY0dLOXdLU21FZ3luWnVG
            U0x5V3ZzN3drWitiUUlUeHpxcHlBazBBL0dVCnc1OVpLbHR2SnQzdXJZUDIrcGQx
            NTFiTE1ZMnRpdjNzdFlPM2pTdDRqcTAKLS0tIGM0Z0g4eE1xcEducFdMS2p3UDcv
            NnhVMGhOYTZLRlVHZ0ZIM1E0MjdQak0KY9mw3/Fwz9XeY4uaM6fGqTPhp35ydqa8
            gStzTIfL443OA7A2hLaltXoJ7CxJXDkV+Gq8+ahE1EPcnTtTjnvr2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T00:22:09Z"
    mac: ENC[AES256_GCM,data:xLaghXJXD/3qARBia7B0MzMeW7sUAF4oMEXbWl6gsmIR43Jpn8ZW2hJB4ep9B+Y44DSPv2FkxtEhYwygh8OKC4DIAxLDTb7urZdkp2keZyMubAL1dbHv/h3R6+6IHNdK5bd3F5ohSkAKr3H6OCo0slYaij49PrBqr4+L+h3bmLQ=,iv:x8u7cFaS2OjC+ghZRqLwX1DOGe35j2gBJ7F29TCTZqA=,tag:aWNBPMocMEB3I312hGEeoQ==,type:str]
    version: 3.13.1
