apiVersion: v1
kind: Secret
metadata:
    name: minio-replication-secret
    namespace: backup
type: Opaque
stringData:
    SRC_ACCESS_KEY: ENC[AES256_GCM,data:7eigT/IliaK6xSHqh2dmYW75b8M=,iv:kz0fp5YmpT4SJX1Pq0VXK1tgZ80pJHnfYhrEy+xtVZs=,tag:i1swjcgPpiFKuJaFgJ+FxA==,type:str]
    SRC_SECRET_KEY: ENC[AES256_GCM,data:NjBQnr+S3ukFBZI5U4JpEuF1rXrl6fNZarZoNjKGvezS9JL9zx1SYg==,iv:Zd53UdlqhIXkxnCqma5sIbDp0DIeaYFa2BfoPluD2tA=,tag:KLgwtWONiRz2XR1jW/+4OQ==,type:str]
    DST_ACCESS_KEY: ENC[AES256_GCM,data:xhm/bU43xlFMmaY=,iv:khpN99h2WS7j05NdZtok9XrRvpjx66CSpkNGP+Veo98=,tag:YdthZdaqZ6KKzuR4/h08jA==,type:str]
    DST_SECRET_KEY: ENC[AES256_GCM,data:NLoafDuTGgVX4CWtWMFB2OizGHXGC7XYxyWhzg==,iv:S7A7hSpdBpDaLqpb8W0w5WmDNAvDjI7qNAnL/gK8zhc=,tag:0JjueZnMkfxTZUKKk0/CGQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bTVWdFJzRzlTMlBZYjJG
            N0RzWHo0em9NcmJVM2JBenNjazhJOFFOejJBClUzQjVpbGpJVXQyMCt6cm5zcThi
            aUZFOW4zU3RFbUZCMUhPaFBiTWtLMHcKLS0tIExyRlhoWXNMakpVWFJRTFJkbDg2
            amRMVU5pS2lISGpVakwvSm53cXNCQ1kKfiW7pUlS59ryOpi6PKCV3/qo7MPRz39L
            uqQjxBNIVIru+YB0kITNGhMsKSMmekWKuMz9h43r1CKGL7w9qOVrOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T23:16:13Z"
    mac: ENC[AES256_GCM,data:Z0fhv8Dc0xMePek5Vtf5k0VFXB0iO6JjfCDYrHa+gMFgJ4V0WrMmDfqFlGFFz9zQDh3JrBRlDHqKAkD5Ie8/jN0IdiG90DtVnc88gdK98j7SF/2fY/a0AKH6pzsM7V2z14HA1Yhd/l0VUCT2YqPlml+axqXLM58AmyrMcPyJNt8=,iv:5c5V1BHc5J4AyHFim321F/FEwJPQlxOVTJ1hMmAiXqk=,tag:ymPH1VtKuiGhwTojQHAtKA==,type:str]
    version: 3.13.1
