apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: backup-s3-secret
    namespace: n8n
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Ku3la2zOL2jHngZIhYXp+bRVqAPGqG1ODptgVA==,iv:cUcBupbDuI/O3Y0lNvVouVGQNsQIuRCywoLKW5Dnp6w=,tag:tyzv56MDQf+/GfaN/CBiUA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:B2/QJ+ekO7QjPS9W7b1oBsJMlPsXBEUDwK4q9u8AYGXBo+OgIl9l8/qUel20Zy2ZUuAUGv0Drrg=,iv:BLOHDY3yKCg5yN/0qqJSY+py+lN15oELd2CG0Ap271M=,tag:r35jG5CEdsLWbuQT/ihnCQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:YyLolPFJZCOvS9dkZNGR3i5aCxXCOMeaLA3pHK/kCdf9udVu,iv:ueLak9CegV6Z7euqQVY9R4iP06L/d1LrPW9+dBS9V3I=,tag:HkOfJVDnFQC+OOCbFjZfWg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNGQ5eWtSQ09KRXZwNFBC
            RG1aaVhHb3c2MmFGWHdiWkNrWnBUVjFBK1F3Cmd3MXR2SGRsMTl2VEpPMlZTcVhO
            cXd4M21CeVgxR3VmK0YxeEpWRERTdDAKLS0tIFlrTGxsSUd1Z29PZ2dPaEJ1VnNK
            ZExPL1pEUVF6SjBLakpxdzBpYmtrOVUKlHWgbtpTDpKk1BY65s69bTeHZEXqbErF
            0UG3acKGxHKf2DEHZDPf+buC9tvQu/iXF/1jvuvs14u6i+PHkpostw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVWJXVVA5OW1IbzNUWlJ1
            Yk1XN2g0ZDNqVC9BVmxjQmRsQUM4S2J6akFRClRxY3JUTDJyOW5iL1JYVlZVTENr
            MWVzRTkxYjVJaHFoQXluOFN0Wm9kRG8KLS0tIGYyc0NxaGRzVERNN1VWVFpWZzlI
            bm9NVHJPaXNXWFhwUW9oQjhCMVlhL0kK5/ulWn29cPq2FCFhR4lIlC/iwSVlC3To
            cnZKH0pC8CgpcySzn3GW8ViaDH6VzrhfjuXRFBBaZx25a/EDvzr1rQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNa2p3dE11dmxmMXdBU2sv
            RmhVeE96SzFZUkNqUFdqdW5mb0NRK1NWS3dFCkxZcmlVNHJKcEcyckV4bDUwRFBh
            bml6M0RmSytRZFV6WkZLTG1sb0lIRmsKLS0tIDdzeENQRnVCbUlIcmoxVkpnZHFW
            ZWJoNjhIVWhDZWliS2lQVktTTnpNNzAK8yIei/TNRwf5ec0fOmpBEKVleMPXWS1E
            jof4ipYWQLRveSkXWYHBYmdanadeNVlSujLanU6BsFcz9o/0MLXXrA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T00:22:09Z"
    mac: ENC[AES256_GCM,data:hhcIyKWxWiCN+gh/6Atgkc3+2nyeQagGn5H5u+yufFibZpCj1pt2PBtpEjRl5K/GvqLyEVGeW8z57B2UiA3FvBl8bg6AGRJCrH2cQuUQ6+tBONiCo6thSAtHlW5LdLZyKDFga8rA0eZbWcgctFrPND0dF98ts3aKjtrBtek7uvY=,iv:eZ57xiz0dapvsPRCW6GLOcHEwDzGVfAv7kSErUXY5Wk=,tag:cBLPY3B14tkkjtKFKibnPg==,type:str]
    version: 3.13.1
