apiVersion: v1
kind: Secret
metadata:
    name: backup-s3-secret
    namespace: n8n
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ZPMHAqK14W69EDd+ivKKE7rblQg=,iv:hm41FyaTnp8F/Lml7MsX+ISx4QO9bU650ZSLK39sk+U=,tag:tTdxPxEuVCD50mhEVccvgA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:w3Q1ma8b7wUHG78UIIi/VNxbZrAgT6PCJkCNET0TbnbT6azGhUYNsA==,iv:ImZ3lq+miCqGB7INazhdOX+OsnQcSw3xkdmqtUtRqPM=,tag:PmUh9DE7PK4KGT65kqJ9yg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:x3fNX5IUtUlQgk/yJwKkIp5U2QP59S5nAA==,iv:kzx5XSxShY3osKRdlveofGDVeirA2ZlGSVFBumG5Yvg=,tag:iM91LBqx/ypHdlap8DXpPA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSK2VhYWFJWGJRSko2dWFI
            aDc0R202Vmg4R0pEd0t5N3RVeW5oQW15ZGlvCkZndlc5UkpoWlkvRTJJK2E3L0k1
            TFEzM3cyMlBYVHRXZC94aHQ5R3ZpOFUKLS0tIGI1RnBwQnJtVlYvN3NHQ1kxUnhB
            WWVGUVlQSWhGM1pZZXhzUGhVekl0Q3MKKeDfw0DkBq5ITnNAcbgTmjbHxVIX4x4e
            2diUTJxYBVhN15bvDgJ3ndYV8cHp3VEN7wYqA5LTluuuIl+nAcf+rQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T23:16:13Z"
    mac: ENC[AES256_GCM,data:Y9w4bJrCr1nUiveIBLVE/ksi+Z+aISstFva17xeqWF9+wILolk31/IT230yHZqmhxGnjeYxSmFi1t9BtdT1PB6outKMvE4/ukPmCACpVPHnwS3uoGqtw7chXdUhDuvJrtbqdWDL6ts47xOpbv5gYvM045j4Nz36pk3FrFwVZulI=,iv:66zp3atFJO9IvfYpcqryPhFNbuvGIYrhlaZ409EPQcA=,tag:s9zvTk3bhpy9cSE+bzy8Wg==,type:str]
    version: 3.13.1
