apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: n8n
  namespace: n8n
spec:
  podSelector:
    matchLabels:
      app: n8n
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: bjj
      ports:
        - port: 5678
  egress:
    - ports:
        - port: 443
        - port: 80
      to:
        - ipBlock:
            cidr: 0.0.0.0/0
    - ports:
        - port: 4000
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ai
    - ports:
        - port: 5432
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: bjj
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
