apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
    namespace: n8n
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:k0tnpAdHZedDzjPZjpzXNqMcsndA3tVs0ZP3o/IaF1hK69Y9K44vaPBTsOlnsoHATw27BAPBJ3KQhOKD72jVuA==,iv:DGIVvled7OSU+RMgFSA/K2p2bO6gJ/l9AnoYbM/WyoE=,tag:+kjvRC77PFeGXRAbORF+PA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdHJBN1IrSFlOUzErTUZp
            VWtWdC8xR2dVQ20rREJMVExGOXUxSjBRUVVvCis3WVBRV1V2MjFrc3ZuazBqT1h0
            THk0NTRBMjZwSWJtT3BjM0M4K1BpZEkKLS0tIFVid0liWHJjVC8yRE9qYlNrdzZL
            U1c3ZFA2R2JaZVNyN2VEbmowM2ZUUTQKkwOO9mlEF9V4Gal2Ha4z6BtoVOkdpHWR
            2jzJF7wIefWsEr9iFoRp93vEdqbqTj/U0spKUe3bzMIieLfsFAMPVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T16:48:16Z"
    mac: ENC[AES256_GCM,data:zGAvxK1eYk/tGZlEhHc2dXYwXbohyIvMQFwfqdCOunhMvpkLnZgt3mtcSqZQKvR/PmmAPOKmz2Qy97jZGtYP5JmI0XugwA9q9G9xF3p7S/KPEhqD4hoY5pGTmXsS2BqV+BhaX/KddXB6iq5B8ZhGD9Wqvv2bPEKh4ppVUbQL4iw=,iv:8Yd0y68dJd1hS5ga0+wt2fkupVNUx4FNIUfQ4URXjZ8=,tag:z88U0GjVFFC2XxM0lXBOxw==,type:str]
    version: 3.13.1
