apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: n8n
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
