apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
    namespace: n8n
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:k0tnpAdHZedDzjPZjpzXNqMcsndA3tVs0ZP3o/IaF1hK69Y9K44vaPBTsOlnsoHATw27BAPBJ3KQhOKD72jVuA==,iv:DGIVvled7OSU+RMgFSA/K2p2bO6gJ/l9AnoYbM/WyoE=,tag:+kjvRC77PFeGXRAbORF+PA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuT1hrNEZibldVWnhaQ2ti
            NnZwMVFJemt0SGZpS1VEK0ZSaEI2SzBXOWw4CnVHUU5OaENubXVPWTlXeDFNZmpk
            ZnRiaXNRVlhZcWNaT1pNMG1uei9mMGcKLS0tIGtyZzBxV3VSNkR3Z09nbnF3RU9m
            cDVzeC9LTnF0anBaUWx2RkVocjRhbnMKVieHqqq100CJ45hEv99SW7Uo+WS1NG3A
            /LiHj/hIFOC4RYs6ZCluVO/aYGa2BFsxpkeadkuZkW8GdCUDOIGCCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRkZDVy8vNWxhbTNYZWVx
            QnZScHZSTWxPaTJjSWlzNi8waWFNS04yTGtRCmlzL2xKK2R3TmFIQ0hxZCttQkFR
            QUtLTWhpcVd1b3FuVXhPUi8vYk9FUWsKLS0tIEFjS1ZmNGtma0k1SEFmMTFqa21K
            QnRkUURSeVprd3NJZm5DZDJxN3N1RGsKsufp1DoYxUFQUzDrZU0s+44hTwLsvZ4k
            7Po/nHDbhcGCp10/iiIgiW12tXsg9CAkZ4WggfB0306zQj78xX7lTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRWp4M1pkbG5ZSHhtNS80
            R3lWRVo4cHpUTVRjL21PK2xEWUNoaGc5QVVRCmI4MlNTbVJweEhybWZ2SEVqWWFI
            SUpnOTRoUC9JcTZ5bFNqT2VBZHk1UW8KLS0tIGxwYS9HMElFK3lPd1haRVRKRUha
            enVIRGYwZzBqeEN3Q2dVa1NIdm9YbnMKYuFt/g/3qw5Iwm052OQ4pygXMrturkF/
            x9uE67XBto4DOmQunH9oRzM7lm13+/UFpttMeSqLKU0vIy61fMY3FQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T16:48:16Z"
    mac: ENC[AES256_GCM,data:zGAvxK1eYk/tGZlEhHc2dXYwXbohyIvMQFwfqdCOunhMvpkLnZgt3mtcSqZQKvR/PmmAPOKmz2Qy97jZGtYP5JmI0XugwA9q9G9xF3p7S/KPEhqD4hoY5pGTmXsS2BqV+BhaX/KddXB6iq5B8ZhGD9Wqvv2bPEKh4ppVUbQL4iw=,iv:8Yd0y68dJd1hS5ga0+wt2fkupVNUx4FNIUfQ4URXjZ8=,tag:z88U0GjVFFC2XxM0lXBOxw==,type:str]
    version: 3.13.1
