apiVersion: v1
kind: Secret
metadata:
  name: homepage-secret
  namespace: homepage
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
