apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
    namespace: homepage
type: Opaque
stringData:
    HOMEPAGE_VAR_UNRAID_KEY: ENC[AES256_GCM,data:tH1C8a9P2LXxlk96tN5a4q93Nq67z05Lkv7EmbjsqnAQLeyrbT60C0t8nbxMGc8C74TzjksrpI+n1ZLq1XHtHg==,iv:e8RgGhIh0AVh22dXHkuztaH1vY0hfJHlL2Baun2KE48=,tag:be6C+TzNLfqQplxpvYCYoQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSzZLdXZ1eW9xaWw1RVVv
            bEtHMm9ORkFxOHlNbzBuRE1tRGV1RkRPbzFNCkZPZDhTR284OFhhYVBBK09BRHJI
            V3pmamRNNDcvN040NzBiZHNHYlpzdU0KLS0tIFdRSExGVnYxZFdGYmFNWEc1SXd2
            R3dWUFhBeGd3TndoMmtDaFhBZno3TFUK98NHJH/OF2CR3IAc+V5zCUOqG2RSpkNe
            O/LlDO7wtzA9BalwHQq82+4myU6BrZUNQ6tz6HFaiRbGRn1i853tLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T00:13:12Z"
    mac: ENC[AES256_GCM,data:N2agACzuEQQ5Tybuz0fICFH+XRVFNjIxqm960urOwAqH18DUWquNxwkBIel63/lK6wrWIH6GrnNpakO83PKBv0FnhnmmiAxBXkaOzhOAcKkNE3k5krXYqYt0JObjgK2aJVx9GYI+WnZLw6Ea6QqFjH4ET/J9x6dKlR+rx8yWVk0=,iv:seJ6n9drGL3scIyEUDYTrOA+YJBMG+YD/UfjYpJfH1c=,tag:W5CmAqgy3r3n9eA29zU2TQ==,type:str]
    version: 3.13.1
