apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: marianna-media-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: immich-marianna-media-pv
  resources:
    requests:
      storage: 200Gi
