apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: paperless-drali
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:rpYrMUQ0ZVB5,iv:XkpaMIxPyKrxS3wrDzBDlk5DPI6h1BbRitx3txYc5hQ=,tag:zXSD03pzlQxitLa/BO02Gw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:aBT8KgNri0eS,iv:Fpg6yXRFyytB4hDkCj+z20xRR8bXjl88fmH6PzYfRF4=,tag:QDyV/NEdWjMtelzpJINgOw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:k93b2FaWv5SPlGNVTQxtmi7knlP0JyjZv+TfU7IRoA==,iv:QSCGr7jW5Z/qnr3voCU1kiRGVj0rn4JvI655VRTngSI=,tag:x6HtzIqUmFE/wLVNpM9zhQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRS3A0cEI3SDMyWTZTdEY4
            TXByWGw2K3pIR0JmeFNmSkF3OE9Kem5OUkEwCmppV0JMSmozWVFBUXpqei9pdlk5
            dDRpUU1hYmxndnVEcFRvRmc2d0ZjYzgKLS0tIFNic08wZ1Q3aVJzVmFMQ3BWN01J
            bnVYY29nRWRvSWhGTk13b2VoK3FmeHMKZJQZHr/7woHU0UuZl9cIZO8a7u3kwOXF
            E4w1vAubP0VKOe6wbPZTM5XT3QTdi2vWEjH2bKHaL8xghRVgLXhJlg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T18:49:13Z"
    mac: ENC[AES256_GCM,data:/wV/0gPjbSbqKHaWHXBR2bm7Cp3JncSn8/Y9sMzMkjQqjL6zKhS34stMcY3DTOfDGiys9qLKqJ/mA8gFTMAvwbNco72msGomaVhODMnE+ILkumMH8cc9fT0u8d5zdPlE5REqPU44s3LAj72AH2TVQ1eRuW3jMghMUMb6de9xx/Q=,iv:KfS2aLoh8yr3NYahtNoLAvvI24kyOYVFkYiQum3pMl0=,tag:p6Qlk7Ut2jd30SYyP6hQMg==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: paperless-drali
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:pj9MGyaC6QkaRkR2oOgA8YQIc17UMpdeGah1zPB4F32lWKc62xcHB3wqCBnrbXNFRGEf,iv:lcJ+bBAunwY1/ZKQB8JvI63jqUD8n45oljxaj6hqY9A=,tag:qSUKP3hf+xfSk6rWkSOurQ==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:uJyixqpxc3shSTiqHhD5O5k1eW43XAGiXLUuDbubxw==,iv:SvfuYUyzFsAM+ngZJGD942iow0fJr8Vxb5paICwaKc8=,tag:QZ02uiM5oOlL/XPTXxSJcw==,type:str]
    PAPERLESS_REDIS: ENC[AES256_GCM,data:9jZTouAWDyCO+da9Q0LeSw6YPr7XXZ0J/nfmOiVaMw9mfNuEe/VPxDK80+A=,iv:zn7ZNDKEqFSlBgAGwP1Peu0/tN/jEfg8wVBL+yxXUO0=,tag:ssUiyM4yAbWZuW9f6FHGZg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:GPPIGdygqgdrfEcEv56kFGyHlbjm6j39,iv:XMet3X4jX0M0oEhFxuz+VKTAl+eZ9Z0W/IMYhaU1qpA=,tag:VT6PbsOBF0B1lotKIxIbJg==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:chVeuWc=,iv:7rnX7oOOW1vcbPi0fgllE7M0VW+KGhUX2UTVMZ7RqVU=,tag:8UuDqxLlmzLvncjoaFKrjw==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:HCO8kOYi73gyUUBMg9wx7GVe0NCcC//9lf9fHYjqFn1oMLLIYtBDLQ==,iv:hqpTIxDBD0AcIvPWtwEeMTeS0hGdbxpvb/5Kh/bNGH4=,tag:ssgab+1+xlPmPQIdHifkfA==,type:str]
    PAPERLESS_ADMIN_MAIL: ENC[AES256_GCM,data:06Pw4GXY/Uskm3qx/H+IbGhxJvs=,iv:eVWnzjvk4oBdTkVJlXjNv8+s3oIx6GLUPpjQYqDCkXw=,tag:MxLPTvzYhoSeEc6IMu1pSA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRS3A0cEI3SDMyWTZTdEY4
            TXByWGw2K3pIR0JmeFNmSkF3OE9Kem5OUkEwCmppV0JMSmozWVFBUXpqei9pdlk5
            dDRpUU1hYmxndnVEcFRvRmc2d0ZjYzgKLS0tIFNic08wZ1Q3aVJzVmFMQ3BWN01J
            bnVYY29nRWRvSWhGTk13b2VoK3FmeHMKZJQZHr/7woHU0UuZl9cIZO8a7u3kwOXF
            E4w1vAubP0VKOe6wbPZTM5XT3QTdi2vWEjH2bKHaL8xghRVgLXhJlg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T18:49:13Z"
    mac: ENC[AES256_GCM,data:/wV/0gPjbSbqKHaWHXBR2bm7Cp3JncSn8/Y9sMzMkjQqjL6zKhS34stMcY3DTOfDGiys9qLKqJ/mA8gFTMAvwbNco72msGomaVhODMnE+ILkumMH8cc9fT0u8d5zdPlE5REqPU44s3LAj72AH2TVQ1eRuW3jMghMUMb6de9xx/Q=,iv:KfS2aLoh8yr3NYahtNoLAvvI24kyOYVFkYiQum3pMl0=,tag:p6Qlk7Ut2jd30SYyP6hQMg==,type:str]
    version: 3.13.1
