apiVersion: v1
kind: Secret
metadata:
    name: couchdb-secret
    namespace: obsidian-livesync
type: Opaque
data:
    adminPassword: ENC[AES256_GCM,data:3zHX6mGZNlNXaDvU0N60Zw7+FDinmkTKEKaQtUIoGplCAVpwp9sUS9wNQS5xXyckREekOD4OAReVldy9,iv:FvQUTfxuncjhLY7tES7lskAiuDgRjgnWl6tFrMoxMC8=,tag:Dk4vGeF6lNdIYvAkJm6JPg==,type:str]
    adminUsername: ENC[AES256_GCM,data:fZNCbUpVla4=,iv:+CPQprwfQ9E7PxIoq0JN6rxuRl845gpIrCnjv9QX8z8=,tag:rRlhxthqCiWi25Ti+LusFg==,type:str]
    cookieAuthSecret: ENC[AES256_GCM,data:+k+9eBZkrgYwzclg2jrtg8jykh8JtPl4DN/NVOpo4XsSS/vXMZ3W7ubpm3VkboP3vJVSM6o+Y7olm5z9,iv:lAk6CUAk+gK8IT+qIbGvmG9+dK1RbIlT6xUGVMJvcR0=,tag:J/QF7VYPQJzWQFwUkSCMGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybWU2YnNyZUdNMW00aVpJ
            RVBBeXd5N3VINGpXNE5wS010VndWRnlQb1hjCk4vSUMzN2g1K2M4WFU3ZFQ0eXZp
            bWdDREt3eWl6aGJvR01ablprRjIzWE0KLS0tIHRCcFE3cDdTa0xEZGhuU0Nqbk5W
            dlNyNFJudGhJRFRidUdIMkJEM1BrQlUKk1JIlmL5vPmE2qpeCp0TndfYZXOg3hVF
            wNEv4lpoj/i/jhW/SGVmAL1E5QQ/mqX3kJKGK5YRbgv79cXdBr9bSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdXA3ZVBiZXRMdmlnSUd0
            NzQ4L0Y5QVZSbVY0ZWNjVkliaWRSak1xem5nCkZLRVJSSEtGL3g3OUVGQjFyNmc1
            T21JaXVVT0xTeERiL3poY00va0srQ1UKLS0tIE1jYzFQZWpVZ09yM2FWYVAyMmFp
            OGhZSUMvUDBjc0p1MzJrWXJWTFRRN0kKVoKeXRsHAIDqpGpykA+AVPAsivxL+Pgg
            uRNe4o8llP/zI0HF8H5iIHHwPwfJOYK+vuMBKDWiUk4Rd4pAELGoaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRGdQRXNCY1N3eTZzV1Q1
            YnovTWt4Z1ljTTlzTUJTVWJxQjJwenFwZFhvCkxxdm01WnVnbCtNWjV4bVYzQWtG
            VTBsVThEK0FzVHpveWhsY1ExYXdheDgKLS0tIGhxZ3c2Z2lCeldkQWxWYVN2NDI3
            WW9vTVJhOWd2N0xFUi81NjRPaTFRNjAKxzXYJ84i8kc3OKcfVPzukRx612elcHL+
            OwfCJY4xWXvR30I3zQ4q8EMzS06HHmXTSBHJAlsznIt5WiQQZ7k5cA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-16T18:46:11Z"
    mac: ENC[AES256_GCM,data:T+Fpo+kOBE2bDeovm34E+iSaF1B9nhTi8bP2IUk8ZEgKpw4t5L5IQNcypyfe3Ipm20ca+01HdZiaXyWp+9RkqukVd5pLXBkDxQSkwbgGJEVJ8E9ocPmObQrqAR0Pu7WRrrc4wEILrdRQcGW6yT12h8QEvCg1n64VQxfbWCY0+Ow=,iv:dpsSM8M+3Avea1vscKFFG+JayyvRUfTZx3IK/03uQ94=,tag:A9prmIbALbFmUxfJiz6IlA==,type:str]
    version: 3.13.1
