apiVersion: v1
kind: Secret
metadata:
    name: couchdb-secret
    namespace: obsidian-livesync
type: Opaque
data:
    adminPassword: ENC[AES256_GCM,data:3zHX6mGZNlNXaDvU0N60Zw7+FDinmkTKEKaQtUIoGplCAVpwp9sUS9wNQS5xXyckREekOD4OAReVldy9,iv:FvQUTfxuncjhLY7tES7lskAiuDgRjgnWl6tFrMoxMC8=,tag:Dk4vGeF6lNdIYvAkJm6JPg==,type:str]
    adminUsername: ENC[AES256_GCM,data:fZNCbUpVla4=,iv:+CPQprwfQ9E7PxIoq0JN6rxuRl845gpIrCnjv9QX8z8=,tag:rRlhxthqCiWi25Ti+LusFg==,type:str]
    cookieAuthSecret: ENC[AES256_GCM,data:+k+9eBZkrgYwzclg2jrtg8jykh8JtPl4DN/NVOpo4XsSS/vXMZ3W7ubpm3VkboP3vJVSM6o+Y7olm5z9,iv:lAk6CUAk+gK8IT+qIbGvmG9+dK1RbIlT6xUGVMJvcR0=,tag:J/QF7VYPQJzWQFwUkSCMGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcG1KUXVVSHZzK2g0K2Rp
            eGxXWTFLbWlKc2FZWExjMHUyMVhxTHJmOUNVClp4dVZmREMxbFlJWHdxRkFXQ29v
            cDdoZFovdFJhaDlOdEZMMU9PdWFvWHcKLS0tIHhIOW5Ub3FCOXJxZkxQeXd3UVcv
            SmR4bnZUY0RzVWc1TjVGNk9rc1NRazgK9O01D7WMfIIQ2dixFfriw2/E9rsXwGsx
            8inNIpfy5ddtEvqK1eptFenx/BtUq21JWqZMffKhC5UbgNXu5tHYUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-16T18:46:11Z"
    mac: ENC[AES256_GCM,data:T+Fpo+kOBE2bDeovm34E+iSaF1B9nhTi8bP2IUk8ZEgKpw4t5L5IQNcypyfe3Ipm20ca+01HdZiaXyWp+9RkqukVd5pLXBkDxQSkwbgGJEVJ8E9ocPmObQrqAR0Pu7WRrrc4wEILrdRQcGW6yT12h8QEvCg1n64VQxfbWCY0+Ow=,iv:dpsSM8M+3Avea1vscKFFG+JayyvRUfTZx3IK/03uQ94=,tag:A9prmIbALbFmUxfJiz6IlA==,type:str]
    version: 3.13.1
