apiVersion: v1
kind: Secret
metadata:
  name: couchdb-secret
  namespace: obsidian-livesync
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
