apiVersion: v1
kind: Secret
metadata:
    name: manual-htpasswd
    namespace: gompha
    annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
type: Opaque
stringData:
    auth: ENC[AES256_GCM,data:16hWqMsllU7tC5M9DXwxpsB4a8RJfkRf+EG8fgk3Hn/Jx/pydawra1KTNgY=,iv:kaTCLlllzPNIIeqQciYkjvMxfOGtr0Hq10Hg5YS6SqY=,tag:p9U6t6KVy+O2BTph6ZTJhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMDQ0MGx6ZHhzY1VMbUZl
            ZnA2T0Q1NjVhbmNJc0txSGNjS1F0YnFXaGs4ClpUc3VHTk16bGFRdGcrRWJYZS8w
            NzFZU3IxcmZPNHVOZHpSaWtveEtXL1EKLS0tIENmcUxCc3RkOTB4RE1JMEhnT1Vn
            dElkSEJWVkw4VXNiV204UmlHWlBFbGMKovXRd+Vb5utNwXKSuWViCPKNPCjyL6Ne
            7AaaweylBtA8xlGOaUoprs7Czpn/vKauVFZl7o+9dpqwdWQjGwabOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T22:58:05Z"
    mac: ENC[AES256_GCM,data:DqvZD/Ahz5zdBEYD1gh2SPMI3VR1BVVvxybLZFC2SeTbGomALNH6/bivvR3aIsN1HdCwe9nI2vR+6NduXsnsETEbo16SSAxCYunm1Ptl7RcMkUzC5seqqf98/iO3jAqR8rIZyRJD+tCzDZJWfxkhQ4B7z4dbczsjoZyvvjkePx8=,iv:sOIgd9nsdUuJYQ9h6BrzaH2pFSSNR2oLSg6gCGG/D5s=,tag:Yb373ZxezLAxZAUlZZbbjA==,type:str]
    version: 3.13.1
