apiVersion: v1
kind: Secret
metadata:
    name: manual-gate
    namespace: gompha
    annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
type: Opaque
stringData:
    MANUAL_KEY: ENC[AES256_GCM,data:7MoXZ19PrxBgGOobKPmKoV7yIuY=,iv:Gt/D0KI3Gr2OhyiYAj22LJRK0XwJpAjC2qKsfU2lW78=,tag:EzbpTHKr6QwB1Zfh+TgKmQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4L1B5SWRDNHpJT1k4L2dH
            NDdTQTI4SUpCZUpWTGY2aXk2L2ZuWlkyWm1FCjZpNWtBMzRIcGxWUXdRejgyK0dt
            ZjgvKzZTZ3RxZ2hOK3kzVmRnY0R4YncKLS0tIE5Sa3hiTjVnTUdvcEMvWFc1TFB1
            R3JpakZUNyt5WWtaWkRNMmxjV25pQXMK7Y53cS2SZ0muB+fFlDSdx65f3ZAZ6JHE
            oVUeHzQ9uBB9wR2WUIcrwmQ69pFIxogPSTvia2PKZvVFciJ6I45a5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T01:50:36Z"
    mac: ENC[AES256_GCM,data:HNslfMP+P5xsuZklxJ9lG6R09Ljtv8j7pavQF2glLv9E2d4DTDE9Mij3XNMapxvfvGGqQ3BTum8C7JOS137PHBJDMqM04gas/k4A74CLKHSIl2uoQ5mX8bS6K9Wk3nvXfR2KYJUr4FsOJWJQbfNuqu6Hvx4zPdZxqDw1BLENC64=,iv:CUbKdmPmUFQ9ngyPNdPnw8JXO2bOpyuQUZo+5d6z6lE=,tag:Tyc+iL4OJMtJTlKIv7Sh4Q==,type:str]
    version: 3.13.1
