apiVersion: v1
kind: Secret
metadata:
    name: manual-htpasswd
    namespace: gompha
type: Opaque
stringData:
    auth: ENC[AES256_GCM,data:3KOqULye1X12zcx066zbMDF16BST+nfuKSZzXqsYzC7OZoXz7zRsYyBUxIw=,iv:u3XB9XrNRyxe+7EBFlf0gW/ASLy16nYrSzi3MbSKnjI=,tag:MCDGG9o1DLWsnwht0wvWVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WVdMcWx3ci8xYWp6V1lx
            cy9uZU1jQVJ4dzdRT2prUHJOL3owakJyYXdZCnZZMFBtelRYckNYaWhWTDBmYUNn
            QzN2SEpPSG8xNi9Rck4yVFNqYUFDTGcKLS0tIExLd0xxbFpwdGxPNTIyclVRT054
            ZStkdzhRVFBrREhNUkwwaXdYRnNVN00Kslx9grlwewpMQd6GGqjd7agDdoVJ2myT
            A0DcRIFA3Fq3o8M9mCT/NiGqlDVosikHs/6N8YRvt2Sl1t4zgV4lYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T21:21:07Z"
    mac: ENC[AES256_GCM,data:q/6NsocliHpviHdKFzZ5q36SAzYcLhlZPWOhCMq3DGBL0xACIfERyjbhMuQXT5kyVMmYN6X96xVdfMTzAdpKEA83AO9GnCybLXLYajYhAqsRRIB3ZZkXS9oclCJxD1ZtnpbfjjgpFy79LDrI4zcACtSsBV2CvAC1pJga2CJvLk0=,iv:07fz4rqNmat8jH9MUAHS2/ly4CJIVp79rGBlKyV3Jow=,tag:QwXtyQm8UtGq2Bp3oCtT4Q==,type:str]
    version: 3.13.1
