apiVersion: v1
kind: Secret
metadata:
    name: mariadb-secret
    namespace: studioconcreteluka
stringData:
    MARIADB_DATABASE: wordpress
    MARIADB_USER: wordpress
    MARIADB_PASSWORD: REPLACE_WITH_STRONG_PASSWORD
    MARIADB_ROOT_PASSWORD: REPLACE_WITH_STRONG_ROOT_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
    name: wordpress-secret
    namespace: studioconcreteluka
stringData:
    WORDPRESS_DB_PASSWORD: SAME_AS_MARIADB_PASSWORD_ABOVE
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-token
    namespace: studioconcreteluka
stringData:
    token: PASTE_CF_TUNNEL_TOKEN_HERE
