apiVersion: v1
kind: Secret
metadata:
    name: mariadb-secret
    namespace: studioconcreteluka
stringData:
    MARIADB_DATABASE: ENC[AES256_GCM,data:h9u6r2d2wfQG,iv:tOr2T6zuQnPYmfWLtk2kMjMWb2MEr3Ei91HIClfg+3s=,tag:0rDsv2rnCqJJQKcqyf63/A==,type:str]
    MARIADB_USER: ENC[AES256_GCM,data:v4iNTD5D4mQm,iv:DkRbCKmfGOe/Rzd3+7SUCAp1mimfNpTHYMDukkkQT80=,tag:+9hC3aDYXr7dja5OwDuR4Q==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:e9ykgMEkCX4gAwRnQedJpMT0cVpoAI0GbsmLIXpLENU=,iv:zAFuGYPPi0seyGgiI2FX9+U42yKBS+EbjHO60or9sVA=,tag:AmxaXRAbpQ0f1rnYIyn5/A==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:qog3TNPvMB8Zqys/djk1u8VigRrYLq2bS9YANlz2BHk=,iv:b0+7uULGxylBzNHYUCCuqALTLIJoLptPIyOnQ8rYxUw=,tag:cNZL3E0vYqWFbkf1pno3vw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVE9rcE5BRkZjYlVjUExS
            Zk1nS21zT0FMODVKamNyN2NaL1MybGZJOUZnCllicmwyTUVwM0h2QmNEWFBvSEJ3
            ZXdHWlREWGFjcEt0NVkvRVpMNXArNWcKLS0tIDZ0Zlh5NDM5OFl2SG1KZGhRZDJa
            VXdpUHZPQlFGditaSTl4NmZxQkduRGsKIzQxNC7ZwrFIUplqoCTkuY6ZGV2pAkWi
            D1b8bMPgY3RJ8dvGudMr2W0kHf11koJE06o9on5C5ZlU+6MI549zZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T15:35:08Z"
    mac: ENC[AES256_GCM,data:meVu1yXieQcLh9q2kGHpmf+PhhMjDwdbA+Jo+H1FmkW+EYXLGrfJ6yik1riaJXW4UpwL+qUSr9cHEtE/pg3tBoAY/P9+4I5m1l4+KbORETcsN6i/iLtb7bHQtqPqdEwZCG8oS8NYXBvkGxOS2dpsH9qIKRzEg61DHI00LXS27T0=,iv:vjoSgmnuF7Dc35s27zJfTwSbcsoIcyxZLRrytHjCNQo=,tag:4xanIaaW+QWoc2ff7Z5aPA==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: wordpress-secret
    namespace: studioconcreteluka
stringData:
    WORDPRESS_DB_PASSWORD: ENC[AES256_GCM,data:PCtrcvgHhEgru8+6r6mItnorJQedhv9R7Sxi4SRx1Dw=,iv:gTlqaxa4cHXZI8Dy6aqhtjrWxJKbqOni6hU7ZmXM62E=,tag:8cX92n6ipdCfkZ66/LsSAw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVE9rcE5BRkZjYlVjUExS
            Zk1nS21zT0FMODVKamNyN2NaL1MybGZJOUZnCllicmwyTUVwM0h2QmNEWFBvSEJ3
            ZXdHWlREWGFjcEt0NVkvRVpMNXArNWcKLS0tIDZ0Zlh5NDM5OFl2SG1KZGhRZDJa
            VXdpUHZPQlFGditaSTl4NmZxQkduRGsKIzQxNC7ZwrFIUplqoCTkuY6ZGV2pAkWi
            D1b8bMPgY3RJ8dvGudMr2W0kHf11koJE06o9on5C5ZlU+6MI549zZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T15:35:08Z"
    mac: ENC[AES256_GCM,data:meVu1yXieQcLh9q2kGHpmf+PhhMjDwdbA+Jo+H1FmkW+EYXLGrfJ6yik1riaJXW4UpwL+qUSr9cHEtE/pg3tBoAY/P9+4I5m1l4+KbORETcsN6i/iLtb7bHQtqPqdEwZCG8oS8NYXBvkGxOS2dpsH9qIKRzEg61DHI00LXS27T0=,iv:vjoSgmnuF7Dc35s27zJfTwSbcsoIcyxZLRrytHjCNQo=,tag:4xanIaaW+QWoc2ff7Z5aPA==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-token
    namespace: studioconcreteluka
stringData:
    token: ENC[AES256_GCM,data:UtZEGrsLsUQT+n+UJ/LaJoPfNGL4enBKkLa8x5PM9s/bgtQVuPJk+iLxKqL1H62GCGpgPN69907jD0BZPI3MiM5ySVJxNdgZFpjHnWWx4vVB57PXovNmdbzpYmVtek7G0Y7eW+Gk3Z1K7BAKvSGpgQaEtUxMMqXa/F1of2LAH5KKZAtCby8UEWB1kyKxMoCjcF34T/sqIejuAU96jhYOFV84XS+MNZ+8I9+jaVunkVXu/NAJo5ZQ/A==,iv:jXbOSWzGHKbZjo/Z5KVvYhbgg6ps25vvNFhAYN/EL8c=,tag:glSRdvmLIo0QPN0/Kt+mfg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVE9rcE5BRkZjYlVjUExS
            Zk1nS21zT0FMODVKamNyN2NaL1MybGZJOUZnCllicmwyTUVwM0h2QmNEWFBvSEJ3
            ZXdHWlREWGFjcEt0NVkvRVpMNXArNWcKLS0tIDZ0Zlh5NDM5OFl2SG1KZGhRZDJa
            VXdpUHZPQlFGditaSTl4NmZxQkduRGsKIzQxNC7ZwrFIUplqoCTkuY6ZGV2pAkWi
            D1b8bMPgY3RJ8dvGudMr2W0kHf11koJE06o9on5C5ZlU+6MI549zZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9pqv93dtdg7zuk2uc423rdtapu9p0fqucd2s9p6curt2c0y2vuq4yzw9n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T15:35:08Z"
    mac: ENC[AES256_GCM,data:meVu1yXieQcLh9q2kGHpmf+PhhMjDwdbA+Jo+H1FmkW+EYXLGrfJ6yik1riaJXW4UpwL+qUSr9cHEtE/pg3tBoAY/P9+4I5m1l4+KbORETcsN6i/iLtb7bHQtqPqdEwZCG8oS8NYXBvkGxOS2dpsH9qIKRzEg61DHI00LXS27T0=,iv:vjoSgmnuF7Dc35s27zJfTwSbcsoIcyxZLRrytHjCNQo=,tag:4xanIaaW+QWoc2ff7Z5aPA==,type:str]
    version: 3.13.1
