apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: studioconcreteluka
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: studioconcreteluka
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-token
  namespace: studioconcreteluka
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
