apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-uploads-pvc
  namespace: immich-test
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres-pvc
  namespace: immich-test
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-pvc
  namespace: immich-test
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany   # shared between 2 ML replicas
  resources:
    requests:
      storage: 10Gi
