apiVersion: v1
kind: Secret
metadata:
    name: backup-s3-secret
    namespace: neo4j
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5xPOmmIWOa58RaQN,iv:hwb1egcGeLZ+PlCQHCbaAwPNFtn5gi29U+obD7PU3ZE=,tag:tXb/ES/agLRD8EMNfBWwvg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:B4PKc/ycVYsI7K2vDfuwyF7FoTbbzhr986kI9dClszLAMv3L0bARgg==,iv:zRjoSTLoqrJF+yloB1vgS+abuGziaOqOYH7/xAMyLrA=,tag:cpfLy+lOs6YQD1xQ2xxQGA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:/nY3EycAyWwjc7OP832Er0WBkFyHJNQdlQ==,iv:2BOSAxj7JETC0vJeWEOFyCHm5Y4ffMhIb8p/yE7OzF0=,tag:s5b2EO5hV/+JhImN4S7tlw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSVhSVHF1WkpJVXRTYmxY
            SUpUSmhzZzNva29QdjNESzd0UTZjZXR0ZERJCm9NMWljbWNEajlRaE1vWDdGYmFI
            aUxJN012NFV1ZUVlR3FJMFZkeFNrRFkKLS0tIHA2d1BLTVJRa05rUkZaYXZnSWMy
            c0FETTRDMXR4VTZlNFZCWnZVQnNOQzgKGrmeqplqXWCbnGyvCPw1aUztnDhZwtVj
            M5p1+5RE+5k5j6lG63Wamo6DXzC7yW0T4HTOjAayDzEROKMZ09ssrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyb0k1TVkzL3hsTTFQU3Ux
            b0FZRGhNYlk0dWV3czMvNDhWYTVERmpmT0R3CmV5RDlwWC9VMzU2RVEzRWFyckwv
            UVgxM1I1ZDhPNXhOMWRCYnhNb1VZL2MKLS0tIGRhbzhKWmRYM3RCRW5pQ3FKZFZL
            TUlaM0s1aWlTUXRvcnF2ck04RDFUS1UKUffWW+vrqMa+ryhssxJa9gBkUQQy8RGZ
            c/pOpMDyBBslLQTN544RNUHZOuYVO4ojqbuK5M6KnABM1ki0kea/Mg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYlI1bHl0aHB3bGRicVR6
            dllKakFPNnNlM3RvSDBEbmh5YjVEekUxU1J3CkVTbjJTL0MvNEphSjNxKy9zRTYy
            S1RiUEl2YjgvRUZCUEVrNkF0OXZzbFkKLS0tIElmeFFySGw1a3Nib3hLR2c5K0I1
            ZEtSRk5GYnVEVnY0RmQxY3F1YWlaVzAKijfHHOufg8JV+59wdDqrqQ3z7vvqIFyg
            E//hNzZWzs/aB+BTFWSaJXB+h72ok4rs56CEIla75MOcToED/dseaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T23:51:20Z"
    mac: ENC[AES256_GCM,data:CODOMneZ5GyzLttWGOglxurLeuAL4IHlLqJwyoZTRpmtSS6DhhbmK8TF55YL/ATHkjK1N6EOBZkv3ilZOd+h/5upNmjD/Oea42dT4fw+NxNUmQ82dEO/oZ4HGLVFFah5rvTErnGQ2FcjrSbqEqBoCXRjmwVcD4zzpovly2YN6TA=,iv:WJ4mz1yNFB/++XekF0snCyMfOqV5hHnOzh/Duwc4DWY=,tag:bH0UxdLqXcGqOQjnNiw9SA==,type:str]
    version: 3.13.1
