apiVersion: v1
kind: Secret
metadata:
    name: neo4j-auth
    namespace: neo4j
type: Opaque
stringData:
    #ENC[AES256_GCM,data:/XOI2kBsiIRayMB4JjsQ3NWwNxM4STTR59TYLYvrgUhSD+e2yNjvRPADLf7CjfTepuZzCyw=,iv:dwXeCMUHd+AvSdPNSPZ0XqZJgymtCJSRHqfHzjnrQkc=,tag:+oCyC5upltGEpaDh28aENA==,type:comment]
    NEO4J_AUTH: ENC[AES256_GCM,data:zMY6ZnWfVqz8cSXWDuSUjZQkC0WA7KZszevNC3IIj28lTQ==,iv:xU8zCE0yKinZlr7bqYFwm1JqdXO9Nq4dC8DzrxooC5Y=,tag:c9tfV1aYBumUZcZ9IVcw4Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSDV4MEtLZmwyQ1NqSDlG
            eSsyMzN2eXRmcGx1b3JKd2V3WVVrc1VVc1VVClBqZ0dhbnNzR01YWVF0YndIVCty
            TkhPZDBIdFNHU1h4ZWt4SjdtQzU1bFkKLS0tIGlmZ1p0RW1KN2xuc1Nqb01PQmZl
            V0h3cTZleFJzdkplVnh5VTJyUk1aVlkKzuXpQNttCFrzh8FWaUSylQQfUlV0ns8p
            qlai3IrTlDK0Hh+hS3fwSDyyMHuP7VrxVjefDnTXSDBeiIEkkOQuAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sv9srthxjgaxqufmnf8dwdwg3pugdxkxye8mmndstvjh45zqg9qcsk8c5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOGozSWxLOWgwYkxEdXFR
            dlBhTzlPa1VpVmo3VVk0bkR4WjV3c1dHblRNCnc2NWMyMWFCV29DUksxbVpIdW5j
            NHFVdTE0Q1ZGd20vdEgzaUhINDd0WG8KLS0tIDZQbU1Md0ZIOTZxZkVmRmFDTmd1
            RUhlYUlSN2l4c0JEam1PVmFodDBac0kK0d9XC+7gKt4oGFMCu6WiT9Lh/bwJOCsX
            UhI/qNcbwzGXQp3C/ZrN/vO6pj760Nv5kDr2PVQBSbaXyf2inSE2AQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nu9pu2s9cy3gf9gdgfm6pwqyrm9t2jnkvvrrcqe07tfcemfxafq4v4sv6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZY0hNM0kreDIwazRPb2Yy
            ak0xZE1WUVBIbng4SmIwTUV6c0d2RjhoRHcwCjhjdTlvaWJqUkFZNlY4YmpKcXor
            dlhJcjdlT3hyR1V4MlMrc1lTQzE2S28KLS0tICtBcXZrY3VyQXhqQzlrVUc4TG1V
            WVhHVU1rS3BMM2x1Y3VQVmx0S3Y5SG8KiPUKaWTxPkzFuuW+OWvFDYXgR2/qtMBg
            rpRQjUuQC3U+KkNdbsPqNB4yyHX4TZcYK3xR0W4L6umw2m6VC9nAXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15el6f6wzcdzge9fvpcawuqfdjgld8tlpawyunktmm2lyxtdwlv8sa88y7s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T23:46:45Z"
    mac: ENC[AES256_GCM,data:/FPZAF5Djrh0dElDeZudwqpcVD4MSDyIaTVIUcUBXunTJxS+6NJVyxmwNfMYK1+T8VqvRKuHwi8wZfwLVIrxz5jWXDfPS6Vz9Aghk6HbfA8albn6rGOcjZcK883ztoZUrF0jQNuxhCB3+IYeoxO/6FsPn0I/lSOQOIxrL3YwTdU=,iv:F2PzCe3skBEd/nNNRsitiZLMOpv3iS6yb8EtpNSfu6M=,tag:JMZpHwB1dixitz61CmnDwg==,type:str]
    version: 3.13.1
